### ISSUE TITLE
Watcher fails if index from previous day does not exist

### ISSUE THREAD

**Issue by almico** [sirensolutions/sentinl#100]
If indexes to be read are like the following ones:

```
          "index": [
            "<blackip-{now/d}>",
            "<blackip-{now/d-1d}>"
          ]
```

But indexing just started, the index from the previous day might not exist yet and the watcher appears to failing with the following message:

```
[error][Sentinl] An error occurred while executing the watch: [index_not_found_exception] no such index
```

**Comment by lmangani** [comment]
@almico there' s currently no way SENTINL can check if indices exist before querying them, but it should be sufficient to remove the second index from the config to address this - could you confirm so?

**Comment by almico** [comment]
Removing the second (previous day) index was my mitigation action.
What about the "**ignore_unavailable**" option found on this page?

[https://www.elastic.co/guide/en/elasticsearch/reference/2.4/multi-index.html](url)

**Comment by lmangani** [comment]
@almico you can try adding the parameter to the watcher query after the indices to validate if it addresses the scenario - if so we can just add it to the template:
```ignoreUnavailable: true```
