### ISSUE TITLE
"elastic" watcher action fails

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#101]
I tried the ["elastic" watcher action described in wiki](https://github.com/sirensolutions/sentinl/wiki/SENTINL-Watcher-Actions#elasticsearch-index), and it fails.

More precisely, I tried the suggested example in wiki and get this error in logs :
`  log   [16:02:00.053] [error][Sentinl] An error occurred while executing the watch: TypeError: Cannot read property 'message' of undefined`

By the way, I'm not sure to understand fully what this action does :
- which is target index ?
- which is target type ?
- does it index only one doc with all query results inside ? or one doc per query result ?

Here's my complete watcher :
``` json
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "elastic_action",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "at 15:21"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "logstash-*"
          ],
          "body": {
            "query": {
              "query_string": {
                "query": "*"
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 0"
      }
    },
    "transform": {},
    "actions": {
      "to_elastic": {
        "elastic": {
          "priority": "DEBUG",
          "message": "Hit Count : {{payload.hits.total}}"
        }
      }
    }
  }
}
```

**Comment by lmangani** [comment]
This action was briefly used (or at least intended) to log events but has been since decommissioned - should probably be suspended and redesigned to be an easy alternative to the webhook inserts?

**Comment by fbaligand** [comment]
OK, thanks for the explanation !
So, meantime, it could be relevant to remove this action in "watcher actions" wiki page ?

For the future potential redesign, it could be relevant to create a new action called "index" with behavior similar to [Elastic X-Pack Alerting "index" action](https://www.elastic.co/guide/en/x-pack/current/actions-index.html) ?

**Comment by lmangani** [comment]
@fbaligand this is a great idea, fits the purpose - for simplicity could you reopen a new issue with the last suggestion alone? I commented out the section from the wiki in the meantime

**Comment by fbaligand** [comment]
Thanks for wiki update !

As you suggested, I just opened a new issue to add "index" watcher action : #102

**Comment by fbaligand** [comment]
@lmangani 
By the way, thanks for the "collaborator" invitation !
I accept it with pleasure :)
