### ISSUE TITLE
Email alerts not being sent (ES5 branch)

### ISSUE THREAD

**Issue by matejzero** [sirensolutions/sentinl#103]
1. Issue Description
When I have a watcher set up to send an email on alarm, I can see event in log file, but no email is actually sent.

2. Reproducing the Issue step-by-step
Use ES5 branch and set up a simple watcher with send email action.

3. Expected Results vs. Actual Results
I would expect email to be sent, instead only event is logged .

4. Additional Details
In kibana log I see this:
```
Feb 03 15:36:00 example.com kibana[22713]: {"type":"log","@timestamp":"2017-02-03T14:36:00Z","tags":["status","info","KaaE"],"pid":22713,"message":"Executing watch: too_many_acl_hits"}
Feb 03 15:36:00 example.com kibana[22713]: {"type":"log","@timestamp":"2017-02-03T14:36:00Z","tags":["status","info","KaaE"],"pid":22713,"message":"Action Report requires Email Settings! Reports Disabled."}
Feb 03 15:36:00 example.com kibana[22713]: {"type":"log","@timestamp":"2017-02-03T14:36:00Z","tags":["status","info","KaaE"],"pid":22713,"message":"Processing action: admin_email"}
Feb 03 15:36:00 example.com kibana[22713]: {"type":"log","@timestamp":"2017-02-03T14:36:00Z","tags":["status","info","KaaE","email"],"pid":22713,"message":"Subject: SENTINL TEST NOT HTML, Body: Total Hits: 13500"}
Feb 03 15:36:00 example.com kibana[22713]: {"type":"log","@timestamp":"2017-02-03T14:36:00Z","tags":["status","info","KaaE"],"pid":22713,"message":"Storing Alarm to ES with type:admin_email"}
```

Kibana.yml config file:
```
sentinl:
  es:
    timefield: '@timestamp'
    default_index: watcher
    type: watch
    alarm_index: watcher_alarms
  sentinl:
    history: 20
    results: 50
  settings:
    email:
      active: true
      host: localhost
```

Watcher:
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "too_many_acl_hits",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 2 min"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "logs-hw-acl-*"
          ],
          "body": {
            "size": 0,
            "query": {
              "bool": {
                "must": [
                  {
                    "query_string": {
                      "analyze_wildcard": true,
                      "query": "*"
                    }
                  },
                  {
                    "range": {
                      "@timestamp": {
                        "gte": 1486126433600,
                        "lte": 1486127100000,
                        "format": "epoch_millis"
                      }
                    }
                  }
                ],
                "must_not": []
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 100"
      }
    },
    "transform": {},
    "actions": {
      "admin_email": {
        "email": {
          "to": "user@example.com",
          "from": "kibana@example.com",
          "subject": "SENTINL TEST NOT HTML",
          "priority": "high",
          "body": "Total Hits: {{ payload.hits.total }}"
        }
      }
    }
  }
}
```

Same happens if I select webhook... I can see the event in log file, but nothing happens.

This is tested with:

- ES: 5.1.1
- Kibana: 5.1.2
- Kaae: today's ES5 branch

Let me know if more info are needed.

**Comment by cristi-** [comment]
Hi,

 For the 5.x branch sentinl is still kaae from what it seems. I used the old config method, where you enable/disable features in either /opt/kibana/plugins/kaae/kaae.json or /etc/kaae.json. 

This works on the 5.x branch for me:

[root@test kaae]# cat /opt/kibana/plugins/kaae/kaae.json
{
  "es": {
    "timefield":	"@timestamp",
    "default_index":	"watcher",
    "type": 		"watch",
    "alarm_index":	"watcher_alarms"
  },
  "kaae": {
    	"history": 	20,
      "results": 50
  },
  "settings" : {
    	"email" : {
    	   "host":	"localhost",
    	   "ssl":	false,
    	   "active":	true
    	},
    	"slack" : {
    	   "username":	"KAAE",
    	   "hook":	"https://hooks.slack.com/services/<token>",
    	   "channel":	"#kaae",
    	   "active": 	false
    	},
      "report" : {
         "tmp_path" : "/tmp/",
         "active": 	false
      },
      "pushapps" : {
        "api_key" : "<pushapps API Key>",
        "active":	false
    }
  }
}

**Comment by matejzero** [comment]
Great! Thanks for info. Will try tomorrow and close if that solves the problem.

**Comment by matejzero** [comment]
This solved my problem... Mails are now sent.

On the other hand, webhooks still don't work, but I can live with email only for now.

**Comment by lmangani** [comment]
@matejzero thanks for the update, please feel free to open an issue if you need help with the webhooks
