### ISSUE TITLE
How to add a customized action

### ISSUE THREAD

**Issue by wilbur1991** [sirensolutions/sentinl#104]
Hi guys,thanks for your amazing work. I need to add a customized action to send alert. And i have not found any related articles. So how should i add a new action?

**Comment by lmangani** [comment]
Hi @wilbur1991 adding a new action type is quite simple (although not modularized yet) and can be achieved by editing/extending ```server/lib/actions.js``` and cloning the action of your preference as a starting point. Mind any additional nodejs module would have to be added to the dependencies, etc.

Hope this helps!

**Comment by fbaligand** [comment]
I'm curious : what new action do you want to add ?

**Comment by wilbur1991** [comment]
@lmangani thx a lot.
