### ISSUE TITLE
Send webhook over https

### ISSUE THREAD

**Issue by daveres** [sirensolutions/sentinl#108]
Hello,

I have just been trying to send a POST webhook over https but I couldn't.

First try (using example from comments in /server/lib/actions.js):

```
"actions": {
      "telegram_bot": {
        "throttle_period": "1m",
        "webhook": {
          "method": "POST",
          "host": "api.telegram.org",
          "port": 443,
          "path": "/bot<xxx>:<xxx>/sendMessage",
          "body": "{\"chat_id\": <xxx>, \"text\": \"alarma\"}",
          "headers": {
            "Content-Type": "application/json"
          }
        }
      }
    }
```

I receive the following error (kibana in verbose mode)
```
  log   [19:53:00.255] [debug][status][KaaE] Webhook Response: <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.10.0</center>
</body>
</html>
```

Second chance (trying to copy the config for Pushapps in server/lib/actions.js)
```
"actions": {
      "telegram_bot": {
        "throttle_period": "1m",
        "webhook": {
          "method": "POST",
          "host": "https://api.telegram.org",
          "port": 443,
          "path": "/<xxx>:<xxx>/sendMessage",
          "body": "{\"chat_id\": <xxx>, \"text\": \"alarma\"}",
          "headers": {
            "Content-Type": "application/json"
          }
        }
      }
    }
```
I see the following error:
```
  log   [20:02:00.395] [err][status][KaaE] Error shipping Webhook: getaddrinfo ENOTFOUND https://api.telegram.org https://api.telegram.org:443
```

Regards,

**Comment by fbaligand** [comment]
I invite you to use the very last version : 4.6.3-1
With that version, you can set this web hook option :
protocol: "https"

**Comment by daveres** [comment]
Hi Fabien,
A lot of thanks. I forgot to mention that I have been using the branch 5.0 because our ES servers are in 5.0.1.
I have just checked that that this option is in the /server/lib/actions.js for the mentioned version but not in the 5.0 branch. Do you have any idea if this option will be implemented in 5.0?
Regards,

**Comment by fbaligand** [comment]
Sure !
But I can't say you when.

**Comment by daveres** [comment]
Ok, a lot of thanks

**Comment by EricSmekens** [comment]
Can't get this to work, even by specifying "protocol":"https".

**Comment by EricSmekens** [comment]
4.6.4-4
