### ISSUE TITLE
Can't install sentinl for kibana-5.2.1

### ISSUE THREAD

**Issue by simpleuser99** [sirensolutions/sentinl#111]
Hello!

I have kibana-5.2.1 with x-pack.
I tried to install sentinl using the following manual https://github.com/sirensolutions/sentinl/blob/5.0/README.md#app-installation

Result:
I don't see kaae in kibana but 
```
 /usr/share/kibana/bin/kibana-plugin list
kaae@0.5.0
x-pack@5.2.1
```
And I haven't errors during the instalation sentinl

Please, help me install sentinl in kibana-5.2.1.

**Comment by fbaligand** [comment]
Hi @simpleuser99, 

Currently, sentinl/kaae for kibana 5 is under development.

But if you have x-pack, you already have watcher/alerting plugin, no ?

**Comment by simpleuser99** [comment]
@fbaligand  

> Currently, sentinl/kaae for kibana 5 is still under development.
I think, but I want install dev version.
> But if you have x-pack, you already have watcher/alerting plugin, no ?
Yes I have alerting plugin, but this plugin don't have web interface for control it

**Comment by fbaligand** [comment]
OK. I'm surprised by your last remark. You talk about watcher list, alarm list or spy plugin in kibana visualizations ?

**Comment by simpleuser99** [comment]
I'm talking about the alerting plugin as a whole. I don't see any button for alerting plugin in kibana. I think that alerting plugin haven't web interface, but may be I not right?

**Comment by lmangani** [comment]
@simpleuser99 correct

**Comment by fbaligand** [comment]
@simpleuser99 
Sorry, as it's not free, I had not tested Elastic X-Pack Alerting, and was convinced there was at least a basic UI to manage watchers.
Since you have to pay to have X-Pack Alerting plugin, I'm "a little bit" surprised there is no UI at all...

**Comment by simpleuser99** [comment]
@fbaligand I was also surprised when I tried to work with the alerting.

But back to the topic, how I can install sentinl in kibana-5.2.1 ?

**Comment by fbaligand** [comment]
For your problem with kaae/sentinl, the first thing you can do so that it is visible in Kibana is :
- edit $KIBANA_HOME/installedPlugins/kaae/package.json
- update kibana version in entry `"kibana.version": "5.0.2"`
- restart kibana

**Comment by simpleuser99** [comment]
I try it. 
I open /usr/share/kibana/plugins/kaae/package.json and set `"kibana.version": "5.2.1"`
And kibana not working, I have the next error:
```
FATAL TypeError: Cannot read property 'indices' of undefined
    at Object.createKaaeIndex (/usr/share/kibana/plugins/kaae/server/lib/helpers.js:51:15)
    at ScopedPlugin.module.exports [as externalInit] (/usr/share/kibana/plugins/kaae/init.js:20:15)
    at ScopedPlugin.tryCatcher (/usr/share/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.attempt.Promise.try (/usr/share/kibana/node_modules/bluebird/js/main/method.js:30:24)
    at /usr/share/kibana/src/server/plugins/plugin.js:160:44
    at undefined.next (native)
    at step (/usr/share/kibana/src/server/plugins/plugin.js:11:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by fbaligand** [comment]
Yes, you get the next problem...
This branch has been developed, tested and works "nearly well" with Kibana version 5.0.2.
Since this version, this branch development is "taking a break"

**Comment by lmangani** [comment]
Mostly short on hands and time while busy but its not forgotten! Thanks @fbaligand for helping us keep track! ;)

**Comment by kiambogo** [comment]
Very much looking forward to support for 5.2.1 :)

**Comment by lmangani** [comment]
Just an update, the team has expanded and we'll soon have a proper 5.x release :)

**Comment by kayrus** [comment]
@lmangani nice. also looking for 5.x support

**Comment by waseem-presenso** [comment]
We are also waiting forward for this to be compatible with 5.2.2. 
Thanks

**Comment by zxq1002** [comment]
And doesn't support 5.1.1 too, it can be installed without errors, but when click the menu "KaaE",  error occurs with message "Kibana did not load properly. Check the server output for more information."

**Comment by lmangani** [comment]
Any KAAE 5.x will present the same issues, until we release SENTINL for 5.x.
@SergeyBondarenko and Myself are working on a proper release in the coming weeks, keep the faith up!

**Comment by lmangani** [comment]
5.2.2 released for testing - closing old issues to welcome new ones:
https://github.com/sirensolutions/sentinl/releases/tag/tag-5.2.2

**Comment by davidkarlsen** [comment]
What would it take to support 5.4.0?

**Comment by jccq** [comment]
We working on  coordinated releases in the Siren Platform
Sentinl/Kibi/Vanguard (the elasticsearch plugin) . 5.4 will come all
together with the rest. (5.3 soon this or next week. then 5.4)

if there is an urgent commercial grade reason please reach out, happy to
talk about it, info@siren.solutions or as always we're happy to consider PRs

**Comment by fbaligand** [comment]
What is vanguard ?
Did you mean searchguard ?
