### ISSUE TITLE
Cannot copy watcher contents from the browser

### ISSUE THREAD

**Issue by stunndard** [sirensolutions/sentinl#113]
When I open watchers section with some preconfigured watchers, press .... then the watcher code will be expanded, I can select the text and copy, but when I paste it to any text editor I get only "[]" but not the watcher code. I tried both Ctrl + c, and right click -> Copy.

I'm using Windows and the latest Firefox.

**Comment by lmangani** [comment]
@stunndard can you copy when its in "edit" mode or do you get the same issue? I do not have a windows box to test/replicate

**Comment by stunndard** [comment]
I've tried both in edit mode and in read-only mode, It only copies some odd symbol. Tried with notepad, Word, and other text editors.

![copypaste](https://cloud.githubusercontent.com/assets/9940084/24265438/88d8ff44-103e-11e7-80fa-740cc09585fb.png)

The code of alarms, though, can be copied with no problems.

**Comment by lmangani** [comment]
This is probably a windows-specific issue. I'm unable to help but happy to keep this open in case others can.

**Comment by fbaligand** [comment]
Personally, I have no problem to copy/paste Json content, using windows 7 or windows 10.

**Comment by stunndard** [comment]
I confirm again: using Windows 10, Firefox 52.0.1, I can copy and paste JSON from the Alarms tab, but CANNOT copy and paste JSON from the Watchers tab.

**Comment by fbaligand** [comment]
Really surprising.
I just tested with Firefox 52.0.1 and Windows 7, and it worked fine. (yes it is not exactly the same windows version)

**Comment by stunndard** [comment]
I've just tried with IE 11 and it works, though it copies CR instead of CRLF (windows standard) thus all line breaks are messed up.
![ie11](https://cloud.githubusercontent.com/assets/9940084/24298274/74792b3a-10e0-11e7-8971-45e7ecefd6a3.png)

**Comment by fbaligand** [comment]
Interesting...
Maybe you have flash disabled in Firefox or a weird Firefox plugin which blocks copy in some case...

**Comment by fbaligand** [comment]
The line breaks are probably tied to notepad itself.
You could try with a more advanced editor like notepad++ (for instance), you should not have line breaks.

**Comment by lmangani** [comment]
Closing as apparently unrelated to Sentinl/Ace editor itself.
