### ISSUE TITLE
How to get hits[] property in alarms?

### ISSUE THREAD

**Issue by stunndard** [sirensolutions/sentinl#114]
I have the following watcher (sorry for the image I cannot copy and paste the watcher code from the browser, it's another bug which I've already reported):

![sentinl](https://cloud.githubusercontent.com/assets/9940084/24264642/14e59c52-103c-11e7-9e77-67e7985aba11.png)

This watcher looks for any records with status_code = 304 and sends the alarms to slack. My question is how do I access other fields from all fetched records with status_code=304, I have for example url, http_verb, client_ip in my ElasticSearch.

So the alarm in slack looks like this: 
```
Alarm Test, count = 6
alarm = 1, url = /somepath, http_verb = POST, client_ip = x.x.x.x
alarm = 2, url = /anotherpath, http_verb = GET, client_ip = x.x.x.x
....
```

This is how the alarm looks now in Alarms section:
```
{
  "@timestamp": "2017-03-23T18:20:00.074Z",
  "level": "INFO",
  "message": "Alarm Test : 6 [object Object]",
  "action": "kiban",
  "payload": {
    "took": 38,
    "timed_out": false,
    "_shards": {
      "total": 13,
      "successful": 13,
      "failed": 0
    },
    "hits": {
      "total": 6,
      "max_score": 0,
      "hits": []
    }
  },
  "report": false
}
```

Do I need to write some ES script to achieve that? Couldn't find out from the available docs and githib issues...

**Comment by lmangani** [comment]
@stunndard I believe this is simply due to  the ```size: 0``` telling ES to return no actual hits, just counting.
Once you change it to return data, you can iterate it moustache to create the alarm you want using any value in the payload scope. If you need to modify those values for display, you can use a script.

Hope this helps!

**Comment by stunndard** [comment]
Can you please give me an example on how to iterate over the payload data? I've changed size to 2 and payload.hits now contains my data now. However, payload.hits displays only ``[object Object]`` in Slack alarm. And what section of the watcher code should I put that script?

**Comment by lmangani** [comment]
Objects can't be printed directly - you need to point the variable or iterate the objects seeking one.
I suggest you read how Mustache templating works, its as simple as powerful - here's an example where we use it to build an XML document iterating the payload elements: https://github.com/sirensolutions/sentinl/wiki/SENTINL-Random-Examples

Happy to continue helping, closing the ticket as this is a non-issue

**Comment by stunndard** [comment]
Thanks for info, but I still can't figure out how to access payload.hits.hits[]._source where all the data is contained.

This is my alarm:

```
{
  "@timestamp": "2017-03-24T11:25:00.068Z",
  "level": "INFO",
  "message": "Alarm Test : 7 ",
  "action": "kiban",
  "payload": {
    "took": 13,
    "timed_out": false,
    "_shards": {
      "total": 23,
      "successful": 23,
      "failed": 0
    },
    "hits": {
      "total": 7,
      "max_score": 8.532951,
      "hits": [
        {
          "_index": "logstash-2017.03.24",
          "_type": "syslog",
          "_id": "AVsADxkHtYO77BRPUiBX",
          "_score": 8.532951,
          "_source": {
            "message": "[24/Mar/2017:11:23:59.517] 443~ 443_/543181d8ea727b5823de7d6416e89a011dbc5b1e 1007/0/0/6/1013 304 354 - - --VN 1/1/0/0/0 0/0 \"GET / HTTP/1.1\"",
            "@version": "1",
            "@timestamp": "2017-03-24T11:23:59.517Z",
            "type": "syslog",
            "host": "10.42.81.195",
            "syslog_timestamp": "Mar 24 11:24:00",
            "priority": "134",
            "program": "haproxy",
            "client_ip": "",
            "client_port": 50526,
            "haproxy_timestamp": "24/Mar/2017:11:23:59.517",
            "frontend_name": "443~",
            "backend_name": "443__",
            "server_name": "543181d8ea727b5823de7d6416e89a011dbc5b1e",
            "time_client_req": 1007,
            "time_queue": 0,
            "time_backend_connect": 0,
            "time_server_response": 6,
            "time_duration": 1013,
            "status_code": 304,
            "bytes_read": 354,
            "captured_request_cookie": "-",
            "captured_response_cookie": "-",
            "termination_state_with_cookie_status": "--VN",
            "actconn": 1,
            "feconn": 1,
            "beconn": 0,
            "srvconn": 0,
            "retries": 0,
            "srv_queue": 0,
            "backend_queue": 0,
            "http_verb": "GET",
            "http_request": "/",
            "http_version": "1.1"
          }
        },
        {
          "_index": "logstash-2017.03.24",
          "_type": "syslog",
          "_id": "AVsADwUCtYO77BRPUh_5",
          "_score": 8.532951,
          "_source": {
            "message": "[24/Mar/2017:11:23:55.569] 443~ 443__/543181d8ea727b5823de7d6416e89a011dbc5b1e 309/0/2/5/316 304 354 - - --VN 1/1/0/0/0 0/0 \"GET / HTTP/1.1\"",
            "@version": "1",
            "@timestamp": "2017-03-24T11:23:55.569Z",
            "type": "syslog",
            "host": "10.42.81.195",
            "syslog_timestamp": "Mar 24 11:23:55",
            "priority": "134",
            "program": "haproxy",
            "client_ip": "",
            "client_port": 50526,
            "haproxy_timestamp": "24/Mar/2017:11:23:55.569",
            "frontend_name": "443~",
            "backend_name": "443__",
            "server_name": "543181d8ea727b5823de7d6416e89a011dbc5b1e",
            "time_client_req": 309,
            "time_queue": 0,
            "time_backend_connect": 2,
            "time_server_response": 5,
            "time_duration": 316,
            "status_code": 304,
            "bytes_read": 354,
            "captured_request_cookie": "-",
            "captured_response_cookie": "-",
            "termination_state_with_cookie_status": "--VN",
            "actconn": 1,
            "feconn": 1,
            "beconn": 0,
            "srvconn": 0,
            "retries": 0,
            "srv_queue": 0,
            "backend_queue": 0,
            "http_verb": "GET",
            "http_request": "/",
            "http_version": "1.1"
          }
        }
      ]
    }
  },
  "report": false
}
```

I need to send to slack the data from _source, for example "http_request". I'm trying to use the following in my watcher:

```
...
"actions": {
  "kiban": {
    "slack": {
      "channel": "#dev-notify-errors",
      "message": Alarm Test {{ payload.hits.total }} {{ payload.hits.hits[0]._source.http_request }}
    }
  }
}  
...
```

I still get the following in the logs and in the Slack channel:

``{"type":"log","@timestamp":"2017-03-24T11:30:00Z","tags":["status","info","Sentinl","Slack"],"pid":18,"message":"Webhook to ##dev-notify-errors msg: Alarm Test : 5 "}``

So apparently ``payload.hits.hits[0]._source.http_request`` doesn't work. How do I access "http_request" for my case? Can anyone answer this simple question please?

**Comment by lmangani** [comment]
I guess you decided not to read though the mustache documentation.... it's super simple and would greatly help you understand how to answer this simple question. Anyhow, here you go:
```
{{#payload.hits.hits}} {{ _source.http_request }}  {{/payload.hits.hits}}
```
If you opened up the link I sent you would have noticed a link to a jsfiddle - I forked one with your data: http://jsfiddle.net/bab35skk/

Is this lazy-mode enough? ;) 

Enojoy
