### ISSUE TITLE
Kibana 5.0.2 and webhooks

### ISSUE THREAD

**Issue by immavalls** [sirensolutions/sentinl#116]
We are testing sentinl on an ELK stack 5.0.2 using branch 5.0. 

When configuring a Webhook to insert into an elasticsearch cluster, it works.

Configuration looks like this:

```
"webhook": {
          "method": "POST",
          "host": "<elastic_cluster>",
          "port": 9200,
          "path": "/my_index/my_alerts",
          "body": "{\"Id\":\"{{payload.watcher_id\",\"Hostname\":\"my_host\",\"Severity\":\"4\",\"Summary\": \"Elevated value {{payload.aggregations.avg.value}}\"}",
          "headers": {
            "Content-Type": "application/json"
          }
}
```

Logs:

```
log   [07:58:00.009] [info][status][KaaE] Processing action: My_Action
log   [07:58:00.023] [debug][status][KaaE] Webhook Response: {"_index":"mos","_type":"alerta","_id":"AVtCRSdNAbCL4tX2KynO","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"created":true}
```

When changing configuration to send the alerts to a different server - IBM Tivoli, we can't see any Webhook Response in the logs, nor errors. We've also tried to not inform path, since there's none on the server.

```
"webhook": {
          "method": "POST",
          "host": "<tivoli_server>",
          "port": 80,
          "path": "/",
          "body": "{\"Id\":\"{{payload.watcher_id\",\"Hostname\":\"my_host\",\"Severity\":\"4\",\"Summary\": \"Elevated value {{payload.aggregations.avg.value}}\"}",
          "headers": {
            "Content-Type": "application/json"
          }
}
```

Logs:

`log   [08:01:00.024] [info][status][KaaE] Processing action: My_Action`

Sending a request to the Tivoli server via curl from Kibana machine works, so we don't suspect any network or Tivoli server issues.

Is there a way to see what's going on, if the webhook is trying to send anything, and what is sending?

Thanks.

**Comment by lmangani** [comment]
Hi @immavalls is your loglevel already set to DEBUG? This might provide further details. I'm assuming the watcher condition is not returning true thus dropping further processing.

**Comment by immavalls** [comment]
We configured Kibana on debug. That's how we get this log when it works.

`log   [07:58:00.023] [debug][status][KaaE] Webhook Response: {"_index":"mos","_type":"alerta","_id":"AVtCRSdNAbCL4tX2KynO","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"created":true}`

Is there anything we can add in terms of logging to see more info? 

REgarding the alert, for testing purposes we have a watcher that always generates an alert. When the webhook points to elasticsearch cluster, we are able to see a new document every minute (as scheduled). When we change the webhook to point at our Tivoli Server, we don't receive anything. And in our kibana logs we don't see the "Webhook response", although the line "Processing Action" appears.

**Comment by lmangani** [comment]
This might be a simple firewalling issue - can you exclude that is the case? You can also ngrep for webhooks being sent over the network and see if they ever originate.

**Comment by immavalls** [comment]
We are not able to run ngrep on that server (limited permissions...), sorry. That's why I was aiming for a log that could tell us what's happening. 
We were ruling out firewall issues nonetheless, since a curl command (for that we do have permissions) reaches the remote Tivoli server.

**Comment by lmangani** [comment]
Dejavu.... Could you post the configuration you are using, replacing the URLS/IPs?

**Comment by lmangani** [comment]
Trying to replicate this again, is the query example you posted 1:1 accurate? (spaces, commas, escapes, etc)

**Comment by lmangani** [comment]
5.2.2 released for testing - closing old issues to welcome new ones:
https://github.com/sirensolutions/sentinl/releases/tag/tag-5.2.2

**Comment by cissecedric** [comment]
Hi 
@immavalls , I'm facing the same issue, could you please tell me how did you manage to enable your tivoli server to be able to receive webhook posted by sentinl ?

**Comment by immavalls** [comment]
Hi @cissecedric. We stopped trying. Without plugin logs and no sysadmin privileges on the server we couldn't go forward. We've finally bought elastic's x-pack and are using watcher.

**Comment by lmangani** [comment]
@immavalls we could have definitely solved this, so that's a shame. 
anything different in the watcher configuration resulting in a successful post?
We have a bunch of users using webhooks without issues so this puzzles me plenty.

**Comment by cissecedric** [comment]
@immavalls , thank you for your answer. The main problem I m facing is finally with Tivoli server.. where/how did you configured it to be able to receive http post ? Could you please give me a link that describe how to enable tivoli server to receive webhook ? That would be great !
many thanks,

**Comment by cissecedric** [comment]
Hi,
@immavalls , sorry I will just try one last time... ;-) 
Do you have any information to give me about how did you manage to make IBM Tivoli server able to receive Http post requests ? One month after, I still don't have no idea about how is it possible.
Thank you in advance !
