### ISSUE TITLE
Index an alert into ES including all fields of the alert document.

### ISSUE THREAD

**Issue by SergeyBondarenko** [sirensolutions/sentinl#117]
Original request message: 

Indicizzare gli alert (con info degli stessi documenti che hanno causato l'alert)
1. regole di cross correlazione
2. storico, dashboarding, studio e analisi

**Comment by lmangani** [comment]
Can we post an example, just to make sure we nail this on the head?

PS: The query response is already saved as non-searchable object in ES to save on indexing and greatly simplify mapping, but can be changed to be indexed as well.

**Comment by lmangani** [comment]
Closing and moved to Dev
