### ISSUE TITLE
Kibana 5 - Webhook over HTTPS

### ISSUE THREAD

**Issue by rifqifatih** [sirensolutions/sentinl#119]
Hello everyone!

I'm currently testing sentinl on Kibana 5. The problem is I can't send my webhook action over https by using `options.protocol` as suggested in #108 by adding few lines in `actions.js`, and i got the following error

```
Unhandled rejection Error: Protocol "https" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:55:11)
    at Object.exports.request (http.js:31:10)
```

The workaround for me was changing the line in `actions.js` to `var http = require('https')`

I'm new to node js development, and from the error log i see, is it correct that node http api doesn't support https protocol? does the project plans on using the node https api?

**Comment by fbaligand** [comment]
Actually, "protocol" option has not been yet added on sentinl 5.0 branch.

**Comment by lmangani** [comment]
We're getting there! SENTINL 5.x Release time should be by May.

**Comment by fbaligand** [comment]
@lmangani
Great news !
I'm impatient to test it !
