### ISSUE TITLE
Kibana 5.0.2 and webhooks path error ? 

### ISSUE THREAD

**Issue by hailin0** [sirensolutions/sentinl#120]
input
--------------------------------
      "my_webhook": {
        "throttle_period": "1m",
        "webhook": {
          "method": "POST",
          "host": "192.168.1.1",
          "port": 9200,
          "path": "{{payload.hits.hits[0]._index}}/_forcemerge",
          "body": "",
          "headers": {
            "Content-Type": "application/json"
          }
        }
      }

output
------------------------------

"Webhook Response: {\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\

path: http://192.168.1.1:9200/{{payload.hits.hits[0]._index}}/_forcemerge

How is this to return a responsibility excuse me ?

**Comment by hailin0** [comment]
@lmangani 
Hello：
 can you help me. Thank you very much!

**Comment by lmangani** [comment]
You're going to have a to wait a few weeks for sentinl 5.x to be released, sorry! Everything should work then, including the new features we since implemented. Kaae 5.x is obsoleted
