### ISSUE TITLE
can't install sentinl plugin in kibana-5.4.0

### ISSUE THREAD

**Issue by hemasalma** [sirensolutions/sentinl#121]
Hello,

we tried to install sentinl plugin through the command 

kibana plugin install sentinl url https://github.com/sirensolutions/sentinl/releases/download/snapshot/sentinl-latest.tar.gz

we got the error:
/download/snapshot/sentinl-latest.tar.gz Attempting to transfer from sentinl
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/sentinl/sentinl-5.4.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."

when i try to install using url i got the following error

error:

apshot/sentinl-latest.tar.gz
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/snapshot/sentinl-latest.tar.gz
Transferring 2214505 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /home/abc/kibana-5.4.0-linux-x86_64/node_modules/yauzl/index.js:179:14
    at /home/abc/kibana-5.4.0-linux-x86_64/node_modules/yauzl/index.js:539:5
    at /home/abc/kibana-5.4.0-linux-x86_64/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

so can i know the procedure to install sentinl?

**Comment by lmangani** [comment]
5.x is not yet release and should be out in the coming weeks. We have a dev-only branch, but its still not fully functional or syncronized with the latest features. Keep an eye on the repository!

**Comment by hemasalma** [comment]
Hello,

Do we have any other previous versions to download?
