### ISSUE TITLE
not able to install the plugin

### ISSUE THREAD

**Issue by elieyaza** [sirensolutions/sentinl#122]
1. Issue Description
my machine is centos 7
kibana: 5.2.2
i tried to installing using Snapshot Plugin Install
i got the error 
 ERROR  unknown command plugin

so i have downloaded the zip file to the server and i have run the command
 kibana/bin/kibana-plugin install   file:///root/sentinl-master.zip
i get the error 
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

i have tried to rename the sentinl-master.zip to sentinl.zip and i put it under /usr/share/kibana also i got the same error response

it tried using Manual Plugin Install, i got the following errors. i have the lateste version of npm and node.json

npm WARN angular-ui-bootstrap@0.13.4 requires a peer of angular@^1.3.x || >= 1.4.0-beta.0 || >= 1.5.0-beta.0 but none was installed.
npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "--production"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/sentinl/npm-debug.log

2. Reproducing the Issue step-by-step

3. Expected Results vs. Actual Results

4. Additional Details

**Comment by fbaligand** [comment]
Hi, 
I invite you to test with sentinl 5.2.2 release : 
https://github.com/sirensolutions/sentinl/releases/download/tag-5.2.2/sentinl-latest.tar.gz

**Comment by zxq1002** [comment]
Unable to install sentinl 5.2.2 release through "./bin/kibana-plugin install" command（kibana 5.x doesn't support "./bin/kibana plugin --install xxx" command anymore）. My kibana version is v5.1.1.
So I download the archive file of "https://github.com/sirensolutions/sentinl/releases/download/tag-5.2.2/sentinl-latest.tar.gz", and unpack to kibana plugin directory, then modify the version configuration in package.json to 5.1.1, at last run "npm install".
after that, i run kibana with development mode （--dev）, and click the menu "Sentnl" on the left, nothing is returned with white page... The console of Chrome Dev Tool output error info: "VM1188:1 GET https://localhost:5601/zhu/api/sentinl/example 404 (Not Found)"

**Comment by lmangani** [comment]
@elieyaza 5.2.2 branch readme updated with the correct instructions

**Comment by elieyaza** [comment]
hello,

always, same problem. using the command
/usr/share/kibana/bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.2.2/sentinl-latest.tar.gz


the error is : 
Error: Could not find the End of Central Directory Record
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"


also i tried donwloading it to install the plugin always with no success

**Comment by SergeyBondarenko** [comment]
@elieyaza do you have any errors in the browser, browser console or in the kibana log?

**Comment by fbaligand** [comment]
Hi @SergeyBondarenko ,

After some tests, it seems that https://github.com/sirensolutions/sentinl/releases/download/tag-5.2.2/sentinl-latest.tar.gz is a tar archive and not a tar.gz archive.

**Comment by fbaligand** [comment]
OK, to successfully install sentinl plugin, I had to do these actions :
- rename "sentinl-latest.tar.gz" to ".tar"
- untar content
- create a wrapping folder "kibana" (I mean : "kibana" as parent folder of "sentinl")
- zip "kibana" directory
- install the plugin using this command :
`/kibana/bin/kibana-plugin install file:///path/to/sentinl.zip`

**Comment by VincentNgai86** [comment]
Try to follow but seems not success
repacking.. kibana/sentinl/
then zip kibana
tar -zcvf sentinl.zip kibana
/usr/share/kibana/bin/kibana-plugin install file:///{mypath}/sentinl.zip

Result in 
Attempting to transfer from file:///home/deployer/tmp/sentinl.zip
Transferring 4355756 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: Could not find the End of Central Directory Record
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

**Comment by fbaligand** [comment]
If you use "tar -zcvf" command, you generate a ".tar.gz" archive (even if you name it ".zip")
To generate a zip file, I invite you to use "zip" command.

**Comment by SergeyBondarenko** [comment]
I updated the [tag-5.2.2](https://github.com/sirensolutions/sentinl/releases/tag/tag-5.2.2) with correct tar.za archive.

**Comment by SergeyBondarenko** [comment]
I updated the [tag-5.2.2](https://github.com/sirensolutions/sentinl/releases/tag/tag-5.2.2) with the correct tar.gz archive.

**Comment by fbaligand** [comment]
I just tried your last archive, and it doesn't work.
For having several tests yesterday, Kibana 5.2.2 requires a zip file and a "kibana" wrapping folder.

Here's a valid plugin archive (works on my host), build from your ".tar.gz" :
[sentinl-5.2.2.zip](https://github.com/sirensolutions/sentinl/files/1024758/sentinl-5.2.2.zip)

**Comment by SergeyBondarenko** [comment]
@elieyaza strange, I did the following and it works for me:
```
cd ~/Dev/kibi/plugins
wget https://github.com/sirensolutions/sentinl/releases/download/tag-5.2.2/sentinl-latest.tar.gz
tar -xzvf sentinl-latest.tar.gz
```

**Comment by fbaligand** [comment]
@SergeyBondarenko It works now, because now, the file is a real ".tar.gz" and not a ".tar" named ".tar.gz".
That said, it would be great to add in 5.2.2 release, the zip archive so that everybody can install sentinl plugin using `kibana-plugin install ...`

**Comment by fbaligand** [comment]
Hi @SergeyBondarenko 
I saw that you added sentinl-5.2.2.zip into release => thanks for that !
That said, I realized that in the zip file you released, sentinl plugin is present at 2 locations :
- sentinl
- kibana/sentinl

It would be great that you remove "sentinl" root folder in ZIP archive.

**Comment by SergeyBondarenko** [comment]
@elieyaza please try the latest release https://github.com/sirensolutions/sentinl/releases/tag/tag-5.3.2, the command is 
```
./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.3.2/sentinl.zip
```

**Comment by SergeyBondarenko** [comment]
@elieyaza we produced several new releases, you can check them here https://github.com/sirensolutions/sentinl/releases. Please feel free to re-open this issue if you still have the problem.
