### ISSUE TITLE
Version 5.2.2  - Error 504 Gateway Time-out: undefined

### ISSUE THREAD

**Issue by VincentNgai86** [sirensolutions/sentinl#123]
Setup environment
Ubuntu 16
--------------------
elasticsearch - 5.4
kibana - 5.2.2
logstash - 5.2.2
-------------------
Plugin install in elasticsearch
analysis-icu
ingest-geoip
ingest-user-agent
readonlyrest
repository-s3

Plugin install in Kibana
sentinl@5.2.2-SNAPSHOT

I am success to installed sentinl 5.2.2 Version and startup
however when i click into the plugin tab
it show me Error 504 Gateway Time-out: undefined
![screen shot 2017-05-25 at 9 43 18 am](https://cloud.githubusercontent.com/assets/24584190/26432518/dad60c44-412e-11e7-9d9f-1be27c86fb73.png)

I try disabled readonlyrest (which is control permission) and restart , but it show same result 

What do i miss ?

**Comment by lmangani** [comment]
Could you please attach the relevant logs emitted by Kibana on startup of Sentinl and when triggering the above error for better understanding?

**Comment by VincentNgai86** [comment]
Yes


**# Kibana Log**

{"type":"response","@timestamp":"2017-05-25T08:30:49Z","tags":[],"pid":16908,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/example","method":"get","headers":{"connection":"upgrade","host":"{myhost}","accept":"application/json, text/plain, */*","kbn-version":"5.2.2","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36","referer":"http://{myhost}/app/sentinl","accept-encoding":"gzip, deflate, sdch","accept-language":"en-GB,en-US;q=0.8,en;q=0.6"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://{myhost}/app/sentinl"},"res":{"statusCode":200,"responseTime":1,"contentLength":9},"message":"GET /api/sentinl/example 200 1ms - 9.0B"}

{"type":"response","@timestamp":"2017-05-25T08:30:49Z","tags":[],"pid":16908,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/set/interval/%7B%22from%22:%22now-15m%22,%22to%22:%22now%22,%22mode%22:%22quick%22%7D","method":"get","headers":{"connection":"upgrade","host":"{myhost}","accept":"application/json, text/plain, */*","kbn-version":"5.2.2","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36","referer":"http://{myhost}/app/sentinl","accept-encoding":"gzip, deflate, sdch","accept-language":"en-GB,en-US;q=0.8,en;q=0.6"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://{myhost}/app/sentinl"},"res":{"statusCode":200,"responseTime":2,"contentLength":9},"message":"GET /api/sentinl/set/interval/%7B%22from%22:%22now-15m%22,%22to%22:%22now%22,%22mode%22:%22quick%22%7D 200 2ms - 9.0B"}

{"type":"response","@timestamp":"2017-05-25T08:30:49Z","tags":[],"pid":16908,"method":"get","statusCode":304,"req":{"url":"/bundles/4b5a84aaf1c9485e060c503a0ff8cadb.woff2","method":"get","headers":{"connection":"upgrade","host":"{myhost}","origin":"http://{myhost}","if-none-match":"\"574ea2698c03ae9477db2ea3baf460ee32f1a7ea\"","if-modified-since":"Wed, 24 May 2017 09:12:21 GMT","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36","accept":"*/*","referer":"http://{myhost}/bundles/commons.style.css?v=14723","accept-encoding":"gzip, deflate, sdch","accept-language":"en-GB,en-US;q=0.8,en;q=0.6"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://{myhost}/bundles/commons.style.css?v=14723"},"res":{"statusCode":304,"responseTime":1,"contentLength":9},"message":"GET /bundles/4b5a84aaf1c9485e060c503a0ff8cadb.woff2 304 1ms - 9.0B"}


**# Nginx Log**

25/May/2017:08:30:54 +0000|GET|http|80|{myhost}|/api/sentinl/list/alarms|CLIENTIP|504|http://{myhost}/app/sentinl|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36|762|5.001|-

**Comment by SergeyBondarenko** [comment]
@VincentNgai86 please try the latest release https://github.com/sirensolutions/sentinl/releases/tag/tag-5.3.2
