### ISSUE TITLE
Condition Error for new_watcher_ypuiw4xhk: SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by thanh3d** [sirensolutions/sentinl#124]
For conditon, I put as below: 
> {
>       "inline": "return ctx.payload.hits.total > threshold",
>       "params": {
>         "threshold": 0
>       }
> }
> 

1. Issue Description

> Condition Error for new_watcher_ypuiw4xhk: SyntaxError: Unexpected token :

E.S 5.2.2 and kibi 5.2-beta1

**Comment by lmangani** [comment]
Hi @thanh3d 
We don't support such syntax in SENTINL yet, currently scripts are pure JavaScript:
```
"condition": {
      "script": {
        "script": "payload.hits.total > 0"
      }
    },
    "transform": {
      "script": {
        "script": "payload.hits.total += 100"
      }
    }
```

**Comment by thanh3d** [comment]
thanks, but not sure I still got error when applied conditon above.

> Sentinl] Condition Error for new_watcher_ypuiw4xhk: SyntaxError: Unexpected token :

**Comment by SergeyBondarenko** [comment]
@thanh3d  please try the latest release https://github.com/sirensolutions/sentinl/releases/tag/tag-5.3.2

**Comment by SergeyBondarenko** [comment]
@thanh3d in the Transform tab, you need to configure it like this:
![screenshot from 2017-05-29 18-25-24](https://cloud.githubusercontent.com/assets/5389745/26556687/492f69ea-449c-11e7-9d9f-b7d611cf1360.png)
But, in the Raw tab like this:
![screenshot from 2017-05-29 18-26-29](https://cloud.githubusercontent.com/assets/5389745/26556717/7834f21e-449c-11e7-9464-8c9c7019f9d1.png)

**Comment by fbaligand** [comment]
Simply click on "Save" button, and the "Raw" tab content will be updated.
