### ISSUE TITLE
Multiline Transform script?

### ISSUE THREAD

**Issue by eyalzek** [sirensolutions/sentinl#129]
I'm testing version 5.3.2 locally (https://github.com/sirensolutions/sentinl/releases/download/tag-5.3.2/sentinl.zip) and it is unclear to me what exactly is the format for the `Transform` script?
When I run a one liner like:
`payload.failedJobs = payload.hits.hits.map(function(x){ return x._source.message.split("\'")[1]});`

I'm getting the data and the trigger without an issue. I've been also trying to create a more complicated script with functions, etc:

```
payload.failedJobs = getRelevantFailures(payload.hits.hits);

function getRelevantFailures(jobs) {
    var relevant = [];
    var _now = new Date();
    
    for (var i = 0; i < jobs.length; ++i) {
        if (minsSinceFailure(jobs[i], _now) < 1000) {
            relevant.push(jobs[i]._source.message.split("\'")[1]);
        }
    }
    
    return relevant;
}

function minsSinceFailure(job, now) {
    var t = new Date(job._source['@timestamp']);
    return ((now - t) / 1000 / 60);
}
```

it seems like the entire block is ran using `eval` (https://github.com/sirensolutions/sentinl/blob/37981d673d209c50294717db9d1851cc6a7d5d5d/server/lib/scheduler.js#L158) and when I test locally with the same data structure and I evaluate this piece of code, I get the expected result, but using `sentinl`, the action for that watcher is not executed. The condition in this case is: `payload.failedJobs.length > 0`

I'm also not seeing any errors in the debug output from sentinl.

Is there a limit of lines/statement? Is there an example of a multinline `Transform` script somewhere? Can I set more than one attribute on the `payload` object?

**Comment by eyalzek** [comment]
Actually I notice now that I'm getting:
`TypeError: Cannot read property 'length' of undefined`

so I guess that `payload.failedJobs` is not getting set?

**Comment by lmangani** [comment]
@eyalzek regardless of the internal processing and/or new payload values being calculated or added, the scripts should always return a true condition in order for execution to be triggered.

**Comment by eyalzek** [comment]
@lmangani I'm not sure I understand what you mean by returning a true condition? in the `Transform` section? in which part?

I found an example here https://github.com/sirensolutions/sentinl/wiki/Statistical-Anomaly-Detector which I tried to implement and I'm still seeing the same result.

**Comment by eyalzek** [comment]
Ok I understood what you mean, I cannot use `payload.failedJobs` in the script condition since it is undefined before the transform is completed... What would be the correct way to trigger on a custom value?

**Comment by lmangani** [comment]
Condition and Transform in SENTINL are quite similar and just sharing the workload at different stages, where condition is intended to be lightweight (to efficiently discard events fast) and the second can drill down selective events. Condition can also contain a full script before its true/false status is returned explicitly (```return true;```) or by mean of an operation (```payload.something > 0```). 

For your case, I think you should declare ```getRelevantFailures``` before using it in order for the inline script to actually work. Could you give that a shot?

**Comment by eyalzek** [comment]
Since the entire logic of my operation was to filter events that have happened in a certain period, I updated my `input` accordingly to filter that specific range. This feels like the best way to go at it anyway.

Thanks for the help! maybe it's worth documenting the fact that the condition cannot contain "custom" fields which are added in the `transform` part?

**Comment by lmangani** [comment]
Conditions can define variables for Transform variables to find when well formed, while the opposite is not true.
