### ISSUE TITLE
Add support for configuration via environment variables

### ISSUE THREAD

**Issue by eyalzek** [sirensolutions/sentinl#130]
Having the option to configure action settings (e.g: email credentials, slack hooks, etc) via environment variables would make running kibana+sentinl on a container platform such as `Marathon` easier, giving the option to inject configuration according to environment (staging/production/etc).
I'm not sure how straightforward of a change is it, but would definitely be nice to have as an enhancement in the future.

**Comment by fbaligand** [comment]
@eyalzek 
I think it is more an issue to open on Kibana itself.

**Comment by eyalzek** [comment]
Hm, I guess you are right!
