### ISSUE TITLE
Spy Set Watcher button : "Ready! Continue Editing in Sentinl" button does not work

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#131]
Tested with Kibana 5.4.0 and last sentinl 5.4.0 release and Firefox 53.0.3 :
- I choose a visualization
- I click on "Set Watcher" spy button
- define all parameters, with one webhook action
- and when I click on "Ready! Continue Editing in Sentinl" button, the sentinl app is launched in a new tab, but without my new watcher added to the watchers list.

Here's my watcher definition :
![image](https://cloud.githubusercontent.com/assets/3750300/26587067/8a26a0b6-4551-11e7-9e55-e6d5bff5e4c4.png)

**Comment by shamil** [comment]
Experiencing exactly same issue, sentinl `5.4.0`

**Comment by lmangani** [comment]
We're refactoring the SPY plugin to pass data into our new wizard - stay tuned.

**Comment by fbaligand** [comment]
For information, I don't reproduce the issue since I remove kibana-time-plugin.
This plugin has negative impact on Kibana itself and sentinl plugin.

**Comment by mobdns** [comment]
have the exact same problem - kibana 5.4.3 with latest sentinl release.

**Comment by fbaligand** [comment]
@mobdns
Do you have kibana-time-plugin installed on your kibana instance ? If yes, I invite you to remove it.

**Comment by mobdns** [comment]
I think i have found what causing this. When i create visualization against time-based index, and when i click on the "Set Watcher" button in the console i see the following:

commons.bundle.js?v=15122:38 TypeError: Cannot set property 'filter' of undefined
    at ChildScope.$scope.makeAlarm (kibana.bundle.js?v=15122:282)
    at kibana.bundle.js?v=15122:282
    at Object.fn (commons.bundle.js?v=15122:91)
    at Scope.$digest (commons.bundle.js?v=15122:39)
    at ChildScope.$apply (commons.bundle.js?v=15122:39)
    at HTMLAnchorElement.<anonymous> (commons.bundle.js?v=15122:42)
    at HTMLAnchorElement.dispatch (commons.bundle.js?v=15122:28)
    at HTMLAnchorElement.elemData.handle (commons.bundle.js?v=15122:28)

On the same index with unselected checkmark (Index contains time-based events )in kibana index patern does not produce this kind of error and the button is working fine.

**Comment by mobdns** [comment]
As a workaround enclose with quotes your watcher indices for ex:
`"<logstash-{now/d}>","<logstash-{now/d-1d}>"`

**Comment by lmangani** [comment]
reopen if still needed. the spy button will be replaced in future versions with integrated kibana tools.
