### ISSUE TITLE
hi,when will this sentinl can support the new version 5.4.0 of elasticsearch and kibana? 

### ISSUE THREAD

**Issue by dubingchao** [sirensolutions/sentinl#134]
1. Issue Description

2. Reproducing the Issue step-by-step

3. Expected Results vs. Actual Results

4. Additional Details

**Comment by lmangani** [comment]
It does already https://github.com/sirensolutions/sentinl/releases/tag/tag-5.4.0

**Comment by dubingchao** [comment]
i have try this version.but it did not work.
first,when click the sentinl button.it loads slowlly.and did not show anything.but when i click twice,it show the sentinl window,and after kibana response "kibana did not load properly". I have no idea what is wrong.

**Comment by lmangani** [comment]
please open an issue for this incident on the repository and attach the Kibana logs displaying the error, or a screenshot, etc Thanks!
