### ISSUE TITLE
need twice show window,then kibana respose wrong!

### ISSUE THREAD

**Issue by dubingchao** [sirensolutions/sentinl#135]
1. Issue Description
i use tag-5.4.0 version,installing OK.
first,when click the sentinl button.it loads slowlly.and did not show anything.but when i click twice,it show the sentinl window,and after, kibana response "kibana did not load properly,Check the server output for more information".

2.Here is the screen shot and log.
![image](https://cloud.githubusercontent.com/assets/25807326/26720989/bd94cbf4-47bc-11e7-853f-719a3ff7b487.png)
[kibana.txt](https://github.com/sirensolutions/sentinl/files/1047326/kibana.txt)

Looking forward to your response. Thanks~

**Comment by fbaligand** [comment]
In kibana.txt, I saw no error/warning.
Maybe you can try to delete $KIBANA_HOME/optimize/* and then restart Kibana so it regenerate optimized files correctly ?

**Comment by cshudson** [comment]
I meet the same error too. My ES&Kibana version is also v5.4.0, and the kibana's output(with --verbose) does not show any error or warnings. Looking forward to it. THX.

**Comment by SergeyBondarenko** [comment]
@cshudson @dubingchao have you tried to delete everything in `$KIBANA_HOME/optimize/*` folder and restart Kibana?

**Comment by dubingchao** [comment]
I have tried to delete,but it not working.what next i can do?

**Comment by dubingchao** [comment]
Maybe this is connected with timezone setting? I Inadvertently change the timezone from browser to other.but when sentinl goes wrong,the setting is changed back automatically。Hope this message will help
