### ISSUE TITLE
Requests being made to `/api/reporting/jobs/list_completed_since`

### ISSUE THREAD

**Issue by eyalzek** [sirensolutions/sentinl#136]
I'm using sentinl 5.3.2 on several environments, since I installed the plugin I see requests on the kibana logs similar to:
`/api/reporting/jobs/list_completed_since?....`

this is not a major problem on environments where the reporting feature is under trial - but since we do not actually use `reporting` and therefore do not have a license for it, on other environments the kibana log is flooded with 403 responses to those request, or 404 if I set:
`xpack.reporting.enabled: false` in the `kibana.yml` file.

I'm not exactly sure where this is coming from, since it happens immediately when I run kibana with the `sentinl` plugin installed, even when no watchers or reports are configured.

What generates all of these requests? Can this be disabled somehow?

**Comment by lmangani** [comment]
HI @eyalzek 
I'm afraid those are not related to SENTINL in any way, and rather look as remains of an X-Pack reporting setup still in place. The SENTINL API calls should all look like ```/api/sentinl/...```

**Comment by lmangani** [comment]
Re-Opening, Picked the wrong button.

**Comment by eyalzek** [comment]
As you said, this is unrelated to sentinl. After rolling out kibana without the `X-Pack` plugin, those requests seem to go away.
