### ISSUE TITLE
Recursive console payload

### ISSUE THREAD

**Issue by bwoodbury3** [sirensolutions/sentinl#139]
1. Issue Description
An action payload includes the log result from Elasticsearch which caused a previous action. Each successive action will include the previous action's metadata and this eventually builds a giant heap of JSON if left unchecked.

2. Reproducing the Issue step-by-step
Create an action with the following input:
`"query": {
    "range": {
      "@timestamp": {
        "from": "now-1m"
      }
    }
}`
Then, create a condition:
`payload.hits.total > 0`

3. Expected Results vs. Actual Results
I would expect Sentinl to truncate the console payload or ignore its own metadata in a search.  Instead, I get a payload that resembles this (at a high level):
`Console Payload: {`
`hits: { Console Payload {`
`hits: { Console Payload {`
`hits: { Console Payload {`
`}}}}}}}`
What's happening is that Sentinl's metadata is being stored in Elasticsearch, which triggers the action.  This action is stored in Elasticsearch, so it triggers an action at the next minute.
This action is stored in Elasticsearch, so it triggers an action at the next minute.
This action is stored in Elasticsearch, so it triggers an action at the next minute, and so on.
Triggering the action is annoying enough in itself, but the data from each action also piles up recursively.

4. Additional Details
This is a little petty, but I think that Sentinl's metadata should be abstracted away from the user better, since this isn't data that I want to include as part of my alerting/monitoring.
If there is a way to configure this off, then please let me know! But I also think that should be a default option.

**Comment by lmangani** [comment]
Hi @bwoodbury3 thanks for the excellent report. It should be possible to disable internal logging of events using the ```stateless``` option for actions (needs some testing) or by explicitly excluding SENTINL indices from the queries or viceversa targeting the query, unless I misunderstood your scenario.

**Comment by lmangani** [comment]
Extension: you can drop the original payload at the script level if you only want to store your interpolation.
Feel free to reopen this if you are still using sentinl and gathered further results/experience meanwhile.
Thanks!
