### ISSUE TITLE
Cluster Aware?

### ISSUE THREAD

**Issue by LazyDBA247-Perion** [sirensolutions/sentinl#14]
Hi,
When i install 2+ kibana services to have a load balancer between them, so i can have high availability for the user dashboards/reports, both service are using the same .kibana index to save get the dashboards and it doesn't mater which server the user gets.

how kaae is going to behave when installed more the once per elasticsearch cluster, will the alerts be fired twice?

maybe in a multi service install there should be a "Heartbeat" that all services will register, and update a index with what host/node is now live and taking care of alerts, but when not reporting more than 1 minute, electing another node/host  to handle the alarms?

10x!

**Comment by lmangani** [comment]
KAAE runs in Kibana, and sends queries to the ES Cluster Kibana is configured to use. As long as you don't run multiple Kibana/Kaae pairs and your load balancer is transparent, there should be no impact.

**Comment by LazyDBA247-Perion** [comment]
but to achieve high availability you **do install** multiple kibana/kaae, so currently the alerts will be send twice?
do you think you'll add support for this?

**Comment by lmangani** [comment]
Sure, we just need to come up with a good strategy, or mimic whatever the mothership Watcher is using. Input and proposals here are extremely welcome, hopefully new users and developers will come onboard with valuable suggestions and ideas  _(...or code contributions!)_

**Comment by chenryn** [comment]
Only find a word of "Make sure Watcher is installed on every node in the cluster." in watcher's troubleshooting document.
I think there is a fast way to implement: just decide whether to send email by check the version of alert history.
A better but complex way is just what @LazyDBA247-Perion suggest, use a special index to record the state of kaae daemons.

**Comment by lmangani** [comment]
It's been a long time, picking up this after a long pause as we ship firmly towards the future.

An ongoing idea is to leverage GunDB (gundb.io) a new-school distributed graph "database" (but not really) to create an independent cluster of Sentinls and as a centralized location to keep watcher statuses and other elements critical to the distribution of the tasks and/or saved scripts. Being natively developed in NodeJS provides clear advantages as well as shipping with synchronization, automatic conflict resolution and offline-first behaviour. We can even represent it graphically ;)

I'll be prototyping a model in the coming weeks. If anyone cares to join in the discussion, let's talk!

**Comment by lmangani** [comment]
Closing this in favor of future discussion on recent versions.
