### ISSUE TITLE
Can not delete watcher > "Error 404 Not Found: undefined"

### ISSUE THREAD

**Issue by uschtwill** [sirensolutions/sentinl#141]
1. Issue Description
I am trying to delete a watcher but get the message "Error 404 Not Found: undefined" as a red alert at the top of the Browser.

2. Reproducing the Issue step-by-step
Trying to delete a watcher...

3. Expected Results vs. Actual Results
I was able to delete watchers before. It worked. That's what I'd expect.

4. Additional Details
Restarted Kibana, no change in behaviour.
Kibana 4.6.1

**Comment by SergeyBondarenko** [comment]
What Sentinl release do you use, [4.6.4-4](https://github.com/sirensolutions/sentinl/releases/tag/tag-4.6.4-4)?

**Comment by uschtwill** [comment]
What is the most straight forward way to get the version number?

**Comment by szydan** [comment]
@uschtwill 
Look inside plugins/sentinl/package.json

**Comment by uschtwill** [comment]
Thanks @szydan! 

4.6.3

**Comment by fbaligand** [comment]
In that case, I invite you to test the last 4.x version : 4.6.4-4
https://github.com/sirensolutions/sentinl/releases/tag/tag-4.6.4-4

**Comment by uschtwill** [comment]
Thanks, will try on Monday and let you know how I do. :)

Fyi, I think https://github.com/sirensolutions/sentinl/releases/download/snapshot/sentinl-latest.tar.gz as in `/opt/kibana/bin/kibana plugin --install sentinl -u https://github.com/sirensolutions/sentinl/releases/download/snapshot/sentinl-latest.tar.gz` found [here](https://github.com/sirensolutions/sentinl/wiki/SENTINL-Installation 
) is pointing to the wrong build/snapshot/release.

**Comment by fbaligand** [comment]
Yes , this doc is obsolete and needs to be updated. 
Because it depends which kibana version you have. 
Si I invite you to download "sentinl.zip" in this release to be sure to get the right version :
https://github.com/sirensolutions/sentinl/releases/tag/tag-4.6.4-4

**Comment by uschtwill** [comment]
But those are the only and authoritative docs, right?

**Comment by lmangani** [comment]
Wiki instructions updated

**Comment by fbaligand** [comment]
@lmangani 
I think it would be nice to have 2 sections in "SENTINL Installation" wiki page : 
- Kibana 4.x 
- Kibana 5.x 

Because installation command is not the same.

**Comment by lmangani** [comment]
@fbaligand updated but best handled in a separate issue from here on?

**Comment by uschtwill** [comment]
Alright, just finished the upgrade to 4.6.4-4, which has a nice interface for watcher editing by the way. Kudos! 

But the 404 error persists.

**Comment by uschtwill** [comment]
Same error on trying to save or disable watchers.

**Comment by fbaligand** [comment]
Could you provide some kibana server log, and also which URI returns 404 error ?

**Comment by uschtwill** [comment]
Got it! I wasn't aware there is no escaping for watcher IDs/names, so putting slashes in there was not very smart. :)
