### ISSUE TITLE
Can't install plugin Sentinl

### ISSUE THREAD

**Issue by teddyamp** [sirensolutions/sentinl#142]
Hi everyobody,

I have an issue regarding the installation of the plugin Sentinl 4.6.4-4. I use Kibana 5.0.1. I have this error : 
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

I then tried to install Sentinl 5.4.0 : 
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [sentinl]. Expected [5.0.1]; found [5.4.0]"

Can someone help me to install the plugin ?

Thank you.

**Comment by lmangani** [comment]
@teddyamp we do not have a release for 5.0.1 but you can attempt building your own sentinl for it using the 5.2.2 branch, basically changing the target version and crossing your fingers - although 5.0.1 is quite old and most likely would require plenty of other obsolete adjustments we can't support. Hope this helps!
