### ISSUE TITLE
Alerting in version 5.2.2-1 is not accurately triggered.

### ISSUE THREAD

**Issue by zxq1002** [sirensolutions/sentinl#143]
1. Issue Description
    I was testing the alerting function of sentinl v5.2.2-1 in kibana dev environment, and used "makelogs" command to prepare test data. And I found two problems: 1) when the input returns no data, the alarm was still triggered; 2) "Throttle period" seems no effect, I set it to 5min, and the condition matched in the first two or three mins, but didn't match at the end, the alarm still be triggered.
    I am not sure if my config was wrong, could you help me to fix the problem.

2. Reproducing the Issue step-by-step
    Watcher config :
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new_watcher_kdryzx9x3",
  "_score": 1,
  "_source": {
    "title": "watcher_test",
    "disable": true,
    "uuid": "new_watcher_kdryzx9x3",
    "trigger": {
      "schedule": {
        "later": "every 1 mins"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "logstash-0"
          ],
          "body": {
            "size": 0,
            "query": {
              "bool": {
                "must": {
                  "match": {
                    "machine.os": "ios"
                  }
                },
                "filter": {
                  "range": {
                    "@timestamp": {
                      "gte": "now-1m",
                      "lte": "now"
                    }
                  }
                }
              }
            },
            "aggs": {
              "avg_over_time": {
                "date_histogram": {
                  "field": "@timestamp",
                  "interval": "30s"
                },
                "aggs": {
                  "avg_one_time": {
                    "avg": {
                      "field": "machine.ram"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "\"var match=false; if (payload.hits.total > 0) { payload.aggregations.avg_over_time.buckets.forEach(function(e){ if(e.avg_one_time.value > 20000000000) {match=true;} }); } match;\""
      }
    },
    "transform": {
      "script": {
        "script": "payload.avgs = payload.aggregations.avg_over_time.buckets"
      }
    },
    "actions": {
      "sentinl alert mail test": {
        "throttle_period": "0h5m0s",
        "email": {
          "to": "zxq1002@foxmail.com",
          "from": "zxq1002@qq.com",
          "subject": "SENTINL ALARM {{ payload._id }} 测试",
          "priority": "medium",
          "body": "Series Alarm {{ payload._id}} 监控阀值：> 20000000000 \n\n指标明细：\n{{ #payload.avgs }}\nTime:{{ key_as_string }}   Count:{{ doc_count }}   Avg Ram:{{ avg_one_time.value }}\n{{ /payload.avgs }}",
          "stateless": false
        }
      },
      "Sentinl Alerting console": {
        "throttle_period": "0h1m0s",
        "console": {
          "message": "Series Alarm {{ payload._id}} 监控阀值：> 20000000000 \n\n指标明细：\n{{ #payload.avgs }}\nTime:{{ key_as_string }}   Count:{{ doc_count }}   Avg Ram:{{ avg_one_time.value }}\n{{ /payload.avgs }}"
        }
      }
    }
  }
}
```

3. Expected Results vs. Actual Results
the condition is not matched, but alarm triggered.

4. Additional Details
the query result sample:
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "avg_over_time": {
      "buckets": [
        {
          "key_as_string": "2017-06-13 09:24",
          "key": 1497345840000,
          "doc_count": 2,
          "avg_one_time": {
            "value": 15569256448
          }
        },
        {
          "key_as_string": "2017-06-13 09:25",
          "key": 1497345900000,
          "doc_count": 1,
          "avg_one_time": {
            "value": 6442450944
          }
        }
      ]
    }
  }
}
```

**Comment by zxq1002** [comment]
<img width="1251" alt="2017-06-13 5 38 18" src="https://user-images.githubusercontent.com/9085824/27076229-31ec135e-505f-11e7-921f-2b6886d9cf42.png">

**Comment by lmangani** [comment]
@zxq1002 I'm sorry, what i meant are the KIBANA logs (if possible, in debug mode) when replicating your issue or while running the problematic watches - thanks!

**Comment by lmangani** [comment]
PS: based on the example above, your script condition seems to be broken in formatting. Also make sure it returns TRUE or FALSE explicitly.

**Comment by zxq1002** [comment]
@lmangani  I modified the script condition, and the problem still appeared.
```
"var match=false; if (payload.hits.total > 0) { payload.aggregations.avg_over_time.buckets.forEach(function(e){ if(e.avg_one_time.value > 20000000000) {match=true;} }); } return match;"
```

**Comment by lmangani** [comment]
please provide the logged entry for this alarm with the payload response attached if possible

**Comment by zxq1002** [comment]
alerting when respons empty:
```
{
  "@timestamp": "2017-06-13T12:33:00.012Z",
  "watcher": "watcher_test",
  "level": "medium",
  "message": "Series Alarm  监控阀值：> 20000000000 \n\n指标明细：\n",
  "action": "sentinl alert mail test",
  "payload": {
    "took": 1,
    "timed_out": false,
    "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
    },
    "hits": {
      "total": 0,
      "max_score": 0,
      "hits": []
    },
    "aggregations": {
      "avg_over_time": {
        "buckets": []
      }
    },
    "avgs": []
  },
  "report": false
}
```

alerting when condition doesn't match:
```
{
  "@timestamp": "2017-06-13T12:27:00.017Z",
  "watcher": "watcher_test",
  "level": "medium",
  "message": "Series Alarm  监控阀值：> 20000000000 \n\n指标明细：\nTime:2017-06-13T12:26:00.000Z   Count:1   Avg Ram:7516192768\n",
  "action": "sentinl alert mail test",
  "payload": {
    "took": 4,
    "timed_out": false,
    "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
    },
    "hits": {
      "total": 1,
      "max_score": 0,
      "hits": []
    },
    "aggregations": {
      "avg_over_time": {
        "buckets": [
          {
            "key_as_string": "2017-06-13T12:26:00.000Z",
            "key": 1497356760000,
            "doc_count": 1,
            "avg_one_time": {
              "value": 7516192768
            }
          }
        ]
      }
    },
    "avgs": [
      {
        "key_as_string": "2017-06-13T12:26:00.000Z",
        "key": 1497356760000,
        "doc_count": 1,
        "avg_one_time": {
          "value": 7516192768
        }
      }
    ]
  },
  "report": false
}
```

the attachment is a few of test data:

**Comment by lmangani** [comment]
Here's a fiddle replicating your case - the matching seems correct, except the transform script which I think would cause errors: http://jsfiddle.net/lmangani/zm5m9cLd/1/

Could you find and paste the Kibana logs for the SENTINL execution corresponding to one of those? If possible, in debug mode - thanks for the detailed case.

**Comment by zxq1002** [comment]
[log.txt](https://github.com/sirensolutions/sentinl/files/1073510/log.txt)

Above is a part of log when alarms triggered, is it helpful?

**Comment by zxq1002** [comment]
As you see at the sentinl web page, I only have two watcher, one for alert test and another for report test, and also the report watcher was always turned off. Do you mean that I need to remove all the watchers and add a new one to test? And how could I know what and how many watchers was running at background actually?
<img width="1074" alt="2017-06-19 11 01 19" src="https://user-images.githubusercontent.com/9085824/27268451-1e9237a2-54e2-11e7-8ddc-367cf97bbbab.png">

**Comment by zxq1002** [comment]
I tested again, and found that the alarm is always triggered because the condition below seems returns true all the time... 
```
"var match=false; if (payload.hits.total > 0) { payload.aggregations.avg_over_time.buckets.forEach(function(e){ if(e.avg_one_time.value > 20000000000) {match=true;} }); } match;"
```
Is there something wrong with it? Or Sentinl do not support this kind of condition?

**Comment by fbaligand** [comment]
I invite you to replace last `match;` by `return match;`

**Comment by zxq1002** [comment]
Sorry, I forget to say that I have replaced it already several days ago, bud the problem remains unsolved. 
```
"var match=false; if (payload.hits.total > 0) { payload.aggregations.avg_over_time.buckets.forEach(function(e){ if(e.avg_one_time.value > 20000000000) {match=true;} }); } return match;"

```

**Comment by fbaligand** [comment]
Did you try to add some `\n` ? I recommand to use the script editor provided by sentinl.
Especially, just before `return match;`

Because, globally, I don't see anything wrong in your script...
Maybe 20000000000 is a "too big" number in javascript ?

**Comment by zxq1002** [comment]
I add ```\n``` before ```return match```, but still doesn't work .
And also 20000000000 is not the reason of the problem, I tried other smaller number.
Does the input box of condition in sentinl support "newline" instead of ";" ？
And what is script editor provided by sentinl, I input the conditon script directly to condition input box in watcher config pages.

**Comment by fbaligand** [comment]
I speak about this sentinl watcher tab :

![sentinl](https://user-images.githubusercontent.com/3750300/27685983-e98ee81a-5cd0-11e7-9c8d-7bfe9134d751.png)

**Comment by zxq1002** [comment]
Yes，I use this to edit condition script.
Does it support "newline" instead of ";" to separate each code line？

**Comment by fbaligand** [comment]
Yes, it supports multiline.
But I advice you to always use ";" to separate code instructions.

**Comment by zxq1002** [comment]
OK, Thanks.
Is there any other advice about this strange problem?

**Comment by lmangani** [comment]
Could you try again without ```return```statement on the latest version?

```var match=false; if (payload.hits.total > 0) { payload.aggregations.avg_over_time.buckets.forEach(function(e){ if(e.avg_one_time.value > 20000000000) {match=true;} }); };  match;```

**Comment by zxq1002** [comment]
I tried the latest version on master branch without ```return``` statement, and also removed the quotes at the beginning and the end of condition script, now it seems works...Thanks, I will try some times more.

**Comment by lmangani** [comment]
Thanks for the update. the quotes around the command would indeed prevent the commands being interpreted as anything due to escaping.
