### ISSUE TITLE
Integrate Pagerduty in Sentinl

### ISSUE THREAD

**Issue by Arun-Ghosh** [sirensolutions/sentinl#144]
Hi Team,
It would be really nice if pagerduty is integrated with Sentinl

**Comment by Arun-Ghosh** [comment]
Hi Team,
Just wanted to checkout when you are planning to integrate this or when it will be live ? What is your release cycle ?

**Comment by lmangani** [comment]
Hi @Arun-Ghosh we're currently focusing on some core improvements, will start adding new delivery methods in the coming release. In the meantime you should be able to post to pagerduty using the REST API on their end, is this something you tried already?

**Comment by Arun-Ghosh** [comment]
Hi @lmangani Thank you for the update. Really appreciate it. Yes I am using that only. Sorry missed to update that. Currently looking forward for issue #14 (Getting duplicate alert for 2 kibana node pointing to same ElasticSearch cluster)

**Comment by narayanan1993** [comment]
I am using email integration with the pagerduty and Its working fine in production Environment too.

**Comment by lmangani** [comment]
@narayanan1993 could you point at an example for this config we can add to the wiki?

**Comment by lmangani** [comment]
Moving to 6.x and cleaning up issues. Please reopen if this is still useful / required. Thanks!
