### ISSUE TITLE
Help Regarding Output Syntax

### ISSUE THREAD

**Issue by shubhamverma27** [sirensolutions/sentinl#146]
How do I out put the value of a specific filed in the message body
for ex i am comparing browsermajor > 45 in script and want to write in message the browsermajor like {{browsermajor}} and it should give its current value. but this doesnt work..whats the correct syntax???

**Comment by lmangani** [comment]
This depends how your reponse is formed. The mustache template will just navigate the JSON content according to your definition. Show me the current payload + template and we'll try advice.

**Comment by shubhamverma27** [comment]
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new_watcher_8azer5nf0",
  "_score": 1,
  "_source": {
    "title": "DLS-IIS",
    "disable": false,
    "uuid": "new_watcher_8azer5nf0",
    "trigger": {
      "schedule": {
        "later": "every 5 secs"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "clas"
          ],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "browsermajor > 45"
      }
    },
    "transform": {
      "script": {
        "script": ""
      }
    },
    "actions": {
      "testmail2": {
        "throttle_period": "0h0m15s",
        "email": {
          "to": "alarm@localhost",
          "from": "sentinl@localhost",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Found {{browsermajor}} Events"
        }
      },
      "DLS-IIS Title2 {{browsermajor}}": {
        "throttle_period": "0h0m1s",
        "console": {
          "message": "Browser version : {{browsermajor}}",
          "priority": "medium"
        }
      },
      "New report action sas b4bsdsz4bn8": {
        "throttle_period": "0h0m1s",
        "report": {
          "to": "ads",
          "from": "sda",
          "subject": "",
          "body": "asd",
          "snapshot": {
            "res": "1280x900",
            "url": "http://www.google.com",
            "path": "/home/temp/elk/",
            "params": {
              "delay": 5000
            }
          },
          "priority": "medium"
        }
      }
    },
    "report": true
  }
}



I am trying it to test on how to output a key's value in message body!! @lmangani 
        "message": "Browser version : {{browsermajor}}", this basically

**Comment by lmangani** [comment]
@shubhamverma27 we need to see the ES response - anyway, you can't just invent variables, they need to be existing inside of the JSON response you receive from Elasticsearch for your query.

Take a look at the examples we provide: 
JSON: ``` payload: { hits: { total: 100 } } ```
Template: ```Found {{payload.hits.total}}```

**Comment by shubhamverma27** [comment]
@lmangani  how to check the es response?

**Comment by lmangani** [comment]
It is saved alongside the results in the sentinl index. Just open the watcher results and expand.

**Comment by shubhamverma27** [comment]
![image](https://user-images.githubusercontent.com/22194930/27120425-2115ad2c-5101-11e7-811b-dd827872ed3f.png)


Still a little confused..Please check

**Comment by lmangani** [comment]
@shubhamverma27 you need to take this one step at the time and understand each.

1) SENTINL uses a query to get data. Run the same query in your Dev Tool.
2) Check the reponse of the query. This is what SENTINL will receive.
3) Use the received structure to extract your data.

Please before proceeding, check [this presentation](https://www.slideshare.net/secret/gobTp9S3omqn9a) where I explain in more detail the internals of SENTINL and how it works.

**Comment by shubhamverma27** [comment]
SENTINL uses a query to get data. Run the same query in your Dev Tool. 
@lmangani I am still not able to find this query..where can I see it.

Saw the PPT too but no mention of the same in that

**Comment by lmangani** [comment]
@shubhamverma27 happy to help you with SENTINL but we can't go all the way into explaining how to run queries in ES. This is general knowledge you should possess before using SENTINL in order to succeed.

**Comment by shubhamverma27** [comment]
Hi, @lmangani 
I am getting Objects as response inside hits ..now how do i access the elements inside that for creating my condition like payload.hits.hits.last >3
Will it automatically check inside the objects?because i dont think its working this way!!
timed_out: false,
  _shards: { total: 5, successful: 5, failed: 0 },
  hits:
   { total: 12257,
     max_score: 1,
     hits:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] } }

**Comment by lmangani** [comment]
Yes, it works this way and will automatically check the conditions against the payload JSON object. You're not the first one to use it, so there's a level of confidence in this statement.

Every time SENTINL runs, it logs an entry with the results you can access form the UI under ALARMS (or REPORTS, in case of a report) From there you can expand the row to see what we received back from ES and how we processed it. Based on the available data, you should create your logic.

If you do not understand how ES objects are formed and navigated, I suggest to experiment by following the Wiki examples and trying to understand the relevance of each step.

**Comment by shubhamverma27** [comment]
@lmangani Hi, Its how do I specify it to load just one hit/object at a time? and then check its condition then continuously for the rest

**Comment by shubhamverma27** [comment]
@lmangani I am still not able to print a value inside the hits array of objects.. I guess its not possible tried all these combinations :-
{{payload.hits.hits[0]._id}}
{{payload.hits.hits[1]._score}}
{{payload.hits.hits[1]._source.symbol}}

{{payload.hits.hits._score[0]}}
{{payload.hits.hits._score[1]}}
{{payload.hits.hits._score}}

total
{{payload.hits.total}}


only the total comes while rest nested ones dont..

**Comment by lmangani** [comment]
@shubhamverma27 you are doing it WRONG - this is not how you navigate objects in Mustache. I've sent you a presentation where the mustache templating is explained in a lot of detail, with included examples, but you decided to ignore it so I'm not sure how to help you further. Just open the presentation and read it.

**Comment by shubhamverma27** [comment]
Hi,
i had read the ppt but now have understood the same..
Thanks...
Do we have implementation of HTTP Basic Auth in this plugin? If no , can it be added?
Because its the compatibility with readonlyrest and authentication thats causing the issues? @lmangani

**Comment by lmangani** [comment]
@shubhamverma27 this is the only workaround until we extend the client to allow authentication, which is in the works for future versions: https://github.com/sirensolutions/sentinl/wiki/SENTINL-FAQ#q-how-can-i-use-sentinl-with-readonlyrest-authentication

**Comment by shubhamverma27** [comment]
@lmangani Okay , Shall be waiting for the release.

Does your plugin also provide automatic purging and archiving of old indices?

**Comment by lmangani** [comment]
not automatic, you should use curator as per any other time-based ES index

**Comment by fbaligand** [comment]
You could also use SENTINL itself to do that !

- you make a daily schedule
- you make a ES input request on `/<watcher_alarms-{now-30d}>`
- you make a condition `payload.hits.total > 0`
- you make an output action `webhook` with verb=`DELETE`, port=`9200`, uri=`/<watcher_alarms-{now-30d}>`

**Comment by lmangani** [comment]
@fbaligand right, you should add this to the Wiki :)

**Comment by fbaligand** [comment]
It would be nice...
I have to find time to do that... (not easy currently)

**Comment by shubhamverma27** [comment]
@fbaligand But the Method DELETE option is not there in the webhook action?

**Comment by fbaligand** [comment]
You can do it using "raw" tab.
