### ISSUE TITLE
Best Practice for Version Control

### ISSUE THREAD

**Issue by uschtwill** [sirensolutions/sentinl#147]
I was wondering what the best practice regarding version control is for watchers. Yes, they are in the ES index, but I would actually like to keep them in git. 

Has someone achieved some level of sophistication in this regard or is manually copy/pasting from editor to GUI and vice versa the only way to go right now?

**Comment by lmangani** [comment]
@uschtwill not sure I understand the point precisely but I'll try - if you want is to backup/restore, that's totally possible as per any other index in ES using a tool such as elasticdump, etc. 
In future versions I plan moving watchers and data away from ES (or any other backend we'll monitor) to support clustering and job-distribution, will sure provide a few more options once we get there.

**Comment by uschtwill** [comment]
Well the point would be to be able to harness all the goodness that generally comes with using version control, of which a blunt backup/restore capability is just one part, right? 

But yeah I thought that scripting something between git and ES, involving tools like elasticdump, would probably what would be needed. I just thought maybe someone already did that work?

**Comment by fbaligand** [comment]
@uschtwill 
By the way, if your only need is to "tag" watchers versions, list tags, and restore a previous "tag", maybe snapshot/restore elasticsearch feature could answer your need.
If so, you don't have to create a git repository and especially to manage synchronization between git and elasticsearch storage.

On the contrary, if you need to see "diff" between 2 versions, git is necessary...

**Comment by lmangani** [comment]
Abandoned thread. Comment to reopen if interested.
