### ISSUE TITLE
HTTP Basic Header Authentication

### ISSUE THREAD

**Issue by shubhamverma27** [sirensolutions/sentinl#149]
Hi,
It would be great and Very Easy to implement this..
I request the developers to Please add it As soon as possible as it would resolve all issues while using it with authenticated Elastic Search.

I myself am using ReadOnlyREST Plugin and Desparately need this feature to progress my work

++ @lmangani We already had a chat about this, Please Get it implemented soon :)

**Comment by fbaligand** [comment]
Have you tried this ?
https://github.com/sirensolutions/sentinl/wiki/SENTINL-FAQ#q-how-can-i-use-sentinl-with-readonlyrest-authentication

I know it is not exactly what you request, but it allows to work with readonlyrest. 

On the other side, to implement this, I think it would be nice to reuse kibana authentication to elasticsearch, rather than developing a specific way.

**Comment by shubhamverma27** [comment]
@fbaligand This method was actually​ suggested by me .. But the problem with this method is that You have to make an exception for each and every index that you Access via Sentinl

**Comment by fbaligand** [comment]
Sorry, I didn't get it was you !
Anyway, your issue is relevant.

**Comment by shubhamverma27** [comment]
@lmangani Hi, Can you let me know which file to edit in order to implement Basic Authetication header? 
I 'll Try to develop it on my own

**Comment by lmangani** [comment]
@shubhamverma27 we're working on this in our private repository so it is in progress, if you want to push a PR it's welcome but unfortunately no time for anything else :(

**Comment by shubhamverma27** [comment]
@lmangani any progress?

**Comment by shubhamverma27** [comment]
@lmangani ??

**Comment by lmangani** [comment]
You can add a question mark a day, but it is not going to make things any faster sorry.
Once we've got updates on this front we'll push them to the repository. The method involves changes to leverage the ES client from Kibana and complement with authentication we now have to store somewhere securely, etc. It's not as easy as hacking a line in, but if that's what you're after, just modify the ES client function and off you go. We'll go for the quality release not the rushed one. Thanks for understanding.

**Comment by shubhamverma27** [comment]
@lmangani Thanks.
Can you Please Help me edit the ES client function so as to I can use it for the time being?

**Comment by shubhamverma27** [comment]
/**
 * Returns the Elasticsearch client used to create indices, execute watches and store alarms.
 */
export default function getElasticsearchClient(server, type = 'data') {
  if (type === 'data') {
    if (server.plugins.kibi_access_control) {
      return server.plugins.kibi_access_control.getSentinlClient();
      console.log('KIBI ACCESS CONTROL');
    }
    return server.plugins.elasticsearch.getCluster('data');
  }
  return server.plugins.elasticsearch.getCluster('admin');
}


I guess this file has to be edited??

**Comment by SergeyBondarenko** [comment]
@shubhamverma27 yes, it is

**Comment by shubhamverma27** [comment]
@SergeyBondarenko What Should I edit it ..no idea..can you help me a little?

**Comment by lmangani** [comment]
@shubhamverma27 in such case, I would suggest waiting for our official patch if you have no idea, you might dig a hole in the water otherwise...

**Comment by shubhamverma27** [comment]
@Imangani Okay
