### ISSUE TITLE
Coupling Kibana/Sentinl

### ISSUE THREAD

**Issue by uschtwill** [sirensolutions/sentinl#150]
Just got: 
`"stderr": "Plugin installation was unsuccessful due to error \"Incorrect Kibana version in plugin [sentinl]. Expected [5.4.1]; found [5.4.0]\""`

Do I get it right, that Sentinl version https://github.com/sirensolutions/sentinl/releases/tag/tag-5.4.0 won't install if Kibana is already at version 5.4.1 (or a later version for that matter)? 

If that is the case: that sort of close coupling down to the patch version number seems rather cumbersome, as it is really inflexible. I do get that as Sentinl is a Plugin for Kibana the coupling will always be quite close... but won't minor version numbers do?

**Comment by lmangani** [comment]
We need to thank Elastic for this. Version needs to match 1:1 including minor 
We're working to keep up with their nonsense, but there's some latency since it's always a surprise in terms of what's changed (unless you spend 24/7 watching their changes, that is)

**Comment by uschtwill** [comment]
Wow, I just read up on it. That is inconvenient!

**Comment by lmangani** [comment]
You have no idea - it's designed to alienate even the most tenacious maintainers of related projects

**Comment by shubhamverma27** [comment]
You can just edit the version in the package.json .
It will work
