### ISSUE TITLE
A few issues with installation and few questions

### ISSUE THREAD

**Issue by Genluck** [sirensolutions/sentinl#151]
Hello everyone.

I had 2 issues with installation:
1. "git clone https://github.com/sirensolutions/sentinl" not works with the latest version of Kibana (error version mismatch between 5.4.0 at the git and 5.4.1 of latest Kibana). Could be avoided by downloading file manually and editing json file at the archive (but people who is installing plugin by readme file don't know about it, so they couldn't install plugin).
2. Installation by "manual" method doesn't work too. Here is an error during the installation.
```
npm install --production
npm WARN deprecated phantomjs@2.1.1: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> phantomjs@2.1.1 install /tmp/sentinl/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/sentinl/node_modules/phantomjs/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [========================================] 100%
Received 22866K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: Command failed: tar jxf /tmp/sentinl/node_modules/phantomjs/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /tmp/sentinl/node_modules/phantomjs/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /tmp/sentinl/node_modules/phantomjs/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm ERR! Linux 3.10.0-514.21.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@2.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@2.1.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/sentinl/npm-debug.log
```
I did try to create file manually and download it by myself. But the result is the same.

And my questions are:
1. How is it possible to create filter per device. For example I want to raise alert if there is more then X messages by device at the specific time range. I have more then 300 devices. If I want to make an alert fo 5 messages there will be a lot of false alarms...
2. Is it possible to acknowledge alerts as it made at the original watcher (https://www.elastic.co/guide/en/watcher/current/actions.html#actions-ack-throttle - acknowledge by API)?
3. And summary of both questions above: I want to use around 100 types of alerts per more than 300 devices. It would be a hell for creating alerts for each device. So does plugin support alerts per device with acknowledging per device?

**Comment by lmangani** [comment]
Hi @Genluck 

5.4.1 does not have an official release yet and we'll support it once we do, in the meantime you can download the 5.4.0 archive, change the version, repack and install it to try that out - I expect it should work but again, we won't support it until you see an official SENTINL release.

In terms of your questions:

1) Yes, you can create dynamic queries and return results dynamically only for the groups (devices) above threshold - check out the wiki examples they should get you started
2) We do also support Throttle and logging of all watcher decisions
3) See answer 1) you can make it as dynamic as your queries can return data

Hope this helps! Closing as this is not an issue rather questions.
