### ISSUE TITLE
wrong tips : No indices found, Initializing

### ISSUE THREAD

**Issue by karencaocjj** [sirensolutions/sentinl#152]
1. Issue Description
restar  kibana,saw this error:

Sentinl Watchers: Error 404 Not Found: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="watcher" & index_uuid="na" & index="watcher" } :: {"path":"/watcher/watch/_search","query":{"size":50,"allow_no_indices":false},"statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index_uuid\":\"na\",\"index\":\"watcher\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index_uuid\":\"na\",\"index\":\"watcher\"},\"status\":404}"}

2. Reproducing the Issue step-by-step
release 5.4.0   i changed verison in packge.josn to fit my kibana
3. Expected Results vs. Actual Results

4. Additional Details

**Comment by fbaligand** [comment]
Which kibana version do you use precisely?
Same question for sentinl ? or do you use latest snapshot ?
Do you use a security plugin ? X-pack, searchguard, readonlyrest ?

**Comment by karencaocjj** [comment]
kibana version 5.2.1
i just download https://github.com/sirensolutions/sentinl/releases/download/tag-5.3.2/sentinl.zip  ,change the package,json.  then install sentinl with offline the new zip.
and i installed x-pack before sentinl

**Comment by shubhamverma27** [comment]
XPack Might be Blocking access to sentinl , You should make POST and Get exceptions on the indices to be accessed/created by sentinl.
Like /watcher & /watcher-alarm.* etc

**Comment by shubhamverma27** [comment]
Yeah Its the same problem I faced,
You need to make exceptions in the XPack Settings

**Comment by fbaligand** [comment]
By the way, if you use kibana 5.2.x, you should use sentinl 5.2.x

**Comment by karencaocjj** [comment]
I remove the 5.4.0 sentinl ,and intall the release 5.2.2 ,also changed the package.json.
and  I creat a watcher index in the dev tools.
the red error at the top of the windw not appearence any more ,
but the log of kibana also shows "No indices found, Initializing", every 30s .

**Comment by fbaligand** [comment]
Ok. As mentioned previously by others, you need to add x-pack security configuration to let sentinl access/modify its indices without authentication.

I invite you to read last question in "FAQ" wiki page. It will help you to know what should be configured in x-pack

**Comment by karencaocjj** [comment]
which file should I add these config,and how?
the elasticsearch.yml or kibana.yml?

**Comment by fbaligand** [comment]
The config you saw in FAQ is for readonlyrest security plugin. 
You have to get inspiration from this config to configure x-pack security.
And to configure x-pack security, I invite you to read x-pack documentation or to call elastic support.

**Comment by karencaocjj** [comment]
Thanks both two. I soulved this problem by configure readonlyrest.
