### ISSUE TITLE
Email Attachments

### ISSUE THREAD

**Issue by shubhamverma27** [sirensolutions/sentinl#153]
Hi,
Is there any way to attach the Payload Json data to the attachment in the email..
Or just display the whole json in the email?

**Comment by lmangani** [comment]
You have full access to the payload so you can stringify it and attach it to the body, if you wish.

**Comment by shubhamverma27** [comment]
Any tutorial on that??
because i tried JSON.stringify (payload/payload.hits/payload.hits.hits)
didnt work  @lmangani

**Comment by fbaligand** [comment]
Json.stringify should be done in transform script, to be stored in payload.json (for example).

Then you reference {{payload.json}} in email body.

**Comment by shubhamverma27** [comment]
Hi, @fbaligand 
My Payload.json1 looks like this(without stringify)
"json1": {
      "@timestamp": "2017-06-20T07:32:00.047Z",
      "gender": "female",
      "surname": "Nicolau",
      "name": "Mirela",
      "@version": "1",
      "tag": "uinamesTag",
      "region": "Romania",
      "type": "Test1"
    }


Now while trying to Create a POST webhook and passing {{payload.json1}} as body is not working while posting it via dev tools is and also posting from sentil by creating a json by myself in body is working

what could be the reason??
"xx": {
        "throttle_period": "0h0m1s",
        "webhook": {
          "method": "POST",
          "host": "localhost",
          "port": 9200,
          "proxy": false,
          "path": "/testlive/newalert",
          "body": "{{payload.json1}}",
          "create_alert": true,
          "priority": "high",
          "headers": {
            "Content-Type": "application/json",
            "Authorization": "Basic kibana:kibana"
          }
        }
      }

**Comment by fbaligand** [comment]
Could you give your transform part ?
I mean this :
``` json
"transform": {
      "script": {
        "script": "..."
      }
    }
```

**Comment by shubhamverma27** [comment]
"transform": {
      "script": {
        "script": "payload.json123 = JSON.stringify(payload.hits.hits[0]._source, undefined, 4);payload.json1 = payload.hits.hits[0]._source"
      }
    },

here json123 is for priniting to email and json1 for POST (I tried POST with stringify too ) 
@fbaligand

**Comment by fbaligand** [comment]
In this script, you should have : 
`payload.json1 = JSON.stringify(payload.hits.hits[0]._source)"`

**Comment by shubhamverma27** [comment]
@fbaligand 
Thats what I  wrote that I tried both of these that is payload.json123 (which is with stringify) and one without  stringify

**Comment by lmangani** [comment]
@shubhamverma27 please fork this fiddle to simulate your response and scripts by pasting them in place, and check the outcome. It should be pretty much the same as SENTINL would output (or error)

http://jsfiddle.net/lmangani/zm5m9cLd/embedded/result/

**Comment by shubhamverma27** [comment]
@lmangani This isn't working .I mean It's throwing errors when I edit the payload to my payload.
Hope You have understood the problem and Could Direct me to why this is happening?

**Comment by lmangani** [comment]
@shubhamverma27 this is what the fiddle is for, since we don't know your payload. Save it and share it for comments.

**Comment by shubhamverma27** [comment]
@lmangani I meant when I am Putting the transform script in fiddle "payload.json123 = JSON.stringify(payload.hits.hits[0]._source, undefined, 4)"
Its throwing the error " Cannot read property 'hits' of undefined" 
While its working as is in sentinl , Though the issue of POST is different as the transform script is working fine

**Comment by shubhamverma27** [comment]
Condition: false
{ "@timestamp": "2017-06-20T07:32:30.045Z", "gender": "female", "surname": "Carlier", "name": "Chloë", "@version": "1", "tag": "uinamesTag", "region": "Belgium", "type": "Test1" }
I am getting the output in fiddle now, Though Transform was not working properly in fiddle

**Comment by shubhamverma27** [comment]
@lmangani The output is as expected but its still not posting as webhook whichever way I try , be it JSON.stringify or direct object pass

**Comment by lmangani** [comment]
Then you need to troubleshoot the webhook part instead. Attach relevant logs in debug mode.

**Comment by shubhamverma27** [comment]
See, IF the body is  
{
 "key" :"value/{{payload.hits.total}}", etc.....
}
it works

but if the body is
{{payload.json1}} (or {{payload.json123}})
it doesn't
Even though I can clearly see that json1 is a json object as visible in alert payload details (json123 is stringified json)

@lmangani So the configuration for post is correct but there is some problem in the body

**Comment by lmangani** [comment]
PASTE your fiddle so we can comment, this what it's made for. If you don't want to share the example, we really can't help.

**Comment by shubhamverma27** [comment]
@lmangani The Fiddle code does not include the webhook.. does it?
Still Here it is

http://jsfiddle.net/a58sy34j/

**Comment by shubhamverma27** [comment]
Its working Now..Thanks 
Maybe {{{}}} helped

**Comment by shubhamverma27** [comment]
@lmangani @fbaligand Sorry for so many questions but the last one :P  ,
How to iterate in the transform script
for (i = 0; i < payload.hits.total; i++) { 

payload.json123 = JSON.stringify(payload.hits.hits[i]._source, undefined, 4);
payload.json1 = payload.hits.hits[i]._source;
}
will this work,maybe it isnt?

**Comment by lmangani** [comment]
You don't have to do this iteration by hand, mustache does it for you...... I think you're working against the tool, really :) Take a look at a modified example here: http://jsfiddle.net/lmangani/4267hx8r/

```

```

**Comment by shubhamverma27** [comment]
but I want to iterate in the transform field ..where moustache won't work.
I want to create a array similar to hits array where I would store the json
and then email all of them
without the need to mention each key separate.
so basically using stringify with an iterator...
@Imangani

**Comment by shubhamverma27** [comment]
Basically, Use Case :- Make an Array of Json Stringified objects
