### ISSUE TITLE
Sentinl 5.1

### ISSUE THREAD

**Issue by mza97** [sirensolutions/sentinl#154]
Hi,

First, I appreciated the work done for sentinl 4+, I think this project is a wonderful idea. 
My team and I have just upgrated our stack ELK to the 5.1.1 version, we were waiting for sentinl 5+, but it's only available for 5.2+ version.
Is a version compatible with ELK 5.1 is planned ? 

Best regards.

**Comment by lmangani** [comment]
Hi @mza97 thanks for the kind words. We don't plan backporting to 5.1 but being all open, it's always possible if there are hands and demand. 

The best shot for you right now would be to try patch 5.2.2 OR download the 5.2.2 zip and modify the package version to match the 5.1.1 Kibana version.

**Comment by lmangani** [comment]
Closing as non-issue, but feel free to post updates here if needed.

**Comment by mza97** [comment]
Thank you for the quick response to my questions. 
I will keep you posted about the updates if needed.
