### ISSUE TITLE
report doesn't work on SUSE 12

### ISSUE THREAD

**Issue by zxq1002** [sirensolutions/sentinl#155]
I installed sentinl 5.2.2 on kibana 5.2.2, and also I have installed phantomjs-prebuilt on the server. But when the report watcher is scheduled, sentinl throw an exception like "Unhandled rejection  HeadlessError: phantom immediately  exited whth: 126 .....".
The detail error info is at the attachment. I'm sorry that the photo may not be very clearly,  because my company do not allow us to connect to internet by work laptop, so I took the screen picture by my telephone ...
![wechatimg1](https://user-images.githubusercontent.com/9085824/27681083-984d24b0-5cf0-11e7-934b-e71cb51b7ec8.jpeg)

**Comment by SergeyBondarenko** [comment]
Hi @zxq1002  Could you please try [the latest release](https://github.com/sirensolutions/sentinl/releases/tag/tag-5.4.0)? Let me know the result.

**Comment by SergeyBondarenko** [comment]
@zxq1002 In order to make it work for v5.2.2 change kibana version in package.json
```
~/dev/sentinl$ grep -rne "kibana\"" package.json -A 1
9:  "kibana": {
10-    "version": "5.4.0"
```

**Comment by zxq1002** [comment]
Do you mean sentinl v5.4.0 is compatible with kibana v5.2.2, not only for kibana v5.4.0? 
I always thought that version must be consistent before, So I used [https://github.com/sirensolutions/sentinl/releases/download/tag-5.2.2-1/sentinl.zip](V5.2.2-1)...
This version works on my macbook pro, so I think there is something wrong on my SUSE 12, but from the log info, I couldn't find the root reason, and doesn't know what to do... I hope someone can  give me some advice..
By the way, I compared the source code between v5.2.2-1 and v5.4.0 just now, the only difference is "package.json" and "README.md", so I think they are the same in fact.

**Comment by SergeyBondarenko** [comment]
@zxq1002 No, these releases are not identical. Even if you look at the .zip packages, [v5.4.0](https://github.com/sirensolutions/sentinl/releases/download/tag-5.4.0/sentinl.zip) is approximately 52M bigger than [v5.2.0](https://github.com/sirensolutions/sentinl/releases/download/tag-5.2.2-1/sentinl.zip).

**Comment by SergeyBondarenko** [comment]
I think your problem is that Sentinl couldn't locate phantomjs binary. It is used to create screenshots by report action.

**Comment by zxq1002** [comment]
I have linked phantomjs binary in node_modules directory to /usr/bin directory, but it still doesn't work.

**Comment by zxq1002** [comment]
I pulled the latest version b621d4 and packaged by command "gulp package --version=5.2.2", it works now. Thanks a lot!
