### ISSUE TITLE
404 /api/sentinl/example not found

### ISSUE THREAD

**Issue by seshu3564** [sirensolutions/sentinl#159]
Hi 
I have installed Sentinl 5-x tag 5.0.0 version using usr/share/kibana/bin/kibana-plugin install <link> command and install was successful. when i restart kibana sentinl option appears in side nav but when i click on it nothing appears and in browser console i found the error
<my-domain>/api/sentinl/example 404(not found). I already had elastic  data for kibana and working for some time and none of other features like x-pack. Should i add any more configs?

[EDIT] My domain runs in https.... will that cause a problem?

**Comment by lmangani** [comment]
Please install the proper version for your Kibana and try again

**Comment by seshu3564** [comment]
When i have upgraded all elastic search and kibana and sentinl to 5.4.0 it worked. but it failed in 5.0.0 version of kibana and sentinl. I have tried both types of install with lastest code building and direct plugin install. it didnt work for both.But it is working fine for me now in 5.4.0.
