### ISSUE TITLE
Preparation for Kibana 5

### ISSUE THREAD

**Issue by lmangani** [sirensolutions/sentinl#16]
Since the Gentlemen at Elastic decided to make everyone's life a living hell with Kibana too, some preparation steps are required to guarantee KAAE surviving the hop and keeping up with their insanity-based version checks and undocumented API changes. 

Reference: https://siren.solutions/in-kibana-5-all-your-plugins-will-break-at-each-and-every-update/

All and every community input, help or suggestion extremely welcome

EDIT: Development branch for [5.0](https://github.com/elasticfence/kaae/tree/5.0) now available

### Installation Steps
```
cd KIBANA5_HOME/plugins
# If the plugins folder does not exist, change to installedPlugins and continue.
git clone -b 5.0 --single-branch https://github.com/sirensolutions/kaae.git kaae
cd kaae
npm install
```
Important: If you have any problem with the plugin version (like a warning message "it expected Kibana version "x.x.x", and found "5.0.0-rc1"") only change the value of the "version" tag on the KAAE package.json to your Kibana version

### Unistall:
```
cd KIBANA5_HOME
rm -rf plugins/kaae/
```

**Comment by ddavidebor** [comment]
Take a look at what we did here https://github.com/fermiumlabs/mathlion with gulp and Travis-CI

**Comment by lmangani** [comment]
I keep getting ``` "Error retrieving metadata from plugin archive"` ``` when attempting although the basic package structure should be compatible with at least spitting some errors. Any Gulp master willing to spare a hand with a proper builder for 5.0.x?

**Comment by ddavidebor** [comment]
Using our script? (really the script from rashidkpc...)

**Comment by lmangani** [comment]
A broken, development only branch for [5.0](https://github.com/elasticfence/kaae/tree/5.0) migration is now available for the brave souls willing to help. Plenty of work ahead....

**Comment by Daritos** [comment]
I have created PR request https://github.com/elasticfence/kaae/pull/60 to the 5.0 branch which could assist a little in getting KAAE more compatible with Kibana 5. These changes will add a placeholder navbar for navigation, some changes to the ui.routes and some modifications made to the request body used to fetch alerts/alarms in order for it to work with the latest version of the Elasticsearch API.

**Comment by fbaligand** [comment]
Hi, I'm interested by testing kaae plugin in Kibana 5.0.
Can you tell me how to install it on Kibana 5 ?

**Comment by lmangani** [comment]
Hi @fbaligand I updated the issue description with basics instructions

**Comment by fbaligand** [comment]
Thanks a lot !

Some first feedback :
- when launching `npm install`, I get this warning :
`WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
- Then, no warning about Kibana version compatibilty (I use Kibana 5.0.1 under Windows 10).
- At startup, I get the following logs, including an error with stack trace :
```
  log   [14:34:15.310] [info][status][KaaE] KaaE Initializing
  log   [14:34:15.340] [info][status][KaaE] Core Index check...
  log   [14:34:15.341] [info][status][KaaE] Alarm Index check...
  log   [14:34:15.356] [info][status][plugin:kaae@0.5.0] Status changed from uninitialized to green - Ready
Unhandled rejection [index_not_found_exception] no such index, with { resource.type=index_or_alias resource.id=watcher index_uuid=_na_ index=watcher } :: {"path":"/watcher/watch/_count","query":{},"statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index_uuid\":\"_na_\",\"index\":\"watcher\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index_uuid\":\"_na_\",\"index\":\"watcher\"},\"status\":404}"}
    at respond (C:\Developpement\outils\elk\kibana-5.0.1-windows-x86\node_modules\elasticsearch\src\lib\transport.js:289:15)
    at checkRespForFailure (C:\Developpement\outils\elk\kibana-5.0.1-windows-x86\node_modules\elasticsearch\src\lib\transport.js:248:7)
    at HttpConnector.<anonymous> (C:\Developpement\outils\elk\kibana-5.0.1-windows-x86\node_modules\elasticsearch\src\lib\connectors\http.js:164:7)
    at IncomingMessage.wrapper (C:\Developpement\outils\elk\kibana-5.0.1-windows-x86\node_modules\elasticsearch\node_modules\lodash\lodash.js:4962:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  log   [14:34:16.159] [info][status][KaaE] Alarm Index response
  log   [14:34:16.161] [info][status][KaaE] Core Index response
```
- After launching plugin UI, and then restart Kibana, no error logged anymore at startup, all is fine :
```
  log   [14:39:55.032] [info][status][KaaE] KaaE Initializing
  log   [14:39:55.055] [info][status][KaaE] Core Index check...
  log   [14:39:55.057] [info][status][KaaE] Alarm Index check...
  log   [14:39:55.067] [info][status][plugin:kaae@0.5.0] Status changed from uninitialized to green - Ready
```

**Comment by fbaligand** [comment]
Then  I tried this watcher :
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "watcher1",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 minute"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": "logstash*",
          "body": {
            "query": {
              "query_string": {
                "analyze_wildcard": true,
                "query": "_type:request"
              }
            },
            "size": 3
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 0"
      }
    },
    "transform": {},
    "actions": {
      "to_console": {
        "throttle_period": "1m",
        "console": {
          "priority": "WARN",
          "message": "Series Alarm {{ payload._id}} > 0: {{ payload.hits.total }}"
        }
      }
    }
  }
}
```

And when execution time happened, here the result logs :
```
  log   [16:21:00.004] [info][status][KaaE] Executing watch: watcher1
  log   [16:21:00.015] [info][status][KaaE] Action Report requires Email Settings! Reports Disabled.
  log   [16:21:00.026] [info][status][KaaE] Processing action: to_console
  log   [16:21:00.032] [info][status][KaaE] Console Payload: {"took":3,"timed_out":false,"_shards":{"total":10,"successful":10,"failed":0},"hits":{"total":2,"max_score":1,"hits":[{"_index":"logstash-2016.11.05","_type":"request","_id":"r2","_score":1,"_source":{"@timestamp":"2016-11-05T19:01:01.000Z","message":"message2","msg":"msg2","request_uri":"/r2","sql_duration":13,"ws_duration":25,"java_duration":19}},{"_index":"logstash-2016.11.05","_type":"request","_id":"r1","_score":1,"_source":{"@timestamp":"2016-11-05T21:01:01.000Z","message":"message1","msg":"msg1","request_uri":"/r1","sql_duration":12,"ws_duration":24,"java_duration":18}}]}}
  log   [16:21:00.033] [info][status][KaaE] Storing Alarm to ES with type:to_console
```

And then, when I go to "Alarms" tab, I can see the generated alarm line.
When next executions happen, new lines are added in "Alarms" tab.
If I click on an Alarm line, I can see the payload.

=> So all of this just works fine !!!

**Comment by lmangani** [comment]
Thanks @fbaligand this is nothing but great news!

**Comment by fbaligand** [comment]
Now, few bugs :
- when I am on "Alarms" tab, if I click on "bell icon", I get a blank screen. It seems that on link, it misses a "/" at url's end
- if I already have opened "kaae" app, and I click again on "kaae app icon", I get also a blank page. I think it is for the same reason than "bell icon" bug.
- when I am on "Alarms" tab, if I delete the second alarm line, the wrong line is deleted (for example : the first line is deleted)
- when I am on "Watchers" tab, if I try to delete a "watcher" line,  the watcher is deleted, but I got a FATAL error UI page with that explanation :
```
Error: Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.4.7/$rootScope/inprog?p0=%24apply (http://localhost:5601/bundles/commons.bundle.js?v=14458:35)
window.onerror@http://localhost:5601/bundles/commons.bundle.js?v=14458:69:13547
[1772]/</$scope.watcherDelete@http://localhost:5601/bundles/kaae.bundle.js?v=14458:1:6236
anonymous/fn@http://localhost:5601/bundles/commons.bundle.js?v=14458 line 41 > Function:2:331
ngEventDirectives[directiveName]</<.compile/</</callback@http://localhost:5601/bundles/commons.bundle.js?v=14458:42:11001
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:5601/bundles/commons.bundle.js?v=14458:39:4607
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:5601/bundles/commons.bundle.js?v=14458:39:4945
ngEventDirectives[directiveName]</<.compile/</<@http://localhost:5601/bundles/commons.bundle.js?v=14458:42:11102
jQuery.event.dispatch@http://localhost:5601/bundles/commons.bundle.js?v=14458:28:19750
jQuery.event.add/elemData.handle@http://localhost:5601/bundles/commons.bundle.js?v=14458:28:14633
```
- the second time I try to delete a "watcher", I get no error, had a deletion confirmation message... but line is not "visually" removed. If I go to "Alarms" tab and come back to "Watchers" tab, this time, line is "visually" removed. So it is just a "visual" problem.

**Comment by lmangani** [comment]
Excellent work, could you kindly submit the issues separately so we can work them out best?

**Comment by fbaligand** [comment]
@lmangani 
Kibana 5.0.2 is just released out.
I've tried kaae plugin with that version, and kaae is blocked at startup, because in `package.json`, kibana version is set to 5.0.1.
=> Can you update `package.json` to set kibana version to 5.0.2 ?
Or do you want a special issue for that ?

**Comment by fbaligand** [comment]
@lmangani 
I just created the following issues, as you requested :
- link to blank page :  https://github.com/sirensolutions/sentinl/issues/72
- wrong line deleted on "Alarms" tab : https://github.com/sirensolutions/sentinl/issues/73
- fatal error while deletion on "Watchers" tab : https://github.com/sirensolutions/sentinl/issues/74

**Comment by lmangani** [comment]
@fbaligand thanks for following up, we will address the issues individually - kibana.version also updated to 5.0.2 ;)

**Comment by fbaligand** [comment]
Nice ! :)

**Comment by justintime4tea** [comment]
Testing with Kibana 5.1.1 and Elasticsearch 5.1.1

Time Picker isn't working in Firefox or Chrome in Kaee -> Alarm tab.

When I have time I'm going to check out the source for timepicker and see if I can get it working or get it replaced with the original timepicker from Kibana.

**Comment by bassebaba** [comment]
Hello!

I would like to run this with kibana 5.
I tried the snapshot instructions in your readme, but it seems like "kibana plugin" now is "kibana-plugin".  But fails the install.

I think the readme is a bit unclear. 
Does the current master branch not support kibana 5.x?
The green/Black info box says "kibana 4.5+". Is one supposed to undetstand that it means only 4.x+?
5.0 > 4.5+

I guess then I am supposed to use the 5.0 branch? But that one has no commits for 3 months and seems to be 234 commits behind master?

Where can I read about status for Kibana 5.x support?

Thanks!

**Comment by fbaligand** [comment]
Hi,

First, the right instructions for install on kibana 5  are here :
https://github.com/sirensolutions/sentinl/blob/5.0/README.md#installation-steps

Then, the master branch does not support kibana 5. Only the 5.0 branch supports it. 
On master, kibana 4.5+ means 4.5 <= version < 5.0

Currently, the 5.0 branch is an alpha version. 
And yes, that means there are several bugs with kibana 5.

**Comment by kosfist** [comment]
Hi,
When you planned the release for 5 x?

**Comment by lmangani** [comment]
We should have a version for testing around the end of May
