### ISSUE TITLE
An error occured while looking for indices : [security_exception]

### ISSUE THREAD

**Issue by FluffyAlpaca** [sirensolutions/sentinl#160]
Hi, I installed Sentinel v.5.4.2 on Kibana 5.4.3 after editing the package.json. I also have X-Pack installed.

1. Issue Description
When I launch Kibana,  right after the log message "Ready", I have the following error : 
[error][status][Sentinl] An error occurred while looking for indices: [security_exception] action [indices:data/read/search] is unauthorized for user [kibana] :: {"path":"/watcher/watch/_count","query":{},"statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"action [indices:data/read/search] is unauthorized for user [kibana]\"}],\"type\":\"security_exception\",\"reason\":\"action [indices:data/read/search] is unauthorized for user [kibana]\"},\"status\":403}"}

2. Reproducing the Issue step-by-step
I just launched Kibana on the command line : 
kibana.bat

3. Expected Results vs. Actual Results
I don't know if it has an impact on the functionning of Sentinl. 

Thank you in advance for your time.

**Comment by lmangani** [comment]
Hi @FluffyAlpaca 
SENTINL requires read/write permissions to work and is not a read-only Kibana App. In order for it to work with the current version and inherit permissions, Kibana itself should be authorized to access the cluster (via its yaml config)

**Comment by FluffyAlpaca** [comment]
Great, it worked ! If someone has the same error as me, I edited the fields "elasticsearch.username" and "elasticsearch.password" in "kibana.yml".  Thank you for your help !

**Comment by lmangani** [comment]
No problem!

**Comment by gauravkarens** [comment]
Where can I find the kibana.yml file inside the container

**Comment by gauravkarens** [comment]
@FluffyAlpaca  where can I find the kibana.yml file insid the kibana container
