### ISSUE TITLE
5.5 Release

### ISSUE THREAD

**Issue by andyh69uk** [sirensolutions/sentinl#164]
After building a release for 5.5.0 the plugin fails to start with the following error:-

Attempting to transfer from file:///home/osboxes/releases/sentinl-v5.5.0.zip
Transferring 88954789 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Joi.string() does not allow arguments."

Any ideas?

**Comment by lmangani** [comment]
Welcome to our life :) Everytime a new release comes out, we hunt for this type of changes.
Keep an eye on our releases until SENTINL 5.5 is built and supported, until then feel free to share any progress in this ticket.

**Comment by andyh69uk** [comment]
Ok so changing line 80 of index.js to Joi.string().default(undefined) gets over that problem, going to test it out now

**Comment by andyh69uk** [comment]
Kibana now throws this error in the browser:-

Error: TypeError: __webpack_require__(...).register is not a function (http://localhost:5601/bundles/kibana.bundle.js?v=15404:279)
[2491]/window.onerror@http://localhost:5601/bundles/commons.bundle.js?v=15404:90:20880

**Comment by fbaligand** [comment]
@andyh69uk 
In 5.5 version, the way to import dependencies has changed.
If you want to make the migration, here's the changes I've done to migrate transform_vis plugin :
https://github.com/PhaedrusTheGreek/transform_vis/pull/7/files

**Comment by andyh69uk** [comment]
@fbaligand That's awesome, this definitely helped us out, all working now just doing a pull request now

**Comment by lmangani** [comment]
Thanks guys! Much appreciated!
