### ISSUE TITLE
Can't find a solution to use sentinl with x-pack security plugins

### ISSUE THREAD

**Issue by DrizzleRisk** [sirensolutions/sentinl#168]
I have read the elk x-pack document, but can't find way to solve the permission problem

**Comment by lmangani** [comment]
Hi @DrizzleRisk upcoming releases will allow you to define authentication per watcher and instance to provide more flexibility around the various security backends out there, but at this time the only viable way is to set the authentication in Kibana configuration and let SENTINL inherit them, acting as a user.

**Comment by DrizzleRisk** [comment]
OK, I will waitting for the upcoming releases version , thank you very much !

**Comment by jccq** [comment]
Drizzle, for curiosity, why wouldnt use use X Pack notification
capabilities?
best

**Comment by DrizzleRisk** [comment]
@jccq I think it's not good ☺

**Comment by fbaligand** [comment]
"Not good" ?
What do you mean ? X-pack alerting feature is less powerful than sentinl ?

**Comment by DrizzleRisk** [comment]
it's doesn't have an useful ui tool in Visualize

**Comment by fbaligand** [comment]
Indeed !
