### ISSUE TITLE
Created watchers disappeared after re-install

### ISSUE THREAD

**Issue by Macbook-63** [sirensolutions/sentinl#170]
I created some watchers for monitoring our system. After re-creating the server running Kibana and the Sentinl plugin (all v5.4.2) the created watchers didn't show up anymore.

I still can create watchers and do not get any errors. Am I missing something? I would expect the watchers are listed again as the definition is stored in the Elasticsearch index.
I can see the entries in the index 'watcher' but can't see them in the list on the web interface.

Help would be appreciated.

Best, Tom

**Comment by lmangani** [comment]
From which SENTINL/Kibana version were you upgrading?

**Comment by Macbook-63** [comment]
I didn't do an upgrade - I destroyed the server running Kibana+Sentinl (leaving the ES intact) and rebuild it. Always using Kibana+Sentinl in version 5.4.2

**Comment by lmangani** [comment]
Sentinl only initializes a new index when it can't find one - is the startup log reporting anything interesting?

**Comment by Macbook-63** [comment]
I restarted it again and this an the sentinl part:

`{"type":"log","@timestamp":"2017-07-19T13:53:10Z","tags":["status","info","Sentinl"],"pid":982,"message":"Sentinl Initializing"}
{"type":"log","@timestamp":"2017-07-19T13:53:10Z","tags":["status","info","Sentinl"],"pid":982,"message":"Core Index check..."}
{"type":"log","@timestamp":"2017-07-19T13:53:10Z","tags":["status","info","Sentinl"],"pid":982,"message":"Alarm Index check..."}
{"type":"log","@timestamp":"2017-07-19T13:53:19Z","tags":["status","plugin:timelion@5.4.2","info"],"pid":982,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-07-19T13:53:20Z","tags":["status","info","Sentinl"],"pid":982,"message":"Scheduled Watch: new_watcher_5xpg6vl85 every every 1 mins"}
{"type":"log","@timestamp":"2017-07-19T13:53:20Z","tags":["listening","info"],"pid":982,"message":"Server running at http://0.0.0.0:5601"}
{"type":"log","@timestamp":"2017-07-19T13:53:20Z","tags":["status","ui settings","info"],"pid":982,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-07-19T13:53:20Z","tags":["status","error","Sentinl","report"],"pid":982,"message":"Failed to install phantomjs: Error: EACCES: permission denied, mkdir '/usr/share/kibana/plugins/sentinl/phantomjs/phantomjs-2.1.1-linux-x86_64'"}`

only issue I can see is phantomjs but this needed for reports only, right?

**Comment by lmangani** [comment]
Wait, I'm confused. There is a watcher picked up and scheduled - is it showing up? or was this a new test?

**Comment by Macbook-63** [comment]
this watcher 'test' was newly created and is showing up in the list, but the other ones don't. 

Those are the indices in the ES cluster:

`green open watcher_alarms-2017.07.19 fvO0WdJhTiqhtwiERrhiQg 5 1    61 0 444.2kb 222.1kb
green open watcher_alarms-2017.07.17 MQ3xbAV8QliGlXAiRmdzJg 5 1     9 0 134.7kb  67.3kb
green open watcher                   vrtCLb9QRZOcc2T5aBCDyg 1 1    25 4 130.1kb    65kb
green open watcher_alarms            oOXA-ccfSASfdKrmgvksJw 1 1     0 0    260b    130b`

But I can't find the watcher with title 'Test' in the watcher index. What is weitd too is - I created a second watcher and this one isn't in the index 'watcher' as well!

**Comment by lmangani** [comment]
This might sound odd but are you positive you're looking at the right ES server? :)

**Comment by Macbook-63** [comment]
this is the kibana log of creating the watcher:

`{"type":"log","@timestamp":"2017-07-19T14:50:33Z","tags":["status","info","Sentinl"],"pid":982,"message":"Saving Watcher with ID: new_watcher_l4vvbpe
q5"}
{"type":"response","@timestamp":"2017-07-19T14:50:33Z","tags":[],"pid":982,"method":"post","statusCode":200,"req":{"url":"/api/sentinl/watcher/new_watcher_l4vvbpeq5","method":"post","headers":{"x-forwarded-for":"10.107.143.27","x-forwarded-proto":"https","x-forwarded-port":"443","host":"co-kibana-staging.xyz.de","x-amzn-trace-id":"Root=1-596f71b9-53e753a9081395f17a6195f8","content-length":"561","accept":"application/json, text/plain, */*","origin":"https://co-kibana-staging.xyz.de","kbn-version":"5.4.2","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36","content-type":"application/json;charset=UTF-8","dnt":"1","referer":"https://co-kibana-staging.xyz.de/app/sentinl","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4"},"remoteAddress":"10.134.28.143","userAgent":"10.134.28.143","referer":"https://co-kibana-staging.xyz.de/app/sentinl"},"res":{"statusCode":200,"responseTime":51,"contentLength":9},"message":"POST /api/sentinl/watcher/new_watcher_l4vvbpeq5 200 51ms - 9.0B"}
{"type":"response","@timestamp":"2017-07-19T14:50:33Z","tags":[],"pid":982,"method":"get","statusCode":200,"req":{"url":"/","method":"get","headers":{"host":"10.134.29.242:5601","connection":"close","user-agent":"ELB-HealthChecker/2.0"},"remoteAddress":"10.134.95.244","userAgent":"10.134.95.244"},"res":{"statusCode":200,"responseTime":1,"contentLength":9},"message":"GET / 200 1ms - 9.0B"}`

seem like everything went fine

**Comment by Macbook-63** [comment]
that came to my mind as well! So I checked it. The count of watchers show with the '_cat' API on ES side is identical querying the index on Kibana side (index 'watcher').

`green open watcher                   vrtCLb9QRZOcc2T5aBCDyg 1 1    25 4 130.1kb    65kb`

So this should be the ES cluster in use

**Comment by Macbook-63** [comment]
Found it! In the kibana configuration the default_index changed! And as you have to set an index to search in within kibana discover.
As I tried it in the DevTool (where no index is set) I saw the entry in the wrong index. Shame on me and sorry for bothering you.

Best, Tom

**Comment by lmangani** [comment]
No Shame, and Good Catch! Glad you got it sorted and thanks for the update! :)
