### ISSUE TITLE
Can't get any POST body in my remote host

### ISSUE THREAD

**Issue by RickyHuo** [sirensolutions/sentinl#171]
ELK and sentinl version 5.4.2

My action config like this:
```
"actions": {
  "New webhook action aq9e6jb31lt": {
    "throttle_period": "0h0m1s",
    "webhook": {
      "method": "POST",
      "host": "hostname",
      "port": 8080,
      "proxy": false,
      "path": "/alert/sentinl_alert",
      "body": "{\"hello\": \"world\"}"
    }
  }
}
```
But I cant't get any request body in my remote host built by Django.
The interface(**/alert/sentinl_alert**) I built to print POST body.

```
request body:
[20/Jul/2017 02:19:15]"POST /alert/sentinl_alert HTTP/1.1" 500 73711
```

**Comment by lmangani** [comment]
The two examples slightly discord, so I'm not sure what to suggest ( ```/alert/prometheus_alert```vs ```/alert/sentinl_alert```) Please capture the request being sent out for debugging, or check what's causing the 500 on the remote server specifically?

**Comment by RickyHuo** [comment]
@lmangani  Thank you for your replay.
I'm sorry to write the wrong response info.
I have modified the issue yet.

**Comment by lmangani** [comment]
Hi @RickyHuo as the 500 error comes back from your app it probably explains the issue best - based on that, we can "cure" the watcher config accordingly. Thanks!
