### ISSUE TITLE
condition   Configuration detail

### ISSUE THREAD

**Issue by c3399** [sirensolutions/sentinl#172]
Do you have any details about the condition configuration? How can I use it to locate a keyword in the log message?
The condition example of Wiki alone can't be understood. How should I configure it to get the corresponding value?

**Comment by lmangani** [comment]
Hi @c3399 
Condition and Tranform are pure JS expressions targeting the JSON response object returned by ES.
As you can see in the examples you can either have a simple gate (true/false) or complex iterations through the buckets and objects returned, etc.

If you have a specific example you'd like to use for learning feel free to share it here for advice, and we can add it to the WIki to help others later.

**Comment by lmangani** [comment]
Closing as non-issue but feel free to add content if needed
