### ISSUE TITLE
install successed,but show blank in kibana

### ISSUE THREAD

**Issue by benjiming032558** [sirensolutions/sentinl#173]
verson:5.0.1
sentinl install successed,but kibana has nothing like the image belov:
![sentinl](https://user-images.githubusercontent.com/5990264/28450982-509d7a78-6e1d-11e7-969b-9ca7ab9e04b2.png)
I look forward to your answer!!

**Comment by shubhamverma27** [comment]
Its due to Xpack, most probably.
Wait for the next version to release then It will be solved

**Comment by benjiming032558** [comment]
but when i remove Xpack，Still exist the problem

**Comment by thlc** [comment]
Had the same problem with 5.0.0, ended up upgrading the ELK stack to 5.4.2 and the UI plugin now works fine.

**Comment by lmangani** [comment]
Thanks for sharing @thlc indeed unfortunately not much to do about 5.0.x with the number and frequency of updates, current targets are rather 5.5 and 6.0

**Comment by whx4J8** [comment]
thanks for sharing ~

**Comment by woostundy** [comment]
5.1.1 also has this problem, do you have plan to solve it ?
