### ISSUE TITLE
Joi.string() does not allow arguments  - kibana 5.5.0

### ISSUE THREAD

**Issue by mobdns** [sirensolutions/sentinl#174]
Running sentinl undel kibana 5.5.0 produce the following error:

`Jul 21 06:07:53 kibana kibana[40906]: FATAL Error: Joi.string() does not allow arguments.
Jul 21 06:07:53 kibana kibana[40906]:     at Object.exports.assert (/usr/share/kibana/node_modules/joi/node_modules/hoek/lib/index.js:736:11)
Jul 21 06:07:53 kibana kibana[40906]:     at root.string (/usr/share/kibana/node_modules/joi/lib/index.js:93:14)
Jul 21 06:07:53 kibana kibana[40906]:     at ScopedPlugin.config [as getExternalConfigSchema] (/usr/share/kibana/plugins/sentinl/index.js:79:33)
Jul 21 06:07:53 kibana kibana[40906]:     at /usr/share/kibana/src/server/plugins/plugin.js:116:34
Jul 21 06:07:53 kibana kibana[40906]:     at next (native)
Jul 21 06:07:53 kibana kibana[40906]:     at step (/usr/share/kibana/src/server/plugins/plugin.js:21:191)
Jul 21 06:07:53 kibana kibana[40906]:     at /usr/share/kibana/src/server/plugins/plugin.js:21:437
Jul 21 06:07:53 kibana kibana[40906]:     at /usr/share/kibana/src/server/plugins/plugin.js:21:99
Jul 21 06:07:53 kibana kibana[40906]:     at ScopedPlugin.getConfigSchema (/usr/share/kibana/src/server/plugins/plugin.js:118:7)
Jul 21 06:07:53 kibana kibana[40906]:     at /usr/share/kibana/src/server/plugins/plugin_collection.js:18:39
`
Which i believe is triggered by this line:
`/usr/share/kibana/plugins/sentinl/index.js:            phantomjs_path: Joi.string(undefined),`

**Comment by truongdqse03303** [comment]
Have you solved the issue?
I had the same problem and can't find the solution

**Comment by frankvandebergh** [comment]
Have similar issue after upgrading to 5.5.1 and installing the plugin : 
```
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/tag-5/sentinl-v5.5.1.zip
Transferring 116209440 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Joi.string() does not allow arguments."
```

**Comment by lmangani** [comment]
Until merged, manual fix for 5.5+ is the same as shown here by @rmacd : https://github.com/rmacd/sentinl/commit/a082874cb66194168a046861e0e9d94f34a890d1

**Comment by lmangani** [comment]
New Branch is here: https://github.com/sirensolutions/sentinl/tree/branch-5.5

**Comment by lmangani** [comment]
https://github.com/sirensolutions/sentinl/releases/tag/tag-5.5
Closing issue, please re-open if needed on the 5.5 branch
