### ISSUE TITLE
Snapshot plugin install link broken . Tag 5.4.2 wont exist

### ISSUE THREAD

**Issue by ffahri** [sirensolutions/sentinl#175]
https://github.com/sirensolutions/sentinl/#snapshot-plugin-install
this link wont work ->
https://github.com/sirensolutions/sentinl/releases/download/tag-5/sentinl-v5.4.2.zip

**Comment by lmangani** [comment]
rebulding of releases in progress, 5.4.2 will reappear momentarily - unfortunately our features have to be backported each time Elastic decides to add a comma to the code.
