### ISSUE TITLE
conditions in sentinl watcher

### ISSUE THREAD

**Issue by bopagama** [sirensolutions/sentinl#176]
Is sentinl support IF statements in condition potion of the watcher?

I try to put following condition in condition section of the watcher,

`if (payload.aggregations.minutes.buckets.size() == 0) return false; def latest = ctx.payload.aggregations.minutes.buckets[-1]; def node = latest.nodes.buckets[0]; return node && node.cpu && node.cpu.value >= 75;`

But I got Following error on kibana logs,

`"type":"log","@timestamp":"2017-07-27T09:31:30Z","tags":["status","info","Sentinl"],"pid":18513,"message":"Condition Error for new_watcher_eeuxixash: SyntaxError: Illegal return statement"}`

Any ideas??

**Comment by SergeyBondarenko** [comment]
Why do you use `def` keyword here? The condition should be JavaScript, use `var`.

**Comment by bopagama** [comment]
I'm trying to create a Watcher to alert when cpu utilization in over 80%. will this condition work for that purpose?
