### ISSUE TITLE
How to specify index name date format

### ISSUE THREAD

**Issue by v01t** [sirensolutions/sentinl#177]
Hello,

how can I define date format that is used in index names?
as an example I have following index-date format:
- foo-bar-2017-07-26

if I'm adding watcher from discovery tab and check it in watcher object, I see following definitions for index:
- foo-bar-2017-07-26{now/d}
- foo-bar-2017-07-26{now/d-1d}

that, of course, failed during execution because index name contains date twice:
- foo-bar-2017-07-262017.07.26
- foo-bar-2017-07-262017.07.25

but even after manually updating definition for index to:
- foo-bar-{now/d}
- foo-bar-{now/d-1d}

I still see in the error logs that sentinl trying to query:
- foo-bar-2017.07.26
- foo-bar-2017.07.25

so how to define that date format is YYYY-MM-DD and not YYYY.MM.DD, is there some place for that?
Thanks.

kibana/plugin version: 5.2.2

Regards.

**Comment by lmangani** [comment]
Hi @v01t 
SENTINL is not involved with interpreting the dynamic time formats - Elasticsearch does - so the same issue should really appear when using Sense on the same cluster. Could you confirm if this is the case?

**Comment by lmangani** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math

**Comment by v01t** [comment]
Hi @lmangani 
problem is not in interpreting time formats in index name by elastic, yes I can specify:
`foo-bar-{now/d{YYYY-MM-DD}]}` and then elastic will interpret it correctly,
problem is that in doc that created in watcher index by clicking on "add watcher" button in discovery tab, initial value for index name:
`foo-bar-2017-07-26{now/d}`

and I can't modify that, or is there a way to configure that?
Thanks.
