### ISSUE TITLE
Access aggregation buckets for payload

### ISSUE THREAD

**Issue by bopagama** [sirensolutions/sentinl#178]
I need to create a alert when CPU utilization is above 0.05%. In order to do that Flowing input watch was created. 

```
{
  "search": {
    "request": {
      "index": [
        "<metricbeat-{now-5m}>"
      ],
      "body": {
        "query": {
          "bool": {
            "filter": [
              {
                "range": {
                  "@timestamp": {
                    "gte": "now-5m"
                  }
                }
              }
            ]
          }
        },
        "aggs": {
          "host": {
            "terms": {
              "field": "beat.hostname.keyword",
              "size": 20,
              "order": {
                "cpu_utilization": "desc"
              }
            },
            "aggs": {
              "cpu_utilization": {
                "max": {
                  "field": "system.cpu.system.pct"
                }
              }
            }
          }
        }
      }
    }
  }
}
```
But in order to use condition to filter out the CPU utilization above 0.05% for a certain host I have to access buckets inside `host` aggregation. How to access buckets and sub buckets in condition scripts? 

I have run the above input script in SENSE and the aggregation output as follows,

```
..............................
      }
      }
    ]
  },
  "aggregations": {
    "host": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "F01-COM-056",
          "doc_count": 3213,
          "cpu_utilization": {
            "value": 0.06729999929666519
          }
        }
      ]
    }
  }
}
```
I tried following script in Sentinl watch Condition Section. But no success,

`payload.aggregations.host.buckets.cpu_utilization.value > 0.05`

Thanks in advance...

**Comment by seshu3564** [comment]
Buckets is an array there. so you should access using the index. for your example

payload.aggregations.host.buckets[0].cpu_utilization.value > 0.05

**Comment by lmangani** [comment]
Closing as non issue, feel free to continue discussing in this thread if help is needed

**Comment by bopagama** [comment]
It worked..
thank you  @seshu3564

**Comment by bopagama** [comment]
Another issue if I want to get the host name I used following,

`payload.aggregations.host.buckets[0].key.value`

But it's not working? Is it because the host name value is **string type** ?

**Comment by lmangani** [comment]
Glad its working. The second issue depends depends how you're trying to use it in your script, condition or template.

**Comment by bopagama** [comment]
I'm going to use it in Email Alert body.

**Comment by lmangani** [comment]
In this case, its a completely different angle and its related to mustache templating.
Please look up and read read how mustache works for iterating objects and arrays.

Check out our presentation for reference: https://www.slideshare.net/secret/gobTp9S3omqn9a

**Comment by seshu3564** [comment]
you have to paste this in both body and body html 
{{payload.aggregations.host.buckets[0].key}}
key is a string and not object 
if you want value of cpu_utilization use  {{payload.aggregations.host.buckets[0].cpu_utilization.value}}

and you have to learn mustachejs formatting for using payload variables in emails

**Comment by bopagama** [comment]
Yes I got it worked thank you @lmangani and @seshu3564

**Comment by jindov** [comment]
Hi,

I want to the value in this json (condition)
```
"aggregations": {
      "1": {
        "values": [
          {
            "key": 90,
            "value": 1214.4249999999997
          }
        ]
      }
    }
```
`payload.aggregation.1.values[0].value` but it's not working with error `Condition Error for new_watcher_j6m9fy92l: SyntaxError: Unexpected number`

**Comment by lmangani** [comment]
@jindov the answer is in the question itself :)
```payload.aggregation[1].values[0].value```

**Comment by jindov** [comment]
@lmangani thank you for quickly answer, but I think `1` is a nested field, not a property of aggregation. I try yours but this lead to this error `Condition Error for new_watcher_j6m9fy92l: TypeError: Cannot read property '1' of undefined`

**Comment by lmangani** [comment]
You skipped an 's' in the aggregations name probably? You did so in your example too.

**Comment by jindov** [comment]
OMG, sorry @lmangani, my mistake. But I don't understand why `1` is an index. As I see, if I use total hit, it's would be `payload.hits.total`, `total` equal with `1`. Thanks

**Comment by lmangani** [comment]
I believe this should be simply ```{{ payload._id}}``` - inspect the full payload to confirm

**Comment by jindov** [comment]
this is my message in slack action: `{{ payload._id}}: {{#payload.aggregations.1.values}} {{value}} {{/payload.aggregations.1.values}} `
and message was sent is: `:  963.5`

Thanks
