### ISSUE TITLE
problem with emailing sentinl+kibana

### ISSUE THREAD

**Issue by benjaminpeere** [sirensolutions/sentinl#183]
hi everyone, 
i encounter a problem, 
i have create a simple watcher for testing : 
`{
  "_index": "watcher",
  "_type": "monitoring",
  "_id": "new",
  "_version": 4,
  "found": true,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 minutes"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "<monitoring>"
          ],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 0"
      }
    },
    "transform": {
      "script": {
        "script": ""
      }
    },
    "actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "*******@gmail.com",
          "from": "sentinl@localhost",
          "subject": "SENTINL Alarm",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      },
      "slack_admin": {
        "throttle_period": "15m",
        "slack": {
          "channel": "#kibi",
          "message": "SENTINL Alert! Found {{payload.hits.total}} Events"
        }
      }
    }
  }
}`
and i have this error in kibana (i'm using kibana 5 and elasticsearch 5) : 
![capture](https://user-images.githubusercontent.com/19531148/28865458-54e9bbd0-7770-11e7-8bde-e8acc70fc691.PNG)
here is my configuration in kibana.yml : 
![image](https://user-images.githubusercontent.com/19531148/28865763-3b7d4bac-7771-11e7-9039-4c65275b9242.png)

i'm actually using an application password for gmail,
i also have this in my sentinl alarms in kibana : 
![image](https://user-images.githubusercontent.com/19531148/28865601-b91be574-7770-11e7-876b-fefc5e1b8b75.png)

and don't know why my email are not sent, so if you can help me i would really appreciate it!
thanks!

**Comment by lmangani** [comment]
You resolved this issue? I would guess it was the SSL port?

**Comment by gonna123** [comment]
Hello,
I have the same problem, my email are not sent. :(
Here is my configurations in kibana.yml
############################################
sentinl:
   settings:
     e-mail:
       active: true
       user: "XXX" -> user have special character /
       password: "XXX"
       host: "ip: 25"
       ssl: false
     report:
       active: true
       tmp_path: / tmp /
############################################
My logs in kibana:
  log   [13:34:05.368] [info][status][Sentinl][email] Error: timedout while connecting to smtp server
    at module.exports (//kibana-5.5.1/plugins/sentinl/node_modules/emailjs/smtp/error.js:3:13)
    at TLSSocket.timedout (/kibana-5.5.1/plugins/sentinl/node_modules/emailjs/smtp/response.js:32:29)
    at TLSSocket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket.Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

I'm using an my personal smtp server.

I will be grateful for any help! :)

**Comment by lmangani** [comment]
@gonna123 are you using a non-standard port for your server?
@sergibondarenko we might have to add the ```port```,```domain``` and ```tls``` properties to emailjs config
