### ISSUE TITLE
problem creating watcher

### ISSUE THREAD

**Issue by benjaminpeere** [sirensolutions/sentinl#184]
hi everyone, 
i have a problem, i'm new to sentinl and i try to create a watcher to check the last temperature send from elasticsearch in my index monitoring, so i have create the following watcher : 
`{
  "_index": "monitoring",
  "_type": "watch",
  "_id": "new",
  "_version": 14,
  "found": true,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 mins"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "<monitoring>"
          ],
          "body": {
            "query": {
              "filtered": {
                "query": {
                  "query_string": {
                    "analyze_wildcard": true,
                    "query": "*"
                  }
                }
              },
              "filter": {
                "range": {
                  "date": {
                    "from": "now-5m"
                  }
                }
              }
            },
            "aggs": {
              "watch_temp": {
                "field": "temperature"
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.aggregations.watch_temp.value > 20"
      }
    },
    "transform": {
      "script": {
        "script": ""
      }
    },
    "actions": {
      "email_admin": {
        "throttle_period": "0h15m0s",
        "email": {
          "to": "*********@gmail.com",
          "from": "sentinl@localhost",
          "subject": "SENTINL Alarm",
          "priority": "high",
          "body": "anomalie température"
        }
      },
      "slack_admin": {
        "throttle_period": "0h15m0s",
        "slack": {
          "channel": "#kibi",
          "message": "SENTINL Alert! Found {{payload.hits.total}} Events"
        }
      }
    },
    "title": "temperature",
    "disable": false
  }
}`
bu i have the following error : 
![image](https://user-images.githubusercontent.com/19531148/28876321-151e947a-7799-11e7-9f16-dfc22cfd0f3e.png)
i don't know what i do wrong, if there someone who can help me, i would really appreciate it, 
thanks

**Comment by lmangani** [comment]
The filtered query has been deprecated and removed in ES 5.x - are you porting a query from 2.x?

**Comment by benjaminpeere** [comment]
hi, thanks for your reply, no i'm not porting a query from 2.x, i just inspired from this example https://github.com/sirensolutions/sentinl/wiki/SENTINL-Watcher-Examples
what do i have to use instead?

**Comment by lmangani** [comment]
Good point, we'll have to mark this as a 2.x example indeed.
You can read more here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html
