### ISSUE TITLE
Problem sending email

### ISSUE THREAD

**Issue by guy-bouchard** [sirensolutions/sentinl#185]
Kibana 5.4.3

Watchers works and it's very simple:

{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new_watcher_c6nd6oqe2",
  "_version": 46,
  "found": true,
  "_source": {
    "title": "test_watcher",
    "disable": false,
    "uuid": "new_watcher_c6nd6oqe2",
    "trigger": {
      "schedule": {
        "later": "every 30 secs"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "mos"
          ],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.max_score > 0"
      }
    },
    "transform": {
      "script": {
        "script": ""
      }
    },
    "actions": {
      "email_admin": {
        "throttle_period": "0h1m0s",
        "email": {
          "to": "test@gmail.com",
          "from": "test@gmail.com",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Low MOS Detected:"
        }
      }
    }
  }
}

Alarms are well displayed in Kibana but I can't get Sentinl to send email.
Kibana logs always return this error

{"type":"log","@timestamp":"2017-08-03T01:03:35Z","tags":["status","info","Sentinl","email"],"pid":2036,"level":"error","message":"timedout while connecting to smtp server","error":{"message":"timedout while connecting to smtp server","name":"Error","stack":"Error: timedout while connecting to smtp server\n    at module.exports (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/error.js:3:13)\n    at Socket.timedout (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/response.js:32:29)\n    at Socket.g (events.js:291:16)\n    at emitNone (events.js:86:13)\n    at Socket.emit (events.js:185:7)\n    at Socket._onTimeout (net.js:342:8)\n    at ontimeout (timers.js:380:14)\n    at tryOnTimeout (timers.js:244:5)\n    at Timer.listOnTimeout (timers.js:214:5)","code":4}}

kibana.yml

sentinl:
  settings:
    email:
      active: true
      user: XXXXXXXX
      password: XXXXXXX
      host: smtp.mailtrap.io
      ssl: false
    report:
      active: true
      tmp_path: /tmp/

I also tried with gmail , no luck

No proxies, direct access to the web

thanks

**Comment by bopagama** [comment]
Try to  fix this issue yourself by changing smtp.js in emailjs from `this.loggedin = (options.user && options.password) ? false: true; " to this.loggedin = (options.user && options.password) ? true : false;`

**Comment by guy-bouchard** [comment]
Thanks bopagama,

I've just tried that, same error.

**Comment by bopagama** [comment]
Have you done a full server restart?

**Comment by lmangani** [comment]
The error seems very clear: ```timedout while connecting to smtp server``` so either the port is wrong, or there's a firewall rule in between, etc.

**Comment by guy-bouchard** [comment]
bopagama, yes I even reboot the vm and it doesn't work

Imangani there is not firewall, no selinux, no proxy...

mail -s "Test Subject" xxxxx@gmail.com < /dev/null 
from command line works

Thanks

**Comment by lmangani** [comment]
the method the local command and our client use are radically different. Please try configure the delivery to a mailtrap.io account or alternate destination (with different smtp) to get more details

**Comment by guy-bouchard** [comment]
Hi Imangani,

I have no problems sending mails to mailtrap.io with their smtp server with mailx on the same centos 7 machine .

echo "This is the message body and contains the message" | mailx -v -r "xxxxx@gmail.com" -s "This is the subject" -S smtp="smtp.mailtrap.io:25" -S smtp-auth=login -S smtp-auth-user="xxx" -S smtp-auth-password="xxx" -S ssl-verify=ignore  xxxx@gmail.com
Resolving host smtp.mailtrap.io . . . done.
Connecting to 34.230.160.120:25 . . . connected.
220 mailtrap.io ESMTP ready
>>> EHLO localhost
250-mailtrap.io
250-SIZE 5242880
250-PIPELINING
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-AUTH PLAIN LOGIN CRAM-MD5
250 STARTTLS
>>> AUTH LOGIN
334 xxxxx
>>> xxxxx=
334 xxxxx
>>> xxxxx=
235 2.0.0 OK
>>> MAIL FROM:<xxxxx.com>
250 2.1.0 Ok
>>> RCPT TO:<xxxxx@gmail.com>
250 2.1.0 Ok
>>> DATA
354 Go ahead
>>> .
250 2.0.0 Ok: queued
>>> QUIT
221 2.0.0 Bye

Thanks

**Comment by guy-bouchard** [comment]
Hi,

I increased the timeout in kibana.yml
timeout: 10000

Now I receive this error

{"type":"log","@timestamp":"2017-08-03T23:40:35Z","tags":["status","info","Sentinl","email"],"pid":2500,"level":"error","message":"connection encountered an error","error":{"message":"connection encountered an error","name":"Error","stack":"Error: connection encountered an error\n    at module.exports (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/error.js:3:13)\n    at TLSSocket.error (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/response.js:26:29)\n    at emitOne (events.js:101:20)\n    at TLSSocket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1281:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)","code":5}}

**Comment by SergeyBondarenko** [comment]
@guy-bouchard try to put `ssl: true` in kibana.yml

**Comment by gsjadhawar** [comment]
@guy-bouchard I am also facing issue. if you solved can you please let me know solution for it

**Comment by msgtomm** [comment]
Looks like sentinl uses TLS port (587) for email delivery. mailx by default uses 25. can you check,if 587 port is allowed in your environment.
