### ISSUE TITLE
Webhook Elasticsearch

### ISSUE THREAD

**Issue by mza97** [sirensolutions/sentinl#186]
I would like to index a new document with Webhook within the interface but I don't know how to add payload's elements.

I tried:
```
@timstamp: {{payload.date}}
and
{"@timstamp": {{payload.date}}}
and
'"@timstamp": {{payload.date}}'
```

without payload's elements it's working:
```
{"@timstamp": "data"}
```

**Comment by lmangani** [comment]
Hi @mza97 this approach is well described in our presentation as well as implemented within the [ATLAS](https://github.com/sirensolutions/sentinl/wiki/Statistical-Anomaly-Detector#first-watcher) example in our wiki. Please take a look it should answer your question.

**Comment by lmangani** [comment]
Closing. Feel free to continue commenting here if you need help!

**Comment by mza97** [comment]
Yep thank you it helped, I forgot the "" around payload elements
from the interface:
```
{"@timestamp":"{{payload.date}}"}
```
