### ISSUE TITLE
Not all the watchers is displayable in the sentinl interface

### ISSUE THREAD

**Issue by mza97** [sirensolutions/sentinl#189]
I wanted to test if sentinl can handle up to 1000 watches, I created a simple script and added 1001 watches in the watcher index.

All the watches are not displayable (even with the search bar), however Sentinl processed them all. 

![w1](https://user-images.githubusercontent.com/17797162/29195331-4266cd94-7e2e-11e7-8437-b080837bb74b.png)
![w2](https://user-images.githubusercontent.com/17797162/29195332-4267de46-7e2e-11e7-8abe-40fbc06435c5.png)
![w3](https://user-images.githubusercontent.com/17797162/29195333-426e5122-7e2e-11e7-9d85-f34f573e7d68.png)
![w4](https://user-images.githubusercontent.com/17797162/29195334-426e6090-7e2e-11e7-98b7-39be6b2c8ae0.png)

**Comment by lmangani** [comment]
Nice Test! Have you tried to fiddle with the results configuration? It limits the results of the list function:
```
sentinl:
  sentinl:
    results: 50
```

**Comment by lmangani** [comment]
Closing this as we're moving to a different display approach to minimize the challenges, displaying contents only on demand. Watch for upcoming releases to feature this improvement.
