### ISSUE TITLE
Headers dissappear from action tab

### ISSUE THREAD

**Issue by seshu3564** [sirensolutions/sentinl#191]
Whenever i try to edit a watcher from sentinl ui and i save the watcher without opening webhook action tab the headers from webhook action becomes empty. But if i open the webhook once and then save the watcher then the headers stays.

**Comment by lmangani** [comment]
please attach screenshots and logs, thanks

**Comment by lmangani** [comment]
@seshu3564 Do you have any details or data to reproduce and work this case?

**Comment by oscarquinde** [comment]
@lmangani  I also noticed this, very annoying when editing frequently Watchers with webhooks , can't give logs but detailed steps to reproduce are:

1) Open watcher editor on an existing watcher.
2) Go to to actions, and check the webhook headers exists.
3) Click on save (top right corner button)
4) When the watcher is successfully saved, check the webhook header again, now its empty. But if you go to Raw the header exists.

My current workaround is return to Watchers list, and open from there the editor then the headers show up.

**Comment by lmangani** [comment]
Thanks @oscarquinde for the detailed steps to reproduce.
@sergibondarenko could you take a look and include this in the next patch set?

**Comment by lmangani** [comment]
@sergibondarenko could you add this check to the next batch general? Might be already resolved?

**Comment by lmangani** [comment]
Moving to 6.x and cleaning up issues. Please reopen if this is still useful / required. Thanks!
