### ISSUE TITLE
Notification when status is ALERT or OK

### ISSUE THREAD

**Issue by jindov** [sirensolutions/sentinl#192]
Hi guys,

Like many notification systems, I think sentinl should have an option to execute when the value is below threshold, sending an alert when over threshold then sending an ok when it back to normal. And slack action should allow customize template with color for ALERT(red) or OK(green)
Thanks

**Comment by lmangani** [comment]
This will be possible with action conditions, discussed in https://github.com/sirensolutions/sentinl/issues/234
