### ISSUE TITLE
How to get reports from Kibana dashboard protected with Searchguard

### ISSUE THREAD

**Issue by rohitchaudhary95** [sirensolutions/sentinl#193]
Report function of Sentinl is taking screenshot of searchguard login page and sending mail.
The dashboard is protected by Seachguard login.

I'm using Elastic 5.5, Kibana 5.5 and searchguard for both elastic and kibana.

Is there any way to access dashboard?

**Comment by lmangani** [comment]
Proper security integration w/ Search Guard is currently only available for Kibi users - unless your setup allows authentication to be defined as part of the monitored URL and/or whitelist SENTINL as client.

**Comment by jerpic** [comment]
Hello @rohitchaudhary95 , I have exactly the same issue, did you find a solution ?

Regards
