### ISSUE TITLE
Restrict access of Sentinl app to admin

### ISSUE THREAD

**Issue by rohitchaudhary95** [sirensolutions/sentinl#195]
Hi,
I'm using Elasticsearch-5.5, Kibana-5.5, searchguard-5.5 and sentinl-5.5. 
Is there a option to show sentinl app for creating alerts and reports only to admin?

**Comment by lmangani** [comment]
Hi,
This is currently only possible when using Kibi and its integration with SearchGuard featuring user-level permissions, etc.
