### ISSUE TITLE
watcher index: please explain "input" and "condition" types

### ISSUE THREAD

**Issue by uschtwill** [sirensolutions/sentinl#196]
This is just a question to better understand how Sentinl works.

I am looking at the "watcher" `index` and see 3 different `types`: `watch`, ´input` and `condition`.

But it seems like the `watch` type documents already carry complete watcher information, and`input` and `condition` type documents are just free-floating and dangling parts that are not references anywhere else. 

Could someone explain the different types, how they work together and what they're for?

**Comment by lmangani** [comment]
Hi @uschtwill did you check out the SENTINL [presentation](https://www.slideshare.net/secret/gobTp9S3omqn9a) available on the wiki? I think it should answer most of your questions - if not feel free to post here.

**Comment by uschtwill** [comment]
Jep, that answered the question. Thanks!
