### ISSUE TITLE
Is it possible send report by webhook?

### ISSUE THREAD

**Issue by cyberdak** [sirensolutions/sentinl#197]
My server hava no internet premission,i want send report by webhook just like watcher.

**Comment by lmangani** [comment]
I'm sorry I do not understand your scenario. Could you please raise an issue providing a description, expected/desired results vs. actual results?

**Comment by cyberdak** [comment]
reporter now only provide a email action, i want a webhook action which can
send reporter by http-POST.

2017-08-22 22:51 GMT+08:00 Lorenzo Mangani <notifications@github.com>:

**Comment by lmangani** [comment]
we do already provide webhook support since quite a while. Are you running a recent version?

**Comment by cyberdak** [comment]
my version is 5.4.3.

Lorenzo Mangani <notifications@github.com>于2017年8月22日周二 下午11:24写道：

**Comment by cyberdak** [comment]
look Readme.MD agian,it said,"deliver them via email using the report
<https://github.com/sirensolutions/sentinl/wiki/KAAE-Report-Example> action
".
so, is it forget to update this document or it is still only can send
reporter vis email?


Alex Dak <hyperdak@gmail.com>于2017年8月22日周二 下午11:35写道：

**Comment by lmangani** [comment]
Have you installed SENTINL? If you did, you probably know there is a wizard proposing all the supported options - some need configuration such as email and slack, others do not. 

All the current options are listed on our wiki: https://github.com/sirensolutions/sentinl/wiki/SENTINL-Watcher-Actions

Hope this helps!
