### ISSUE TITLE
How to embed report snapshot in the email instead of attachmements

### ISSUE THREAD

**Issue by targeting** [sirensolutions/sentinl#198]
1. Issue Description How to embed report snapshot(image in png format) that is generated through watcher as inline email message instead of attachments

2. Reproducing the Issue step-by-step
I have scheduled a watched to run every 1 hour, once the the watcher is triggererd, it is configured to pull a snapshot of Dashboard that leads to the generation of image in PNG format, when the email is sent it goes out as attachments, is there a way to configure embedding the image in email through Sentinl watcher configurations
3. Expected Results vs. Actual Results

4. Additional Details

**Comment by lmangani** [comment]
Please use the ```email_html``` examples to achieve what you're after - feel free to comment here if needed.
