### ISSUE TITLE
Can't delete watcher that the value of "_id" end with space

### ISSUE THREAD

**Issue by wuyouzi** [sirensolutions/sentinl#199]
While the watcher _id that end with space，the delete request URL is : "http://xxx.xxx.xxx.xxx/api/sentinl/delete/watcher/test". The response of this request will be `{"statusCode":404,"error":"Not Found","message":"Error: Not Found"}`. 
The right URL should be : "http://xxx.xxx.xxx.xxx/api/sentinl/delete/watcher/test%20".

**Comment by wuyouzi** [comment]
Branch 4.6.4. Thanks!

**Comment by lmangani** [comment]
a space as part of the ```_id```? my first question would be why/how would that be a use case?
