### ISSUE TITLE
Need help with query watcher

### ISSUE THREAD

**Issue by truongdqse03303** [sirensolutions/sentinl#200]
I have this query 
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new_watcher_illttg8d1",
  "_version": 4,
  "found": true,
  "_source": {
    "title": "watcher_title",
    "disable": false,
    "uuid": "new_watcher_illttg8d1",
    "trigger": {
      "schedule": {
        "later": "every 5 secs"
      }
    },
    "input": {
      "index": "heartbeat-*",
      "query": {
        "query_string": {
          "analyze_wildcard": true,
          "query": "*"
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.up : false"
      }
    },
    "transform": {
      "script": {
        "script": ""
      }
    },
    "actions": {
      "report_admin": {
        "throttle_period": "0h0m5s",
        "report": {
          "to": "report@localhost",
          "from": "sentinl@localhost",
          "subject": "Sentinl Report",
          "body": "Sample Sentinl Screenshot Report",
          "snapshot": {
            "res": "1280x900",
            "url": "http://127.0.0.1/app/kibana#/dashboard/Alerts",
            "path": "/tmp/",
            "params": {
              "delay": 5000
            }
          }
        }
      }
    },
    "report": true
  }
}
```
Can anyone help me how to correct this to run watcher?
Thanks

**Comment by lmangani** [comment]
It's unclear what the issue even is - maybe you could describe the expected vs. actual results as suggested by our template. At first sight, the issue is with your condition - its unclear what you're trying to do there?

**Comment by truongdqse03303** [comment]
Hi @lmangani 
I try to set watcher about the up field of heartbeat index.
My expected results is whenever up field of heartbeat is false, tell me in the Alarms page. 
Actual results i dont see anything in alarms page
Thanks

**Comment by lmangani** [comment]
We'll need to see what the query responds to give you actual advice as I (at least) have no clue what the ```payload.hits``` returns. Run it in SENSE and paste the output here.

**Comment by truongdqse03303** [comment]
Hi @lmangani 
Here is my query and result
![capture](https://user-images.githubusercontent.com/14819525/29697045-ee642aa8-8976-11e7-8ba6-cadd4db819cc.PNG)

**Comment by lmangani** [comment]
Alright, so your actual data sits inside ```payload.hits.hits``` which is an array. In order to check if any of the returned values for ```up``` are ```false``` and trigger the screenshot, you need to iterate the elements and return true to the condition if any are found. You could try something as follows (untested):
```var status=false; payload.hits.hits.forEach(function(e){ if (e.up == false){ status=true; return status; } }); status; ```

**Comment by truongdqse03303** [comment]
Hi @lmangani 
Thank for your advise, i was curious how can i test my query if the watcher run or not?
