### ISSUE TITLE
Watcher action email_html is not sending action's html text

### ISSUE THREAD

**Issue by mknezic** [sirensolutions/sentinl#201]
1. Issue Description
    When using email_html action I configured different messages for plaint text (email_html action's body property) and HTML email (email_html action's html property). However, I'm only getting emails with plain text.

2. Reproducing the Issue step-by-step
    Configure email_html action, in body property set message1, in html property set message2. When action is triggered and email is sent, email will contain message1 in both text/html and text/plain email message parts.

3. Expected Results vs. Actual Results
    Email message should have HTML body from action's html property, not action's body property (which is valid for text part, not HTML part of message, as per configuration examples from wiki).

4. Additional Details
    It seems there is a typo in https://github.com/sirensolutions/sentinl/blob/master/server/lib/actions.js#L202, instead of using **action.email_html.body** there should be **action.email_html.html** at both places in given line, to use configured html text as per given configuration sample at line https://github.com/sirensolutions/sentinl/blob/master/server/lib/actions.js#L194.

**Comment by lmangani** [comment]
Thanks @mknezic Great report! We're looking into this.
