### ISSUE TITLE
Using bound condition in sentinl

### ISSUE THREAD

**Issue by Arun-Ghosh** [sirensolutions/sentinl#203]
Hi Team,

Seems like below kind of condition ids not working in sentinl.
**payload.hits.total >= 1 AND payload.hits.total <= 3**

Am I doing something wrong or its still not supported ?

**Comment by lmangani** [comment]
Hi @Arun-Ghosh our scripts are in plain Javascript, so ```ÀND``` is not a recognized condition - Please try something like: ```(payload.hits.total >= 1 && payload.hits.total <= 3)```

**Comment by Arun-Ghosh** [comment]
Thank you @lmangani ... Really Appreciate

**Comment by lmangani** [comment]
No Problem! Hope you'll enjoy Sentinl ;)
