### ISSUE TITLE
Actions are replacing text with HTML entity names instead of the original value

### ISSUE THREAD

**Issue by bhatch4** [sirensolutions/sentinl#204]
**1. Issue Description**
We have sentinl setup to email and write to console whenever a specific text appears in our logs. If it finds a match it will include the top few errors messages in the body of the email or console so that we can more quickly understand what is going on. 

The problem is that it is replacing certain characters with the correlating HTML entity value. For example, double quotes are replaced with `&quot;`. Single quotes are replaced with `&#39;` and so on. This makes the alert much harder to read depending on what kind of data you are storing.

**2. Reproducing the Issue step-by-step**

First insert some data into Elasticsearch that contains some special characters such as quotes, semi colons and other characters. 

Now write an input that pulls this data in. In our situation we ran an aggregation type query. The results of our query look like the below.

```
"aggregations": {
    "2": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "Cannot open database \"dlrMaster\" requested by the login. The login failed.\r\nLogin failed for user 'PROD\\username'.",
          "doc_count": 3
        },
        {
          "key": "Cannot open database \"dlrAdmin\" requested by the login. The login failed.\r\nLogin failed for user 'PROD\\username'.",
          "doc_count": 2
        }
	}
}
```

Now create an action on this data. We have tried write to console and email with the same results. Our action looks like the below. 

```
The most common messages were:

{{#payload.aggregations.2.buckets}}
Number of Events: {{doc_count}}
Message: {{key}}


{{/payload.aggregations.2.buckets}}
```

Now let it run and check the console/check your email. The above data was translated to look like:
```
The most common messages were:

Number of Events: 3
Message: Cannot open database &quot;dlrMaster&quot; requested by the login. The login failed.
Login failed for user &#39;PROD\username&#39;.


Number of Events: 2
Message: Cannot open database &quot;dlrAdmin&quot; requested by the login. The login failed.
Login failed for user &#39;PROD\username&#39;.
```

**3. Expected Results vs. Actual Results**

We would expect the alert body to match the original data from Elasticsearch as closely as possible. Preferably line feeds and all. Any special characters in the ES data should show up the same way in any actions.
However in this situation line feeds were ignored, and some characters such as double and single quotes were replaced with the [HTML entity name/number](https://www.w3schools.com/html/html_entities.asp). 

**4. Additional Details**

I was thinking at first that it may have been due to email vs HTML email, but the exact same thing occurs when it is written to the console which does not have those options.

**Comment by lmangani** [comment]
Hi @bhatch4 

In mustache all variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{key}}} - it's that simple and not a bug, rather a feature.

Thanks!

**Comment by lmangani** [comment]
Just noticed this is also in the FAQ: https://github.com/sirensolutions/sentinl/wiki/SENTINL-FAQ#q-how-can-i-avoid-string-encoding-in-mustache-templates-output

**Comment by bhatch4** [comment]
Just in case someone is still looking at this, the URL for the FAQ changed. You can now find it here. 
http://sentinl.readthedocs.io/en/latest/FAQ/#how-can-i-avoid-string-encoding-in-mustache-templates-output
