### ISSUE TITLE
Kibana 5.6.0

### ISSUE THREAD

**Issue by Youkoulayley** [sirensolutions/sentinl#206]
Hi,

When could you release a 5.6.0 compatible version with Kibana ?

Thanks in advance.

**Comment by lmangani** [comment]
Hi @Youkoulayley we do not have an actual ETA yet for 5.6.0 or 6.0.0 (which I believe are similar in changes) keep an eye on the release pages in the coming weeks. 

You can of course attempt to build a SENTINL for 5.6.0 starting from the latest release in the meantime and report any errors in this thread. Thanks!

**Comment by sergibondarenko** [comment]
The release was published https://github.com/sirensolutions/sentinl/releases/tag/tag-5.6.2

**Comment by fbaligand** [comment]
Great !
Thanks for your work @sergibondarenko !

**Comment by smoreaud** [comment]
Nice! Thanks.
