### ISSUE TITLE
Support for "composite schedules" of later.js 

### ISSUE THREAD

**Issue by shamil** [sirensolutions/sentinl#207]
Currently to use the more advanced schedule definitions like `on the 15th through 20th day of the month` I need to use `raw` editing mode. It would be nice to have an option set those generally and not via `raw` tab.

**Comment by lmangani** [comment]
Hi @shamil thanks for your enhancement suggestion.

The wizard is designed with those with no knowledge (or will to mature it) about later.js - we will discuss and consider adding a "switch" button to the form accepting raw input in future revisions. Anyone else with the same problem out there?

**Comment by shamil** [comment]
Thanks for response @lmangani 

My main concern is if I mistakenly save the watcher without enabled `raw` mode I lose he schedule definition which resets to empty string.

**Comment by lmangani** [comment]
@shamil is this still an issue with the latest releases? Please comment to re-open if needed.
