### ISSUE TITLE
Firewalled environments cannot load bootstrap.min.css from CDN

### ISSUE THREAD

**Issue by magruder85** [sirensolutions/sentinl#208]
1. Issue Description

Loading the sentinl plugin in a firewalled envionment is not possible due to reliance on maxcdn connection to download bootstrap.min.css

There are two ways to reproduce. 
Install Kibana/ES on a local machine. Install Sentinel plugin. Turn off internet connection. Navigate to Sentinl plugin. Dev tools will show hanging on maxcdn to download boostrap.min.css.

You could also modify your local hosts file or resolv.conf to force all DNS requests for maxcdn.bootstrapcdn.com to return 127.0.0.1. 

I understand this is likely an edge case but there should be consideration of fallback to local incase of CDN outages. (rare but when they happen you notice it). There's a good article on this here:

http://www.hanselman.com/blog/CDNsFailButYourScriptsDontHaveToFallbackFromCDNToLocalJQuery.aspx

For now, I have created a local copy of boostrap.min.css and modified the import statement in sentinl.style.css so that it points to a copy local to the bundles directory. That's the best hacking around it I can do for now but wanted to open this issue up for awareness. 

Thank you. Let me know if there's anything I'm missing in this issue.

**Comment by lmangani** [comment]
@sergibondarenko lets include this dependency on the next release

**Comment by lmangani** [comment]
Now included in archive, backported back to 5.6 releases
Please retest and comment to re-open this issue.
