### ISSUE TITLE
Condition is not working 

### ISSUE THREAD

**Issue by oldcodeoberyn** [sirensolutions/sentinl#210]
In server/lib/scheduler.js:199:
```javascript
        /* Validate Condition */
        let ret;
        try {
          ret = eval(condition); // eslint-disable-line no-eval
        } catch (err) {
          server.log(['error', 'Sentinl', 'scheduler'], `Condition Error for ${task._id}: ${err}`);
        }

        if (ret) {
          if (transform.script) {
            try {
              eval(transform.script.script); // eslint-disable-line no-eval
            } catch (err) {
              server.log(['error', 'Sentinl', 'scheduler'], `Transform Script Error for ${task._id}: ${err}`);
            }

```
here condition is an object something like: "{ script: { script: 'payload.hits.total >= 100' } }"
eval(condition) will return this object. if(ret) will always pass, since the ret is also an exist object
it have to be fixed like:
```javascript
        /* Validate Condition */
        let ret = false;
        if(condition.script)
        {
          try {
            ret = eval(condition.script.script); // eslint-disable-line no-eval
          } catch (err) {
            server.log(['error', 'Sentinl', 'scheduler'], `Condition Error for ${task._id}: ${err}`);
          }
        }
```

**Comment by jmmerino** [comment]
Same problem here. 

For now I have a workaround, using "range" instead of "condition". For example, to check if there are more than 50 results this is my config in "condition" tab:
```
{
  "range": {
    "field_to_check": "payload.hits.total",
    "min": 50,
    "max": 99999,
    "tolerance": 5
  }
}
```

if there are more than 99999 results, no alert is triggered... but it's better than no condition at all... 😬

**Comment by StupidScience** [comment]
Not sure if i have same problem. But simple condition doesn't work.
For example i just trying:

```
{
  "script": {
    "script": "payload.aggregations.summa.value > 10000000"
  }
}
```

And it always return true.
Also tried:
```
{
  "range": {
    "field_to_check": "payload.aggregations.summa.value",
    "min": 10000000,
    "max": 9999999999,
    "tolerance": 5
  }
}
```
and looks like it works, but when payload.aggregations.summa.value=0 it's also alerts to me.

Tried to use complex conditions to fix it:

```
{
  "script": {
    "script": "payload.hits.total > 0"
  },
  "range": {
    "field_to_check": "payload.aggregations.summa.value",
    "min": 10000000,
    "max": 9999999999,
    "tolerance": 5
  }
}
```

but it also always return true.

**Comment by lmangani** [comment]
Thanks for your report! Patch combo for conditions is on the way.

**Comment by sergibondarenko** [comment]
@oldcodeoberyn @StupidScience @jmmerino @lmangani 
Fixed, install Sentinl .zip from release https://github.com/sirensolutions/sentinl/releases/tag/tag-5.5 or deploy from [master branch](https://github.com/sirensolutions/sentinl).
Feel free to re-open this issues if you see the problem again.

**Comment by StupidScience** [comment]
Looks like now even just `payload.hits.total > 0`script doesn't work

**Comment by sergibondarenko** [comment]
@oldcodeoberyn @StupidScience @jmmerino @lmangani 
There is a fix. Please install new Sentinl .zip from release https://github.com/sirensolutions/sentinl/releases/tag/tag-5.5 or deploy from [master branch](https://github.com/sirensolutions/sentinl).

**Comment by StupidScience** [comment]
Now looks like conditions working great. 
Big thanks guys.

**Comment by lmangani** [comment]
Great work @sergibondarenko patching this quickly and efficiently. Closing.
