### ISSUE TITLE
Some troubles with sentinl and elasticsearch watcher

### ISSUE THREAD

**Issue by jmreymond** [sirensolutions/sentinl#212]
Hi,
I am using sentinl with Kibana 5.5.
In my configration of kibana.yml, I have a user sentinl

```
elasticsearch.username: "sentinl"
elasticsearch.password: "elastic"
```

In elasticsearch watcher,  the user sentinl has a role role_sentinl:
Privileges all on watcher/* watcher_alarms/* watcher/sentinl-watcher/*

When kibana starts, I have the following messages
```
  log   [07:40:30.376] [error][status][Sentinl] Failed to check if core index exists: Authorization Exception :: {"path":"/watcher","query":{},"statusCode":403,"response":""}
  log   [07:40:30.379] [info][status][Sentinl][report] Phantom installed at /usr/share/kibana-pirate/plugins/sentinl/phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  log   [07:40:30.385] [error][status][Sentinl] [security_exception] action [indices:admin/mapping/put] is unauthorized for user [sentinl]
  log   [07:40:30.387] [error][status][Sentinl] Failed to check if core index exists: Authorization Exception :: {"path":"/watcher_alarms","query":{},"statusCode":403,"response":""}
```

and each minute, the following message

`log   [07:34:25.086] [error][status][Sentinl][scheduler] An error occurred while looking for data in indices: [security_exception] action [indices:data/read/search] is unauthorized for user [sentinl] :: {"path":"/watcher/sentinl-watcher/_count","query":{},"statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"action [indices:data/read/search] is unauthorized for user [sentinl]\"}],\"type\":\"security_exception\",\"reason\":\"action [indices:data/read/search] is unauthorized for user [sentinl]\"},\"status\":403}"`}``

A clic on in the GUI on sentinl/Watchers gives the message in log file:
```
error  [07:44:54.837]  [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="watcher" & index_uuid="_na_" & index="watcher" } :: {"path":"/watcher/sentinl-watcher/_search","query":{"size":50,"allow_no_indices":false},"statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index_uuid\":\"_na_\",\"index\":\"watcher\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index_uuid\":\"_na_\",\"index\":\"watcher\"},\"status\":404}"}
    at respond (/usr/share/kibana-pirate/node_modules/elasticsearch/src/lib/transport.js:295:15)
    at checkRespForFailure (/usr/share/kibana-pirate/node_modules/elasticsearch/src/lib/transport.js:254:7)
    at HttpConnector.<anonymous> (/usr/share/kibana-pirate/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/usr/share/kibana-pirate/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

```
what's wrong with my installation ?
any tips ?
Thanks for your advice

**Comment by jmreymond** [comment]
what do you mean with "the SENTINL user being configured in your kibana.yml" ?
In my kibana.yml, I use 
`elasticsearch.username: "sentinl"`
and the user sentinl has very large rights
I have the same issue whith pre-build user elastic which is admin

**Comment by lmangani** [comment]
As you can see from the logs, the user does not have sufficient rights to even create its own indices ```[indices:data/read/search] is unauthorized for user [sentinl]```

**Comment by jmreymond** [comment]
I have found a superuser role and it is correct
thanks
