### ISSUE TITLE
index closed exception

### ISSUE THREAD

**Issue by jmreymond** [sirensolutions/sentinl#214]
1. Issue Description
message in log file: 
  log   [09:03:54.500] [error][Sentinl][scheduler] An error occurred while executing the task._source: [index_closed_exception] closed, with { index_uuid="U0H1r--qSCmuVNcL8blc8w" & index="idx_mys_bad_demiis-2017.08.24" } :: {"path":"//_search","query":{},"body":"{}","statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_closed_exception\",\"reason\":\"closed\",\"index_uuid\":\"U0H1r--qSCmuVNcL8blc8w\",\"index\":\"idx_mys_bad_demiis-2017.08.24\"}],\"type\":\"index_closed_exception\",\"reason\":\"closed\",\"index_uuid\":\"U0H1r--qSCmuVNcL8blc8w\",\"index\":\"idx_mys_bad_demiis-2017.08.24\"},\"status\":403}"}

2. Reproducing the Issue step-by-step

kibana with sentinl is running and watcher action is scheduled

3. Expected Results vs. Actual Results
watcher does not work but it is the first run. Not sure that 403 error is the cause
4. Additional Details

Closed index are usual in our environnment and sometimes we open again these indexes.

**Comment by jmreymond** [comment]
more precisely, I have an alias with closed indexes.
So, I purge the alias and no more error messages

**Comment by lmangani** [comment]
@jmreymond thanks for the resport, but I'm not sure what could be expected out of SENTINL since the error message (thus decision to 403) is coming from the backend and not our API. Any suggestion here?

**Comment by jmreymond** [comment]
I have the same issue withHEAD and I have "solved" with curator removing each night closed indexes from aliases

**Comment by lmangani** [comment]
Closing for lack of action request. Feel free to comment if useful and thanks for sharing!
