### ISSUE TITLE
[Reporting] Visualize: unknown error

### ISSUE THREAD

**Issue by jmreymond** [sirensolutions/sentinl#219]
1. Issue Description

When using report facility to have kibana screenshots, the kibana scrrenshot is not complete and the title of the window has the message Visualize: unknow error
2. Reproducing the Issue step-by-step
create a report in sentinl with valid URL

3. Expected Results vs. Actual Results
have a complete screenshot Kibana
4. Additional Details
In my browser, all is OK
no shield or watcher installed

![report-1wx06thqx-28-09-2017-12-3-21](https://user-images.githubusercontent.com/8809413/30961462-941de1d4-a446-11e7-9660-b243de70774a.png)

set loglevel.debug to true in kibana.yml
[bugs-sentinl.txt](https://github.com/sirensolutions/sentinl/files/1340454/bugs-sentinl.txt)

**Comment by lmangani** [comment]
@jmreymond we'll need to see how you configured your report watcher in order to help. Its definitely something in the query or URL you're passing Kibana as ENTINL only takes a screenshot using the details and does not interact much with the content.

**Comment by jmreymond** [comment]
My raw file
[sentinl-raw.txt](https://github.com/sirensolutions/sentinl/files/1340773/sentinl-raw.txt)

short URL is
http://up0tx755:5601/goto/66067a30b81f7b4f2879b03fed94b6e7
long URL is:
http://up0tx755:5601/app/kibana?#/visualize/create?type=line&indexPattern=idx_mys_bad_*&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(filters:!(),linked:!f,query:(query_string:(analyze_wildcard:!t,lowercase_expanded_terms:!f,query:%27type:MYS_BAD_F5*%27)),uiState:(),vis:(aggs:!((id:%271%27,params:(),schema:metric,type:count),(id:%272%27,params:(customInterval:%272h%27,extended_bounds:(),field:%27@timestamp%27,interval:auto,min_doc_count:1),schema:segment,type:date_histogram),(id:%273%27,params:(field:idnt_datacenter,order:desc,orderBy:%271%27,size:5),schema:group,type:terms)),listeners:(),params:(addLegend:!t,addTimeMarker:!f,addTooltip:!t,defaultYExtents:!f,drawLinesBetweenPoints:!t,interpolate:linear,radiusRatio:9,scale:linear,setYExtents:!f,shareYAxis:!t,showCircles:!t,smoothLines:!f,times:!(),yAxis:()),title:%27New%20Visualization%27,type:line))

same result :-(

**Comment by lmangani** [comment]
Are you able to screenshot a dashboard, for example? This might be an issue with the #visualizer requiring a session or what-not

**Comment by jmreymond** [comment]
You're right. It is OK with a dashboard but broken with visualize.
Fortunately, it is more important that dashboard works fine :-)

**Comment by lmangani** [comment]
Great! Happy Reporting and don't forget to star the project :) closing this issue.
