### ISSUE TITLE
Error in kibi upgrade

### ISSUE THREAD

**Issue by almico** [sirensolutions/sentinl#221]
Using siren-kibi-5.4.3-2-linux-x86_64.zip (file size is 248054951), "kibi upgrade" leads to this error:

```
log   [11:58:16.758] [error][status][Sentinl] [illegal_argument_exception] Mapper for [title] conflicts with existing mapping in other types:
[mapper [title] is used by multiple types. Set update_all_types to true to update [fielddata] across all types.]

```

**Comment by rendel** [comment]
can someone look into this issue if this is blocking the release, e.g., @sergibondarenko. Thanks.

**Comment by almico** [comment]
@fabiocorneti helped me find a workaround and I think he is going to write the fix.

**Comment by fabiocorneti** [comment]
Issue moved to [sirensolutions/sentinl-private #405](https://github.com/sirensolutions/sentinl-private/issues/405) via [**ZenHub**](https://www.zenhub.com/)
