### ISSUE TITLE
Add silence time frame(s) to suppress alerts

### ISSUE THREAD

**Issue by Macbook-63** [sirensolutions/sentinl#224]
As some events do not appear all time with the same frequency (e.g. events customers place orders etc.) it would be of great benefit to define times where alerts don't get triggered.

Feature:
- define 1..n time frames defined by 'start time' / 'end time'
- action: skip concerned check within the defined time frame(s)

Behaviour:
when a check rule is triggered it will be checked if current time is within of one of the defined 'silence time frames'. If that's the case the check is skipped. If it is not the check rule will be excuted.

**Comment by chenryn** [comment]
+1

**Comment by narayanan1993** [comment]
+1

**Comment by lmangani** [comment]
Could you compare this against the existing throttle functionality?

**Comment by Macbook-63** [comment]
Well, throttling is a different feature. Let's stick with the shop example.

If you monitor the amount of placed orders in a shop this may vary during the day and throttling the alert is fine (e.g. you may want to have a look at your system if no more orders coming in because you released a new version. So throttle alerts to 15min,  because this may also happen if no one buys your stuff.

But during the night placing no orders happens quite often because your customers went to bed.
So even throttling to 15min will always trigger an alert/mail. This is the use of the wanted feature 'silence time'. This would switch off checks between 2a.m. and 6a.m. because it doesn't make sense to check for this metric of orders. 

Best, Tom

**Comment by lmangani** [comment]
This should be possible using the ```later``` [text parser](https://bunkat.github.io/later/parsers.html#text) combos - have you tried that already?

**Comment by Macbook-63** [comment]
@lmangani - how would you this? What do I need to do?

**Comment by lmangani** [comment]
@Macbook-63 you need to experiment... for example:
```
every 2 hours except after 20th hour
```
produces this schedule: 
```
Thu 12.10.17 - 18:00
Thu 12.10.17 - 20:00
# notice the break here until
Fri 13.10.17 - 02:00
Fri 13.10.17 - 04:00

```

**Comment by lmangani** [comment]
Here's a codepen you can use to save time: https://codepen.io/antonlydike/full/KgygpA
