### ISSUE TITLE
How many concurrent watchers can sentinl run at same time

### ISSUE THREAD

**Issue by seshu3564** [sirensolutions/sentinl#226]
How many concurrent watchers can sentinl run at same time.

**Comment by sergibondarenko** [comment]
@seshu3564 Sentinl relies on Elasticsearch [search thread pool](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html). By default, it is 1000 concurrent requests (if server hardware is powerful enough), also this value can be configured. Thus theoretically, by default, we can support 1000 watchers running at the same time. Though Sentinl was never tested with this number of watchers.

One more thing, in Sentinl configuration there are hard limits for number watchers and alarms, look the links below. If you need to increase the limits you must specify it in kibana.yml.
https://github.com/sirensolutions/sentinl/blob/master/index.js#L85
https://github.com/sirensolutions/sentinl/blob/master/index.js#L86
We plan to remove these limits in the nearest future.

**Comment by lmangani** [comment]
Added to wiki/FAQ, closing
