### ISSUE TITLE
Noticed hitch -- Version 5.5.0 and 5.6.1

### ISSUE THREAD

**Issue by smoreaud** [sirensolutions/sentinl#227]
Hi, sorry for the previous version (obviously a fail using my keyboard). 
I am a new (aka highly inexperienced) user. I have been looking at the different issues/questions and  thought I should report a few (minor) things, for new users and developers. 
I also have several questions, but I will save them for a different post. 

I installed Sentinl along with a kibana  5.6.1 (I like to live dangerously) as well as kibana 5.5.0 (for troubleshooting). 
So far I have successfully been able to get both alerts and reports with kibana  5.6.1.  (It might interest people checking #206) 
The following behaviours are common to both version. 

- When executing the a watcher "now" (by clicking on the execution arrow rather than waiting on a scheduled trigger), I consistently receive multiple emails (also described in #220).  
- The snapshot resolution parameter doesn't affected the snapshot resolution. Whatever I tried I always get a 1280x900 pixels. Is there a limitation on this parameter?    
- the ".png" extension is doubled in the emailed report name. Appears as report-tag-DD-MM-YYYY-hh-mm-ss.png in my tmp folder, but I received  report-tag-DD-MM-YYYY-hh-mm-ss**.png.png** attached with my email.

All of them are easy enough to reproduce, just click on the arrow and check your emails and reports 
Please let me know if you have any comments or suggestions

**Comment by sergibondarenko** [comment]
>So far I have successfully been able to get both alerts and reports with kibana 5.6.1. (It might interest people checking #206)

The release 5.6 was published. Download a .zip compatible with your Kibana version https://github.com/sirensolutions/sentinl/releases/tag/tag-5.6.2

>When executing a watcher "now" (by clicking on the execution arrow rather than waiting on a scheduled trigger), I consistently receive multiple emails (also described in #220).

It was solved. Check the latest release.

>The snapshot resolution parameter doesn't affected the snapshot resolution. Whatever I tried I always get a 1280x900 pixels. Is there a limitation on this parameter?
>the ".png" extension is doubled in the emailed report name. Appears as report-tag-DD-MM-YYYY-hh-mm-ss.png in my tmp folder, but I received report-tag-DD-MM-YYYY-hh-mm-ss**.png.png** attached with my email.

We know about this. It will be solve it in nearest days.

**Comment by smoreaud** [comment]
Thanks. :-)

**Comment by sergibondarenko** [comment]
@smoreaud solved in [Sentinl 5.5.X](https://github.com/sirensolutions/sentinl/releases/tag/tag-5.5) and [Sentinl 5.6.X](https://github.com/sirensolutions/sentinl/releases/tag/tag-5.6.2). Please download a .zip according to your Kibana version.
