### ISSUE TITLE
Question: Can I specify the snapshot/report name? 

### ISSUE THREAD

**Issue by smoreaud** [sirensolutions/sentinl#228]
Hi, 
Is it possible to specify a name for the report issued? The snapshot is saved as report-tags-date-12hTime.png, I would like to be able to name it something like report-HumanFriendlyTags-date-24hTime.png

Thanks

**Comment by sergibondarenko** [comment]
Now there is no such possibility. It will be added as soon as possible.

**Comment by smoreaud** [comment]
Great. :-)
Thanks for taking the time to answer.

**Comment by sergibondarenko** [comment]
@smoreaud Now, in [Sentinl 5.5.X](https://github.com/sirensolutions/sentinl/releases/tag/tag-5.5) and [Sentinl 5.6.X](https://github.com/sirensolutions/sentinl/releases/tag/tag-5.6.2) you can specify name for the report file. Download .zip according to your Kibana version.
![screenshot from 2017-10-11 09-52-59](https://user-images.githubusercontent.com/5389745/31428131-07167b92-ae6a-11e7-8d48-a388c39402a9.png)

**Comment by fbaligand** [comment]
Nice ! 
Thanks @sergibondarenko !

**Comment by smoreaud** [comment]
Thank you so much! :-)
