### ISSUE TITLE
content of matching messages in alert e-mail body

### ISSUE THREAD

**Issue by Evertvz** [sirensolutions/sentinl#229]
1. Issue Description
Hello. I've just installed sentinl and would like to thank you for the work you put into its development.
An issue I can't seem to solve or find in the documentation is that one of my managers would like to receive the content of the one or multiple messages that match an alert. I noticed the payload variable that can be used for the occurences but can't seem to find the documentation on how to retrieve the content of certain fields of the messages themselves.

Is this a possibility with Sentinl and if yes could someone point me in the right direction please? Thanks.

**Comment by sergibondarenko** [comment]
@Evertvz 
Thank you for the kind words.
Elasticsearch documents that you receive after a watcher execution are objects inside `payload.hits.hits` array. You can parse the array and retrieve any data you want from these documents. 

For example, you want to list all compnies names which you can find in the received docs. Then you can write a small JS script in `Transfrom` tab which parses the docs and puts company names into some new property, `payload.hits.my_companies` in my example.
```
{
  "script": {
    "script": "payload.hits.my_companies=[];for(var i=0;i<payload.hits.hits.length;i++)payload.hits.my_companies.push({name:payload.hits.hits[i]._source.label});"
  }
}
```
Then you create `email html` action under `Actions` tab and render the compnies list using [mustache](https://www.npmjs.com/package/mustache#usage) syntax and HTML:
```
<h1 style="background-color:DodgerBlue;color:white;padding:5px">Companies</h1>
<div style="background-color:Tomato;color:white;padding:5px">
<ul>
{{#payload.hits.my_companies}}
<li>{{name}}</li>
{{/payload.hits.my_companies}}
</ul>
</div>
```
For more details, please refer to our wiki here on GitHub https://github.com/sirensolutions/sentinl/wiki
