### ISSUE TITLE
How to install on version 6.0.0-rc1 [question]

### ISSUE THREAD

**Issue by michaeleino** [sirensolutions/sentinl#235]
Hello there!

Is there a way for version 6.0.0-rc1 ??

**Comment by jccq** [comment]
support for ES 6.x by Siren platform is expected Q2 2018, so realistically
in about 6 months.

We have no hurry r given the large  amounts of issues the 5.x has had since
short ago.

This said Sentinl is open source so contributions are welcome to speed this
part up.

**Comment by sergibondarenko** [comment]
@michaeleino the 6.0.0 release is ready https://github.com/sirensolutions/sentinl/releases/tag/tag-6.0.0
