### ISSUE TITLE
Kibana 5.6.3 + Sentinl 5.6.3 + Search Guard 5.6.3 + Kerberos

### ISSUE THREAD

**Issue by Sergeyemcev** [sirensolutions/sentinl#236]
Hello !
I use ELK + Search Guard with Kerberos authorization. All versions 5.6.3 
I decided to try Sentinl. Added parameters to kibana.yml for Sentinl:

sentinl:
   settings:
     authentication:
       enabled: true
       mode: 'basic' # for now only 'basic' mode exists
       https: true
       admin_username: 'kibanaserver' # user to execute system level operations
       admin_sha: '92861083f4bc8e059207cf4fb2b9971a'
       user_index: 'sentinl_users'
       user_type: 'user'
       verify_certificate: true
       path_to_pem: '------------------------------'
       encryption:
         algorithm: 'aes256'
         key: 'b9726b04608ac48ecb0b6918214ade54'
         iv_length: 16

Change parameters in sq_roles.yml

# For the kibana server
sg_kibana_server:
  cluster:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
      - cluster:admin/xpack/monitoring*
  indices:
    '?kibana':
      '*':
        - INDICES_ALL
    'watcher*':
      '*':
       - indices:data/read/search
       - MANAGE
       - CREATE_INDEX
       - INDEX
       - READ
       - WRITE
       - DELETE

Apply script search guard after this changes.

And this not work (((
In browser i see error:   Sentinl Watchers: Error 502 Bad Gateway: undefined

When i try set searchguard.basicauth.enabled: true  in kibana.yml - Sentinl works fine.   

Please, let me know - Sentinl support kerberos authorization search guard ?

**Comment by jccq** [comment]
Hi Kerberos is exclusively avaialble in the enterprise (paid) version of
Searchguard, do you have one such licence?

if so we can work together with Searchguard and look into tthis as we're
partners with them (withn the context of a Siren stack project).

best

<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-philadelphia-november-2017?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature&utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
Siren
will be atBig Data & Analytics for Pharma Summit (Philadelphia Nov 1-2,
2017)
<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-philadelphia-november-2017?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature&utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by Sergeyemcev** [comment]
Hi, yes.

**Comment by lmangani** [comment]
@Sergeyemcev please use this [link](https://siren.io/contact) to progress this discussion. Closing issue.
