### ISSUE TITLE
Gulp Plugin install fails

### ISSUE THREAD

**Issue by dyioulos** [sirensolutions/sentinl#237]
I'm running Kibana 5.6.3 on Ubuntu 16.04 LTS.  I installed sentinl-v5.6.3.zip-5.6.3.zip successfully (though I don't know if it works with the installed Kibana version).  I tried installing th Gulp Plugin by following these instructions:

git clone https://github.com/sirensolutions/sentinl
cd sentinl && npm install && gulp package --version=5.6.3

At this stage is when I get I get an installation failure:

npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! husky@0.10.2 install: `node ./bin/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the husky@0.10.2 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the husky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
~

The most recent versions of npm and node.js are installed on the system.  The npm-debug.log is attached.

[npm-debug.log](https://github.com/sirensolutions/sentinl/files/1419762/npm-debug.log)

**Comment by lmangani** [comment]
Not sure I understand. If you installed the plugin with the ZIP, why are you trying to run the Gulp scripts?
Installing the plugin via release is all you need, there are no follow up steps required.

**Comment by lmangani** [comment]
Closing, feel free to comment to re-open.
