### ISSUE TITLE
Webhook is not working. Need help

### ISSUE THREAD

**Issue by bharathphatak** [sirensolutions/sentinl#238]
Hi All,

I have configured webhook as action and when the alert is triggered i am getting below error in Kibana.log

**,"tags":["status","error","Sentinl","watcher"],"pid":4511,"message":"Watcher hcok17kb8wp-4l3a8gaob5e-a0wmvcg4rhm: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object."}**

Below is my watcher action configuration

 "ServiceNow Webhook": {
        "throttle_period": "0h0m1s",
        "webhook": {
          "method": "POST",
          "host": "hostname",
          "port": 80,
          "proxy": false,
          "path": ":/api/now/table/incident",
          "body": "{\"short_description\":\"Testing Sentil Webhook\",\"description\":\"Test one more time\",\"caller_id\":\"Test\",\"impact\":\"3\",\"urgency\":\"3\"}",
          "auth": {
            "basic": {
              "username": "test",
              "password": "test"
            }
          },
          "use_https": true,
          "headers": {
            "Content-Type": "application/json",
            "Accept": "application/json"
          },
          "create_alert": false
        }
      }

I am using Kibana 5.6.2.

Please let me know if any changes in config is required.

**Comment by lmangani** [comment]
At first sight, your body is not correctly escaped and will cause all sorts of issues.
```
"body": "{"short_description":"Testing Sentil Webhook","description":"Test one more time","caller_id":"Test","impact":"3","urgency":"3"}",
```
Please stringify the body before attaching it or correctly escape it to avoid double ```"``` sequences

**Comment by bharathphatak** [comment]
Thanks for the reply. I will make the relevant changes and update this thread.
