### ISSUE TITLE
5.5.2  SyntaxError Became TypeError 

### ISSUE THREAD

**Issue by GuillaumeDuf** [sirensolutions/sentinl#241]
Hi guys , I use Sentinl v5.5.2 and Kibana 5.5.2  & ElasticSearch 5.5.2 
I think i found a glitch in Sentinl when we get errors in the `Condition Block` : 
When i write something incorrect i get these errors
```
Sentinl Watcher Editor: Fail to save Sentinl custom settings: SyntaxError: Unexpected token : in JSON at position 17
Sentinl Watcher Editor: Fail to save field: SyntaxError: Unexpected token : in JSON at position 17
```
And this is logic , of course
But , when i rollback to a valid condition configuration  like this one

```
{
  "script": {
    "script": "payload.hits.total > 100"
  }
}
```
I get this error,
```
Sentinl Watcher Editor: Invalid throttle configuration: TypeError: Cannot read property 'hours' of undefined
```
Because throttle and `run every` input have been  reseted to unfilled for unknown reason. And  when i try to refill them manually , they are automaticaly unfilled and i get the same error.
To avoid this , i have to remake a watcher from scratch..
Maybe i'm doing something wrong , or this is a bug ??

Thank you for your support .

**Comment by lmangani** [comment]
Hi @GuillaumeDuf are you using the Wizard and then editing in advanced mode when this happens?

**Comment by sergibondarenko** [comment]
@GuillaumeDuf check this video https://youtu.be/PiUbmzJ1F5U
I have just made it using Kibana 5.5.2 and [the latest Sentinl 5.5.2](https://github.com/sirensolutions/sentinl/releases/tag/tag-5.5 ). Do you create a watcher in the same way?

**Comment by GuillaumeDuf** [comment]
Thank you , i'll check this

**Comment by lmangani** [comment]
@GuillaumeDuf please comment on this issue to re-open discussion if needed. Thanks!
