### ISSUE TITLE
5.5.2 how to delete watcher by curl?

### ISSUE THREAD

**Issue by DanJunAD** [sirensolutions/sentinl#242]
I wrote a wrong action, and now the kibana can't work, and the watcher can't be deleted by curl -XGET 'http://ip:port/_watcher/watch/watcher_id',  so ,how to delete this watcher ?

**Comment by szydan** [comment]
@DanJunAD did you try the DELETE instead of GET?
```
curl -XDELETE 'http://ip:port/_watcher/watch/watcher_id'
```

**Comment by DanJunAD** [comment]
@szydan I have tried,but it don't work.
Here is the error,
![image](https://user-images.githubusercontent.com/22073105/32270785-4a91246a-bec5-11e7-8987-4f55c771fb0e.png)
and I tried 
`curl -XDELETE 'http://10.72.247.248:9200/_watcher/watch/a5xuy1649s-wl11qsc58l-l09bihgkk4'`
but it return like this, it is telling me the watcher is not exit , right?
![image](https://user-images.githubusercontent.com/22073105/32270854-7ad239d4-bec5-11e7-8ce5-faea055d655e.png)

**Comment by lmangani** [comment]
I think you *might* have malformed this specific ID with the previous attempts. Could you create with a freshly generated watcher from the UI?

**Comment by DanJunAD** [comment]
@lmangani   Kibana don't work because of the error, so I can't  see the UI now，and can't delete or create any watcher from the UI.

**Comment by lmangani** [comment]
You might want to drop the ```.watcher``` index in ES, and start over. SENTINL will re-create on startup.

**Comment by lmangani** [comment]
@DanJunAD also note, ```_watcher``` might be the xpack watcher index unless you changed the settings.....

**Comment by DanJunAD** [comment]
@lmangani I  delete all watcher index in ES, then the problem was solved, and I lose all of my watchers at the same time,it's sad 😭. Anyway thanks a lot for your help~~🌹

**Comment by lmangani** [comment]
Well.. you were playing with DELETES, danger is the name of the game :P I'm sorry this happened, keep in mind the SENTINL index is quite small and can be easily dumped/restored in the future, or you can add this to a wishlist issue.

Thanks!
