### ISSUE TITLE
any backport on old version?

### ISSUE THREAD

**Issue by cyberdak** [sirensolutions/sentinl#246]
i am use ELK on 5.4.2.if i need a new feature on new version sentinl which adapter on new kibana,i must update all my ELK system. This is unacceptable cost on a plugin.

So, any backport plan on old version?

**Comment by lmangani** [comment]
@cyberdak All 5.x should have the same features eventually, but won't be backported to 4.x. 
What feature are you even referring to? What is an "old version"?

**Comment by cyberdak** [comment]
like this.
```
sentinl5.6.x

add report image resolution
add a possibility to specify a name for the report image
hide password when typing it in report action
autodetect Elasticsearch connection settings based on the settings in kibana.yml
fix ace editor error in the watcher editor
add PDF option to the report action
```

from readme , i know 5.6.x is work with kibana 5.6.x.

anyway, can i use sentinl 5.6.x with kibana 5.4.2?
