### ISSUE TITLE
Sentinl reports don't snapshot the correct page

### ISSUE THREAD

**Issue by JMNDev** [sirensolutions/sentinl#247]
Hi

I'm using elasticsearch + kibana 5.5.2 (with searchguard), i have installed sentinl on kibana and everything seems to work fine except the reports snapshot

Description of the issue:

I create a reporter and set the action (report action) for a link of a dashboard for example "http://127.0.0.1:5601/app/kibana#/dashboard/CC-Test-Dashboard" and when the report is generated i expect to receive a snapshot of the dashboard but i only get a snapshot of main kibana page (discover tab)

next is my sentinl configuration and example of reporter configuration, can you help me? 

Thanks

Sentinl configuration at kibana.conf

```
sentinl:
  settings:
    email:
      active: true
      host: smtp.hdi.tvcabo
      ssl: false
      timeout: 10000  # mail server connection timeout
    report:
      active: true
      tmp_path: /tmp/
      search_guard: true
```

Reporter example of configuration (some fields are omitted and the dashboard url is just an example not the real link used)

```
{
  "_index": "watcher",
  "_type": "sentinl-watcher",
  "_id": "o5gtoe69zae-kz0rlju70gq-4s3jdrebbj",
  "_version": 5,
  "found": true,
  "_source": {
    "title": "reporter_title",
    "disable": false,
    "report": true,
    "trigger": {
      "schedule": {
        "later": "every 15 mins"
      }
    },
    "actions": {
      "report_admin": {
        "throttle_period": "0h15m0s",
        "report": {
          "to": "X",
          "from": "sentinl@nos.pt",
          "subject": "Sentinl Report",
          "priority": "high",
          "body": "Sample Sentinl Screenshot Report",
          "save": true,
          "snapshot": {
            "res": "1280x900",
            "url": "http://127.0.0.1:5601/app/kibana#/dashboard/CC-Dashboard",
            "path": "/tmp/",
            "params": {
              "delay": 15000,
              "crop": false,
              "username": "kib",
              "password": "kib"
            }
          }
        }
      }
    },
    "transform": {},
    "input": {},
    "condition": {}
  }
}

```

**Comment by lmangani** [comment]
This is most likely a redirection by the server or SG - which as far as I'm aware is only working with the Siren stack. Generally speaking, this SENTINL action does nothing more than point at the URL and snapshot when the ```delay``` clocks. 

Are you able to follow that link from an anonymous browser session or curl?

**Comment by JMNDev** [comment]
Firstly thank you for your fast response.

I have thinked on that, but i tested in a anonymous browser session and i got the correct page.

Could be because of the report configurations, the search_guard and simple_authentication field?


```
   report:
      active: true
      tmp_path: /tmp/
      search_guard: true
      simple_authentication: true

```
 Thank you

**Comment by sergibondarenko** [comment]
@JMNDev 
First, get the latest Sentinl 5.5.2.
Second, you should have the following config in kibana.yml
```
  report:
      search_guard: true
      simple_authentication: true
```
Third, you have to put username and password to access a page, here in the report action
![screenshot from 2017-11-17 12-40-42](https://user-images.githubusercontent.com/5389745/32945681-a541df2c-cb94-11e7-94b4-d314168c1836.png)

Please try and let me know the result.

**Comment by JMNDev** [comment]
Thank you for your support @sergibondarenko 

I tried like you said.

    report:
      active: true
      tmp_path: /tmp/
      search_guard: true
      simple_authentication: true


And i configured the following report 
![error_config](https://user-images.githubusercontent.com/31067292/32949194-dcaabd30-cb99-11e7-90f4-d95c126a3829.png)

But i got the following result as report ( the login page) :   
![error_result](https://user-images.githubusercontent.com/31067292/32949217-efa7bc6c-cb99-11e7-8f2b-3115640f3d07.png)

Thanks

**Comment by sergibondarenko** [comment]
@JMNDev when did you download and install Sentinl last time? If before 2017-10-16, please download again and install it. Some fixes have been done since then. Here is a link to your version https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v5.5.2.zip
Let me know.

**Comment by JMNDev** [comment]
I have installed on 2017-11-02 so I think I have the last version or there's new releases ? 
Another question, I have tested also on another instance of kibana but with 5.5.3 version, exists any specific version of sentinl for 5.5.3 version of kibana ?

Thank you

**Comment by sergibondarenko** [comment]
@JMNDev 
[The list of available Sentinl versions](https://github.com/sirensolutions/sentinl/releases). Look for .zip archives.

Disable simple authentication: `simple_authentication: false`.  Let me know.

**Comment by JMNDev** [comment]
Thanks for your attention @sergibondarenko.

I have teste with both configurations:

"simple_authentication: true" - the result of the dashboard link report was a screenshot of kibana login page

"simple_authentication: false" - the result of the dashboard link report was a screenshot of kibana discovery tab

**Comment by JMNDev** [comment]
There s any Reporting endpoint that needs to be used to generate the reports, or the url needs to have some specificity to get to the correct place ?

**Comment by sergibondarenko** [comment]
Did you try the following?
```
  search_guard: true
  simple_authentication: false
```

**Comment by JMNDev** [comment]
Yes that's my actual configuration
"
sentinl:
  settings:
    email:
      active: true
      host: smtp.xxxxxxx
      ssl: false
      timeout: 10000  # mail server connection timeout
    report:
      active: true
      tmp_path: /tmp/
      search_guard: true
      simple_authentication: false
"

With this configuration i got the following page 
![image](https://user-images.githubusercontent.com/31067292/33079937-c1b909fe-cece-11e7-8bbb-63b3caa76ff9.png)

**Comment by sergibondarenko** [comment]
I think you have a wrong URL in the Sentinl Report action from. You should paste a URL of a dashboard there. You can get it from the Kibana **Share** menu https://www.elastic.co/guide/en/kibana/5.5/sharing-dashboards.html

**Comment by JMNDev** [comment]
@sergibondarenko,  I have been testing and you are partial correct, I wasn't using the correct url because the plugin only works with shorten urls.
But thanks for the tip

**Comment by sergibondarenko** [comment]
@JMNDev do everything work for you now?

**Comment by JMNDev** [comment]
Yes this was the only limitation i have. now its solved, everything seams to be working just fine.

Once again thank you for the support @sergibondarenko and @lmangani

**Comment by ankitachow** [comment]
Hi ,
I'm using Kibana 5.4 version. I also have SearchGaurd. I don't see the report snapshot in the Sentinl reports tab correctly. Sometimes I see no report generated whereas sometimes its the SearchGaurd/Kibana login page. I'm using the url Share snapshot URL from Kibana dashboard. I dont have smtp. So, I just want to see the Dashboard snapshot at certain interval created as a report in the Reports tab..

Below is my Kibana yml file.

sentinl:
  es:
    host: x.x.x.x
    port: 9200
    timefield: '@timestamp'
    default_index: sar-schema-1
  settings:
    report:
      active: true
      tmp_path: /tmp/
      search_guard: true
      simple_authentication: true

Sentinl Raw settings:

{
  "_index": "sar-schema-1",
  "_type": "sentinl-watcher",
  "_id": "nsr36bkdkce-1r96c0nbycn-pq9h9fxikwc",
  "_version": 5,
  "found": true,
  "_source": {
    "title": "reporter_title",
    "disable": false,
    "report": true,
    "trigger": {
      "schedule": {
        "later": "every 1 mins"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [],
          "body": {}
        }
      }
    },
    "condition": {    },
    "actions": {
      "report_admin": {
        "throttle_period": "0h15m0s",
        "report": {
          "subject": "Sentinl Report",
          "priority": "high",
          "body": "Sample Sentinl Screenshot Report",
          "save": true,
          "snapshot": {
            "res": "1280x900",
            "url": "http://x.x.x.x:5601/app/kibana#/dashboard/",
            "path": "/tmp/",
            "params": {
              "delay": 5000,
              "crop": false,
              "username": "elastic",
              "password": "changeme"
            }
          }
        }
      }
    }
  }
}

**Comment by lmangani** [comment]
@JMNDev try to increase the `"delay` parameter to allow the page to fully load in PhantomJS

**Comment by JMNDev** [comment]
Thank you for the tip @lmangani, but i allready  tried that, but seems after a big "delay" the page crashes and i got a screenshot of a page with errors.
Seems there's some hardcoded max delay. Is that possible ? you know how to change that max value ?

Thank you once again

**Comment by JMNDev** [comment]
@lmangani I have tried to change de delay in the report action to a higher value but i allways get a page with error.
I send you as attachment  the logs you requested and a screenshot of the screenshot i got.

Thank you

![image](https://user-images.githubusercontent.com/31067292/37965032-90945bb2-31bb-11e8-8214-bbc9c4a72f06.png)

[logs_sentinl.log](https://github.com/sirensolutions/sentinl/files/1851758/logs_sentinl.log)

**Comment by ankitachow** [comment]
I was able to get the snapshot of the report under Reports as per the scheduled time. But how to get a pdf of the same?

**Comment by lmangani** [comment]
@ankitachow this option is very sketchy and will be available once we fully switch away from PhantomJS (which is already done in development and soon to be released)

**Comment by ankitachow** [comment]
@lmangani Thanks for your reply.
Now the pdf download option is not available?

**Comment by lmangani** [comment]
You need to use the `master` version with `pupeteer`
```
 report:
      active: true
      executable_path: '/usr/bin/chromium' # path to Chrome v59+ or Chromium v59+
      timeout: 5000
      # authentication:
      #   enabled: true
      #   mode:
      #     searchguard: false
      #     xpack: false
      #     basic: false
      #     custom: true
      #   custom:
      #     username_input_selector: '#username'
      #     password_input_selector: '#password'
      #     login_btn_selector: '#login-btn'
      # file:
      #   pdf:
      #     format: 'A4'
      #     landscape: true
      #   screenshot:
      #     width: 1280
      #     height: 900
```
