### ISSUE TITLE
Allow Scheduling Watchers within 'General' tab

### ISSUE THREAD

**Issue by sethyes** [sirensolutions/sentinl#250]
1. Issue Description:
 The only way to currently schedule a watcher to execute at a specific time is to enable the 'raw' JSON, and put your trigger syntax into the 'later' section. This would be sufficient if it didn't get overwritten the next time someone modifies that alert. However if I modify the alert (e.g. modify the input), the interval is removed and no reporting interval exists. 

2. Reproducing the Issue step-by-step
 Enable 'raw' section of a watcher, place a time, save the watcher. At this point you can see the interval specified in the 'later' section. Now go modify the watcher elsewhere, for instance by modifying input parameters. 

3. Expected Results vs. Actual Results
 Expected: The time set in the raw 'later' section would show up under the 'general' tab. 
 Actual: The 'Run Every' section under the 'general' tab is blank and the watcher never executes.

4. Additional Details
Ideally we could just schedule alerts/reports directly from the General tab, rather than having to enable the raw section and not touch the alert thereafter.

**Comment by sergibondarenko** [comment]
@sethyes I've put your issue in the queue. I'll ping you when it is fixed.

**Comment by sergibondarenko** [comment]
@sethyes this was fixed in the following versions: v5.5.X and v5.6.X
Now you can insert human schedule directly in the General tab. Also you can see when it is executed. Look this demo video https://www.youtube.com/watch?v=PJNxclZSwk4&t=1s&list=PLvxLmGsmqdZdUm6kNNfjL2pD-UhNtfw6b&index=9

**Comment by sethyes** [comment]
Thanks Sergii!

*Best Regards,*

*Seth Smith*
*Seth@SethSmith.net*
*406.451.3462*

On Thu, Dec 14, 2017 at 7:04 AM, Sergii Bondarenko <notifications@github.com
