### ISSUE TITLE
Failed to check if core index exists: Error: Request Timeout after 30000ms

### ISSUE THREAD

**Issue by eyalzek** [sirensolutions/sentinl#251]
Running kibana & sentinl version 5.3.3

The initial request to ES to fetch `watcher`, `watcher_alarms` indices times out. Thus going to the `Sentinl` tab in kibana displays none of the configured watchers. These indices exist on the es cluster, and when making a `curl` request to get them (e.g `curl localhost:9200/watcher`), can be fetched and indeed contain our watcher configuration.

We have 2 kibana docker images running the same version (5.3.3), the difference is between the snapshot versions of sentinl. On the older image:

```
$ ./bin/kibana-plugin list
sentinl@5.4.0-SNAPSHOT
```

and on the newer one:

```
$ ./bin/kibana-plugin list
sentinl@5.4.3-SNAPSHOT
```

In both cases sentinl is installed using:

`bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.4/sentinl-v5.3.3.zip`

with `sentinl@5.4.0-SNAPSHOT` loading the watchers and alarms on startup succeeds:

```
{"type":"log","@timestamp":"2017-11-14T13:37:10Z","tags":["status","info","Sentinl"],"pid":5,"message":"Sentinl Initializing"}
{"type":"log","@timestamp":"2017-11-14T13:37:11Z","tags":["status","info","Sentinl"],"pid":5,"message":"Checking watcher index ..."}
{"type":"log","@timestamp":"2017-11-14T13:37:11Z","tags":["status","info","Sentinl"],"pid":5,"message":"Checking watcher_alarms index ..."}
{"type":"log","@timestamp":"2017-11-14T13:37:13Z","tags":["status","debug","Sentinl"],"pid":5,"message":"Index watcher exists!"}
{"type":"log","@timestamp":"2017-11-14T13:37:13Z","tags":["status","debug","Sentinl"],"pid":5,"message":"Index watcher_alarms exists!"}
{"type":"log","@timestamp":"2017-11-14T13:38:51Z","tags":["status","debug","Sentinl","scheduler"],"pid":5,"message":"Reloading Watchers..."}
```

and with `sentinl@5.4.3-SNAPSHOT` it fails as described above. 

I would happily provide additional information to help debug this. In the meantime, is there a way to install snapshot versions of the plugin or are they overridden every time a new one releases?

**Comment by sergibondarenko** [comment]
@eyalzek several core things were changed. Thus, the best option is to create watchers again using UI. 

But, if you can't, let's try to fix it. Give me results of `curl -XGET localhost:9200/watcher/_mapping?pretty`

**Comment by sergibondarenko** [comment]
@eyalzek 
Is it a fresh install or you have watchers already from some old Sentinl version?

Everything should work fine if it is a fresh install. Look, I've just tried it and made a video for you, Kibana and Sentinl-5.6.3 https://youtu.be/Jfk-CGP0NfU

If you have watchers from old Sentinl then there are some changes. Default document type name changed. Now it is `sentinl-watcher`, not `watcher`. Check your watchers document type using this command `curl -XGET localhost:9200/watcher/_mapping?pretty`. 

To fix it you have several options.
1. Define watcher doc type in kibana.yml, like this
```
sentinl:
  es: 
    type: watcher
```
Here you can find all available config values https://github.com/sirensolutions/sentinl/wiki/SENTINL-Config-Example

2. Create all watchers again using UI
3. Reindex existing watchers, for example, using [elasticdump](https://www.npmjs.com/package/elasticdump). Make sure that all watcher documents have `sentinl-watcher` as type.

**Comment by eyalzek** [comment]
Yeah it appears that all the old ones are under `watch` whereas a test one I created just now was correctly stored under `sentinl-watcher` ... Is this documented somewhere? I would assume more people experience this issue and not just me :D

**Comment by lmangani** [comment]
@eyalzek the preference is still expressed by the SENTINL config, we just changed the default for new setups. If you remove and reinstall the plugin, previous configuration should always be reviewed against the defaults for consistency.

**Comment by eyalzek** [comment]
The default has been changed between patch versions, so if I build rebuild my kibana every day with the exact same sentinl download URL (https://github.com/sirensolutions/sentinl/releases/download/tag-5.4/sentinl-v5.3.3.zip) and I can face this situation, I guess this is not ideal. The indices have been created by the "same" version of sentinl, I wouldn't expect them to be unsupported all of a sudden. But I wasn't aware of the `sentinl.type` configuration, this might be the fastest and easiest fix for me.

**Comment by eyalzek** [comment]
I've done that and now my watchers load, when I try to run any of them I get the following message:
`Sentinl Watchers: Condition 'script' evaluated to false: new_watcher_d6gzqlg4t`

the action eventually fires as expected, but is there actually a problem there?

**Comment by sergibondarenko** [comment]
@eyalzek It informs you that JS code inside `script` was executed and there was no result. Check if the code does what you want it to do with the initial payload.

**Comment by eyalzek** [comment]
It's the default (empty):
```
{
  "script": {
    "script": ""
  }
}
```

but yeah I just assumed it's an error message because of the color of it....

**Comment by sergibondarenko** [comment]
@eyalzek I think the color should be changed to yellow

**Comment by lmangani** [comment]
@eyalzek is this confirmed resolved? Please feel free to comment to re-open this issue.

**Comment by eyalzek** [comment]
Yes, it is resolved. As I mentioned earlier, I see this as an issue of backward incompatible changes without any hint whatsoever. If an application with version X, downloaded from url Y works, then it should always work for the same use case.
