### ISSUE TITLE
watcher is giving a 500 error

### ISSUE THREAD

**Issue by graphicsxp** [sirensolutions/sentinl#253]
1. Issue Description

I have created my first watcher in sentinl but whenever I try to execute it I get a 500 error. When checking the logs, the error is: 

`[parsing_exception] no [query] registered for [filtered], with { line=1 & col=22 } :: {\"path\":\"//_search\",\"query\":{},\"body\":\"{\\\"query\\\":{\\\"filtered\\\":{\\\"query\\\":{\\\"match\\\":{\\\"Properties.Environment\\\":{\\\"query\\\":\\\"Prod\\\",\\\"type\\\":\\\"phrase\\\"}}}}}}\",\"statusCode\":400,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"parsing_exception\\\",\\\"reason\\\":\\\"no [query] registered for [filtered]\\\",\\\"line\\\":1,\\\"col\\\":22}],\\\"type\\\":\\\"parsing_exception\\\",\\\"reason\\\":\\\"no [query] registered for [filtered]\\\",\\\"line\\\":1,\\\"col\\\":22},\\\"status\\\":400}\"}\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:295:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:254:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n    at IncomingMessage.bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)`

The watcher RAW is as followed. Could someone point me in the right direction because I really can't see what I'm doing wrong here.

4. Additional Details

```

{
  "_index": "watcher",
  "_type": "sentinl-watcher",
  "_id": "7cs3nm28w76-oa4dpnes4jo-xt31xx7nyb",
  "_version": 7,
  "found": true,
  "_source": {
    "title": "watcher_title",
    "disable": true,
    "report": false,
    "trigger": {
      "schedule": {
        "later": "every 5 mins"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [],
          "body": {
            "query": {
              "filtered": {
                "query": {
                  "match": {
                    "Properties.Environment": {
                      "query": "Prod",
                      "type": "phrase"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 0"
      }
    },
    "actions": {
      "email_admin": {
        "throttle_period": "0h15m0s",
        "email": {
          "to": "graphicsxp@gmail.com",
          "from": "sentinl@localhost",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      }
    },
    "transform": {}
  }
}

```

**Comment by sergibondarenko** [comment]
@graphicsxp The [filtered query is deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-filtered-query.html), use [bool](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-bool-query.html) instead.

**Comment by graphicsxp** [comment]
Indeed. I was able to fix this by changing filtered with filter and also by removing the query property inside the filtered property.

thanks
