### ISSUE TITLE
 Sentinl Watchers: Error 500 Internal Server Error: An internal server error occurred

### ISSUE THREAD

**Issue by vedicumesh** [sirensolutions/sentinl#256]
kibana version 5+
elasticsearch version 5+
recently i configured sentinl and created alert when i try to run that alert i am getting error like
**Sentinl Watchers: Error 500 Internal Server Error: An internal server error occurred** .Please provide an example of configuration setup for generating alert mail notification based on condition like x>100.

**Comment by lmangani** [comment]
I'm sorry but this is completely unclear. Please take time to read the Wiki documentation, and if you want, feel free to open a new issue with proper description, logs and information. Thanks.
