### ISSUE TITLE
ES 6.x: Rejecting mapping update to [watcher] as the final mapping would have more than 1 type

### ISSUE THREAD

**Issue by nigellh** [sirensolutions/sentinl#257]
1. Issue Description

Receiving from Kibana 

elks_kibana_1         | {"type":"log","@timestamp":"2017-11-24T11:01:30Z","tags":["status","error","Sentinl"],"pid":1,"message":"[illegal_argument_exception] Rejecting mapping update to [watcher] as the final mapping would have more than 1 type: [sentinl-script, sentinl-watcher]"}

2. Reproducing the Issue step-by-step

Apologies, extremely new to ELK Stack, Sentinl, Docker, Docker-Compose, etc. Been asked to try and prototype a monitoring system and still in the basic configuration stage.

Running Ubuntu 16.04
ELK Stack 6.0.0
Sentinl 6.0.0
Latest versions of Docker and Docker-Compose

Not sure if this is the right approach.

Creating a separate container for each of Elasticsearch, Logstash and Kibana using the main ELK definitions.

As we don't want the ELK X-Pack I uninstall it from the images and replace the base .yml files removing any reference to X-Pack.

(I understand that in theory I could just build them without X-Pack and will probably do so at sometime, but just adds to an already large learning curve! :-) )

Using a very basic configuration in a docker-compose.yml file the three containers come up and are happily talking to each other and I can access a pretty much empty Kibana screen.

I add Sentinl into the Dockerfile for creating the Kibana container and it builds fine.

Now when I start with Docker-compose I get the error at the top.

It looks, perhaps, as if the default Sentinl configuration is causing this, but not sure where to look or what to try.

3. Expected Results vs. Actual Results

No error vs Error!

4. Additional Details

```
OK, here goes

Dockerfile for Elasticsearch
-------------------------------------------
FROM docker.elastic.co/elasticsearch/elasticsearch:6.0.0
# This is the Dockerfile for creating the Elasticsearch Container for the ELKS Monitor

# Copy the .yml file with X-Pack removed
ADD elasticsearch.yml ./config/elasticsearch.yml

# Uninstall X-Pack
RUN ./bin/elasticsearch-plugin remove x-pack --purge
-------------------------------------------
elasticsearch.yml file
-------------------------------------------
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
-------------------------------------------
-------------------------------------------
Dockerfile for Logstash
-------------------------------------------
FROM docker.elastic.co/logstash/logstash:6.0.0
# This is the Dockerfile for creating the Logstash Container for the ELKS Monitor

# Copy the .yml file with X-Pack removed
ADD logstash.yml ./config/logstash.yml

# Uninstall X-Pack
RUN ./bin/logstash-plugin remove x-pack
-------------------------------------------
logstash.yml
-------------------------------------------
http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
-------------------------------------------
-------------------------------------------
Dockerfile for Kibana
-------------------------------------------
FROM docker.elastic.co/kibana/kibana:6.0.0
# This is the Dockerfile for creating the Kibana Container for the Desk ELKS Monitor
#
# For this to work it requires the Sentinl Plug-in to be installed
# See https://github.com/sirensolutions/sentinl or https://github.com/sirensolutions/sentinl/wiki/SENTINL-Installation
#

ADD kibana.yml ./config/kibana.yml

# Uninstall X-Pack
RUN ./bin/kibana-plugin remove x-pack

# Install potentially missing libraries that Sentinl requires
USER root
RUN yum install -y fontconfig freetype

# Install Filebeats so the example Kibana Dashboards can be deployed
RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.0.0-x86_64.rpm
RUN rpm -vi filebeat-6.0.0-x86_64.rpm

# Install Sentinl
USER kibana
RUN ./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.0.0/sentinl-v6.0.0.zip
-------------------------------------------
kibana.yml
-------------------------------------------
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0.0.0.0"
elasticsearch.url: http://elasticsearch:9200
elasticsearch.username: elastic
elasticsearch.password: changeme
-------------------------------------------
-------------------------------------------
docker-compose.yml file
-------------------------------------------
# docker-compose.yml file for starting the ELKS Monitoring System

version: '3.4'
services:

# Elasticsearch configuration
  elks_elasticsearch:
    build:
      context: ./elks_elasticsearch
    image: elks_elasticsearch:6.0.0
    ports: 
      - 9200:9200
      - 9300:9300
    networks: 
      - elks_nw
    volumes:
      - /data/elks/elks_data/elks_e_data:/usr/share/elasticsearch/data

# Logstash configuration
  elks_logstash:
    build:
      context: ./elks_logstash
    image: elks_logstash:6.0.0
#   There appears to be a bug in environment so writing them this way
    environment:
      - ELASTICSEARCH_URL=http://elks_elasticsearch:9200
    ports: 
      - 5000:5000
      - 5001:5001
    networks: 
      - elks_nw
    volumes:
      - /data/elks/elks_data/elks_l_data:/usr/share/logstash/data
    depends_on:
      - elks_elasticsearch

# Kibana configuration
  elks_kibana:
    build:
      context: ./elks_kibana
    image: elks_kibana:6.0.0
#   There appears to be a bug in environment so writing them this way
    environment:
      - ELASTICSEARCH_URL=http://elks_elasticsearch:9200
    ports: 
      - 5601:5601
    networks: 
      - elks_nw
    volumes:
      - /data/elks/elks_data/elks_k_data:/usr/share/kibana/data
    depends_on:
      - elks_elasticsearch

networks: 
  elks_nw:
    driver: bridge  
-------------------------------------------
Hopefully as you can see a very basic setup. Hope it is nice and simple.
```

**Comment by lmangani** [comment]
Hi @nigellh 
This is due to a breaking change in Elasticsearch 6.x where Mapping can only allow for one type.
SENTINL support for 6.x is Development only at this stage. If you need to experiment with the current codebase, you might have to do so using 5.x until our development catches up with this issue.

See here: https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html

**Comment by nigellh** [comment]
I have done a shed load of internet searching and it doesn't bringing up anything obvious

**Comment by nigellh** [comment]
Hi @lmangani Wow quick reply and thank you! I will do

**Comment by TigerKid001** [comment]
+1

**Comment by pgnaleen** [comment]
please give us work around for this problem.

**Comment by EricFlis** [comment]
We found a solution which will work until the Sentinl code catches up with Elasticsearch changes. Unfortunately it requires a minor manual modification to the input code when you go to set a watcher. It involves removing the line which defines the index, Sentinl still seems to know where to pull the data from without this reference. Code sample below (with line in bold text that is changed:

```
{
  "search": {
    "request": {
      **"index": [],**
      "body": {
        "version": true,
        "size": 500,
        "sort": [
          {
            "postdate": {
              "order": "desc",
              "unmapped_type": "boolean"
            }
          }
        ],
        "_source": {
          "excludes": []
        },
        "aggs": {
          "2": {
            "date_histogram": {
              "field": "postdate",
              "interval": "30s",
              "time_zone": "Australia/Sydney",
              "min_doc_count": 1
            }
          }
        },
        "stored_fields": [
          "*"
        ],
        "script_fields": {},
        "docvalue_fields": [
          "postdate"
        ],
        "query": {
          "bool": {
            "must": [
              {
                "query_string": {
                  "query": "\"australia\"",
                  "analyze_wildcard": true,
                  "default_field": "*"
                }
              },
              {
                "match_phrase": {
                  "entity": {
                    "query": "Cyber Security"
                  }
                }
              },
              {
                "range": {
                  "postdate": {
                    "gte": 1513053875621,
                    "lte": 1513054775621,
                    "format": "epoch_millis"
                  }
                }
              },
              {
                "range": {
                  "postdate": {
                    "from": "now-1h"
                  }
                }
              }
            ],
            "filter": [],
            "should": [],
            "must_not": []
          }
        },
        "highlight": {
          "pre_tags": [
            "@kibana-highlighted-field@"
          ],
          "post_tags": [
            "@/kibana-highlighted-field@"
          ],
          "fields": {
            "*": {}
          },
          "fragment_size": 2147483647
        }
      }
    }
  }
}
```

**Comment by Izayuh** [comment]
Is the only work around change removing the index? Or what other changes should I be looking for within this sample code?

**Comment by EricFlis** [comment]
Just removing the index name,that is all.

**Comment by Izayuh** [comment]
I get the same error now when I run the watcher. "Rejecting mapping update to [watcher_alarms-2017.12.15] as the final mapping would have more than 1 type: [n24dd03ugfh-408whtx2lcc-cg7z92hsfzl_Slack message, Slack message]

**Comment by EricFlis** [comment]
See my other open issue here:

https://github.com/sirensolutions/sentinl/issues/274

**Comment by gentunian** [comment]
@EricFlis this won't work. Seems that the problem is not with the index you defined but with the `watcher` index. At least, that what the error says:

`Rejecting mapping update to [watcher] as the final mapping would have more than 1 type: [sentinl-script, sentinl-watcher]`

What I understood of that error message is that `watcher` index can't have both: `sentinl-script` and `sentinl-watcher` types.

**Comment by lmangani** [comment]
We're working on smoothing out the edges but the plans for 6.x are bigger than just being compatible. We do not have an ETA yet but happy to form a group of early testers to expedite the work if anyone is willing.

This specific blocker is related to the [saved objects](https://github.com/sirensolutions/sentinl/tree/branch-6.0/server/lib/saved_objects) which used to share the same index as types. The only way out is to have a dedicated index for each, or a shared format between them storing sub-objects. @sergibondarenko what is your preference here to get completely rid of types in 6.x?

**Comment by EricFlis** [comment]
Hi Lorenzo,

Removing the index name as I showed did make it work, not sure how or why but I was then able to generate alerts which included the payload.

Where we are having the issue now is trying to send that alert via webhook. It does not include the payload as it does for on-screen alerts in KiIbana.

**Comment by lmangani** [comment]
@EricFlis could you send a PR with your changes? I'm not sure I understand what you did, but it might help compare to what we're preparing. As of your other question, could you please open a separate issue to avoid confusion?

**Comment by ij3net** [comment]
@lmangani I had trying change it to be compatible with elastic 6.2.1 and get it working with save payload from multiple watcher. 
[My changes](https://github.com/ij3net/sentinl/commit/0037120a78b933925c4f4db7e2a3b4867fcf9b06)
I will be very grateful if you tell me if I'm on the right way.

**Comment by gentunian** [comment]
Maybe setting the same type in `es` settings make it work? did try, I can't try now:

```
  es:
    host: localhost
    port: 9200
    timefield: '@timestamp'
    default_index: watcher
    type: sentinl-watcher
    alarm_index: watcher_alarms
    alarm_type: sentinl-alarm
    script_type: sentinl-script
```

**Comment by lmangani** [comment]
@ij3net sure on the right path but I would avoid hardcoding any values - its best to attach to a SENTINL variable so this can be controlled.- This said, using different indices rather than shared indices with different types is ultimately the viable solution. As of @gentunian suggestion setting all types to the same might get rid of current errors, but would have side effects so I'm still for the above solution. We're also working from our side, so this is good and useful discussion! Thanks guys!

**Comment by ij3net** [comment]
@lmangani  @gentunian sorry I'm newbie in nodejs :) and I understand that hardcode is not correct way. But as I understand in elastic 6.x on the way to remove `type` entity at all. Default temporary value of type for any indices is '_doc'.  So look like right way do not using type at all. Unfortunately as example 
`  client.index({
    index: indexName,
    //type: '_doc',
    body: indexBody
`
not working. Or I don't understand something or nodejs elasticsearch client still not ready for work without `type:`

**Comment by lmangani** [comment]
@ij3net you're doing great! I think this might have to do with using the `latest` version of the elasticsearch client which is not necessarily backwards compatible - also it seems you are still passing a commented item to the query above - try just killing it for a spin and make sure each "unique type" now corresponds to a unique index - or you will have collisions.

**Comment by Roronoa-Zoro** [comment]
I'm running apm server:6.2.3, elasticsearch:6.2.3,kibana:6.2.3, while I get"Rejecting mapping update to [apm-6.2.3-2019.07.01] as the final mapping would have more than 1 type:", do to resolve this?

**Comment by budao666** [comment]
I try delete it，recreate is resovle！
