### ISSUE TITLE
v.5.5.3

### ISSUE THREAD

**Issue by chopchop505** [sirensolutions/sentinl#260]
1. Issue Description

There is no version for v.5.5.3.

2. Reproducing the Issue step-by-step

3. Expected Results vs. Actual Results

4. Additional Details

**Comment by lmangani** [comment]
Hi @chopchop505 as a workaround you can download [5.5.2](https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v5.5.2.zip), unpack, modify the ```package.json``` version number to ```5.5.3```, and repack for installation. You can also use the following format to support multiple 5.5.x versions:
```
"version": "kibana",
  "kibanas": [
    "5.5.1",
    "5.5.2",
    "5.5.3"
  ]
```

**Comment by sergibondarenko** [comment]
Fixed, you can download .zip which attached to the release https://github.com/sirensolutions/sentinl/releases/tag/tag-5.5
