### ISSUE TITLE
Feature Request: Custom Report Filename

### ISSUE THREAD

**Issue by goveebee** [sirensolutions/sentinl#261]
Hi!

I'm trying to name my reports sent by Sentinl by e-mail. It looks like it's possible via the path field in actions, but I get no difference if I fill it in or not. The file generated by Sentinl is named cidmy-report and that's not looking good. How do I use the path-field to achive this?

**Comment by lmangani** [comment]
Hi @goveebee please attach an example of your current configuration for advice. The path is only used to determine the location where to save the data, not involved in naming of the file.

**Comment by goveebee** [comment]
This is what I've got now. It's running well, but it would be nice to be able to change the file name of the mailed file. Is it also possible to have the leftside menu collapsed in the reports?

`{
  "_index": "watcher",
  "_type": "sentinl-watcher",
  "_id": "iihlkjpeh1n-zhb0jhrcaqf-aw5svaa0t7e",
  "_version": 10,
  "found": true,
  "_source": {
    "title": "Daglig snapshot",
    "disable": false,
    "report": true,
    "trigger": {
      "schedule": {
        "later": "at 10:00 am"
      }
    },
    "actions": {
      "Daglid snapshot": {
        "throttle_period": "0h0m0s",
        "report": {
          "to": "xx.xx@xx.se",
          "from": `"xx@xx.se",`
          "subject": "Daglig rapport Stockholms Stad",
          "priority": "high",
          "body": "Se rapporten",
          "save": false,
          "snapshot": {
            "res": "1920x1200",
            "url": "http://xx.xx.xx:1337/app/kibana#/dashboard/AV8vFLDLlBN0bFDQEkSN?_g=(refreshInterval:('$$hashKey':'object:1829',display:'5+seconds',pause:!t,section:1,value:5000),time:(from:now%2Fd,mode:quick,to:now%2Fd))&_a=(description:'',filters:!(),options:(darkTheme:!f),panels:!((col:7,id:CPU-usage-per-process,panelIndex:2,row:5,size_x:6,size_y:6,type:visualization),(col:3,id:AV65J6AGpvXUaLfX5ut_,panelIndex:3,row:1,size_x:2,size_y:2,type:visualization),(col:5,id:AV65JiV-pvXUaLfX5ut-,panelIndex:4,row:1,size_x:2,size_y:2,type:visualization),(col:3,id:AV7nl4T0DDGiyoddiuNE,panelIndex:6,row:3,size_x:4,size_y:2,type:visualization),(col:7,id:AV8VZYGVzigfAVWiSW8x,panelIndex:8,row:1,size_x:6,size_y:4,type:visualization),(col:1,id:AV7xk3sySFr7-onlGXH3,panelIndex:9,row:4,size_x:1,size_y:1,type:visualization),(col:2,id:AV7xkA4qSFr7-onlGVAr,panelIndex:10,row:4,size_x:1,size_y:1,type:visualization),(col:1,id:AV7xm60kSFr7-onlGcTl,panelIndex:11,row:5,size_x:1,size_y:1,type:visualization),(col:2,id:AV7xl2lwSFr7-onlGZnP,panelIndex:12,row:5,size_x:1,size_y:1,type:visualization),(col:1,id:AV8LqhuSQ8FtVuI_cC9b,panelIndex:13,row:6,size_x:1,size_y:3,type:visualization),(col:2,id:AV8LrsNTQ8FtVuI_cGTW,panelIndex:14,row:6,size_x:1,size_y:3,type:visualization),(col:1,id:AV8FoYadSFr7-onl5jMI,panelIndex:15,row:9,size_x:2,size_y:2,type:visualization),(col:5,id:AV64rxe4pvXUaLfX4xOH,panelIndex:16,row:9,size_x:2,size_y:2,type:visualization),(col:5,id:AV64-m22pvXUaLfX4xOJ,panelIndex:17,row:7,size_x:2,size_y:2,type:visualization),(col:3,id:AV65SGqxpvXUaLfX5uuP,panelIndex:18,row:9,size_x:2,size_y:2,type:visualization),(col:3,id:AV69GAj8pvXUaLfX5uuU,panelIndex:19,row:7,size_x:2,size_y:2,type:visualization),(col:1,id:AV9O94SLS_KsvcLSG8lX,panelIndex:20,row:1,size_x:2,size_y:3,type:visualization),(col:3,columns:!(Larm,Tidpunkt),id:AV7nU7Q7DDGiyoddiFAL,panelIndex:21,row:5,size_x:4,size_y:2,sort:!(alert_time,desc),type:search)),query:(match_all:()),timeRestore:!f,title:'Johans+Dashboard',uiState:(P-4:(vis:(legendOpen:!t)),P-5:(vis:(defaultColors:('0+-+75':'rgb(0,104,55)','75+-+90':'rgb(255,255,190)','91+-+100':'rgb(165,0,38)')))),viewMode:view)",
            "path": "myreport.pdf",
            "params": {
              "delay": 10000,
              "crop": true
            },
            "type": "pdf"
          }
        }
      }
    },
    "transform": {},
    "input": {},
    "condition": {}
  }
}`

**Comment by lmangani** [comment]
Hi @goveebee SENTINL only takes a screenshot at this time and does not attempt to interact with content, so if you can generate a link without bar (maybe embed link?) it should work fine. I suggest you rename this Issue to Feature Request: Custom Report Filename and we'll add it to the todo list.

**Comment by goveebee** [comment]
Ok. Thanks for your support! :)
