### ISSUE TITLE
Could I Get The payload.hits.hits?

### ISSUE THREAD

**Issue by wuhg6564** [sirensolutions/sentinl#263]
I could get the email from sentinl,but the content of actions's body which can not meet my needs. I can get the email such as "Found 7 Events" by the setting of actions body "Found {{payload.hits.total}} Events".Could I get the payload.hits.hits by which I can get the content I want.
thanks so much

**Comment by lmangani** [comment]
Yes, you can. Just follow the examples and use the mustache syntax. Thanks.
