### ISSUE TITLE
I am unable to create Set Alarm 

### ISSUE THREAD

**Issue by umeshvasam** [sirensolutions/sentinl#271]
When i click **Set Alarm
![set alarm](https://user-images.githubusercontent.com/34505716/33935930-aadfc888-e023-11e7-8bc6-7ec3690a92a5.png)

** button it redirected to http://kibana.xxx.com:5601/app/sentinl#/wizard?_g=() . Its asking for: 
![wizard](https://user-images.githubusercontent.com/34505716/33935947-bc9416a6-e023-11e7-8a1f-552ffcaef45c.png)
```
Give a proper name for the new watcher

Specify a period of execution (h:m:s)

Enter number of search results there should be to execute this watcher

Add action

Save 
```
I given all required information after that when i try to save Its Saying 

> Sentinl Watcher Wizard: Error 500 Internal Server Error: An internal server error occurred

**Comment by lmangani** [comment]
Hi @umeshvasam you need to check the Elasticsearch logs, and provide the full Error for troubleshooting. If you have any other plugins installed (Authentication, X-Packs, etc) it should be noted, too.

**Comment by umeshvasam** [comment]
Hi @lmangani I did not installed any plugins like Authentication,X-Packs etc and in elasticsearch logs there is no any error, warning log information.

**Comment by sergibondarenko** [comment]
@umeshvasam what are your Kibana and Elasticsearch versions?

**Comment by lmangani** [comment]
Moving to 6.x and cleaning up issues. Please reopen if this is still useful / required. Thanks!
