### ISSUE TITLE
Sentinl-v6.0.0 configuration issue

### ISSUE THREAD

**Issue by neelrana** [sirensolutions/sentinl#272]
I am trying to install and configure Sentinl-v6.0.0 with Kiabana (version 6.0.0). There is some problem with configuring to kibana which I cannot figure out how to solve it. I used the following commands to download and install Sentinl 6.0:

1) /usr/share/kibana/bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.0.0/sentinl-v6.0.0.zip

2) 	cd sentinl
	npm install
	gulp package --version=6.0.0

3) /usr/share/kibana/bin/kibana-plugin install file:///root/sentinl/target/gulp/sentinl-v6.0.0.zip

4) service kibana restart

However, when I go to the Sentinl app on kibana interface, I get this error:

`Error: [$injector:modulerr] Failed to instantiate module kibana due to: [$injector:modulerr] Failed to instantiate module apps/sentinl due to: [$injector:modulerr] Failed to instantiate module apps/sentinl.directives due to: [$injector:modulerr] Failed to instantiate module apps/sentinl.consoleAction due to: [ng:areq] Argument 'name' is required http://errors.angularjs.org/1.6.5/ng/areq?p0=name&p1=required minErr/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:998 assertArg@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:16548 registerDirective@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:18213 runInvokeQueue@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:4117 loadModules/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:4414 forEach@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:1674 loadModules@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:3935 loadModules/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:4354 forEach@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:1674 loadModules@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:3935 loadModules/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:4354 forEach@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:1674 loadModules@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:3935 loadModules/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:4354 forEach@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:1674 loadModules@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:3935 createInjector@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:7728 bootstrap/doBootstrap@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:14494 bootstrap@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:15023 [2691]/chrome.bootstrap@https://127.0.0.1/bundles/commons.bundle.js?v=16070:92:23956 [0]@https://127.0.0.1/bundles/sentinl.bundle.js?v=16070:1:235 __webpack_require__@https://127.0.0.1/bundles/commons.bundle.js?v=16070:1:211 window.webpackJsonp@https://127.0.0.1/bundles/commons.bundle.js?v=16070:1:862 @https://127.0.0.1/bundles/sentinl.bundle.js?v=16070:1:1 http://errors.angularjs.org/1.6.5/$injector/modulerr?p0=apps%2Fsentinl.consoleAction&p1=%5Bng%3Aareq%5D%20Argument%20'name'%20is%20required%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.5%2Fng%2Fareq%3Fp0%3Dname%26p1%3Drequired%0AminErr%2F%3C%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A998%0AassertArg%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A16548%0AregisterDirective%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A18213%0ArunInvokeQueue%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A4117%0AloadModules%2F%3C%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A4414%0AforEach%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A1674%0AloadModules%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A3935%0AloadModules%2F%3C%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A4354%0AforEach%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A1674%0AloadModules%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A3935%0AloadModules%2F%3C%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A4354%0AforEach%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A1674%0AloadModules%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A3935%0AloadModules%2F%3C%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A4354%0AforEach%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A1674%0AloadModules%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A3935%0AcreateInjector%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A7728%0Abootstrap%2FdoBootstrap%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A14494%0Abootstrap%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A15023%0A%5B2691%5D%2Fchrome.bootstrap%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A92%3A23956%0A%5B0%5D%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fsentinl.bundle.js%3Fv%3D16070%3A1%3A235%0A__webpack_require__%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A1%3A211%0Awindow.webpackJsonp%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A1%3A862%0A%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fsentinl.bundle.js%3Fv%3D16070%3A1%3A1%0A minErr/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:998 loadModules/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:4797 forEach@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:1674 loadModules@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:3935 loadModules/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:4354 forEach@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:1674 loadModules@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:3935 loadModules/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:4354 forEach@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:1674 loadModules@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:3935 loadModules/<@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:4354 forEach@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:1674 loadModules@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:3935 createInjector@https://127.0.0.1/bundles/commons.bundle.js?v=16070:36:7728 bootstrap/doBootstrap@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:14494 bootstrap@https://127.0.0.1/bundles/commons.bundle.js?v=16070:35:15023 [2691]/chrome.bootstrap@https://127.0.0.1/bundles/commons.bundle.js?v=16070:92:23956 [0]@https://127.0.0.1/bundles/sentinl.bundle.js?v=16070:1:235 __webpack_require__@https://127.0.0.1/bundles/commons.bundle.js?v=16070:1:211 window.webpackJsonp@https://127.0.0.1/bundles/commons.bundle.js?v=16070:1:862 @https://127.0.0.1/bundles/sentinl.bundle.js?v=16070:1:1 http://errors.angularjs.org/1.6.5/$injector/modulerr?p0=apps%2Fsentinl.directives&p1=%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20apps%2Fsentinl.consoleAction%20due%20to%3A%0A%5Bng%3Aareq%5D%20Argument%20'name'%20is%20required%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.5%2Fng%2Fareq%3Fp0%3Dname%26p1%3Drequired%0AminErr%2F%3C%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A998%0AassertArg%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A16548%0AregisterDirective%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A18213%0ArunInvokeQueue%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A4117%0AloadModules%2F%3C%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A4414%0AforEach%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A1674%0AloadModules%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A3935%0AloadModules%2F%3C%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A4354%0AforEach%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A35%3A1674%0AloadModules%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A3935%0AloadModules%2F%3C%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A36%3A4354%0AforEach%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A1%3A211%0Awindow.webpackJsonp%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A1%3A862%0A%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fsentinl.bundle.js%3Fv%3D16070%3A1%3A1%0A%0Ahttp%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A1%3A211%0Awindow.webpackJsonp%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fcommons.bundle.js%3Fv%3D16070%3A1%3A862%0A%40https%3A%2F%2F127.0.0.1%2Fbundles%2Fsentinl.bundle.js%3Fv%3D16070%3A1%3A1%0A (https://127.0.0.1/bundles/commons.bundle.js?v=16070:35)`

Version: 6.0.0
Build: 16070

**Screenshot shown below:**
![screenshot from 2017-12-13 15-17-58](https://user-images.githubusercontent.com/9300684/33946198-0a5bf800-e019-11e7-96fb-e17a2a2fafc0.png)

_Any help/suggestions/advice would be greatly appreciated, is there is anything that I am doing wrong? Please let me know. Thankyou in advance._

**Comment by lmangani** [comment]
@neelrana the 6.x release is for developers only at this stage and not yet supported/supportable. 
Any PRs are welcome, but unless You (or others) can contribute code/time, I wouldn't expect this before late Q1 2018.

Thanks for your report!

**Comment by neelrana** [comment]
Hi,

No problem, Thank you for all your work! So which is the best version of Sentinl to use so far in your opinion? I have ELK 6.0 at the moment. So I would probably have to downgrade to match the Sentinl plug-in version?

**Comment by neelrana** [comment]
I was also wondering, the whether steps that I have stated above in the problem description are correct inorder to install and configure Sentinl with Kibana? Am I missing anything or do I need to do anything else. Please let me know. Again thanks in advance.

**Comment by lmangani** [comment]
@neelrana 5.6.x is the most active branch at the moment, until we'll switch to 6.x next year. Thanks!
