### ISSUE TITLE
Schedule a watcher : Need help for the configuration.

### ISSUE THREAD

**Issue by jerpic** [sirensolutions/sentinl#275]
Hello,

First of all, many thanks for this Great solution.

I would like for a specific watcher be able to schedule it like this (with 2 periods) : every 5 secs from 8am to 9pm and every 2mns from 9pm to 8am. Does it possible ? Do you have an example please ?

According to this 2 periods, does it possible to have a timestamp value (in the query) per period ?

I mean for the first period : every 5 secs from 8am to 9pm , timestamp from value = **now-15m**

`"body": {
        "query": {
          "bool": {
            "must": [
              {
                "term": {
                  "provider": "sa2"
                }
              },
              {
                "range": {
                  "timestamp": {
                    "from": "now-15m"
                  }
                }
              }
            ]
          }
        },`

for the second period : every 2mns from 9pm to 8am , timestamp from value = **now-1h**

`"body": {
        "query": {
          "bool": {
            "must": [
              {
                "term": {
                  "provider": "sa2"
                }
              },
              {
                "range": {
                  "timestamp": {
                    "from": "now-1h"
                  }
                }
              }
            ]
          }
        },`

Any help would be very much appreciated.

Best Regards,
Jérôme.

**Comment by lmangani** [comment]
Hi @jerpic and thanks for using SENTINL!

My suggestion would be to schedule 2 separate watchers, one of each interval, and each with the custom range query you desire. Our [presentation](https://github.com/sirensolutions/sentinl/wiki#new-to-sentinl-and-watchers) and [Wiki](https://github.com/sirensolutions/sentinl/wiki/SENTINL-Watcher-Anatomy#trigger-schedule) provide some generic examples you can use for the Intervals.

The ```later.js``` syntax does allow for mixing the two intervals, but troubleshooting them might become complex so I wouldn't advice it for new users. 

I hope this helps - feel free to comment on this issue if additional help is needed.

**Comment by jerpic** [comment]
Many thanks @lmangani for your answer, it's clear.
