### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by DimaBogdan-phie** [sirensolutions/sentinl#276]
Hello!

I have ELK Stack, which is protected by searchguard. Kibi works properly, but watcher/reporter does't execute. every 1 min (set in watcher config) I get an error in kibi logs:
<pre>
kibi           | {"type":"log","@timestamp":"2017-12-14T09:33:55Z","tags":["status","debug","Sentinl","scheduler
"],"pid":1,"message":"Reloading Watchers..."}
kibi           | {"type":"log","@timestamp":"2017-12-14T09:33:55Z","tags":["status","debug","Sentinl","scheduler
","auth"],"pid":1,"message":"Enabled: true"}
kibi           | {"type":"log","@timestamp":"2017-12-14T09:33:55Z","tags":["status","debug","Sentinl","scheduler
","auth"],"pid":1,"message":"Mode: basic"}
kibi           | {"type":"log","@timestamp":"2017-12-14T09:33:55Z","tags":["status","debug","Sentinl","get_elast
icsearch_client","AUTH"],"pid":1,"message":"Impersonate ES client by admin"}
kibi           | Elasticsearch ERROR: 2017-12-14T09:33:55Z
kibi           |   Error: Request error, retrying
kibi           |   POST https://localhost:9200/watcher/watch/_count => connect ECONNREFUSED 127.0.0.1:9200
kibi           |       at Log.error (/usr/share/kibi/plugins/sentinl/node_modules/elasticsearch/src/lib/log.js:2
25:56)
kibi           |       at checkRespForFailure (/usr/share/kibi/plugins/sentinl/node_modules/elasticsearch/src/li
b/transport.js:258:18)
kibi           |       at HttpConnector.<anonymous> (/usr/share/kibi/plugins/sentinl/node_modules/elasticsearch/
src/lib/connectors/http.js:157:7)
kibi           |       at ClientRequest.bound (/usr/share/kibi/plugins/sentinl/node_modules/elasticsearch/node_m
odules/lodash/dist/lodash.js:729:21)
kibi           |       at emitOne (events.js:96:13)
kibi           |       at ClientRequest.emit (events.js:188:7)
kibi           |       at TLSSocket.socketErrorListener (_http_client.js:309:9)
kibi           |       at emitOne (events.js:96:13)
kibi           |       at TLSSocket.emit (events.js:188:7)
kibi           |       at emitErrorNT (net.js:1277:8)
kibi           |       at _combinedTickCallback (internal/process/next_tick.js:80:11)
kibi           |       at process._tickDomainCallback (internal/process/next_tick.js:128:9)
kibi           |
kibi           | Elasticsearch WARNING: 2017-12-14T09:33:55Z
kibi           |   Unable to revive connection: https://localhost:9200/
kibi           |
kibi           | Elasticsearch WARNING: 2017-12-14T09:33:55Z
kibi           |   No living connections
kibi           |
kibi           | {"type":"log","@timestamp":"2017-12-14T09:33:55Z","tags":["status","error","Sentinl","scheduler
"],"pid":1,"message":"An error occurred while looking for indices: Error: No Living connections"}
</pre>
(kibi and elasticsearch was started in docker container)

now i have following in kibi.yml:
<pre>
elasticsearch.username: "admin" # role with all rights
elasticsearch.password: "pass"
.....
sentinl:
  settings:
    email:
      active: true
      user: spam@mail.com
      password: passss
      host: smtp.mail.com
      timeout: 1000
    report:
      active: true
      tmp_path: /tmp/
    authentication:
      enabled: true 
      mode: 'basic'
      https: true
      admin_username: 'admin'  # the same role, but i tried system user before
      admin_sha: 'encrypted_pass' 
      user_index: 'sentinl_users' 
      user_type: 'user' 
      verify_certificate: false
      path_to_pem: 'config/signing-ca.pem'
      encryption:
        algorithm: 'aes256'
        key: 'b9726b04608ac48ecb0b6918214ade54'
        iv_length: 16
</pre>

what am I doing wrong?

**Comment by lmangani** [comment]
Not all versions / releases are the same. What version of ELK and SENTINL are you actually using?

**Comment by DimaBogdan-phie** [comment]
<pre>
  "name": "sentinl",
  "version": "5.4.3-1",
  "kibana": {
    "version": "5.4.3"
  }
</pre>
Actually I downloaded demo siren platform with preinstalled sentinl from https://support.siren.io/support/solutions/articles/17000058666-platform-5-4-3-1 , disable and remove all unnecessary for me things (graph browser, gremlin server, vanguard plugin..)

**Comment by lmangani** [comment]
Have you configured authentication details anywhere?

**Comment by DimaBogdan-phie** [comment]
**sg_config.yml**:
<pre>
searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
    authc:
      transport_auth_domain:
        enabled: true
        order: 2
        http_authenticator:
          type: basic
        authentication_backend:
          type: internal
      basic_internal_auth_domain:
        enabled: true
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
</pre>

**sg_roles.yml**:
# Permissions for a Sentinl user.
<pre>
sentinl:
  cluster:
    - "indices:data/write/bulk*"
    - "indices:admin/template/*"
    - KIBI_CLUSTER
  indices:
    '*':
      '*':
        - KIBI_READONLY
    'watcher_alarms*':
      '*':
        - KIBI_READWRITE
        - CREATE_INDEX
    'watcher*':
      '*':
        - KIBI_READWRITE
        - CREATE_INDEX
        - MANAGE
        - INDEX
        - READ
        - WRITE
        - DELETE
</pre>

another configs almost the same as here: https://docs.support.siren.io/5.4.3/platform/#_access_control_configuration

**Comment by DimaBogdan-phie** [comment]
in **kibi.yml** I also have this: 
<pre>
kibi_access_control:
  enabled: true
  cookie:
    password: "12345678123456781234567812345678"
    secure: false
 
  admin_role: kibiadmin
  sentinl:
    elasticsearch:
      username: sentinl
      password: sKzM2VBBB5x2
  acl:
    enabled: false
</pre>

**Comment by sergibondarenko** [comment]
Hi @DimaBogdan-phie 
The following config is needed only if you want to impersonate watcher. In Sentinl, impersonation is attaching specific authentication credentials to a watcher. Of course, the credentials should be configured on Search Guard side. Also, the credentials should be inserted in the username an password input fields in the General tab of the watcher editor. 
```
...
    authentication:
      enabled: true 
      mode: 'basic'
      https: true
      admin_username: 'admin'  # the same role, but i tried system user before
      admin_sha: 'encrypted_pass' 
      user_index: 'sentinl_users' 
      user_type: 'user' 
      verify_certificate: false
      path_to_pem: 'config/signing-ca.pem'
      encryption:
        algorithm: 'aes256'
        key: 'b9726b04608ac48ecb0b6918214ade54'
        iv_length: 16
```

You don't need all these `authentication` config If you want to run Sentinl on behalf of a single user - `sentinl`. This kibi.yml config part
```
  ...
  sentinl:
    elasticsearch:
      username: sentinl
      password: sKzM2VBBB5x2
```

Thus, if you don't want the impersonation, just eliminate `authentication` part from kibi.yml and execute watcher again. It is the default behavior. It works like this when you unpack Kibi distribution and use standard `sentinl` user with password `password`.

And If you want impersonation, please make sure you inserted correct credentials in the username an password input fields in the General tab of the watcher editor. 

Let me know.

**Comment by sergibondarenko** [comment]
@DimaBogdan-phie here is the recently updated wiki page about authentication in Sentinl https://github.com/sirensolutions/sentinl/wiki/Authentication

**Comment by DimaBogdan-phie** [comment]
Thanks!

I've tired this before and had another error. 
Now I did what you suggested, and have this:
<pre>
kibi           | {"type":"log","@timestamp":"2017-12-14T19:18:55Z","tags":["status","debug","Sentinl","scheduler"],"pid":1,"message":"Reloading Watchers..."}
kibi           | {"type":"log","@timestamp":"2017-12-14T19:18:55Z","tags":["status","debug","Sentinl","scheduler","auth"],"pid":1,"message":"Enabled: false"}
kibi           | {"type":"log","@timestamp":"2017-12-14T19:18:55Z","tags":["status","error","Sentinl","scheduler"],"pid":1,"message":"An error occurred while looking for indices: Authentication Exception :: {\"path\":\"/watcher/watch/_count\",\"query\":{},\"statusCode\":401,\"response\":\"Unauthorized\",\"wwwAuthenticateDirective\":\"Basic realm=\\\"Search Guard\\\"\"}"}
</pre>

**Comment by DimaBogdan-phie** [comment]
You can close this issue. That was a problem with roles and permissions.
