### ISSUE TITLE
how to configure "Actions" to show all the detailed payload?

### ISSUE THREAD

**Issue by henghenghahai** [sirensolutions/sentinl#277]
Hi guys,
   I've built ELK5.6.4 with sentinl, and want to send mail out by sentinl.
Normally, after the "INPUT" filter, there will be many events in the payload,I want to send out all the detailed payload ( or some specified columns).

currently,I only configure blow in "Body" of "Actions" to show the payload list by assign payload.hits.hits.**number**,but it's inflexible and insufficient, maybe the count of hits will be different everytime when watcher runs .
is there any method to iterately show the hits? for example.using for loop, or other methods?
thanks.

time:   	{{payload.hits.hits.0._source.@timestamp}}
host:   	{{payload.hits.hits.0._source.beat.hostname}}
env:   	{{payload.hits.hits.0._source.fields.oracle_env}}
database:   {{payload.hits.hits.0._source.fields.oracle_sid}}
message:  {{payload.hits.hits.0._source.message}}

time:   	{{payload.hits.hits.1._source.@timestamp}}
host:   	{{payload.hits.hits.1._source.beat.hostname}}
env:   	{{payload.hits.hits.1._source.fields.oracle_env}}
database:   {{payload.hits.hits.1._source.fields.oracle_sid}}
message:  {{payload.hits.hits.1._source.message}}

time:   	{{payload.hits.hits.2._source.@timestamp}}
host:   	{{payload.hits.hits.2._source.beat.hostname}}
env:   	{{payload.hits.hits.2._source.fields.oracle_env}}
database:   {{payload.hits.hits.2._source.fields.oracle_sid}}
message:  {{payload.hits.hits.2._source.message}}

...

**Comment by lmangani** [comment]
Hi @henghenghahai 
You can absolutely do this in different ways - you can iterate and create a custom object for Actions in the ```transforrm``` scripts, or you can use ```mustache```syntax to iterate the payloads from the Action itself. I invite you to read our Wiki and [presentation](https://github.com/sirensolutions/sentinl/wiki#new-to-sentinl-and-watchers) which will answer most of your questions. If you still need input, feel free to comment or open a new issue with a specific question.

Thanks for using SENTINL!

**Comment by neelrana** [comment]
@lmangani Hi, I am currently having the same problem as OP. I have looked at the presentation but could not fully understand the concept. I believe the hits are stored as an array  and in order to access this array we need to use the transform script (correct me if I am wrong). However, I am having trouble implementing that into my watcher.

Currently, I am manually typing out all the values of the payload hits i.e.:  {{payload.hits.hits.0._source.@timestamp}},  {{payload.hits.hits.1._source.@timestamp}},  {{payload.hits.hits.2._source.@timestamp}} etc...

I would like the watcher to iterate over this and print all the timestamps. From a programming perspective, something like a FOR loop, but I don't know how doing that in here.

Is there any other simpler way? Is using mustache syntax to iterate the payload simpler? Could you please provide an example? It would be great if you could help me out. Also, if @henghenghahai found a solution to your question, it would be great if you could post something to help me out please.  Thank you both of you for your help!

**Comment by lmangani** [comment]
Hi @neelrana 

mustache iteration is very [barebone](https://mustache.github.io/mustache.5.html):
```
{{#array}}  {{value}} {{/array}}
```

Applying the above might solve your issue, but the approach I would suggest is "preparing" your data using a SENTINL JS transform script and simplify the mustache application to the minimum it is designed to do. You can consider this example iterating buckets and storing results where ```doc_count``` matches the condition in a new array called ```payload.newlist``` - You can reapply it to the hits or any other chain with plan Javascript oneliners:
```
"transform": {
  "script": {
    "script": "payload.newlist=[]; payload.payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key; }).forEach(function(bucket){ if (doc_count.length > 1){ payload.newlist.push({name: bucket.key }); }});"
  }
}
```
Once the new temporary array is formed, you can use it it in your ```mustache``` action output simply iterating it and printing the contents:
```
{{#payload.newlist}} Name: {{name}} {{/payload.newlist}}
```

**Comment by varun0002** [comment]
@neelrana: Here is what you should do:
**Transform:**
{
  "script": {
    "script": "payload.hits.my_time=[];for(var i=0;i<payload.hits.hits.length;i++)payload.hits.my_time.push({name1:payload.hits.hits[i]._source['@timestamp']});"
  }
}
**Action Email Html**:
{{#payload.hits.my_time}}<li>{{name1}}</li>{{/payload.hits.my_time}}

**Comment by ds2000** [comment]
Hi guys,
Does this work with Kibana 4?  It's new to us as well and understanding how to view / query the payload into usable variables is driving us crazy :)

**Comment by lmangani** [comment]
@ds2000 did you familiarize with the `mustache` language? What's driving you crazy? :)

**Comment by ds2000** [comment]
We're trying too, I should add we're using eAlerts (we have an EL6 stack in the works so are trying to make a square peg fit a round hole)

The short story is a few of us are new on site and new to the product, we're trying to view how the payload gets constructed and the fields of the array.  Our alerters send a mail but we want to give the end user more information like the hostname, envcode, appcode etc.

**Comment by lmangani** [comment]
You can cherry-pick any value form the payload into the alert body.  Check [this](https://mustache.github.io/#demo) out and it should become obvious.

```
{ name: "someone", action: "needs", target: "help" }
```
```
{{ name }} {{ action }} {{ target }}!
```
```
someone needs help!
```

**Comment by ds2000** [comment]
Thanks for your help, it's a steep curve.  I'll have a read and try not to poke this thread again ;)

**Comment by lmangani** [comment]
The logic is simple, if you know the name/path to an object property, you can use it. Feel free to ask for help here on in a dedicated ticket if you get stuck with something specific.

**Comment by Teressss** [comment]
The guy above wanted to print just the timestamps. I followd instructions here and was able to get an alert which will give me only one field, for example the timestamp. But how to do it, when I want to show whole message or just few fields like timestamp _ client _ host _message? Thanks

**Comment by lmangani** [comment]
You need to use the `mustache` syntax against the response JSON payload.

**Comment by Teressss** [comment]
> You need to use the mustache syntax against the response JSON payload.
Thanks, but I had no idea how to do it. https://github.com/sirensolutions/sentinl/issues/434

**Comment by lshc0** [comment]
@lmangani Hello,guys!
I tried according to your example but failed.Below is the content of my input
`  "input": {
    "search": {
      "request": {
        "index": [
          "logstash-*"
        ],
        "body": {
          "query": {
            "bool": {
              "filter": {
                "range": {
                  "@timestamp": {
                    "gte": "now-1m/m",
                    "lte": "now/m",
                    "format": "epoch_millis"
                  }
                }
              },
              "must": [
                {
                  "match_phrase": {
                    "msg": "Authentication failed, login method (localDB), reason (authentication failure)."
                  }
                }
              ]
            }
          },
          "size": 0,
          "aggs": {
            "IPAgg": {
              "terms": {
                "field": "src.keyword",
                "size": 8000,
                "min_doc_count": 1
              }
            }
          }
        }
      }
    }
  },

Below is the content of the transform
`"transform": {
  "script": {
    "script": "payload.newlist=[]; payload.payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key; }).forEach(function(bucket){ if (doc_count.length > 1){ payload.newlist.push({name: bucket.key }); }});"
  }
}`
Below is the content of the action,I choose webhook
`"body": "{\n  \"msgtype\": \"text\",\n  \"text\": {\n      \"content\":\"{{#payload.newlist}}{{name}}{{/payload.newlist}}\"\n  }\n}",`

But there is no output data, can you help me see it?

**Comment by Eric96** [comment]
> @neelrana: Here is what you should do:
> **Transform:**
> {
> "script": {
> "script": "payload.hits.my_time=[];for(var i=0;i<payload.hits.hits.length;i++)payload.hits.my_time.push({name1:payload.hits.hits[i]._source['@timestamp']});"
> }
> }
> **Action Email Html**:
> {{#payload.hits.my_time}}
> 
> * {{name1}}
> {{/payload.hits.my_time}}

Thank you so much! It just can send one type word , how about more type word?

**Comment by yapnel** [comment]
Are you able to tell us the properties/fields of the Payload JSON object so I can pick up the field held inside please?

**Comment by zffocussss** [comment]
> Are you able to tell us the properties/fields of the Payload JSON object so I can pick up the field held inside please?

yes I also want to know how to get payload details,and sent it to email
