### ISSUE TITLE
Retrieve additional information for the action.

### ISSUE THREAD

**Issue by jerpic** [sirensolutions/sentinl#278]
Hello,

Today I have a watcher (working well, thanks Sentinl) which raise the number bookings (KO) over the last **15** minutes. I'm able with a script to retrieve the number of bookings (OK & KO) and display this information in the email alert. 

My question is : Is there a way to retrieve the number of bookings (OK & KO) over the last 60 minutes when the watcher (the last 15 minutes) raises the alert ?

Here is my watcher : 

```
{
  "_index": "watcher",
  "_type": "sentinl-watcher",
  "_id": "8p8r45d8duk-w0kkyg51f08-my74ada6ssf",
  "_version": 5,
  "found": true,
  "_source": {
    "title": "NEW ALERT PNR Ko GAL",
    "disable": false,
    "report": false,
    "trigger": {
      "schedule": {
        "later": "every 5 secs"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "pnr-*"
          ],
          "body": {
            "query": {
              "bool": {
                "must": [
                  {
                    "term": {
                      "provider": "gal"
                    }
                  },
                  {
                    "range": {
                      "timestamp": {
                        "from": "now-15m"
                      }
                    }
                  }
                ]
              }
            },
            "aggs": {
              "pnr_status": {
                "terms": {
                  "field": "_type"
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "var pnrKO = payload.aggregations.pnr_status.buckets.filter(function( obj ) { return obj.key == \"pnr-ko\"; })[0]; if(pnrKO !=null){ payload.pnr_ko = pnrKO.doc_count} else { payload.pnr_ko = 0 }; var pnrOK = payload.aggregations.pnr_status.buckets.filter(function( obj ) { return obj.key == \"pnr-ok\"; })[0]; if(pnrOK !=null){ payload.pnr_ok = pnrOK.doc_count} else { payload.pnr_ok = 0}; var errorPercentage = (payload.pnr_ko / payload.hits.total);  payload.hits.total > 6 && errorPercentage > 0.5"
      }
    },
    "actions": {
      "HTML : ALERT CONNECTOR GAL": {
        "throttle_period": "0h10m0s",
        "email_html": {
          "to": "",
          "from": "",
          "subject": "ALERT CONNECTOR : GAL - PNR-KO : {{payload.pnr_ko}} - PNR-OK : {{payload.pnr_ok}}",
          "body": "",
          "html": "PNR-KO : {{payload.pnr_ko}} - PNR-OK : {{payload.pnr_ok}}"
        }
      }
    },
    "transform": {}
  }
}


Best Regards,


```

**Comment by jerpic** [comment]
Hello,

In order to solve my problem, I tried to use the "chain transform" see the code of my watcher here: 

Unfortunately, the original payload is replaced by the new one from the chain transform. How can I keep the orginal values ?

{
  "_index": "watcher",
  "_type": "sentinl-watcher",
  "_id": "a1cg2uvmajq-92bhlgtl5dh-74wzecwvgdu",
  "_version": 7,
  "found": true,
  "_source": {
    "title": "ALERT V2 PNR Ko TVP",
    "disable": false,
    "report": false,
    "trigger": {
      "schedule": {
        "later": "every 5 secs"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "pnr-*"
          ],
          "body": {
            "query": {
              "bool": {
                "must": [
                  {
                    "term": {
                      "provider": "tvp"
                    }
                  },
                  {
                    "range": {
                      "timestamp": {
                        "from": "now-15m"
                      }
                    }
                  }
                ]
              }
            },
            "aggs": {
              "pnr_status": {
                "terms": {
                  "field": "_type"
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "var pnrKO = payload.aggregations.pnr_status.buckets.filter(function( obj ) { return obj.key == \"pnr-ko\"; })[0]; if(pnrKO !=null){ payload.pnr_ko = pnrKO.doc_count} else { payload.pnr_ko = 0 }; var pnrOK = payload.aggregations.pnr_status.buckets.filter(function( obj ) { return obj.key == \"pnr-ok\"; })[0]; if(pnrOK !=null){ payload.pnr_ok = pnrOK.doc_count} else { payload.pnr_ok = 0}; var errorPercentage = (payload.pnr_ko / payload.hits.total);  payload.hits.total > 1 && errorPercentage > 0.1"
      }
    },
    "actions": {
      "HTML : ALERT V2 CONNECTOR TVP": {
        "throttle_period": "0h10m0s",
        "email_html": {
          "to": "----",
          "from": "----",
          "subject": "ALERT CONNECTOR : TVP - PNR-KO : {{payload.pnr_ko}} - PNR-OK : {{payload.pnr_ok}} - PNRTOTAL-OK :  {{payload.pnrtotal_ok}}",
          "body": "",
          "html": ""
        }
      }
    },
    "transform": {
      "chain": [
        {
          "search": {
            "request": {
              "index": [
                "pnr-*"
              ],
              "body": {
                "query": {
                  "bool": {
                    "must": [
                      {
                        "term": {
                          "provider": "tvp"
                        }
                      },
                      {
                        "range": {
                          "timestamp": {
                            "from": "now-60m"
                          }
                        }
                      }
                    ]
                  }
                },
                "aggs": {
                  "pnrtotal_status": {
                    "terms": {
                      "field": "_type"
                    }
                  }
                }
              }
            }
          }
        },
        {
          "script": {
            "script": "var pnrTotalKO = payload.aggregations.pnrtotal_status.buckets.filter(function( obj ) { return obj.key == \"pnr-ko\"; })[0]; if(pnrTotalKO !=null){ payload.pnrtotal_ko = pnrTotalKO.doc_count} else { payload.pnrtotal_ko = 0 }; var pnrTotalOK = payload.aggregations.pnrtotal_status.buckets.filter(function( obj ) { return obj.key == \"pnr-ok\"; })[0]; if(pnrTotalOK !=null){ payload.pnrtotal_ok = pnrTotalOK.doc_count} else { payload.pnrtotal_ok = 0};"
          }
        }
      ]
    }
  }
}

**Comment by sergibondarenko** [comment]
@jerpic `transform` is done to replace the original request result. To solve the problem you can create the second watcher to monitor alarms stored by the first watcher. When the second watcher sees the alarm, it retrieves the number of bookings (OK & KO) over the last 60 minutes.
