### ISSUE TITLE
How do I add variables to the message filed?

### ISSUE THREAD

**Issue by neelrana** [sirensolutions/sentinl#281]
1. Issue Description

I am new to this so sorry for stupid question. But I am trying to create a watcher which has a console action. This alert is triggered whenever it comes across  a web error code 304. I want the message to print "Response 304 found with 45 events" (for example). So I am simply trying to print variable values on console (just like any programming language).

2. Reproducing the Issue step-by-step
This is my following JSON code:

> {
>   "_index": "watcher",
>   "_type": "sentinl-watcher",
>   "_id": "kd5j9zca6sb-ue670k6yzjq-uh03uus461",
>   "_version": 8,
>   "found": true,
>   "_source": {
>     "title": "watcher1",
>     "disable": true,
>     "report": false,
>     "trigger": {
>       "schedule": {
>         "later": "every 10 seconds"
>       }
>     },
>     "input": {
>       "search": {
>         "request": {
>           "index": [
>             "apache-*"
>           ],
>           "body": {
>             "query": {
>               "query_string": {
>                 "default_field": "response",
>                 "query": "304"
>               }
>             }
>           }
>         }
>       }
>     },
>     "condition": {
>       "script": {
>         "script": "payload.hits.total > 10"
>       }
>     },
>     "actions": {
>       "New console action 8t2hu2igybs": {
>         "console": {
>           "message": "Response {{payload.hits.response}} found with {{payload.hits.total}} events from {{payload.hits.ip}}",
>           "priority": "high"
>         }
>       }
>     }
>   }
> }

3. Expected Results vs. Actual Results

Expected result: "Response 304 found with 63 events from 198.25.0.3"
Actual Result:     "Response found with 63 events from "

I know that you have to use mustache template however, I cant seem to print the variable values out.

**Comment by burandobata** [comment]
If you would like to iterate through results and check particular fields you will need to use mustache syntax like:
"body": "Events: \n{{#payload.hits.hits}}{{_source.message}}\n{{/payload.hits.hits}}

Maybe you will find this handy: https://mustache.github.io/mustache.5.html

**Comment by lmangani** [comment]
@burandobata is right. You need to use the proper ```mustache``` syntax to iterate objects. Thanks!
