### ISSUE TITLE
Sentinl supported on Windows Server 2012R2?

### ISSUE THREAD

**Issue by bozzerreaneaux** [sirensolutions/sentinl#283]
Hello,

trying to get sentinl working on a Windows box but having trouble. I was wondering if it's actually supported?

I have Elasticsearch and Kibana on the same server. Installed Sentinl via

kibana-plugin.bat install file///<path/to/sentinl.zip>

It installs successfully without any errors and I can see the plugin loaded in the kibana plugins directory. I also see the sentinl tab in the web UI but when I click on Sentinl tab I get the following angular error in the Kibana UI:

"Directive name '' is invalid. The first character must be a lowercase letter http://errors.angularjs.org/1.4.7/$compile/baddir?p0="

Any help is greatly appreciated

**Comment by enterdv** [comment]
Try with another browser, it's not working on Internet Explorer.

**Comment by bozzerreaneaux** [comment]
gosh! thank you!
it works on chrome :)
