### ISSUE TITLE
Timezone 

### ISSUE THREAD

**Issue by enterdv** [sirensolutions/sentinl#284]
Hi! Thanks for you work!

My question: Is it possible to send the time in alert not in UTC but in my local time?
Now in my alert I have time in this format - 2017-12-20T15:03:57.000Z

**Comment by lmangani** [comment]
Hi @enterdv 
You can try set ```sentinl.es.watcher.schedule_timezone``` to ```local``` for later.js to use the ```localTime``` - mind the fact UTC is used internally has a bunch of good reasons to be the default particularly when dealing with distributed clusters across timezones.

**Comment by enterdv** [comment]
Hi @lmangani 
Thanks for your answer! And where can I found later.js? And how excactly I should set the option `sentinl.es.watcher.schedule_timezone`

**Comment by lmangani** [comment]
This is a preference to be edited in the sentinl portion of your kibi/yml or kibana.yml either.
