### ISSUE TITLE
in example about configure sentinl it have error

### ISSUE THREAD

**Issue by zqc0512** [sirensolutions/sentinl#286]
Example (extended)
sentinl:
  es:
    host: localhost
    port: 9200
    timefield: '@timestamp'
    default_index: watcher
    type: sentinl-watcher
    alarm_index: watcher_alarms
    alarm_type: sentinl-alarm
    script_type: sentinl-script
  sentinl:
    history: 20
    results: 50
    scriptResults: 50
  settings:
    email:
      active: false
      user: username
      password: password
      host: smtp.server.com
      ssl: true
      timeout: 10000  # mail server connection timeout
    slack:
      active: false
      username: username
      hook: 'https://hooks.slack.com/services/<token>'
      channel: '#channel'
    webhook:
      active: false
      method: POST
      host: host
      port: 9200
      path: ':/{{payload.watcher_id}'
      body: '{{payload.watcher_id}}{payload.hits.total}}'
    report:
      active: false
      tmp_path: /tmp/
      **search_guard: false,
      simple_authentication: false,**
    pushapps:
      active: false
      api_key: '<pushapps API Key>'  

      **search_guard: false,
      simple_authentication: false,**
this mast be
      **search_guard: false
      simple_authentication: false**

1. Issue Description

2. Reproducing the Issue step-by-step

3. Expected Results vs. Actual Results

4. Additional Details

**Comment by lmangani** [comment]
Thanks for spotting it! Fixed
