### ISSUE TITLE
there is some docs about how configure and use it (sentinl) how about kibi ?

### ISSUE THREAD

**Issue by zqc0512** [sirensolutions/sentinl#287]
there is some docs about how configure and use it (sentinl) how about kibi 
it now use sentinl not kibi about es 5.6.x?

1. Issue Description

2. Reproducing the Issue step-by-step

3. Expected Results vs. Actual Results

4. Additional Details

**Comment by lmangani** [comment]
https://github.com/sirensolutions/sentinl/wiki
