### ISSUE TITLE
Alternative date-time format?

### ISSUE THREAD

**Issue by neelrana** [sirensolutions/sentinl#288]
1. Issue Description

Hi, I have set up a watcher that sends alerts to slack and email (and it works fine!). I was wondering wheter it is possible for the alerts to displace the time (extracted from the tag @timestamp) in a more readable date-time formate?

3. Expected Results vs. Actual Results

For example, at the moment I receive alerts and it prints this date-time format: 2018-01-05T10:28:05.000Z (I believe that is the TZ format)

I wanted the alters to display the date and time in maybe this format: 2018-01-05   10:28:05
Is this possible?

Thank you

**Comment by lmangani** [comment]
@neelrana sure, you can use plan Javascript to convert any of your data or timestamps in a transform script, before reaching the final action stage. Beauty of SENTINL is payloads are direct drive.
```
new Date('2018-01-05T10:28:05.000Z ').toUTCString()
```

Hope this helps.

**Comment by neelrana** [comment]
Thanks for your response, Will this work?

```
transform: {
        "script": {
                "script": "newDate('{{#payload.hits.hits}}{{_source.@timestamp}}{{/payload.hits.hits}}' ).toUTCString()"
           }
}
```

I want all the elements in payload.hits.hits array to display alternative date-time format.
