### ISSUE TITLE
Sentinl in Kibana 5.6.5

### ISSUE THREAD

**Issue by DwijadasDey** [sirensolutions/sentinl#290]
Hi
I am trying to generate PDF reports using sentinl and for that i have installed sentinl in ubuntu 16.04 using following command.

$ ./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.6.5/sentinl-v5.5.1.zip
I can find the sentinl link in the kibana [5.6.5] left menu bar. 

Now for report generation and sending them to my gmail account, i have copied the following configurations in the /etc/kibana/kibana.yml and restarted kibana

sentinl:
  settings:
    email:
      active: true
      user: username@gmail.com
      password: mypassword
      host: smtp.gmail.com
      ssl: true
    report:
      active: true
      tmp_path: /tmp/

But I did not find any report in the sentinl->report tab or in my mail box.

Shall i need to configure few more parameters ?

**Comment by lmangani** [comment]
Hi @DwijadasDey 
A 5.5.1 release is not optimal for 5.6.5 and might have many side effects. You should download and install the proper release for your Kibana version whenever it exists:
```
./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.6.2/sentinl-v5.6.5.zip
```
Reports require PhantomJS on the system. Make sure you check for errors installing PhantomJS bundled with SENTINL and If needed, install it manually system with with npm before following the examples available on the Wiki.

Once you start SENTINL and schedule a basic watcher or reporter, check the Kibana logs for hints as of what's happening behind the scenes and attach here if assistance is required.

I hope this helps you!

LM
