### ISSUE TITLE
Need some help with Watcher input and condition

### ISSUE THREAD

**Issue by bozzerreaneaux** [sirensolutions/sentinl#292]
Hello,

I've been struggling with getting the input and condition parts right but can't seem to get the desired result.
 My problem is very similar to [this one](https://github.com/sirensolutions/sentinl/issues/200) (closed)
I am using ELK heartbeat to probe various service health endpoints. What I am trying to achieve is raise an email alert if heartbeat starts reporting a service down i.e. "up" field in the beat = "false". And perhaps, it's a good idea to only target beats from the last 5 mins, otherwise alerts will keep streaming even though the service health has been restored.

My current watcher config looks like this:

<pre>
{
  "_index": "watcher",
  "_type": "sentinl-watcher",
  "_id": "hx2pbrds8h-kayjlihs1eg-czn9olxygnb",
  "_version": 127,
  "found": true,
  "_source": {
    "title": "service_up",
    "disable": true,
    "report": false,
    "trigger": {
      "schedule": {
        "later": "every 30 secs"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            **"<heartbeat-{now/d}>",
            "<heartbeat-{now/d-1d}>"**
          ],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        **"script": "var status=false;payload.hits.hits.forEach(function(e){ if (e._source.up == false){ status=true; return status; } }); status;"**
      }
    },
    "actions": {
      "Email to Admin": {
        "throttle_period": "0h0m0s",
        "email_html": {}
      }
    },
    "transform": {}
  }
}
</pre>

When I reverted the script condition to target beats with "up == true" I get a notification but when I specify "up == false" the condition is evaluated to "false" and the watcher doesn't execute even though I can clearly see beats coming in ES with up field "false" because I have stopped one of the services to test.
What I can't possibly grasp is what query is sentinl running in the background when I specify "<heartbeat-{now/d}>","<heartbeat-{now/d-1d}>" and how is it possible that it misses recent beats which report that the service is down. 

What I also don't understand is why when I run the following in the Dev Tools console I see only ~10 records not of them reporting the service is down, while there should be hundreds of beats. If the watcher is based on a similar query this explains why the condition doesn't find a single match. But I thought the below query should get all records for the specified day.  
```
GET heartbeat-2018.01.17/_search
{
	"query": {
		"match_all": {}
		}
}
```

Here is the first lines of the above query including the first record in the array:
```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 7784,
    "max_score": 1,
    "hits": [
      {
        "_index": "heartbeat-2018.01.17",
        "_type": "doc",
        "_id": "AWEBbkCiffEhnz27elDg",
        "_score": 1,
        "_source": {
          "@timestamp": "2018-01-17T00:04:17.936Z",
          "beat": {
            "hostname": "************",
            "name": "************",
            "version": "5.6.0"
          },
          "duration": {
            "us": 4010
          },
          "host": "************",
          "http_rtt": {
            "us": 2010
          },
          "ip": "10.145.26.166",
          "monitor": "http@http://************",
          "port": 3400,
          "resolve_rtt": {
            "us": 0
          },
          "response": {
            "status": 200
          },
          "rtt": {
            "us": 4010
          },
          "scheme": "http",
          "tcp_connect_rtt": {
            "us": 1999
          },
          "type": "http",
          "up": true,
          "url": "************"
        }
      }
```

I am sorry for the likely silly questions, I am very new to lucene..
Your help is greatly appreciated

**Comment by lmangani** [comment]
Hi @bozzerreaneaux 
I think you might want to switch approach and use an aggregation query directly targeting the status you're after - there is no need to return all results and code the logic when the ES API can do this for you and bucket the results per host already. Take a look at [this](https://github.com/PhaedrusTheGreek/nagioscheckbeat/blob/master/blog/watch-heartbeat.sense) as starting point.

This said, with the HITS logic you might want to try simplify the logic to iterate all results:
```
var status=false;payload.hits.hits.forEach(function(e){ if (!e._source.up){ status=true; } }); status;
```
or even test the formatted conditions:
```
"condition": {
  "array_compare": {
    "payload.hits.hits" : { 
      "path": "_source.up" ,
      "eq": { 
        "value": false 
      }
    }
  }
}
```

Let us know if this helps.

**Comment by bozzerreaneaux** [comment]
Hi @lmangani ,

Thanks for the great suggestions!

I have modified the configuration a little to use "array_compare" in the condition and also tried to narrow down the input to focus only on records from the past 15 minutes however when I run the watcher I get:

Sentinl Watchers: Error 406 Not Acceptable: [parsing_exception] Unknown key for a START_OBJECT in [filter].

There seems to be a problem with the filter property but I can't figure out what...

By the way, where can I get information on what are all accepted properties that I can use in the input?
(for example how do you know that there is a **range** property inside **must** inside **bool**, etc)

Thanks a lot!

--Boz

**Comment by lmangani** [comment]
@bozzerreaneaux the only available documentation right now is the wiki. If you find inaccuracies just feel free to edit or open an issue. As of the 406 its related to the filter format being different, unrelated to SENTINL. I'll close this issue as this does not seem to outline a bug, but feel free to continue troubleshooting and commenting further if advice is needed.

**Comment by bozzerreaneaux** [comment]
Hi @lmangani, no problem, the only outstanding thing is where can I check what is the correct filter format for Sentinl? I took as example the ones published in the wiki and I tried the following structure but I still get the "Error 406 Not Acceptable: [parsing_exception] no [query] registered for [filtered]"

`{
  "search": {
    "request": {
      "index": [
        "<heartbeat-{now/d}>",
        "<heartbeat-{now/d-1d}>"
      ],
      "body": {
        "query": {
          "filtered": {
            "filter": {
              "range": {
                "@timestamp": {
                  "from": "now-15m"
                }
              }
            }
          }
        }
      }
    }
  }
}`

**Comment by lmangani** [comment]
Sentinl does not have a query format - whatever works in ES should work in SENTINL with the very same results. Make sure you form your query using Dev Tools in Kibana, and once it works there just copy to the Watcher.

**Comment by bozzerreaneaux** [comment]
@imangani, thank you

I thought the query structure was custom to sentinl.

All set!
