### ISSUE TITLE
5.6.2 release tarball is broken

### ISSUE THREAD

**Issue by mxj4** [sirensolutions/sentinl#293]
I found the current 5.6.2 release tarball mixed with some later changes and it's not compatible with Kibana 5.6.2.

If I build the source from `tag-5.6.2` it works fine.

**Comment by lmangani** [comment]
Thanks for the heads up! @sergibondarenko could you please check this out?

**Comment by sergibondarenko** [comment]
@mxj4 yes, it is not compatible with all current releases. It will be fixed in the next release. 

Only the following installation methods work:

1.
```
kibana$ ./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.6.2/sentinl-v5.6.2.zip
```
2.
```
git clone https://github.com/sirensolutions/sentinl
cd sentinl && npm install && gulp package --version=5.6.2
kibana$ ./bin/kibana-plugin install file://`pwd`/target/gulp/sentinl.zip
```
3.
```
cd sentinl && npm install
gulp dev --kibanahomepath=../kibana
```


[Readme](https://github.com/sirensolutions/sentinl#app-installation)
