### ISSUE TITLE
Question: Need help with HTTP call to disable/enable watch

### ISSUE THREAD

**Issue by bozzerreaneaux** [sirensolutions/sentinl#296]
Hello,

I just have a quick question - Need some help with devising an HTTP call to disable/enable a certain watch to simulate maintenance mode, so that alerts are not generated during say deployment time when services get shut down for a moment.

I've tried the following calls but can't seem to get it right:

```
PUT watcher/sentinl-watcher/hx2pbrds8h-kayjlihs1eg-czn9olxygnb
{
  "_source": {

    "disable": false

  }
  
}
```
```
PUT watcher/sentinl-watcher/hx2pbrds8h-kayjlihs1eg-czn9olxygnb
{
  "_source.disable": "true"
}
```
Could someone give me a hint?

Thanks a lot!

--Boz

**Comment by lmangani** [comment]
Hi @bozzerreaneaux 
You can simply pull, modify and update the Watcher document in Elasticsearch. SENTINL should automatically pick up changes within seconds and reflect the new status at execution time.

**Comment by bozzerreaneaux** [comment]
Thanks Imangani, got it to work:

```
POST /watcher/sentinl-watcher/hx2pbrds8h-kayjlihs1eg-czn9olxygnb/_update
{

  "script" : "ctx._source.disable = true"

}
```
