### ISSUE TITLE
kibana in docker container

### ISSUE THREAD

**Issue by screwyy** [sirensolutions/sentinl#298]
Hello, how can I install this plugin in a kibana docker container, since "git" is not installed in the official container ?

**Comment by lmangani** [comment]
@screwyy sure you can by using the ready archives directly as follows:
```
RUN kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v${KIBANA_VERSION}.zip
```

Hope this helps!
