### ISSUE TITLE
Sentinl for Kibana 6.x supported

### ISSUE THREAD

**Issue by mreilly82** [sirensolutions/sentinl#300]
No issues to report, just looking to see if the Kibana 6.x would support Sentinl or if anyone has tried? I did not see anything in open posts for it and just wanted to inquire.

**Comment by permyakovsv** [comment]
+1

**Comment by burandobata** [comment]
Hey,
I'm using Sentinl with Kibana 6.0.1. Have not tested everything, but emails and reports are working for me.

**Comment by reilee** [comment]
Removed index: watcher_alarms will break sentinl, and not possible to re-create it.

**Comment by lmangani** [comment]
@reilee why would you do that? By the way, SENTINL creates its indices on startup. If it doesn't check why in the logs.

**Comment by dgptamayo** [comment]
hi @burandobata - what sentinl release version did you use for kibana 6.0.1 and how did you get around the version check during install? did you manually extract the 5.x or 6.x release and modified the `package.json` file?

**Comment by ssi0202** [comment]
hey can you explain exactly how you got around the version check did you download the files and recompiled them and what if any changes did you make to get around the version check

**Comment by ij3net** [comment]
Hi,
I'm also get sentinl working with ELK 6.1. Only kibana version required was changed in package.json 
All working fine exclude sending alarms by SMTP. If anyone doing same please confirm that emails working or any work around. Possible this problem not related to sentinl directly.

**Comment by dgptamayo** [comment]
hey @ssi0202 

so i followed this instruction from the README.md

```
git clone https://github.com/sirensolutions/sentinl
cd sentinl && npm install && gulp package --version=6.1.0
/opt/kibana/bin/kibana-plugin install file://`pwd`/target/gulp/sentinl.zip
```
note the version flag

**Comment by ssi0202** [comment]
arh cool ill try that thanks

**Comment by ssi0202** [comment]
anyh way do do this easy on a windows machine?

**Comment by Arun-Ghosh** [comment]
Same query : As mentioned in Release notes, 6.0.X release is a ALPHA RELEASE. When the GA is coming up ? Any idea ?

**Comment by lmangani** [comment]
We're working on smoothing out the edges but the plans for 6.x are bigger than just being compatible. We do not have an ETA yet but happy to form a group of early testers to expedite the work if anyone is willing.

**Comment by ij3net** [comment]
JFYI: I had built sentinl for latest kibana 6.2.1 and elastic 6.2.1 and using it as beta in our project. It's working fine :) of course I'm using only basic functionality watchers and email actions. Next planned step using anomaly detection based on alarms. BTW documentation needs many and many corrections and details.

**Comment by lmangani** [comment]
@ij3net open-source power to the rescue, please submit documentation corrections, suggestions and improvements so we can keep growing faster and stronger ;)

**Comment by ij3net** [comment]
@panuinth you are sure sentinl still not ready to 6.2. But I'm working on it :)
https://github.com/ij3net/sentinl/commit/0037120a78b933925c4f4db7e2a3b4867fcf9b06
And here issue related exactly to `Rejecting mapping update to [watcher] as the final mapping would have more than 1 type` error https://github.com/sirensolutions/sentinl/issues/257

**Comment by ebuildy** [comment]
I am too (see https://github.com/sirensolutions/sentinl/compare/branch-6.0...ebuildy:branch-6.0?expand=1).

Also, Kibana is moving to React components via their UI framework https://elastic.github.io/eui/, this could reduce lot of code!

**Comment by lmangani** [comment]
Fantastic! Thank you @ebuildy and @ij3net for getting your hands dirty - SENTINL does need more contributors to bloom and keep its momentum up! The plan for `6.x` is to drop a lot of the UI code currently used, and migrate to the native components in now offers, possibly going entirely API headless. Please do feel free to open PRs with your ongoing work and we'll be happy to cooperate/advise to reach a global coverage.

**Comment by ebuildy** [comment]
I am browsing your code source, and it's an amazing project!

The code is really clean so it's a pleasure to work with, I can spend some days on it since we plan to use it at Qwant.com.

**Comment by ebuildy** [comment]
For instance, using the uid Modal, about page could give:

![](http://b3.ms/NPpnQGvV9EZg)

(branch https://github.com/sirensolutions/sentinl/compare/branch-6.0...ebuildy:refactor/about?expand=1)

**Comment by Sylvain-69** [comment]
Hey !
I can't contribute to this project since I'm not a developper...
But I'm willing to test it and report bugs.
I'm currently running elk v6.1.1

**Comment by ij3net** [comment]
@Sylvain-69 you can try 
`bin/kibana-plugin install https://github.com/ij3net/sentinl/releases/download/6.1.1/sentinl-6.1.1.zip`
It's my testing build with fixes for elastic and kibana 6.x
Please note it's very very alpha but it's working for me with kibana 6.2.1

**Comment by ebuildy** [comment]
@ij3net not sure you need to zip ``node_modules`` dir as well, I tried with Kibana builder and the final zip is only 6Mo (https://github.com/ebuildy/sentinl/releases/tag/tag-6.0.0)

**Comment by yabir** [comment]
@ebuildy , I think the correct @ij3net way for Kibana 6.2.1 is : 

> bin/kibana-plugin install https://github.com/ij3net/sentinl/releases/download/6.2.1/sentinl-6.2.1.zip

Here the @ij3net sentinl releases : https://github.com/ij3net/sentinl/releases

By the way, thank you all for your incredible cooperation. I hope to have some day that level to also add my grain of sand :D
