### ISSUE TITLE
Need help understand Watcher

### ISSUE THREAD

**Issue by shah83** [sirensolutions/sentinl#301]
Hello all, thks for the alternative to X-pack.
I am new to this product. Need help understand the watcher setup.

I looked for many examples and saw for condition it always has payload.hits. Question i have is can we have watcher for a saved visualization in Kibana. I am using Kibana for different purpose than network related tracking. My scenario is particular field value keep increasing day by day. I want to set watcher/alert if it exceeds particular number. Can this be done and where can i find syntax for the same. Any help really appreciate.
Thanks. 
![kibanaforlaert](https://user-images.githubusercontent.com/36020013/35657378-09a22290-06b1-11e8-8549-11d0996601d6.png)

**Comment by lmangani** [comment]
Hi @shah83 this should be easily achievable with SENTINL. You can check out this [presentation](https://www.slideshare.net/secret/gobTp9S3omqn9a) which should hopefully answer some of your questions. You can create a SENTINL Watcher from your existing visualization using the SPY Component as a starting point, too.

I hope this helps!

**Comment by shah83** [comment]
Thanks it helped.
