### ISSUE TITLE
use nginx proxy two kibana, sentinl send two action,how to do?

### ISSUE THREAD

**Issue by taoyantu** [sirensolutions/sentinl#302]
i have a difficult question ,i use nginx proxy to two kibana , all kibana install sentinl ,when trigger alarm,the two kibana do the action ,so i have receive two email .
how to slove it problem , it is very worried .

thanks every one!

**Comment by lmangani** [comment]
SENTINL should only run once per ES cluster, not on each Kibana instance - particularly if the two are connected to the same ES server(s). Future versions might bring this ability, but currently this is only available in the Siren stack. Hope this helps.
