### ISSUE TITLE
Watcher got re-scheduled every 30 seconds

### ISSUE THREAD

**Issue by mxj4** [sirensolutions/sentinl#303]
1. Issue Description

On Sentinl git tag-5.6.2, Watchers got cleared then re-scheduled every 30 seconds, then I cannot configure watchers with intervals longer than 30 seconds.

2. Reproducing the Issue step-by-step

Copy an existing watcher and create a new one (change id, version, etc.), enable it.

3. Expected Results vs. Actual Results

There should be no "Clearing watcher..." logs from Kibana, but I see:
```
{"type":"log","@timestamp":"2018-02-06T20:25:26Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"Clearing watcher: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm"}
{"type":"log","@timestamp":"2018-02-06T20:25:26Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"server.sentinlStore.scheduled Watch: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm every every 24 hours"}
{"type":"log","@timestamp":"2018-02-06T20:25:56Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"Clearing watcher: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm"}
{"type":"log","@timestamp":"2018-02-06T20:25:56Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"server.sentinlStore.scheduled Watch: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm every every 24 hours"}
{"type":"log","@timestamp":"2018-02-06T20:26:26Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"Clearing watcher: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm"}
{"type":"log","@timestamp":"2018-02-06T20:26:26Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"server.sentinlStore.scheduled Watch: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm every every 24 hours"}
{"type":"log","@timestamp":"2018-02-06T20:26:56Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"Clearing watcher: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm"}
{"type":"log","@timestamp":"2018-02-06T20:26:56Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"server.sentinlStore.scheduled Watch: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm every every 24 hours"}
{"type":"log","@timestamp":"2018-02-06T20:27:26Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"Clearing watcher: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm"}
{"type":"log","@timestamp":"2018-02-06T20:27:26Z","tags":["status","info","Sentinl","scheduler"],"pid":8424,"message":"server.sentinlStore.scheduled Watch: ryq74ifgewq-nbcrq20ftxm-tet6371mcvm every every 24 hours"}
```
4. Additional Details

kibana config:
```
server.host: localhost
server.maxPayloadBytes: 40960000

elasticsearch.url: "http://localhost:9200"
elasticsearch.requestTimeout: 300000

sentinl:
  settings:
    email:
      active: true
      host: localhost
      ssl: false
    report:
      active: true
      tmp_path: /tmp/

```
watcher:
```
{
  "_index": "watcher",
  "_type": "sentinl-watcher",
  "_id": "ryq74ifgewq-nbcrq20ftxm-tet6371mcvm",
  "_version": 2,
  "found": true,
  "_source": {
    "title": "<REDACTED>",
    "disable": false,
    "report": false,
    "trigger": {
      "schedule": {
        "later": "every 24 hours"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "<REDACTED>"
          ],
          "body": {
            "query": { "term": "<REDACTED>" }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 0"
      }
    },
    "actions": {
      "<REDACTED>": {
        "throttle_period": "0h1m0s",
        "email": {
          "to": "<REDACTED>",
          "from": "<REDACTED>",
          "subject": "<REDACTED>",
          "priority": "high",
          "body": "<REDACTED>",
          "stateless": false
        }
      }
    }
  }
}
```

**Comment by mxj4** [comment]
I checked the source code and it seems it is by design to clear later schedule every 30 seconds, the problem with my config is `later` [does not recognize `every 24 hours`](https://github.com/bunkat/later/issues/149), you have to use `every 1 day`!
During my test I also tried `at 12:00 am` and it still not working, then I found `later` [will parse `at 12:00 am` to 12:00 pm](https://github.com/bunkat/later/pull/188)!

There should be something in the wiki to warn user those `later` pitfalls and sentinl should improve the UI to make it harder for people to set "invalid schedules" to `later`.

**Comment by lmangani** [comment]
@mxj4 there is no clear every 30 seconds - there is a "refresh" every 25 which either schedules or removes outdated watchers. The issues seems to be with the way you are provisioning or naming them, I suspect. In terms of the `later.js` details, those belong into the project wiki of `later.js` and since the syntax is a text parser, it would be less than ideal to parse the parser for error - we prefer transparency and letting users like you get familiar with the true language behind scheduling time. Hope this helps!


@sergibondarenko could you confirm if the above behaviour is replicable? I couldn't so far.

**Comment by mxj4** [comment]
I created watchers by modify `_id` in `raw` tab, check `enable`, then save.

For `later.js`, the `every 24 hours` text is generated through sentinl UI, in the time picker there is no way to select days, so most user would try `24 hours`, I think that's something sentnl should fix.

**Comment by lmangani** [comment]
AFAIK ```every 24 hours ``` worked just fine - will recheck and confirm

**Comment by mxj4** [comment]
In the later issue I referenced, `every 24 hours` only fails on specific dates. In later.js wiki, they said they only support hour from 0 to 23.

**Comment by lmangani** [comment]
Mistery solved, thanks for confirming this is the case then - the only option would be to "validate" that field against the later.js parser before accepting it

**Comment by jccq** [comment]
Lorenzo having a confirmation that later.js understood our intent was the idea behind the feature to show when the "next invocation" was going to happen

maybe we should power that up and make "next invocations" with a list of next invocations e.g. 10/2 1:30  11/2 1:30  etc..   like a list of the next 10 ..  to make it even more clear if the system worked or not

**Comment by lmangani** [comment]
@jccq this is part of the basic Gun extension, so it'll land when Gun does. Definitely covers this.

**Comment by lmangani** [comment]
Latest versions will display the "next" scheduled time to confirm the Later.JS expected results. Let us know if this is still causing issues and thanks for your report!
