### ISSUE TITLE
Need some help with Watcher

### ISSUE THREAD

**Issue by yuanhaocui** [sirensolutions/sentinl#304]
I got a error like this when execute a new Watcher:
Sentinl Watchers: Error 406 Not Acceptable: Not Acceptable

My transfrom looks like this:

> "transform": {
      "script": {
        "script": "payload.errorCount=0;payload.hits.hits.forEach(function(){if(_source.error>0) {errorCount+=1;}});"
      }
    }

Here is the first lines of my query including the first record in the array:

> {
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 36,
    "max_score": null,
    "hits": [
      {
        "_index": "dw_acquisition",
        "_type": "fluentd",
        "_id": "AWFx-kWnGYqzt-ibnH1K",
        "_version": 1,
        "_score": null,
        "_source": {
          "content": """{"total":8557,"startTime":1518035596210,"timeConsuming":44853,"error":0,"sourceName":"IdentityGetInsuranceV2","endTime":1518035641063,"success":8557}""",
          "hostname": "10.149.80.105",
          "total": 8557,
          "startTime": 1518035596210,
          "timeConsuming": 44853,
          "error": 0,
          "sourceName": "IdentityGetInsuranceV2",
          "endTime": 1518035641063,
          "success": 8557
        },
        "fields": {
          "startTime": [
            1518035596210
          ],
          "endTime": [
            1518035641063
          ]
        },
        "sort": [
          8557
        ]
      },

I am sorry for the likely silly questions, I am very new to lucene. 
And I'm not good at English.
Your help is greatly appreciated

**Comment by lmangani** [comment]
What version of ELK and SENTINL are you using? This is likely not the problem but your JS script seems potentially wrong, too - perhaps ```"payload.errorCount=0;payload.hits.hits.forEach(function(hit){if(hit._source.error>0) {payload.errorCount+=1;}});"```

**Comment by yuanhaocui** [comment]
Hi @lmangani . 
I used your JS script and it worked perfectly!  Thank you very much! 
Now I got into a new trouble. T T
What should I do if I want to change the content's font color when error > 0?

**Comment by lmangani** [comment]
Great! If you want to change the output, you need to work HTML inside of your message. See examples ;)

**Comment by agarwalshivam456** [comment]
@lmangani Can you please help me here as i'm also getting 406 error in kibana.stdout.

{"type":"response","@timestamp":"2018-03-07T07:09:55Z","tags":[],"pid":22785,"method":"post","statusCode":406,"req":{"url":"/api/sentinl/watcher/_execute","method":"post","headers":{"connection":"upgrade","host":"kibana.nlpcaptcha.in","content-length":"1288","accept":"application/json, text/plain, */*","origin":"http://kibana.nlpcaptcha.in","kbn-version":"6.2.1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","content-type":"application/json;charset=UTF-8","referer":"http://kibana.nlpcaptcha.in/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://kibana.nlpcaptcha.in/app/sentinl"},"res":{"statusCode":406,"responseTime":4,"contentLength":9},"message":"POST /api/sentinl/watcher/_execute 406 4ms - 9.0B"}
