### ISSUE TITLE
Can't use object from payload array in email body

### ISSUE THREAD

**Issue by higef** [sirensolutions/sentinl#306]
My watcher generating following document https://hastebin.com/adaqobebej.json Required fields in payload:
      "aggregations": {
        "uniqe_name": {
          "doc_count_error_upper_bound": 0,
          "sum_other_doc_count": 0,
          "buckets": [
            {
              "key": "callCenterNameUnknown",
              "doc_count": 8
            }
          ]
        }
      }
Issue is I can't pass value of {{payload.aggregations.uniqe_name.buckets.key.keyword}} to email body even though I can query this values afterwards. Any way to pass object of array to message body?

**Comment by lmangani** [comment]
Please show your actual SENTINL watcher configuration and its output here to get suggestions and assistance - thanks!

**Comment by lmangani** [comment]
I took a peek - you didn't study your mustache, have you? :)
```
{{#payload.aggregations.uniqe_name.buckets}} 
     {{doc_count}} 
{{/payload.aggregations.uniqe_name.buckets}}
```

**Comment by higef** [comment]
Yeah, I missed that. Thank you for quick response

**Comment by lmangani** [comment]
No problem, happy to help and hope this gets you going ;)
