### ISSUE TITLE
Incorrectly labeled version of sentinl plugin

### ISSUE THREAD

**Issue by mmolinac** [sirensolutions/sentinl#308]
1. Issue Description

The version 5.6.5 of sentinl plugin is incorrectly reported as 5.6.4-SNAPSHOT after installed.

2. Reproducing the Issue step-by-step

I install version 5.6.5 of Sentinl plugin with the following command:

    /usr/share/kibana/bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.6.2/sentinl-v5.6.5.zip

3. Expected Results vs. Actual Results

After the installation, it is expected something like this:

````
$ /usr/share/kibana/bin/kibana-plugin list
sentinl@5.6.5
````

But instead I've got:

````
$ /usr/share/kibana/bin/kibana-plugin list
sentinl@5.6.4-SNAPSHOT
````

This is the same output as if I were to install version 5.6.4

4. Additional Details

As I said, I installed version 5.6.4, and the version reported is exactly the same.
May be a typo or a forgotten label somewhere, I suppose.

**Comment by lmangani** [comment]
Hi @mmolinac certain releases actually root to the same codebase whenever compatible across Kibana releases (a nightmare for us) - so this might be one such case here. Is your version actually running? In other version, is the difference purely cosmetic?

Thanks!

**Comment by mmolinac** [comment]
Hi @lmangani ,
Yes, my version is running and yes, the difference is purely cosmetic.
I was trying to automate the installation with Ansible, and the recipe found that the version reported wasn't the version asked during the installation, so that was the problem.
Now that I know the problems you're dealing with, I'll install 5.6.4 and I'll stick to that until we're able to upgrade.
Thanks for the explanation!
