### ISSUE TITLE
Invalid schedule for .recur().every(360).second()

### ISSUE THREAD

**Issue by aviranco** [sirensolutions/sentinl#309]
every X that is higher than 60 produces an invalid schedule. 

For example: later.parse.recur().every(360).second() 

Produces:
{
    "schedules": [
        {
            "s": [
                0
            ]
        }
    ],
    "exceptions": []
}

which is every 1 minute instead of every 5 minutes.

**Comment by lmangani** [comment]
Hi @aviranco as you might as discovered, laterjs is a little stricter than we'd all like when exceeding a type's max....
