### ISSUE TITLE
Grunt dependency?

### ISSUE THREAD

**Issue by ebuildy** [sirensolutions/sentinl#313]
1. Issue Description

Running test ``gulp test`` gives the error: ``Fatal error: Unable to find local grunt.``

2. Reproducing the Issue step-by-step

After install, run ``gulp test``

3. Expected Results vs. Actual Results

This should run test

4. Additional Details

**Comment by sergibondarenko** [comment]
@ebuildy this should work:
1. `cd sentinl`
2. `npm install`
3. `gulp testbrowser --kibanahomepath=path/to/kibana`
4. `gulp testserver --kibanahomepath=path/to/kibana`

Please reopen the issue if it doesn't work.

**Comment by ebuildy** [comment]
Ho I see, it's using Kibana grunt. Thanks you.
