### ISSUE TITLE
Refactor phantomJS code?

### ISSUE THREAD

**Issue by ebuildy** [sirensolutions/sentinl#318]
1. Sentinl and Kibana version 

Latest version 6.x

2. Issue description

PhantomJS binaries are packaged inside the build, this makes the zip file size = 100Mo! Hard to release.

Also, the project https://github.com/johntitus/node-horseman is no longer supported.

I am wondering if this part of Sentinl will be refactored?

**Comment by lmangani** [comment]
Hi @ebuildy thanks for the feedback. Where would you need to release other than our provided builds
This is/was pretty much the same way the "other" watcher package is distributed to support multiple platforms with no user installation and help the lower-end. You can most definitely build a "naked" SENTINL and as long as PhantomJS is on the system it should work fine. 

The plan is to switch from PhantomJS to Puppeteer but its a tedious task low in priority which might still be months away unless some brave soul steps in the help. Any PR is welcome! ;)
