### ISSUE TITLE
Can the value of "sentinl.settings.email.password" be encrypted

### ISSUE THREAD

**Issue by ahrtr** [sirensolutions/sentinl#320]
You know, a user/password needs to be configured for the email action. I don't think it's good to put the plain text into kibana.yaml, is it possible to encrypt the password? 

> sentinl:
>   settings:
>     email:
>       active: true
>       user: smtp_username
>       password: smtp_password
>       host: smtp.server.com

**Comment by fbaligand** [comment]
As every setting in kibana.yml, you can use kibana keystore to encrypt particular settings. 
It is a new feature in kibana 6.1

**Comment by ahrtr** [comment]
Thanks for the feedback.  The reason why I choose sentinl is that I want to discard X-Pack, but my understanding is that all security related features including the keystore tool are provided by the X-Pack extension. So I have to find some other solution to fix this.  Any suggestions?

Since sentinal 6.x haven't been released yet, so I have to deploy sentinl 5.6.5 with ES/Kibana 5.6.5 for now.  I tested the sentinl alert feature together with ES/Kibana today, and confirmed that it worked. 
But the X-Pack extension is included in ES/Kibana 5.6.5 docker images by default, and I am planning to use the ES/Kibana oss docker images, which do not contain X-Pack at all. So I am a little concerned whether the sentinl 6.x (not released yet) can work with ES/Kibana OSS 6.x, i.e, the alert. Can you please provide comments on this?

**Comment by lmangani** [comment]
Short answer: yes, eventually it will but this is not our primary agenda. If you take time to look you'll see there are already test versions for 6.x from users, and @sergibondarenko from our team is also drafting a 6.2 release ready to latch all new features - but remember this is Open-Source, you'll have to get your hands dirty ;)

**Comment by fbaligand** [comment]
The kibana keystore is a free and open source feature. It is included in kibana core, not in x-pack.

**Comment by lmangani** [comment]
@fbaligand maybe we can add a wiki entry with the basics if you do have an decent example I can use?

**Comment by fbaligand** [comment]
Well, I have nothing more to explain than official kibana doc on keystore feature :
https://www.elastic.co/guide/en/kibana/current/secure-settings.html

**Comment by fbaligand** [comment]
So the command should be :
bin/kibana-keystore create
bin/kibana-keystore add sentinl.settings.email.password

**Comment by lmangani** [comment]
Spot on, thanks @fbaligand - I will add this to the FAQ

**Comment by fbaligand** [comment]
You’re welcome :)

**Comment by ahrtr** [comment]
@fbaligand @lmangani , thanks. 

I just confirmed that the kibana-keystore is included in the kibana-oss 6.1.3 and 6.2.2.
