### ISSUE TITLE
"No valid url specified" when installing 6.2.1 package

### ISSUE THREAD

**Issue by yabir** [sirensolutions/sentinl#324]
**Kibana version** : 6.2.1

**Issue description**

When i try to install the Sentinl Kibana plugin , it returns this message:

> Plugin installation was unsuccessful due to error "No valid url specified."

**Reproducing the issue step-by-step**

following your README installation step: 
```bash
bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.1/sentinl-v6.2.1.zip
```
this is the log it returns with the error at the end:
> Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.1/sentinl-v6.2.1.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.1/sentinl-v6.2.1.zip/https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.1/sentinl-v6.2.1.zip-6.2.1.zip
Plugin installation was unsuccessful due to error "No valid url specified."

Any Ideas?

**Comment by lmangani** [comment]
Hi @yabir - does it make a difference if you download the archive and install it locally?

**Comment by fbaligand** [comment]
It seems that your link is wrong. Here’s the right link : 
https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.2/sentinl-v6.2.1.zip

**Comment by lmangani** [comment]
The link in the readme seems fine... @yabir where did you take that from? I'll correct the example.

**Comment by fbaligand** [comment]
Yes, only the last one must be changed.
The tag name is ambiguous. 
@lmangani, ideally, the tag name should reference a sentinl version, rather than a kibana version. What you think ?

**Comment by lmangani** [comment]
Good point, although the tag reveals the "actual codebase" shared by those releases, this has no value to regular users installing. 

Maybe we can generalize it, ie tag:`6` and releases ` 6.x.x` under it @sergibondarenko

**Comment by fbaligand** [comment]
There are different ways to do, each with its pros/cons.

Personally, I make a tag per plugin version, where I publish the different packages for the different Kibana versions : 
https://github.com/fbaligand/kibana-enhanced-table/releases
