### ISSUE TITLE
"Editor: notify.info is not a function"

### ISSUE THREAD

**Issue by ebuildy** [sirensolutions/sentinl#325]
1. Sentinl and Kibana version 

6.2.2

2. Issue description

It seem Kibana notify object does not support the level "info" any more:

![](https://beemapp2.s3.amazonaws.com/a48a532f-a005-4e5f-ae48-a1b060ca9894.jpg)

3. Reproducing the issue step-by-step

Saving a watcher

4. Expected results vs. actual results

Notification should appear instead of this error.

5. Sample of data

6. Additional details

Use ``banner`` instead of ``info``?

**Comment by lmangani** [comment]
Thanks @ebuildy for catching this - we'll get it fixed right next

**Comment by sergibondarenko** [comment]
Hi @ebuildy.
Did you get Sentinl from [the latest release](https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.2) that was published on March 2? I can't reproduce the issue. Let me know.

**Comment by ebuildy** [comment]
You are right, I was testing against Kibana 6.2.3 (they are moving so fast :/)

Thanks you,
