### ISSUE TITLE
Post installation Not showing anything 

### ISSUE THREAD

**Issue by agarwalshivam456** [sirensolutions/sentinl#326]
Issue description

Post installed sentinl ,It showing no watcher.
Please find screenshot.
![kibana](https://user-images.githubusercontent.com/22490622/36973506-4bd82342-2099-11e8-8890-5d84226b6e75.png)

Step to performed install sentinl:
1. root@elasticsearch /usr/share/kibana/plugins # ./kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.2/sentinl-v6.2.1.zip
2. restart kibana

kibana version: 6.2.1

**Comment by lmangani** [comment]
@agarwalshivam456 by default there will be exactly no watchers but I see the issue here seems all replacements are missing, including dates and parameters. Could you check your Kibana logs for errors?

**Comment by agarwalshivam456** [comment]
Resolved.
I was installing snapshot plugin.

Post installation of Gulp plugin ,It's working normally.

However I found that installation guide is not mentioned properly. Please mention proper steps to install it.

**Comment by Amorik** [comment]
@agarwalshivam456  did you do anything specific? I've attempted to install following the gulp directions but am having the same result.

**Comment by agarwalshivam456** [comment]
**Install Sentinl:**

1. git clone https://github.com/sirensolutions/sentinl
2. cd sentinl
3. Install NPM
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
apt-get install nodejs
4. Install below dependencies:
npm install -g gulp
npm link gulp
npm install -g lodash --save
npm link lodash
npm install -g mkdirp --save
npm link mkdirp
npm install -g rsync --save
npm link rsync
npm install -g bluebird --save
npm link bluebird
npm install -g gulp-eslint --save
npm link gulp-eslint
npm install -g rimraf --save
npm link rimraf
npm install -g gulp-zip --save
npm link gulp-zip
npm install -g minimist --save
npm link minimist
npm install -g gulp-util --save
npm link gulp-util
gulp package --version=6.2.1   #######Version must be same as kibana version######

./kibana-plugin install file:///root/sentinl/target/gulp/sentinl-v6.2.1.zip  #########(Run command under path : /usr/share/kibana/bin)###########

**Comment by agarwalshivam456** [comment]
@lmangani Do i have to install any other plugin apart from sentinl to configure threshold based alert.
Or we can create same from sentinl ?

**Comment by lmangani** [comment]
@agarwalshivam456 is there are a reason you are not using our ready packages? I would strongly suggest so - SENTINL does not have other requirements, its self standing when properly compiled.

**Comment by agarwalshivam456** [comment]
@lmangani what do you mean by ready packages?
You can see my steps to install sentinl in above comment. Am i missing something there?
As i don't find option to create threshold base alert in sentinl.

**Comment by lmangani** [comment]
The default example and template is for a treshold alert. You need to know what you're doing and check out the available documentation, mixing an installation and configuration issue is not going to help either. please start here: http://sentinl.readthedocs.io/en/latest/Watcher-Examples/

Presentation of generics: https://www.slideshare.net/secret/gobTp9S3omqn9a

**Comment by agarwalshivam456** [comment]
@lmangani Can you please help me out here. I am getting below error after created a watcher.
#######################################################
Error: fail to get watcher 7d806e96-4a3d-4be3-8a35-a0655484bab6
    at Watcher.<anonymous> (http://kibana.nlpcaptcha.in/bundles/sentinl.bundle.js?v=16573:1:268707)
    at tryCatch (http://kibana.nlpcaptcha.in/bundles/vendors.bundle.js?v=16573:70:99706)
    at Generator._invoke (http://kibana.nlpcaptcha.in/bundles/vendors.bundle.js?v=16573:70:101781)
    at Generator.prototype.(anonymous function) [as throw] (http://kibana.nlpcaptcha.in/bundles/vendors.bundle.js?v=16573:70:99990)
    at step (http://kibana.nlpcaptcha.in/bundles/sentinl.bundle.js?v=16573:1:264876)
    at http://kibana.nlpcaptcha.in/bundles/sentinl.bundle.js?v=16573:1:265037
    at <anonymous>
#########################################################

**Watcher Configuration:**

{
  "actions": {
    "email_admin": {
      "throttle_period": "0h15m0s",
      "email": {
        "to": "mail-id",
        "from": "mail-id",
        "subject": "Alarm",
        "priority": "high",
        "body": "DE Forntendservers Service failures {{ payload._id}}: Current Value {{ payload.hits.total }} [Threshold : 1]"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "indices": "indices-name",
        "body": {
          "size": 0,
          "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "code:500",
                  "analyze_wildcard": true
                }
              },
              "filter": {
                "range": {
                  "@timestamp": {
                    "from": "now-15m"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 1"
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 5 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "shivam watcher"
}
