### ISSUE TITLE
SentiNL not working on 6.2.1, documentation incorrect and lacking

### ISSUE THREAD

**Issue by Sjaak01** [sirensolutions/sentinl#330]
Hi,

I just installed SentiNL but its not working as its supposed to. I don't see a button or anything to start adding watches.

![image](https://user-images.githubusercontent.com/28028599/37133740-7cfb3a72-22d8-11e8-92c5-045ca261b5c4.png)

Also the documentation is incorrect.

- The path on the code page is incorrect.
- The docs page mentions the "main kibana yaml" file but doesn't bother giving a full path, leaving room for error.
http://sentinl.readthedocs.io/en/latest/Config-Example/
- It also says to add to the main kibana yaml but if you add the example code to the main kibana file you can be 100% sure kibana won't run.
- Docs in general aren't very detailed as far as I can tell from a quick look. For example the query dsl looks like elastic's but it doesn't say whether its actually the same as elastic's.

**Comment by sergibondarenko** [comment]
@Sjaak01 what do you see in the Kibana console? Do you see any error in your browser dev tools console?

**Comment by sergibondarenko** [comment]
@Sjaak01 I've just recorded a video about how to install Senitnl on Kibana 6.2.1 https://youtu.be/9UkuC6xzhxA

**Comment by sergibondarenko** [comment]
@Sjaak01 install it like it is done in the video. Please reopen the issue if you can't install and attach logs.

**Comment by Sjaak01** [comment]
I'm still getting the same as in my original screenshot. 

 

>  log   [23:53:31.998] [debug][plugin] Found plugin at /usr/share/kibana/plugins/sentinl
>   log   [23:53:32.006] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/console
>   log   [23:53:32.008] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/elasticsearch
>   log   [23:53:32.008] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/input_control_vis
>   log   [23:53:32.009] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/kbn_doc_views
>   log   [23:53:32.010] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/kbn_vislib_vis_types
>   log   [23:53:32.014] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/kibana
>   log   [23:53:32.015] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/markdown_vis
>   log   [23:53:32.016] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/metric_vis
>   log   [23:53:32.016] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/metrics
>   log   [23:53:32.017] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/region_map
>   log   [23:53:32.018] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/spy_modes
>   log   [23:53:32.018] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/state_session_storage_redirect
>   log   [23:53:32.019] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/status_page
>   log   [23:53:32.020] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/table_vis
>   log   [23:53:32.022] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/tagcloud
>   log   [23:53:32.023] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/tile_map
>   log   [23:53:32.025] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/timelion
>   log   [23:53:32.025] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/vega
>   log   [23:53:32.531] [debug][optimize] All bundles are cached and ready to go!
>   log   [23:53:32.542] [debug][plugins] Initializing plugin input_control_vis@kibana
>   log   [23:53:32.544] [debug][plugins] Initializing plugin kbn_doc_views@kibana
>   log   [23:53:32.545] [debug][plugins] Initializing plugin kbn_vislib_vis_types@kibana
>   log   [23:53:32.547] [debug][plugins] Initializing plugin markdown_vis@kibana
>   log   [23:53:32.549] [debug][plugins] Initializing plugin metric_vis@kibana
>   log   [23:53:32.550] [debug][plugins] Initializing plugin region_map@kibana
>   log   [23:53:32.552] [debug][plugins] Initializing plugin spy_modes@kibana
>   log   [23:53:32.555] [debug][plugins] Initializing plugin state_session_storage_redirect@kibana
>   log   [23:53:32.557] [debug][plugins] Initializing plugin status_page@kibana
>   log   [23:53:32.558] [debug][plugins] Initializing plugin table_vis@kibana
>   log   [23:53:32.560] [debug][plugins] Initializing plugin tagcloud@kibana
>   log   [23:53:32.562] [debug][plugins] Initializing plugin tile_map@kibana
>   log   [23:53:32.565] [debug][plugins] Initializing plugin kibana@kibana
>   log   [23:53:32.634] [info][status][plugin:kibana@6.2.1] Status changed from uninitialized to green - Ready
>   log   [23:53:32.639] [debug][plugins] Initializing plugin elasticsearch@kibana
>   log   [23:53:32.674] [info][status][plugin:elasticsearch@6.2.1] Status changed from uninitialized to yellow - Waiting for                                                                                Elasticsearch
>   log   [23:53:32.675] [debug][plugins] Initializing plugin timelion@kibana
>   log   [23:53:32.793] [info][status][plugin:timelion@6.2.1] Status changed from uninitialized to green - Ready
>   log   [23:53:32.794] [debug][plugins] Initializing plugin sentinl@6.0.0
>   log   [23:53:32.796] [info][status][plugin:sentinl@6.0.0] Status changed from uninitialized to green - Ready
>   log   [23:53:32.797] [debug][plugins] Initializing plugin console@kibana
>   log   [23:53:32.801] [info][status][plugin:console@6.2.1] Status changed from uninitialized to green - Ready
>   log   [23:53:32.802] [debug][plugins] Initializing plugin metrics@kibana
>   log   [23:53:32.805] [info][status][plugin:metrics@6.2.1] Status changed from uninitialized to green - Ready
>   log   [23:53:32.807] [debug][plugins] Initializing plugin vega@kibana
>   log   [23:53:32.823] [info][listening] Server running at http://0.0.0.0:5601
>   log   [23:53:32.825] [server][uuid][uuid] Resuming persistent Kibana instance UUID: c3da351c-e7cf-489a-a63e-4b0b03321da6
>   log   [23:53:32.834] [debug][plugin] Checking Elasticsearch version
>   log   [23:53:32.845] [info][status][plugin:elasticsearch@6.2.1] Status changed from yellow to green - Ready
>   log   [23:53:32.847] [info][Sentinl][init] initializing ...
>   log   [23:53:32.851] [debug][Sentinl][get_elasticsearch_client] auth via Kibana server elasticseaarch plugin
>   log   [23:53:32.862] [info][Sentinl][init_indices] checking watcher_alarms index ...
>   log   [23:53:32.862] [debug][Sentinl][get_elasticsearch_client] auth via Kibana server elasticseaarch plugin
>   log   [23:53:32.870] [debug][Sentinl][init_indices] index watcher_alarms exists
>   ops   [23:53:41.971]  memory: 67.5MB uptime: 0:00:12 load: [0.32 0.10 0.03] delay: 59.607
>   log   [23:53:41.980] [debug][plugin] Checking Elasticsearch version
>   log   [23:53:42.035] [info][Sentinl][init] phantom installed at /usr/share/kibana/plugins/sentinl/phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
>   log   [23:53:44.517] [debug][plugin] Checking Elasticsearch version
>   ops   [23:53:46.915]  memory: 67.4MB uptime: 0:00:17 load: [0.30 0.09 0.02] delay: 0.338
>   log   [23:53:47.023] [debug][plugin] Checking Elasticsearch version
>   log   [23:53:49.530] [debug][plugin] Checking Elasticsearch version
>   ops   [23:53:51.918]  memory: 67.3MB uptime: 0:00:22 load: [0.27 0.09 0.02] delay: 0.208
>   log   [23:53:52.036] [debug][plugin] Checking Elasticsearch version
>   log   [23:53:54.547] [debug][plugin] Checking Elasticsearch version
>   log   [23:53:55.867] [debug][Sentinl][scheduler] cluster disabled
>   log   [23:53:55.868] [debug][Sentinl][scheduler] reloading watchers...
>   log   [23:53:55.868] [debug][Sentinl][scheduler] auth enabled: false
>   log   [23:53:55.869] [debug][Sentinl][get_elasticsearch_client] auth via Kibana server elasticseaarch plugin
>   log   [23:53:55.880] [debug][Sentinl][scheduler] no watchers found
>   ops   [23:53:56.969]  memory: 68.6MB uptime: 0:00:27 load: [0.25 0.09 0.02] delay: 48.591
>   log   [23:53:57.052] [debug][plugin] Checking Elasticsearch version
>   log   [23:53:59.562] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:01.923]  memory: 67.6MB uptime: 0:00:32 load: [0.23 0.09 0.02] delay: 0.197
>   log   [23:54:02.068] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:04.603] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:06.926]  memory: 65.9MB uptime: 0:00:37 load: [0.21 0.09 0.02] delay: 0.188
>   log   [23:54:07.158] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:09.669] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:11.927]  memory: 65.9MB uptime: 0:00:42 load: [0.19 0.08 0.02] delay: 0.171
>   log   [23:54:12.178] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:14.697] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:16.930]  memory: 65.3MB uptime: 0:00:47 load: [0.18 0.08 0.02] delay: 0.402
>   log   [23:54:17.202] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:19.713] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:21.932]  memory: 65.3MB uptime: 0:00:52 load: [0.16 0.08 0.02] delay: 0.138
>   log   [23:54:22.220] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:24.726] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:25.873] [debug][Sentinl][scheduler] cluster disabled
>   log   [23:54:25.873] [debug][Sentinl][scheduler] reloading watchers...
>   log   [23:54:25.874] [debug][Sentinl][scheduler] auth enabled: false
>   log   [23:54:25.874] [debug][Sentinl][get_elasticsearch_client] auth via Kibana server elasticseaarch plugin
>   log   [23:54:25.878] [debug][Sentinl][scheduler] no watchers found
>   ops   [23:54:26.934]  memory: 65.5MB uptime: 0:00:57 load: [0.23 0.10 0.03] delay: 0.176
>   log   [23:54:27.233] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:29.740] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:31.936]  memory: 65.3MB uptime: 0:01:02 load: [0.21 0.10 0.03] delay: 0.160
>   log   [23:54:32.247] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:34.752] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:36.939]  memory: 65.2MB uptime: 0:01:07 load: [0.20 0.09 0.03] delay: 0.154
>   log   [23:54:37.260] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:39.767] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:41.940]  memory: 66.0MB uptime: 0:01:12 load: [0.18 0.09 0.03] delay: 0.143
>   log   [23:54:42.272] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:44.781] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:46.942]  memory: 65.9MB uptime: 0:01:17 load: [0.17 0.09 0.02] delay: 0.181
>   log   [23:54:47.288] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:49.796] [debug][plugin] Checking Elasticsearch version
>   ops   [23:54:51.945]  memory: 65.8MB uptime: 0:01:22 load: [0.15 0.09 0.02] delay: 0.149
>   log   [23:54:52.304] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:54.807] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:55.875] [debug][Sentinl][scheduler] cluster disabled
>   log   [23:54:55.876] [debug][Sentinl][scheduler] reloading watchers...
>   log   [23:54:55.876] [debug][Sentinl][scheduler] auth enabled: false
>   log   [23:54:55.877] [debug][Sentinl][get_elasticsearch_client] auth via Kibana server elasticseaarch plugin
>   log   [23:54:55.881] [debug][Sentinl][scheduler] no watchers found
>   ops   [23:54:56.946]  memory: 65.8MB uptime: 0:01:27 load: [0.14 0.09 0.02] delay: 0.198
>   log   [23:54:57.313] [debug][plugin] Checking Elasticsearch version
>   log   [23:54:59.822] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:01.947]  memory: 66.8MB uptime: 0:01:32 load: [0.13 0.08 0.02] delay: 0.166
>   log   [23:55:02.341] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:04.846] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:06.948]  memory: 66.6MB uptime: 0:01:37 load: [0.12 0.08 0.02] delay: 0.157
>   log   [23:55:07.352] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:09.859] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:11.949]  memory: 66.5MB uptime: 0:01:42 load: [0.11 0.08 0.02] delay: 0.148
>   log   [23:55:12.363] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:14.869] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:16.951]  memory: 66.4MB uptime: 0:01:47 load: [0.10 0.08 0.02] delay: 0.170
>   log   [23:55:17.375] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:19.883] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:21.953]  memory: 67.1MB uptime: 0:01:52 load: [0.09 0.08 0.02] delay: 0.159
>   log   [23:55:22.389] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:24.894] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:25.879] [debug][Sentinl][scheduler] cluster disabled
>   log   [23:55:25.879] [debug][Sentinl][scheduler] reloading watchers...
>   log   [23:55:25.879] [debug][Sentinl][scheduler] auth enabled: false
>   log   [23:55:25.880] [debug][Sentinl][get_elasticsearch_client] auth via Kibana server elasticseaarch plugin
>   log   [23:55:25.883] [debug][Sentinl][scheduler] no watchers found
>   ops   [23:55:26.955]  memory: 67.1MB uptime: 0:01:57 load: [0.16 0.09 0.03] delay: 0.179
>   log   [23:55:27.400] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:29.907] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:31.957]  memory: 67.1MB uptime: 0:02:02 load: [0.15 0.09 0.03] delay: 0.159
>   log   [23:55:32.411] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:34.916] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:36.959]  memory: 67.0MB uptime: 0:02:07 load: [0.14 0.09 0.03] delay: 0.169
>   log   [23:55:37.423] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:39.931] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:41.960]  memory: 66.9MB uptime: 0:02:12 load: [0.13 0.09 0.03] delay: 0.153
>   log   [23:55:42.440] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:44.947] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:46.962]  memory: 67.6MB uptime: 0:02:17 load: [0.12 0.09 0.02] delay: 0.159
>   log   [23:55:47.451] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:49.960] [debug][plugin] Checking Elasticsearch version
>   ops   [23:55:51.964]  memory: 67.5MB uptime: 0:02:22 load: [0.11 0.09 0.02] delay: 0.152
>   log   [23:55:52.465] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:54.968] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:55.881] [debug][Sentinl][scheduler] cluster disabled
>   log   [23:55:55.881] [debug][Sentinl][scheduler] reloading watchers...
>   log   [23:55:55.881] [debug][Sentinl][scheduler] auth enabled: false
>   log   [23:55:55.882] [debug][Sentinl][get_elasticsearch_client] auth via Kibana server elasticseaarch plugin
>   log   [23:55:55.885] [debug][Sentinl][scheduler] no watchers found
>   ops   [23:55:56.966]  memory: 67.6MB uptime: 0:02:27 load: [0.10 0.08 0.02] delay: 0.156
>   log   [23:55:57.474] [debug][plugin] Checking Elasticsearch version
>   log   [23:55:59.981] [debug][plugin] Checking Elasticsearch version
>   ops   [23:56:01.968]  memory: 67.5MB uptime: 0:02:32 load: [0.09 0.08 0.02] delay: 0.173
>   log   [23:56:02.485] [debug][plugin] Checking Elasticsearch version
> respons [23:56:02.911]  GET /app/sentinl 200 207ms - 9.0B
> respons [23:56:03.679]  GET /bundles/vendors.style.css?v=16573 304 10ms - 9.0B
> respons [23:56:03.676]  GET /bundles/vendors.bundle.js?v=16573 304 27ms - 9.0B
> respons [23:56:03.895]  GET /bundles/sentinl.style.css?v=16573 304 4ms - 9.0B
> respons [23:56:03.896]  GET /bundles/commons.style.css?v=16573 304 7ms - 9.0B
> respons [23:56:04.110]  GET /bundles/commons.bundle.js?v=16573 304 7ms - 9.0B
> respons [23:56:04.334]  GET /ui/favicons/favicon-16x16.png 304 5ms - 9.0B
> respons [23:56:04.335]  GET /ui/favicons/apple-touch-icon.png 304 6ms - 9.0B
> respons [23:56:04.415]  GET /bundles/sentinl.bundle.js?v=16573 304 4ms - 9.0B
>   log   [23:56:04.990] [debug][plugin] Checking Elasticsearch version
> respons [23:56:05.411]  GET /plugins/kibana/assets/visualize.svg 304 6ms - 9.0B
> respons [23:56:05.411]  GET /plugins/kibana/assets/discover.svg 304 8ms - 9.0B
> respons [23:56:05.412]  GET /plugins/sentinl/style/sentinl.svg 304 8ms - 9.0B
> respons [23:56:05.414]  GET /plugins/timelion/icon.svg 304 8ms - 9.0B
> respons [23:56:05.414]  GET /plugins/kibana/assets/dashboard.svg 304 9ms - 9.0B
> respons [23:56:05.415]  GET /plugins/kibana/assets/wrench.svg 304 11ms - 9.0B
> respons [23:56:05.762]  GET /api/sentinl/time 200 2ms - 9.0B
> respons [23:56:05.768]  GET /plugins/kibana/assets/settings.svg 304 1ms - 9.0B
> respons [23:56:05.769]  GET /bundles/ebdca7741674eca4e1fadeca157f3ae6.svg 304 2ms - 9.0B
> respons [23:56:05.770]  GET /plugins/kibana/assets/play-circle.svg 304 4ms - 9.0B
> respons [23:56:06.508]  GET /api/sentinl/config 200 2ms - 9.0B
>   ops   [23:56:06.973]  memory: 76.3MB uptime: 0:02:37 load: [0.08 0.08 0.02] delay: 0.479
> respons [23:56:07.159]  GET /api/saved_objects/?type=sentinl-watcher&per_page=50&page=1&search_fields=title%5E3&search_fields=description 200 10ms - 9.0B
>   log   [23:56:07.496] [debug][plugin] Checking Elasticsearch version
>   log   [23:56:10.059] [debug][plugin] Checking Elasticsearch version
>   ops   [23:56:11.975]  memory: 72.0MB uptime: 0:02:42 load: [0.08 0.08 0.02] delay: 0.269
>   log   [23:56:12.573] [debug][plugin] Checking Elasticsearch version
>   log   [23:56:15.081] [debug][plugin] Checking Elasticsearch version
>   ops   [23:56:16.977]  memory: 72.9MB uptime: 0:02:47 load: [0.07 0.08 0.02] delay: 0.202
>   log   [23:56:17.587] [debug][plugin] Checking Elasticsearch version
>   log   [23:56:20.093] [debug][plugin] Checking Elasticsearch version
>   ops   [23:56:21.979]  memory: 73.6MB uptime: 0:02:52 load: [0.06 0.08 0.02] delay: 0.207
>
