### ISSUE TITLE
Method to export and import watchers?

### ISSUE THREAD

**Issue by neelrana** [sirensolutions/sentinl#333]
Hello, I was wondering whether there is a way to export watchers created in one environment to another?

I have two different ELK stack environments running and I have set up watchers that trigger alerts on one of the environment but I was wondering whether there is a way to copy over those watchers onto a different environment? 

For example, I know that there is a way to export saved objects or index in elasticsearch but I am not sure if I can do that with the watchers.

Or would I have to copy and paste the code the watchers in the other environment?

Please let me know. Thank you in advance!

**Comment by lmangani** [comment]
Hi @neelrana SENTINL is saving everything to Elasticsearch, so its just a matter or copying data indices (corresponding to the configureg `default_index` parameter) between your stacks - you can do this with any tool generic or specific, nothing fancy needed - once watchers are copied, SENTINL should pick them up within seconds.

Hope this helps!

**Comment by neelrana** [comment]
Hi @lmangani , Thanks for the response. So I can just import the watcher index into the new environment? Do you know what the default index for the watchers is? is it '_watcher_alarms_' ?

**Comment by lmangani** [comment]
Yes, unless you changed it from the sentinl yaml config, that's where everything is set - It's easy to confirm so by exploring the index, the documents should look familiar.
