### ISSUE TITLE
Sentinl not initializing on 6.2.2, 6.1.3

### ISSUE THREAD

**Issue by nigellh** [sirensolutions/sentinl#337]
1. Sentinl and Kibana version 
Occurs on both 6.2.2 and 6.1.3, but not in 5.6.4

2. Issue description
![image](https://user-images.githubusercontent.com/12110404/37216449-aece133c-23b2-11e8-822e-bdd198736ee2.png)

I'm a newbie to much of this so this is seen just after bringing up a new system

3. Reproducing the issue step-by-step
Running on Ubuntu 16.04. Creating separate docker instand for each of Eleasticsearch, Kibana and Logstash.

For creating the Kibana instance use the following dockerfile

    FROM docker.elastic.co/kibana/kibana:6.1.3
    # NOTE: The Sentinl Plug-in must be the same version as the Kibana app or it will not install
    # So it is possible that the Kibana app might need to be down level.
    #
    
    ADD kibana.yml ./config/kibana.yml
    
    # Uninstall X-Pack
    RUN ./bin/kibana-plugin remove x-pack
    
    # Install Sentinl
    RUN ./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.2/sentinl-v6.1.3.zip

The kibana.yml replacement file is just the original with the X-Pack entry removed

I can wipe all existing date from previous runs (literally rm -Rf * the directories!)

Use docker-compose to bring all the containers up and they are all happily talking to each other. 

Go to the Kibana site and if I select Sentinl this is the top of the page that is displayed. 

Happy to provide more information if needed, hoping it is something simple!

4. Expected results vs. actual results
A proper screen that enables Sentinl to be configured

5. Sample of data
None needed to recreate

6. Additional details
None

**Comment by lmangani** [comment]
Hi @nigellh thanks for the report! Can you spot any `[sentinl]` rows in the Kibana logs?

**Comment by nigellh** [comment]
Apologies, I've had a quick look and cannot see the logs, there appears to be a comment that logs needs to be turned on for Kibana, trying to look it up, but thought I'd ask here as well. Late in the UK, not sure if I will get to look at it this evening, will try to.

**Comment by lmangani** [comment]
@nigellh the logs should be alongside the normal kibana ones. I'm also CET based so enjoy your upcoming dinner ;)

**Comment by nigellh** [comment]
@lmangani That is the problem, I couldn't find the Kibana ones! Currently running it in a Docker Container so just need to figure out where it is dumping them. I'll get back to this on Monday as I'm away this weekend.

**Comment by lmangani** [comment]
Not sure if this is related somehow, but could you try using the oss images for both `elasticsearch` and `kibana` containers? Just add `-oss` to both image names, ie:
```
docker.elastic.co/kibana/kibana-oss:6.1.3
```

**Comment by sergibondarenko** [comment]
@nigellh here is the docker where Sentinl works https://github.com/sergibondarenko/docker-elk-sentinl
Just start it `docker-compose up` and go localhost:5601 in your browser.  Please check Kibana config in your docker, it should be like this https://github.com/sergibondarenko/docker-elk-sentinl/blob/master/kibana/config/kibana.yml#L9

**Comment by nigellh** [comment]
@sergibondarenko I am running this as separate containers for each of Elasticsearch, Logstash and Kibana not a single container for all three. This allows greater flexibility. What version is the one you are pointing to?

**Comment by nigellh** [comment]
Hi @lmangani the following are the only log entries mentioning sentinl. (Hadn't realised it was sent to the screen Sheesh!)

    {"type":"log","@timestamp":"2018-03-12T10:23:13Z","tags":["status","plugin:sentinl@6.0.0","info"],"pid":6392,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
    {"type":"log","@timestamp":"2018-03-12T10:23:18Z","tags":["info","Sentinl","init"],"pid":6392,"message":"initializing ..."}
    {"type":"log","@timestamp":"2018-03-12T10:23:18Z","tags":["info","Sentinl","init_indices"],"pid":6392,"message":"checking watcher_alarms index ..."}
    {"type":"log","@timestamp":"2018-03-12T10:23:31Z","tags":["info","Sentinl","init"],"pid":6392,"message":"phantom installed at /usr/share/kibana/plugins/sentinl/phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs"}

**Comment by sergibondarenko** [comment]
@nigellh the repo I provided uses docker composer and runs Elastcsearch, Kibana, and Logstash in separate containers. You can find the version looking in one of the Docker files, for example Kibana https://github.com/sergibondarenko/docker-elk-sentinl/blob/master/kibana/Dockerfile

**Comment by nigellh** [comment]
Hi @sergibondarenko my kibana.yml file is pretty empty.

    # Default Kibana configuration from kibana-docker.
    
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.url: http://elkselasticsearch:9200

Are you suggesting I add

    sentinl:
      settings:
        authentication:
          enabled: false
        email:
          active: true
          host: beast-cave
          ssl: false
        report:
          active: false
    tmp_path: /tmp/

into it? Guessing that host: would need to change?

**Comment by nigellh** [comment]
Actually from the container it reads

    # Default Kibana configuration from kibana-docker.
    
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://elasticsearch:9200

What is in the previous comment is in theory from the kibana.yml that is copied into the container when it is buit.

**Comment by sergibondarenko** [comment]
@nigellh please run the docker repo I provided above on your machine. And see if you have any problems with Sentinl there.

**Comment by nigellh** [comment]
Hi @sergibondarenko. Tried.

Created a test directory with a docker-compose.yml file from your repo and a directory and dockerfile from your repo for each ELK component. On starting got:

    ERROR: for test_elasticsearch_1  Cannot start service elasticsearch: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/data/test/elasticsearch/config/elasticsearch.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/5ad2ddba75268d919413bf89cbc75030649e163c94d8c2bd5489af2c6ff9f6ef/merged\\\" at \\\"/var/lib/docker/overlay2/5ad2ddba75268d919413bf89cbc75030649e163c94d8c2bd5489af2c6ff9f6ef/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
    
    ERROR: for elasticsearch  Cannot start service elasticsearch: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/data/test/elasticsearch/config/elasticsearch.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/5ad2ddba75268d919413bf89cbc75030649e163c94d8c2bd5489af2c6ff9f6ef/merged\\\" at \\\"/var/lib/docker/overlay2/5ad2ddba75268d919413bf89cbc75030649e163c94d8c2bd5489af2c6ff9f6ef/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
    ERROR: Encountered errors while bringing up the project.

**Comment by sergibondarenko** [comment]
@nigellh can you start my repo?
Instructions:
1. `git clone https://github.com/sergibondarenko/docker-elk-sentinl.git`
2. `cd docker-elk-sentinl`
3. Stop all running Elasticsearch, Logstash and Kibana instances
4. `sudo docker-compose up`
5. Open a web browser and put the following address into URI http://localhost:5601

**Comment by sergibondarenko** [comment]
@nigellh you can't just copy the docker-compose.yml file into a new directory and expect that it magically creates all the config for you. It doesn't work like this. Or start my repo. Of fix config issues in the directory when you moved the composer file. The error you provided tells you explicitly that config doesn't exist
```
...Check if the specified host path exists and is the expected type...
```

**Comment by nigellh** [comment]
Hi @sergibondarenko, I did say I am pretty new to all this. I'm learning all this the hard way, trial and error and don't tend to ask questions until I've pretty much exhausted other avenues, including the few colleagues that have some experience of this.

I do not have Git installed so cloning it is not an option. So I have downloaded the zip and unpacked it and running docker-compose from the parent directory.

I hope that is closer to what you were after.

**Comment by sergibondarenko** [comment]
@nigellh can you share your docker with me?

**Comment by sergibondarenko** [comment]
Plus the composer file.

**Comment by sergibondarenko** [comment]
@nigellh what web browser do you use? Please try the latest Chrome.

**Comment by nigellh** [comment]
@sergibondarenko You will be please to hear that on Chrome on Windows it works, just not on Firefox on Windows or Ubuntu.

**Comment by nigellh** [comment]
It is fine on Chromium as well. So it appears that it is a Firefox issue.

At least you have something specific to look into.

**Comment by nigellh** [comment]
@sergibondarenko From Firefox which you don't get from Chrome

TypeError: Watcher.list(...).then(...).catch(...).finally is not a function
Stack trace:
listWatchers@http://localhost:5601/bundles/sentinl.bundle.js?v=16588:1:220976
WatchersController@http://localhost:5601/bundles/sentinl.bundle.js?v=16588:1:221134
instantiate@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:33393
$ControllerProvider/this.$get</<@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:91863
link@http://localhost:5601/bundles/vendors.bundle.js?v=16588:74:6769
bind/<@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:9425
invokeLinkFn@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:81640
nodeLinkFn@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:63521
compositeLinkFn@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:52333
compile/<@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:50989
compilationGenerator/<@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:58093
boundTranscludeFn@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:54223
controllersBoundTransclude@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:59389
update@http://localhost:5601/bundles/vendors.bundle.js?v=16588:74:5927
$broadcast@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:148872
commitRoute/<@http://localhost:5601/bundles/vendors.bundle.js?v=16588:74:3708
processQueue@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:132456
scheduleProcessQueue/<@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:133349
$digest@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:144239
$apply@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:147007
done@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:100015
completeRequest@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:104697
createHttpBackend/</xhr.onload@http://localhost:5601/bundles/vendors.bundle.js?v=16588:58:105435
 <div class="application" ng-class="'tab-' + chrome.getFirstPathSegment() + ' ' + chrome.getApplicationClasses()" ng-view="">

**Comment by nigellh** [comment]
Hi, no-one did answer my question on what the -oss versions of ELK are?

**Comment by sergibondarenko** [comment]
@nigellh yes, it is an issue with Firefox. I'll push the fix today and let you know about it.
In my docker repo I use the following ELK pkgs:
```
docker.elastic.co/kibana/kibana-oss:6.2.2
docker.elastic.co/logstash/logstash-oss:6.2.2
docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
```
You can see them in the docker files of the repo.

**Comment by nigellh** [comment]
@sergibondarenko Thanks, but what is the difference between

docker.elastic.co/kibana/kibana-oss:6.2.2
docker.elastic.co/logstash/logstash-oss:6.2.2
docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2

and

docker.elastic.co/kibana/kibana:6.2.2
docker.elastic.co/logstash/logstash:6.2.2
docker.elastic.co/elasticsearch/elasticsearch:6.2.2

What does the -oss give you in the image you are using? does oss stand for anything?

**Comment by lmangani** [comment]
Hi @nigellh the `-oss` versions supposedly only contain open-source components, while the default images do contain `x-pack` and other commercial extensions which might expire or what not.

**Comment by guanghaofan** [comment]
I just install the official released version 6.0.0 and i have the same situation, nothing show in the panel(UTC time is {{ utcTime }}

Local time is {{ currentTime }}
)
But it just worked in the pre-release 6.0.X version.

**Comment by guanghaofan** [comment]
Add the kibana log file.
[kibana_6.0.0.log](https://github.com/sirensolutions/sentinl/files/1805769/kibana_6.0.0.log)

**Comment by lmangani** [comment]
This is a known issue we're working on a new release to address it - thanks!

**Comment by sergibondarenko** [comment]
@nigellh you can read about OSS packages and docker here on the Elastic web site https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_image_types

**Comment by nigellh** [comment]
@sergibondarenko Thanks, I appreciate your help. This is the first time I have done anything with Docker, Docker Compose, Sentinl, ELK and several other things and it has been an interesting learning curve. The hardest thing to get past have been either the undocumented 'features' (No '_' character in a Docker Image Name. Worked for the Kibana image, but not the Logstash image which made it harder to find), the pain in the butt formatting of .yml files, the poor documentation of ELK so that you can have working examples and to cap it all, the breaking of Auditbeat between 6.1 and 6.2. However, I have a basic working system and now it is a case of refining / defining what is interesting and finding out how to get Sentinl to do the notifications when needed. 

Genuninely appreciate your help, even if I'm a "nooby" who still has more to learn, but in a strange way loving all of this!

**Comment by sergibondarenko** [comment]
@nigellh thanks for helping to discover this bug!

**Comment by Ekouyoja** [comment]
I have the same bug when I install sentinl, I just need to wait the next release ?

**Comment by nigellh** [comment]
@sergibondarenko Your welcome, is the fix ready to pick up?

**Comment by sergibondarenko** [comment]
@nigellh @Ekouyoja pick your .zip package under this release https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.2. They were all updated with this new fix.

**Comment by Ekouyoja** [comment]
@sergibondarenko Perfect, it works for me. Thanks for your work.

**Comment by nigellh** [comment]
@sergibondarenko Thanks. All works perfectly on Firefox

![image](https://user-images.githubusercontent.com/12110404/37346651-c76e45c0-26c7-11e8-83ff-6c4935914e70.png)

**Comment by Bader972016** [comment]
Hey there, I would like to re-open this issue as I am having the same problem on ELK version 6.6.0. 
steps: 
Install ELK stack v6.6.0  (from yum repository on CentOS 7) with the corresponding searchguard version for both Elasticsearch and Kibana 
Download the sentinl plugin through the releases link: https://github.com/sirensolutions/sentinl/releases/download/tag-6.6.0-0/sentinl-v6.6.0.zip 

keep sentinl at default configuration (just want to have it running so I can create watchers and alarms through GUI). 

Result: Getting the same "utc Time" and "current Time" instead of the actual values, with none of the buttons to Watcher Report etc available. 

Should I be opening a new issue with this?
[Elasticsearch.yml.txt](https://github.com/sirensolutions/sentinl/files/3326107/Elasticsearch.yml.txt)
[Kibana.log.txt](https://github.com/sirensolutions/sentinl/files/3326108/Kibana.log.txt)
[kibana.yml.txt](https://github.com/sirensolutions/sentinl/files/3326109/kibana.yml.txt)
[Elasticsearch.log](https://github.com/sirensolutions/sentinl/files/3326110/Elasticsearch.log)

Please let me know what to do (open a new issue, provide more info etc) 
I just didn't want to open a new issue randomly when theres the same case of it right here
