### ISSUE TITLE
Failed to get watcher

### ISSUE THREAD

**Issue by masterofcloud1** [sirensolutions/sentinl#341]
We are using ES6 in our environment and we would like to use Sentinl as our alarming component.  
But I'm having issues at creating new alarm at Sentinl. I've tried to follow http://sentinl.readthedocs.io/en/latest/Tutorial/ but had some problems. After some discussion at here https://github.com/sirensolutions/sentinl/issues/334 I've figured out my input was incorrect so I've fixed it. But still the tacher has problems. Every ti,e I'm trying to execute the watcher I'm getting the message "Watchers: fail to get watcher" and the next output:
`Error: fail to get watcher <watcher_id>
    at Watcher.<anonymous> (http://localhost:5601/bundles/sentinl.bundle.js?v=16588:1:268707)
    at tryCatch (http://localhost:5601/bundles/vendors.bundle.js?v=16588:63:99706)
    at Generator._invoke (http://localhost:5601/bundles/vendors.bundle.js?v=16588:63:101781)
    at Generator.prototype.(anonymous function) [as throw] (http://localhost:5601/bundles/vendors.bundle.js?v=16588:63:99990)
    at step (http://localhost:5601/bundles/sentinl.bundle.js?v=16588:1:264876)
    at http://localhost:5601/bundles/sentinl.bundle.js?v=16588:1:265037` 

Adding watcher configuration:
 `{
  "actions": {
    "Testing": {
      "throttle_period": "0h0m1s",
      "webhook": {
        "method": "POST",
        "host": "",
        "port": 9200,
        "proxy": false,
        "path": "",
        "body": "Found {{payload.hits.total}} Events"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "indices": [
          "<mos-{now/d}>",
          "<mos-{now/d-1d}>"
        ],
        "body": {
          "query": {
            "bool": {
              "must": [
                {
                  "query_string": {
                    "query": "mos:*",
                    "analyze_wildcard": true
                  }
                }
              ],
              "filter": {
                "range": {
                  "@timestamp": {
                    "gte": "now-5m",
                    "lte": "now"
                  }
                }
              }
            }
          },
          "aggs": {
            "avg_mos": {
              "avg": {
                "field": "mos"
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": "aggregations.avg_mos.value < 3"
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 1 minute"
    }
  },
  "disable": false,
  "report": false,
  "title": "watcher_title"
}`

**Comment by lmangani** [comment]
Hi @masterofcloud1 thanks for trying out SENTINL on 6.x - this release is still experimental so there are quirks - we've removed the old tutorial as it was confusing most users due to the discontinued format it used.

I suggest to get rid of that - just create a "default" watcher using the wizard instead with the default query and set the condition to be `> 1` then save - basically a watcher counting documents in the cluster and growing each time a watcher result is saved. This should produce a workable watcher you can start with. 

I hope this helps, feel free to comment if you need further support here.
