### ISSUE TITLE
Create some new actions for Sentinl

### ISSUE THREAD

**Issue by br14nb0** [sirensolutions/sentinl#346]
Hello, I want to make a new action like "logging" or "syslog" for Sentinl. Any suggests that I can build easily with the code ? Just like Elastalert, it has a class that I can extend the class with new action. Thanks

**Comment by sergibondarenko** [comment]
Hi @br14nb0 
Here where all actions happen https://github.com/sirensolutions/sentinl/blob/master/server/lib/actions/actions.js
PR is highly welcomed.

**Comment by lmangani** [comment]
@br14nb0 if your intention is simply to create Elasticsearch documents with results, this happens by default with SENTINL regardless of the delivery actions. If not could you describe in more details what the desired outcome would be?

**Comment by br14nb0** [comment]
Thank you guys, i'm using your Watcher to integrate with ELK for my company instead of using X-pack. And I want to code an PDF report action that the admin can modify the template by himself like an Audit report, Assessment report.
In version 6.3.0 x-pack is opensource, hope u can improve Watcher and I assure i will contribute u soon

**Comment by lmangani** [comment]
Thanks @br14nb0 we are happy to receive any contributions to extend and keep SENTINL truly open. 

For absolute clarity, `x-pack` is **NOT** proper opensource at all from what I understand - this is a serious misconception they are pushing out - the reality is this just "shared source" meaning you can debug it for free, and Elastic gets to keep code rights under a non open-source license, and can change back to commercial anytime they want or decide to add conditions to its usage, etc.
