### ISSUE TITLE
Problem with reports

### ISSUE THREAD

**Issue by masterofcloud1** [sirensolutions/sentinl#347]
Hello,
well, I really don;t know if it is a problem with my configuration or something... The documentation is not really clear about that. But I just can't make reports work.Every time I look at the reports tab I see totally nothing.

The code of the reporter:

```{
  "actions": {
    "report_admin": {
      "throttle_period": "0h0m1s",
      "report": {
        "to": "to@email.com",
        "from": "from@email.com",
        "subject": "My Report",
        "priority": "high",
        "body": "Sample Screenshot Report",
        "save": true,
        "snapshot": {
          "res": "1280x900",
          "url": "http://localhost/app/kibana#/dashboard/Alerts",
          "path": "/tmp/",
          "params": {
            "delay": 5000,
            "crop": "false"
          }
        }
      }
    }
  },
  "input": {},
  "condition": {},
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 1 minute"
    }
  },
  "disable": false,
  "report": true,
  "title": "reporter_title_c9b22cab-cee3-43ba-8346-d474e79930ec"
}
```
Noted that i really don't care about the mail. I just want the report to be seen in the kibana

**Comment by sergibondarenko** [comment]
Do you have report `active` in kibana.yml? http://sentinl.readthedocs.io/en/latest/Config-Example/

**Comment by sergibondarenko** [comment]
Also please paste here Kibana log output. What version of Kibana do you use?

**Comment by masterofcloud1** [comment]
I've added this lines to the kibana.yml but the kibana is failing to start since then...
`sentinl:
 settings:
   report:
    active:true
    tmp_path: /tmp
`

**Comment by lmangani** [comment]
@masterofcloud1 did you respect the yaml indentation? I can't tell from your paste.
Check the kibana logs for the reason its not starting.

**Comment by sergibondarenko** [comment]
An example of kibana.yml related to Sentinl
```
sentinl:
  settings:
    email:
      active: true
      host: beast
    report:
      active: true
      tmp_path: /tmp/
      search_guard: true
```

**Comment by masterofcloud1** [comment]
Yes... Still buggy. 
`
sentinl:
  settings:
    report:
      active:true
      tmp_path: /tmp
`

**Comment by lmangani** [comment]
@masterofcloud1 please be specific and attache full details and kibana logs when starting and when running the report - guesswork is dangerous. Thanks!

**Comment by masterofcloud1** [comment]
Found why the kibana didn't start... That was my mistake. Apologize.
But still I can't see any reports. Instead, I see alarms with the following info:
sentinl:
  settings:
    email:
      active: true
      host: beast
    report:
      active: true
      tmp_path: /tmp/
      search_guard: true

**Comment by lmangani** [comment]
Hi did PhantomJS get installed on the system? I guess not - please try install it manually and run again.

*NOTE: We're moving away from PhantomJS very soon*

**Comment by masterofcloud1** [comment]
Installed it again, via npm and apt(Don't really know from where you want to get it).
When I use url with localhost, I still got no report,but now I get empty payload(`{}`).
If I use the IP address instead of localhost, I still don't get any 
report,but now I get an alarm with this:
```
{
  "@timestamp": "2018-03-22T12:28:20.982Z",
  "watcher": "reporter_title",
  "level": "INFO",
  "message": {
    "code": 5,
    "previous": {
      "code": "ECONNREFUSED",
      "errno": "ECONNREFUSED",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 465
    }
  },
  "action": "report_admin",
  "payload": {},
  "report": false
}
```
