### ISSUE TITLE
[error][status][Sentinl][email] Fail to send email. Watcher 0bkdwm7tk9ds-p8cd9mdzyp8-d66ymec8sxb: Error: connection encountered an error

### ISSUE THREAD

**Issue by dzyangxi** [sirensolutions/sentinl#351]
1. Sentinl 6.1 and Kibana 5.5.1

2.[error][status][Sentinl][email] Fail to send email. Watcher 0bkdwm7tk9ds-p8cd9mdzyp8-d66ymec8sxb: Error: connection encountered an error

**Comment by sergibondarenko** [comment]
Sentinl v6+ is compatible **only** with Kibana v6+. Use Sentinl v5.5.1 for Kibana v5.5.1 https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v5.5.1.zip
