### ISSUE TITLE
Config report PDF action

### ISSUE THREAD

**Issue by br14nb0** [sirensolutions/sentinl#352]
Hello guys,
I have a question how I can control the screenshot, because it depends on the loading time of URL.
I'm aware of value of DELAY field in report action. Does it mean waiting time to screenshot after URL is requested ?

![untitled](https://user-images.githubusercontent.com/30727793/37576843-ed2a74d0-2b60-11e8-96a1-d6598f56d51d.png)

**Comment by sergibondarenko** [comment]
@br14nb0 yes put a number of ms you want to wait before the report is done.
