### ISSUE TITLE
Screen hang when "Title" is same

### ISSUE THREAD

**Issue by Arun-Ghosh** [sirensolutions/sentinl#355]
Hi Team,

The Sentinl screen get hung when "Title" is same for each individual component (General, Input, Condition ...) for a same alert. 

<img width="1148" alt="screen shot 2018-03-19 at 12 44 55" src="https://user-images.githubusercontent.com/6536033/37583117-f6d1ecd8-2b75-11e8-9b30-7e2339e860df.png">
<img width="644" alt="screen shot 2018-03-19 at 12 45 43" src="https://user-images.githubusercontent.com/6536033/37583120-fa6d60a2-2b75-11e8-9314-4e7fa702a95a.png">

Not sure this is a properties or a bug of ElasticSearch. [Doubted because no more different **Mapping Types** in ElasticSearch]

Its an intermittent issue. Though its working one of my cluster (With 2 nodes). Only giving below error.

<img width="450" alt="screen shot 2018-03-19 at 12 52 35" src="https://user-images.githubusercontent.com/6536033/37583175-43a8ada8-2b76-11e8-93b9-407bc054b5bc.png">

Another cluster (With 10 nodes) its not giving any message like above but hung. And after that throw below error.

<img width="1254" alt="screen shot 2018-03-19 at 12 54 01" src="https://user-images.githubusercontent.com/6536033/37583216-7c67e3ac-2b76-11e8-9c2c-df4ed6f8e9f9.png">

**ES, Kibana and Sentinl version : 6.2.2**

**Comment by lmangani** [comment]
This should be now resolved in recent versions.  feel free to comment to reopen discussion anytime.
