### ISSUE TITLE
Problem with new line

### ISSUE THREAD

**Issue by masterofcloud1** [sirensolutions/sentinl#358]
Well... This problem is really really odd... 
I am trying to use the transform to add new field to the payload and then using the new field in the actions.
But - i can't add new line to my new field.

That is my transform code(The rest of the alarm is not important):
```{
  "script": {
    "script": "var results=payload.aggregations.group_by_hosts.buckets;var text='';for(var i=0;i<results.length;i++){text+=results[i].key + ':' + results[i].average.value + '\n';}payload.hosts=text;"
  }
}```

**Comment by sergibondarenko** [comment]
please paste a sample of input data and the expected output

**Comment by masterofcloud1** [comment]
For example: I have 2 servers(named ser1 and ser2) which have low CPU idle.
I want to send an E-mail to myself which will look like that:
ser1 low CPU idle: <idle_value>
ser2 low CPU idle: <idle_value>

I want to create a long string with '/n' in the middle. But as I said,the watcher is failing...

**Comment by lmangani** [comment]
You can use `email_html` and loop through the reporting items with mustache:
```{{#hosts}} <p> {{ some_value}} </p> {{/hosts}}```

For more ideas see the mustache documentation and examples - hope this helps!

**Comment by masterofcloud1** [comment]
@lmangani  I figured it out. Just wanted to report on the bug :smile:

**Comment by lmangani** [comment]
@masterofcloud1 thanks! I don't really consider this a bug, since all the "formatting" is to be done in actions, but its appreciated nevertheless to improve documentation and examples
