### ISSUE TITLE
Need to know condition script 

### ISSUE THREAD

**Issue by agarwalshivam456** [sirensolutions/sentinl#359]
**query:**
```
GET irctc-haproxy-2018.03/_search
{
  "size": 0, 
  "query": {
    "bool": {
      "filter": [
      {
        "range": {
          "@timestamp": {
            "from": "now-30m"
          }
        }
        },
      {
        "match_all": {
        }
        }
      ]
    }
  }
  , "aggs": {
    "status_code": {
      "terms": {
        "field": "status_code.keyword",
        "size": 10
      }
    }
  }
}
```
===============================
**Output:**
```
{
  "took": 21,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 601769,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "status_code": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "200",
          "doc_count": 588783
        },
        {
          "key": "304",
          "doc_count": 9175
        },
        {
          "key": "206",
          "doc_count": 2582
        },
        {
          "key": "302",
          "doc_count": 1081
        },
        {
          "key": "500",
          "doc_count": 66
        },
        {
          "key": "404",
          "doc_count": 58
        },
        {
          "key": "400",
          "doc_count": 21
        },
        {
          "key": "408",
          "doc_count": 3
        }
      ]
    }
  }
}
```
===============
I want to grep doc_count where key : 500

**Comment by br14nb0** [comment]
Bucket_selector is the best choice

 "aggs": {
    "status_code": {
      "terms": {
        "field": "status_code.keyword",
        "size": 10
      }
   "aggs": {
            "my_filter": {
               "bucket_selector": {
                  "buckets_path": {
                     "the_doc_count": "_count"
                  },
                  "script": "the_doc_count == 500"
               }
            }
}
}

**Comment by sergibondarenko** [comment]
You have two options:

1. Use [Array compare condition](http://sentinl.readthedocs.io/en/latest/Watcher-Anatomy/#condition_1)
```
"condition": {
  "array_compare": {
    "payload.aggregations.status_code.buckets" : { 
      "path": "key" ,
      "eq": { 
        "value": 500, 
      }
    }
  }
}
```
2. Use the script condition and develop JS to parse buckets
```
  "transform": {
   "script": {
    "script": "function ifBucketKey(key){var buckets=payload.aggregations.status_code.buckets;var result=[];for(var i=0;i<buckets.length;i++){if(buckets[i].key==key)result.push(buckets[i])}return!!result.length}eval(ifBucketKey(500));"
   }
  }
```
Uncompressed version
```
  function ifBucketKey(key) {
    var buckets = payload.aggregations.status_code.buckets;
    var result = []; 
    for (var i = 0; i < buckets.length; i++) {
      if (buckets[i].key == key) result.push(buckets[i]);
    }
    return !!result.length;
  }
  eval(ifBucketKey(500));
```

**Comment by agarwalshivam456** [comment]
@br14nb0 It's not working..

**QUERY:**
GET irctc-haproxy-2018.03/_search
{
  "size": 0, 
  "query": {
    "bool": {
      "filter": [
      {
        "range": {
          "@timestamp": {
            "from": "now-30m"
          }
        }
        },
      {
        "match_all": {
        }
        }
      ]
    }
  }
  , "aggs": {
    "status_code": {
      "terms": {
        "field": "status_code.keyword",
        "size": 10
      }
       ,"aggs": {
         "my_filter": {
          "bucket_selector": {
            "buckets_path": {
              "the_doc_count": "_count"
              },
              "script": "the_doc_count == 500"
            
            }
          }
        }
      }
    }
  }

==========================
**ERROR:**
{
  "error": {
    "root_cause": [],
    "type": "search_phase_execution_exception",
    "reason": "",
    "phase": "fetch",
    "grouped": true,
    "failed_shards": [],
    "caused_by": {
      "type": "script_exception",
      "reason": "compile error",
      "script_stack": [
        "the_doc_count == 500",
        "^---- HERE"
      ],
      "script": "the_doc_count == 500",
      "lang": "painless",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Variable [the_doc_count] is not defined."
      }
    }
  },
  "status": 503
}

**Comment by lmangani** [comment]
@agarwalshivam456 This is unrelated to SENTINL - Once you get a working query for your pattern working in raw Kibana/ES queries, you can directly use those in SENTINL watchers.

@br14nb0 thanks for the valid suggestion! You made an excellent point.
