### ISSUE TITLE
how to add parameter after the url in input ,

### ISSUE THREAD

**Issue by taoyantu** [sirensolutions/sentinl#361]
hello every one !
how to add the config,i want to add parameter after the url like   GET index/_search?preference=xxxx
please help me ,thank you very much !!

**Comment by lmangani** [comment]
Hi @taoyantu 
SENTINL Uses bare Elasticsearch queries - nothing special to them. So if you can make a query work in ES, you can use that in a watcher as-is. Check out the [docs](http://sentinl.readthedocs.io/en/latest/) for a few examples. Hope this helps!

**Comment by taoyantu** [comment]
@lmangani but ， i can`t fing how to add the url parameter "preference" in the query body .do you know how to add this ？i user curl can add the parameter like curl -XGET  "http://1.1.1.1/aaaa/_search?preference=hello"
