### ISSUE TITLE
Errors while using Sentinl

### ISSUE THREAD

**Issue by varun0002** [sirensolutions/sentinl#363]
Sentinl and Kibana version: 5.4.1

I would like to report following issues/queries:

1. Sentinl gives _"Sentinl Watchers: Error 500 Internal Server Error: An internal server error occurred"_ whenever highlighted is there in input query & this comes with each watcher created using SPY plugin from dashboard:
{
  "search": {
    "request": {
      "index": [
        **"<index{now/d}>",
        "<index{now/d-1d}>"**
      ],
      "body": {
        "query": {

Same error, when try similar pattern in condition. This works fine in Dev Tools. example below:
     "@timestamp" : {
                **"gte" : "now-1d/d",
                "lt" :  "now/d"**

2. Sentinl allows same Title for multiple watchers. I believe it should restrict duplicate watcher title name as it creates lot of confusion for the user.

3. Do we have any _copy to_ option available. **Use case**: I want to create multiple watchers with slight change in input and condition definition. Currently, I have to copy all screens in notepad and then paste screen by screen to new alert. Copy to option should help me to generate new watcher and make changes where ever required.

**Comment by lmangani** [comment]
Thanks for your reports @varun0002  - they are deeply welcome and appreciated but for the sake of succeeding, I strongly suggest not to mix multiple issues and reports, or confusion will take over. 

Could you please raise each issue separately with a clear title, so developers and contributors can work on it - Many Thanks!

**Comment by varun0002** [comment]
Done
