### ISSUE TITLE
Duplicate Watcher with same title

### ISSUE THREAD

**Issue by varun0002** [sirensolutions/sentinl#364]
Sentinl and Kibana version: 5.4.1

Issue description:
Sentinl allows same Title for multiple watchers. I believe it should restrict duplicate watcher title name as it creates lot of confusion for the user.

**Comment by sergibondarenko** [comment]
@varun0002 can you rename one of the watchers?

**Comment by sergibondarenko** [comment]
In the latest Sentinl version we have Kibana modal warning user that there is a watcher with this name already and you can give the same name or type a new name.
