### ISSUE TITLE
Sentinl Watchers: Error 500 Internal Server Error with SPY plugin

### ISSUE THREAD

**Issue by varun0002** [sirensolutions/sentinl#366]
Sentinl and Kibana version: 5.4.1

Issue Description:

Sentinl gives "Sentinl Watchers: Error 500 Internal Server Error: An internal server error occurred" whenever highlighted is there in input query & this comes with each watcher created using SPY plugin from dashboard:
{
"search": {
"request": {
"index": [
"<index{now/d}>",
"<index{now/d-1d}>"
],
"body": {
"query": {

Same error, when try similar pattern in condition. This works fine in Dev Tools. example below:
"@timestamp" : {
"gte" : "now-1d/d",
"lt" : "now/d"

**Comment by d-malko** [comment]
What name of an index are you using?

**Comment by sergibondarenko** [comment]
@varun0002 ok, we will fix it. For now, just put correct index name.
