### ISSUE TITLE
Sentinl 6 : blank content on Watcher spy tab

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#367]
1. Sentinl and Kibana version : 6.2.2

2. Issue description
When I am on a visualization, and click on the "spy" button, and then, the "Watcher" tab, I get a blank content.

3. Reproducing the issue step-by-step
I go on "Visualize" app and then create a Data Table
I click on the "spy" button and then "Watcher" tab
I get a blank tab content

6. Additional details
Here's a screenshot on Chrome : 
![image](https://user-images.githubusercontent.com/3750300/37660928-d8a7129a-2c53-11e8-91a7-d80387fe2a9a.png)

I reproduce it on Chrome, Firefox and Internet Explorer.
I have no error in browser console, neither in server logs

**Comment by fbaligand** [comment]
@szydan 
Why did you close this issue ?

**Comment by sergibondarenko** [comment]
@fbaligand I marked this as solved in the private branch fix. Let's have it opened until the fix is ported here.

**Comment by fbaligand** [comment]
Thanks @sergibondarenko for reopening the issue, and especially for the fix !

**Comment by fbaligand** [comment]
I confirm that the bug is now fixed !
=> thanks guys !
