### ISSUE TITLE
Can i define decimal place in transform script in sentinl watcher

### ISSUE THREAD

**Issue by agarwalshivam456** [sirensolutions/sentinl#369]
Created another field (percentage) by two another field. Now i want to have output  to 3 decimal places.
Is it possible in sentinl watcher?
===============================
**transform script:**
{
  "script": {
    "script": "payload.hits.myvar = payload.aggregations.error.value / payload.hits.total * 100"
  }
}

===============================
**output:**
0.00944220192148809

Can i define decimal value here so i can get desire output.

**Real Output:**
0.00944220192148809

**Expected Output:**
0.009

**Comment by lmangani** [comment]
Hi @agarwalshivam456 you can use plain javascript for this: `.toFixed(2)`

**Comment by agarwalshivam456** [comment]
@lmangani Can you please tell me where i have to put this value?

**Comment by agarwalshivam456** [comment]
@lmangani I got that.

Thank you so much @lmangani
