### ISSUE TITLE
Update report doc about chrome path

### ISSUE THREAD

**Issue by sergibondarenko** [sirensolutions/sentinl#374]
1. Sentinl and Kibana version 

2. Issue description

3. Reproducing the issue step-by-step

4. Expected results vs. actual results

5. Sample of data

6. Additional details

**Comment by sergibondarenko** [comment]
Done it here http://sentinl.readthedocs.io/en/latest/Config-Example/

**Comment by d-malko** [comment]
I am a new bee...
What package I must install on my server to receive reports? Chromium with dependencies takes 560M is this packet need to be installed?

**Comment by sergibondarenko** [comment]
@d-malko yes, this package
