### ISSUE TITLE
Change timezone not working

### ISSUE THREAD

**Issue by yabir** [sirensolutions/sentinl#376]
**1. Sentinl and Kibana version**

Kibana: 6.2.1 (Official docker container, OS: CentOS)
Sentinl release: 6.2.1

**2. Issue description**

I want the watchers running in my localtime (not UTC) but it is not changing the execution time even if I change the `sentinl.es.watcher.schedule_timezone`  to `local`.

Here is my sentinl configuration:

```bash
11 #-----Sentinl Kibana plugin configuration--------
12 sentinl:
13   es:
14     host: XXXX
15     port: 9200
16     timefield: '@timestamp'
17     watcher:
18        schedule_timezone: 'local'
19   settings:
20     email:
21       active: true
22       user: XXXX
23       password: XXXX
24       host: XXXX
25       ssl: false
26     report:
27       active: true
28       tmp_path: /tmp/
29       search_guard: false
30       simple_authentication: false
31     slack:
32       active: true
33       username: ELK
34       hook: XXXX
35       channel: XXXX
```

Am I doing something wrong? 

I want to use this localtime.
![image](https://user-images.githubusercontent.com/8483871/37915118-082a48d8-3119-11e8-99cc-3a3e9c5a6304.png)

**Comment by yabir** [comment]
Solution: The `kibana.yml` file was fine. The problem was that my container had the localtime set to UTC, and the localtime that Kibana was showing me (borded by a red rectangule in the issue description), it comes from my browser's localtime.

So I changed the `localtime` of the Kibana container (CentOS) using:

```
###Make a backup
sudo mv /etc/localtime /etc/localtime.bak
### set my localtime
sudo ln -s /usr/share/zoneinfo/XXX/XXX /etc/localtime
```

And it worked.

**Comment by lmangani** [comment]
Thanks for sharing your solition @yabir 
I'll add this to the FAQ to help others!

**Comment by yabir** [comment]
Good @lmangani , I hope it helps.

It would be nice to have another sentinl timezone option that comes directly from the kibana's configuration `(Kibana > Management > Advanced Settings > dateFormat:tz)` since it has already the timezone we're using and it will not be necessary to change it in the Kibana host.

**Comment by lmangani** [comment]
@yabir could you open a feature request with those details? It'll help us keep in the scope of roadmap.

**Comment by yabir** [comment]
Sure, Here's the feature request : #381
