### ISSUE TITLE
Can you add zip artefacts for 5.6.8 version

### ISSUE THREAD

**Issue by d-malko** [sirensolutions/sentinl#382]
Issue description
I want install sentinl for Kibana version 5.6.8, but no zip archive with plugin for this version on github.
But I can`t find assets for this version. Although a few days ago I downloaded them

> https://github.com/sirensolutions/sentinl/releases/download/tag-5.6.2/sentinl-v5.6.8.zip

Thank you!

**Comment by sergibondarenko** [comment]
Added https://github.com/sirensolutions/sentinl/releases/tag/tag-5.6.2

**Comment by d-malko** [comment]
Sergij, thank you very much!
