### ISSUE TITLE
configuring Watchers fail to save

### ISSUE THREAD

**Issue by manish2479** [sirensolutions/sentinl#384]
Hi 

I am new to sentinl and I am trying to follow the docs from here http://sentinl.readthedocs.io/en/latest/Watcher-Wizard/ and did similar steps except the title is different and while saving I get error as below:

`Editor: Fail to save field: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

Here is the raw data of that config.

```
{
  "actions": {
    "email_admin": {
      "throttle_period": "0h15m0s",
      "email": {
        "to": "user@example.net",
        "from": "sentinl@localhost",
        "subject": "Alarm",
        "priority": "high",
        "body": "Found {{payload.hits.total}} Events"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [],
        "body": {}
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 1"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 1 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "Error_Message"
}
```
Any help would be appreciated. Also how to get alerts on system logs where we get any error, any example with "/var/log/messages" files with error would be very useful to learn this tool.

Thank You,
                 Manish

**Comment by sergibondarenko** [comment]
@manish2479 what version of Kibana and Sentinl do you use?

**Comment by sergibondarenko** [comment]
@manish2479 in order to trigger an alarm on an error message came from `/va/log/messages` you must have it stored in Elasticsearch first. Sentinl doesn't have any means to read local files. The goal of Sentinl is to search data in Elasticsearch. 

Use [Logstash](https://www.elastic.co/products/logstash) to inject data from a file to Elasticsearch. Then you can configure Sentinl watcher to execute a search request periodically. And an alarm will be sent if a specified watcher condition is matched.

**Comment by sergibondarenko** [comment]
Here is a short video about how to create a basic watcher https://youtu.be/qk9ZZYqUevU 

The watcher execution heavily depends on what you put in [Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html) and [Condition](http://sentinl.readthedocs.io/en/latest/Watcher-Anatomy/#condition_1) tabs.

**Comment by sergibondarenko** [comment]
@manish2479 if still doesn't work, an example for v6.2.2:
```
# Stop Kibana first
cd kibana
rm -rf plugins/sentinl
./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.3-1/sentinl-v6.2.2.zip
# Start Kibana when finished
```

**Comment by manish2479** [comment]
I was using sentinl v6.2.2, but the new build seems fixed the issue.  I have already got ELK with Filebeat configured and seems working well, So thank you for the new build, now I would like to go in depth with this plugin, like how I can filter certain key words and get alerts only for those and not everything logged into kibana/Elasticsearch.

Now I would like file key words like "kernel"  or "kiblnd_check_txs_locked" and or both of these keys words.

Also is there any slack or jabber alert feature going to be available in near future.
Thank You

**Comment by sergibondarenko** [comment]
@manish2479 
To create an alert based on a filtered data from Elasticsearch, use [bool query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html). Insert it in the editor inside Input tab under `body` property
![screenshot from 2018-04-11 15-02-41](https://user-images.githubusercontent.com/5389745/38618309-816b4de6-3d99-11e8-82ea-8e2561a9f8ef.png)


There is a slack action, look the Actions tab of the watcher UI configuration
![screenshot from 2018-04-11 15-00-12](https://user-images.githubusercontent.com/5389745/38618190-2b50a53c-3d99-11e8-8285-55face7981bb.png)

**Comment by manish2479** [comment]
Hi 

Thanks, so where does the slack URL configuration goes. I see the channel option but not the url or user configuration option.

Thank You

**Comment by lmangani** [comment]
Check out the extended configuration example: http://sentinl.readthedocs.io/en/docs/Config-Example/
Those are all the options we currently provide.

**Comment by manish2479** [comment]
Hi

The problem which I have initially reported and it seems I am able to reproduce it by inputting it in transform tab options. 

`Editor: Fail to save field: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

Entry in transform option is as below:

`payload.custom = "tag"`

Thank You

**Comment by lmangani** [comment]
@manish2479 sorry i have no clue what you mean or to read back and merge the dozens of comments - please help us help you by simply attaching the full `watcher` configuration for an issue you are reporting, the actual logs (including the rows before and after) and any other detail, or we won't be able to do much - Thanks.

**Comment by manish2479** [comment]
I think I figured it out it seems I have not used the right body format in transform body section. Once I defined 

```
{
    "script": {
        "script": "payload.custom = tag"
    }
}
```

where else previously I had only defined payload.custom = "tag", which seems not right format for the body section in transform.

So where do I can find more examples of transform section.

**Comment by lmangani** [comment]
@manish2479 both condition and transport are pure javascript they can do anything JS can to the data.
