### ISSUE TITLE
Importing and Exporting Alerts

### ISSUE THREAD

**Issue by neelrana** [sirensolutions/sentinl#386]
1. Sentinl and Kibana version 
Kibana 6.2.2
Sentinl 6.2.2

2. Issue description

Hello, I was wondering if there is any way to import and export alerts from one cluster to another. I have two different environments with kibana and Sentinl installed. I have created base template watchers on one of the environment however I wanted to know if I could copy those watchers onto the other environment without going through the trouble of creating the whole list of watchers again. Please let me know and thank you for your efforts :)

**Comment by sergibondarenko** [comment]
@neelrana watchers are stored inside `.kibana` index. 
1. Get all watchers first. For example, get first 10 watchers and write them to `my_watchers.json` file.
```
curl -H "Content-Type: application/json" -XGET localhost:9200/.kibana/_search?pretty -d '{"from":0,"size":10,"query":{"exists":{"field": "sentinl-watcher"}}}' > /tmp/my_watchers.json
```
2. Edit file `my_watchers.json`. Delete all lines except those inside `hits.hits` array, for example
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : { 
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0 
  },  
  "hits" : { 
    "total" : 8,
    "max_score" : 1.0,
    "hits" : [
       { ... }, // leave only this
       { ... }  // and this
    ]
  }
}
```
3. Index watcher into another cluster 
```
curl -H 'Content-Type: application/x-ndjson' -XPOST 'localhost:9200/bank/account/_bulk?pretty' --data-binary @/tmp/my_watchers.json
```

**Comment by neelrana** [comment]
@sergibondarenko 

Hello, Thank you for your response, really helpful!

I was just following this and came across a problem. from what I have read, the JSON format from my_watchers.json file is not correct inorder to use bulk api. i.e. below is the json format for one watcher that I retrieved from the old node:
```
{
        "_index": "watcher",
        "_type": "sentinl-watcher",
        "_id": "igafadn5obb-6yg5k8st4wg-n2h0wppov3b",
        "_score": 1,
        "_source": {
          "title": "watcherTitle",
          "disable": false,
          "report": false,
          "trigger": {
            "schedule": {
              "later": "every 30 minutes"
            }
          },
          "input": {
            "search": {
              "request": {
                "index": [
                  "myIndex-*"
                ],
                "body": {
                  "query": {
                    "bool": {
                      "must": [
                        {
                          "term": {
                            "field": {
                              "value": "110"
                            }
                          }
                        },
                        {
                          "range": {
                            "@timestamp": {
                              "from": "now-30m"
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "condition": {
            "script": {
              "script": "payload.hits.total > 0"
            }
          },
          "actions": {
            "The logs was modified": {
              "throttle_period": "0h5m0s",
              "slack": {
                "channel": "#xxxx",
                "message": "The logs was modified",
                "stateless": false
              }
            }
          },
          "transform": {}
        }
      },
```

However, Whenever I try to post this data into new cluster it gives me an error. Below is the bulk api format required:
![image](https://user-images.githubusercontent.com/9300684/38372785-8b8beb8e-38e7-11e8-96dd-1fe0da606492.png)

I got this screenshot from: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

Any ideas how I could fix this without going through each datafield and modifying lines of JSON data?

**Comment by lmangani** [comment]
@neelrana the bulk format is not relevant to the single document - those are unrelated in both logic and code. There are generic tools to perform backup and restore of ES data, those should be preferred.

**Comment by neelrana** [comment]
@sergibondarenko @lmangani  Do you have any idea as to how to fix this?:

![image](https://user-images.githubusercontent.com/9300684/38375601-84d70d08-38ee-11e8-8406-43fa17a9210d.png)

I managed to post single watchers without the bulk api however I cannot seem to post multiple watchers at once

**Comment by szydan** [comment]
@neelrana could you post the testingWatchers.json file?

**Comment by lmangani** [comment]
@neelrana how is this related to sentinl? We cannot unfortunately help with general issues related to Elasticsearch, but perhaps other users might have time to do that - I would suggest practicing from the Kibana dev console.

**Comment by neelrana** [comment]
My apologies, I will ask about this in Elasticsearch discussion thread. I turned to manually importing the watcher alarms in sentinl v6.2.2 with kibana6.2.2 and elasticsearch 6.2.2.

However I get this error. Would you know what the issue might be? as the error message is very ambiguous.

![image](https://user-images.githubusercontent.com/9300684/38621706-4cf129b4-3d99-11e8-99fb-d729d27d75ee.png)


I tried this command for importing watcher in kibana v5.6.5 and it worked fine. I am not sure if this is a known issue or not. Or is this is Kibana issue?

**Comment by sergibondarenko** [comment]
@neelrana you work in the Kibana dev tools, thus it is Kibana issue. Look at the Kibana server logs for errors. Try to reload Kibana.

**Comment by varun0002** [comment]
@sergibondarenko: Will the same steps work for 5.4.1? I tried to run curl command but it returns 0 hits for "field": "sentinl-watcher"

**Comment by lmangani** [comment]
@varun0002 depending on the config on 5.x they will be stored in sentinl's own index

**Comment by varun0002** [comment]
@lmangani: Thanks for your response. Where I can find that configuration? Here is extract from one of our kibana.yml:

  es:
    host: <host>
    port: 9200
    timefield: '@timestamp'
    default_index: watcher
    type: sentinl-watcher
    alarm_index: watcher_alarms
    alarm_type: sentinl-alarm
    script_type: sentinl-script
  sentinl:
    history: 20
    results: 50
    scriptResults: 50

**Comment by lmangani** [comment]
right there in front of you :) 
```
default_index: watcher
type: sentinl-watcher
```

**Comment by varun0002** [comment]
ok, so I ran following command but not getting _type: sentinl-watcher rather it gives me visualization, index-patterns, etc.

GET _search {"from":0,"size":10,"query":{"exists":{"field": "watcher"}}}

GET _search {"from":0,"size":10,"query":{"exists":{"field": "sentinl-watcher"}}} gives 0 results.

What I should run to get only watcher definition?

**Comment by pipko** [comment]
The same issue as @thapliyal28 -- have no idea how to restore previously saved. Always stable error.
