### ISSUE TITLE
How can we support configuration  default_index: watcher at V6

### ISSUE THREAD

**Issue by houhuiteng** [sirensolutions/sentinl#393]
sentinl v6.22  doesn't support configuration  default_index: watcher , 

How can we support it?

**Comment by sergibondarenko** [comment]
@houhuiteng in v6.2.2 Sentinl uses Kibana savedObjectsAPI and saves indexes only in `.kibi` index. Why do you want to support it?

**Comment by jccq** [comment]
sergei should be .siren ?

**Comment by sergibondarenko** [comment]
@jccq the default index is assigned automatically on Sentinl start. Sentinl gets it from kibana.yml or investigate.yml, config option `kibana.index`. Watchers is saved in `.siren` index if this value is assigned to `kibana.index` property. Currently, it is assigned:
```
trex@beast:~/Development/siren/kibi-internal$ grep -rne "\.siren" config/investigate.yml 
30:#kibana.index: ".siren"
```

**Comment by houhuiteng** [comment]
@sergibondarenko  i want to support it, because our Business needs, I have two kibana.sentinl connections to one elasticsearch services.

**Comment by avinchakov** [comment]
I have the same issue. How can I use old "watcher" index rather .kibana default?

**Comment by houhuiteng** [comment]
another question ,how I reindex from old version  watcher  data?

**Comment by sergibondarenko** [comment]
@avinchakov, Sentinl v6 saves watchers only in `.kibana` index. If you want, you can add this functionality and do a PR. 

@houhuiteng, you can reindex manually using Elasticsearch, for example:
1. Get all watchers first. For example, get first 10 watchers and write them to `my_watchers.json` file.
```
curl -H 'Content-Type: application/json' -XGET localhost:9200/.kibana/_search?pretty -d '{"from":0,"size":10,"query":{"exists":{"field": "sentinl-watcher"}}}' > /tmp/my_watchers.json
```
2. Edit file `my_watchers.json`. Delete all lines except those inside `hits.hits` array, for example
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : { 
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0 
  },  
  "hits" : { 
    "total" : 8,
    "max_score" : 1.0,
    "hits" : [
       { ... }, // leave only this
       { ... }  // and this
    ]
  }
}
```
3. Index watcher into another cluster 
```
curl -H 'Content-Type: application/x-ndjson' -XPOST 'localhost:9200/bank/account/_bulk?pretty' --data-binary @/tmp/my_watchers.json
```

**Comment by sergibondarenko** [comment]
Duplication of https://github.com/sirensolutions/sentinl/issues/408
