### ISSUE TITLE
how manual delete alarms

### ISSUE THREAD

**Issue by shrv** [sirensolutions/sentinl#397]
Hello!
I use ELK 6.2
sentinl - 6.2.2.

I tested watcher and save messages in console, before send alarm to mail.

![elk_alarms](https://user-images.githubusercontent.com/11438507/38797690-04d31444-4168-11e8-8d71-c39ad3539f37.jpg)
In the end, I get a page where the delete button is out of the screen.
Changes in the size of the column of the table - not was the result .
How do I delete these messages?
Thank's

**Comment by sergibondarenko** [comment]
Weird! I can't reproduce it. There is some alarm messages overflow over the right but only if browser zoom is more then 400%. As far as I understand from your screenshot it is not the case.

And I definitely can delete alarms. See the video https://youtu.be/qheAbtB9Fts

Please delete Sentinl and Kibana JS bundle. Then try again.
```
cd kibana
rm -rf optimize plugins/sentinl
./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.3-2/sentinl-v6.2.2.zip
```

**Comment by shrv** [comment]
Thank's
The way you proposed - remove and put the new version, helped me :+1:
