### ISSUE TITLE
search guard permission denied 

### ISSUE THREAD

**Issue by TimothyFehr** [sirensolutions/sentinl#405]
1. Sentinl and Kibana version 
6.2.2 (both)

2. Issue description

I followed the dokumenataion by setting up search guard and sentinl but it seams to me that the dokumentation is not complete or i am mssing some other logical step.

3. Reproducing the issue step-by-step
clone https://github.com/deviantony/docker-elk
go to the searchguard branch build and bring up according to read me

tear down the containes,
install the sentilplugin in the Kibana dockerfile an d edit the configuration files according to your Dokumentation 
and instanciate them again with the new configured sentil plugin

(i can provide the files if you want since it is a local demo )

4. Expected results vs. actual results

Expected:
having access to the alerts and reports

I get Following error in the Kibana user interface:
```
Alarms: Error 403 Forbidden: [security_exception] no permissions for [indices:data/read/search] and User [name=kibanaserver, roles=[], requestedTenant=null]
```

**Comment by sergibondarenko** [comment]
@TimothyFehr User permission is assingned in SearchGuard, not in Sentinl. Did you follow [this howto](https://github.com/sirensolutions/sentinl/blob/master/docs/HOWTO-Sentinl-and-SearchGuard.md)?  Please paste content of `kibana.yml` file.

**Comment by TimothyFehr** [comment]
u did it acording to your documentation here:
http://sentinl.readthedocs.io/en/latest/HOWTO-Sentinl-and-SearchGuard/

It is also nearly identical (i use http not https)

my kibana.yml:
`---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

## Custom configuration
#
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
elasticsearch.ssl.verificationMode: 'none'

searchguard.cookie.password: "123567818187654rwrwfsfshdhdhtegdhfzftdhncn"

sentinl:
  es:
    host: 'localhost'
    port: 9200
    # protocol: 'http'
    # results: 50
    # timefield: '@timestamp'
    # default_type: 'doc'
    # alarm_index: 'watcher_alarms'
    # alarm_type: 'sentinl-alarm'
  settings:
    email:
      active: true
      host: 'localhost'
      # user: 'admin'
      # password: 'password'
      # port: 25
      # domain: 'beast.com'
      # ssl: false
      # tls: false
      # authentication: ['PLAIN', 'LOGIN', 'CRAM-MD5', 'XOAUTH2']
      # timeout: 10000  # mail server connection timeout
      # cert:
      #   key: '/full/sys/path/to/key/file'
      #   cert: '/full/sys/path/to/cert/file'
      #   ca: '/full/sys/path/to/ca/file'
    slack:
      active: true
      username: 'Kibana'
      hook: '<my Hook>'
      channel: '#kibana'
    report:
      active: true
      authentication:
        enabled: true
        mode:
          searchguard: true
      file:
        pdf:
          format: 'A4'
          landscape: true
        screenshot:
          width: 1280
          height: 900`

**Comment by sergibondarenko** [comment]
@TimothyFehr 
1. You ES need to set protocol to `https`:
```
sentinl:
  es:
    protocol: 'https'
```
2. Report config misses one important parameter, `executable_path`:
```
    report:
      active: true
      executable_path: '/usr/bin/chromium' # path to Chrome v59+ or Chromium v59+
```
3. Sentinl stores/deletes watchers in an index specified in `kibana.index` of kibana.yml file (`.kibana` by default). Also, Sentinl needs other indices to store/delete alarms, for example
```
watcher_alarms-2018.03.27
watcher_alarms-2018.03.28
...
```  
You have to make sure there are correct permission for Kibana server in Search Guard (file `sg_roles.yml`) in order to allow Sentinl to manage the indices. 
```
sg_kibana_server:
  cluster:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
      - cluster:admin/xpack/monitoring*
  indices:
    '?kibana':
      '*':
        - INDICES_ALL
    'watcher_alarms*':
      '*':
       - indices:data/read/search
       - MANAGE
       - CREATE_INDEX
       - INDEX
       - READ
       - WRITE
       - DELETE
```
4. Get info about SearchGuard user
```
curl --insecure -u kibanaserver:kibanaserver 'https://localhost:9200/_searchguard/authinfo?pretty'
``` 
5. [Reload](https://docs.search-guard.com/latest/sgadmin-examples) the current Search Guard config
```
./sgadmin.sh \
   -ks /path/to/keystore.jks \
   -kspass changeit
   -ts /path/to/truststore.jks \
   -tspass changeit
   -rl
```

**Comment by smhulkund** [comment]
Followed the procedure, but still kibana throws this error

[error][Sentinl][report_action] Error: fail to authenticate via Search Guard, user: kibanaserver, AssertionError: No node found for selector: #username
    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:31:13
    at throw (native)
    at step (/usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:191)
    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:402
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by sergibondarenko** [comment]
No answer from the owner.
