### ISSUE TITLE
Loading watchers in sentinl plugin 6.2.3

### ISSUE THREAD

**Issue by wqshabbir** [sirensolutions/sentinl#406]
Hi,

I have just upgraded ELK stack to version 6.2.3 from version 6.0.0. Just to keep things aligned i also installed sentinl 6.2.3

With version 6.0.0 I used to register my sentinl watchers with elastic search by posting my alert rule to endpoint like this http://localhost:9200/watcher/sentinl-watcher/test1 and it was loading in sentinl app plugin for kibana without any issues.

Now with the recent upgrade to version 6.2.3 posting alert rule to  http://localhost:9200/watcher/sentinl-watcher/test1 isn't loading in sentinl app watchers list. I can see it is successfully registered with elasticsearch.

I have also updated sentinl config in kibana.yml to have these two lines which are optional in version 6.
default_index: watcher
default_type: sentinl-watcher (type isn't supported in 6.2.3)
http://sentinl.readthedocs.io/en/latest/Config-Example/

Just to highlight, adding watchers directly from the UI works and gets loaded in the sentinl app plugin. But posting to port 9200 as mentioned doesn't work.

I also tried to find out the "index" is assigned to watchers added directly from sentinl app/plugin  but no luck (so i can post with that index). It seems default index is changed and not get picked up even specified in the sentinl config.

I am not sure whether there is a bug in the new version or default index is changed. Can someone please share experience. 

Thanks in advance

**Comment by sergibondarenko** [comment]
@wqshabbir please look this issue https://github.com/sirensolutions/sentinl/issues/408
