### ISSUE TITLE
IF a watches condition is met, I want to trigger new watches,how do it？

### ISSUE THREAD

**Issue by InspurKelly** [sirensolutions/sentinl#409]
Sentinl and Kibana version 5.5.1

**Comment by lmangani** [comment]
Hi @InspurKelly 
The simplest way to sidechain is for the first watcher plant a "seed" for the second watcher to use. 
So if and when a Watcher finds a result, it will write something in Elasticsearch for the second Alert to find - or the second Watcher can search for results from the first one either. Hope this helps you step in the right direction.

**Comment by lmangani** [comment]
Closing as this is not an issue. Feel free to continue commenting if advice is needed.
