### ISSUE TITLE
Reporting problems with offline installation on Kibana 6.2

### ISSUE THREAD

**Issue by burandobata** [sirensolutions/sentinl#410]
Hey,

I'm running Kibana 6.2.4 and 6.X.X-2 version of Sentinl in Centos 7 offline environment.
I have problem with setting up reporting. I've installed headless chromium from my repositories (chromium-headless-60.0.3112.113-2), but I can't generate the report.

Here is what I'm receiving:
```
{"type":"error","@timestamp":"2018-04-25T12:00:32Z","tags":["error","Sentinl","report_action"],"pid":111103,"level":"error","error":{"message":"fail to open headless chrome, Error: Timed out after 30000 ms while tr
ying to connect to Chrome! The only Chrome revision guaranteed to work is r543305","name":"Error","stack":"Error: fail to open headless chrome, Error: Timed out after 30000 ms while trying to connect to Chrome! The
 only Chrome revision guaranteed to work is r543305\n    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:75:13\n    at throw (native)\n    at step (/usr/share/kibana/plugins/sentinl/server
/lib/actions/actions/report.js:57:191)\n    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:402"},"message":"fail to open headless chrome, Error: Timed out after 30000 ms while trying t
o connect to Chrome! The only Chrome revision guaranteed to work is r543305"}
```
Is there some guide how we can install a proper version of Chrome offline?

**Comment by burandobata** [comment]
I've managed to download proper package from here: https://npm.taobao.org/mirrors/chromium-browser-snapshots/Linux_x64/543305/chrome-linux.zip. 
After installing all of dependencies it is working nicely.

Is it possible to bundle this in together with necessary libs in future releases?

**Comment by sergibondarenko** [comment]
You can find the chrome inside the puppeter package too
```
sentinl/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome
```
