### ISSUE TITLE
Payload Hits Seem Off for query

### ISSUE THREAD

**Issue by discotab311** [sirensolutions/sentinl#412]
Hello -

Very new to ELK and especially Sentinl.  Trying to wrap my head around the alerts, which I have working, using 6.3.

What I am finding is that my results seem to be high.  I am parsing SIP call logs, just looking for SIP Method INVITE, which is an indexed field.

When I receive my alert email, it is noting "Series Alarm: 15".

When I view the payload in the Alert tab, however, only 10 hits are displayed..

My Query:
```
{
  "actions": {
    "email_admin": {
      "throttle_period": "0h0m0s",
      "email": {
        "to": ",
        "from": "",
        "subject": "INVITE",
        "priority": "high",
        "body": "Series Alarm {{ payload._id}}: {{payload.hits.total}}",
        "save_payload": true
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "siplog-*"
        ],
        "body": {
          "query": {
            "bool": {
              "must": [
                {
                  "term": {
                    "server": "sipserver1"
                  }
                },
                {
                  "term": {
                    "sipmethod": "INVITE"
                  }
                }
              ],
              "filter": {
                "range": {
                  "logtimestamp": {
                    "gte": "now-1h"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 2"
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 5 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "INVITE > 2 per Hour"
}
```

**Comment by lmangani** [comment]
Hi @discotab311 the number of results and the number of returned documents are not expected to be equal but rather a scrolling window into the documents the query covers. To get more than 10 results, you need to explicitly set the `size` parameter in your query - this won't affect the returned total, just the number of documents included in the response. Check the docs out: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html

Hope this helps!
