### ISSUE TITLE
Single watcher for setting alerts on multiple values of index field

### ISSUE THREAD

**Issue by iamShantanu101** [sirensolutions/sentinl#413]
1. Sentinl and Kibana version 

    Sentinl version: 6.2.4
    Kibana version: 6.2.4

2. Issue description

   Here's the use case:
   * I've `N` websites which I need to monitor.
   * I need to setup alerts for sending e-mail when any of the websites goes `down`
   * The format of e-mail should mention the host which has gone down along with HTTP return status.

   **Note:** I am using heartbeat for monitoring the required data which includes:
   ```
   monitor.status: up
   http.response.status: 200 
   monitor.host: xyz.lol
   ```
   Normally, this looks like we just need to loop over `monitor.host`, get the `monitor.status` and `http.response.status` and send an email when `monitor.status: down`. But with sentinl, I'm a little bit confused for ways to achieve this.
 
   Forgive this innocent soul if this seems too easy (I'm new to sentinl).

**Comment by lmangani** [comment]
Apologies for missing this, do you still need help or you figured this out?

**Comment by iamShantanu101** [comment]
Actually, we've put this on hold due to other priorities. This can be closed for now. I'll reopen this in future if required.
