### ISSUE TITLE
Selector error handling and this.browser.close()

### ISSUE THREAD

**Issue by OleksandrSlobodian** [sirensolutions/sentinl#419]
If a selector is not found - this.browser will not be closed...
Please finish unsuccessful report attempt with ```this.browser.close();```

**Comment by sergibondarenko** [comment]
Thank you. A PR is welcomed.

**Comment by OleksandrSlobodian** [comment]
https://github.com/OleksandrSlobodian/sentinl/commit/91e4190e72c58eac73c5a03b88182150e69f4a40

**Comment by lmangani** [comment]
@OleksandrSlobodian feel free to send a PR if you feel you can improve the method. Thanks!
