### ISSUE TITLE
Useless buttons in pdf report view (Safari 11.0.2)

### ISSUE THREAD

**Issue by OleksandrSlobodian** [sirensolutions/sentinl#422]
1. 6.2.2 

2. Useless (non-functional) buttons in pdf report review

![screen shot 2018-05-07 at 4 08 18 pm](https://user-images.githubusercontent.com/12740635/39725687-51d7d1c0-5212-11e8-82f3-5db28205b6b1.png)

![screen shot 2018-05-07 at 4 15 58 pm](https://user-images.githubusercontent.com/12740635/39725705-5ee99be6-5212-11e8-821f-76b2993f6fa0.png)

**Comment by lmangani** [comment]
Hi @OleksandrSlobodian SENTINL really has no role in this and those are added by your browser to allow your interaction with the content. The actual screenshot should not include those if you download it - if it does feel free to attach an actual example (not screenshot of a screenshot)
