### ISSUE TITLE
sentinl and readonlyrest

### ISSUE THREAD

**Issue by danielmotaleite** [sirensolutions/sentinl#423]
Hi!
In the [FAQ](http://sentinl.readthedocs.io/en/latest/FAQ) you have a workaround for getting sentinl working with readonlyrest
"How can I use SENTINL with readonlyRest authentication?"

Have you any plan to fix this, namely allow one to pass a user basic authentication or reusing the browser existent authentication header (if possible)?

Thanks

**Comment by lmangani** [comment]
Hi @danielmotaleite this is not broken or a workaround, rather an example configuration from our community others have used successfully, to be used as a starting point. SENTINL is not in charge of passing authentication details other than those explicitly set in its config.

The methods SENTINL uses can be extended if needed, so feel free to open a feature request.
