### ISSUE TITLE
How to create alert like this?

### ISSUE THREAD

**Issue by Teressss** [sirensolutions/sentinl#432]
Hi, I am new to sentinl. I have it running, connect it to my slack channel. I really miss some tutorials ( I saw lot of webs about it but didn't found any forum etc.)
My question is simple. I want to create an alert, which should send me a notification to slack. I want send there all messages which I can filter in Discover by this: 
"app:kernel AND severity:err".
I really have no idea how to it.
Can anyone please help me?
Thanks a lot. 
Teresa

**Comment by lmangani** [comment]
Hi,

The field is pretty broad on this one, so I'll try to provide an example to play and learn with - you'll have to adjust queries, settings and BYO patience. I assume you can generate the above query in Elasticsearch already, and will be able to port it in a watcher and iterate its response structure.

#### Pipeline
`input` -> `condition` -> `action`

#### Config
First of all, you should extend your Kibana yaml settings to include a SENTINL slack configuration:
```
sentinl:
  settings:
    slack:
      active: true
      username: username
      hook: 'https://hooks.slack.com/services/<your_custom_token>'
      channel: '#your_custom_channel'
```
#### Watcher w/ Slack Action
Once this is set, you can create a watcher feeding it - Here's a basic example - Please don't use this *AS-IS* but rather extract and understand its components to recreate them in your setup:
```
{
  "_id": "new",
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 5 minutes"
      }
    },
    "input": {
      "search": {
        "query": {
          "bool" : {
                "must" : {
                  "term" : { "app" : "kernel" }
                },
                "filter": {
                  "term" : { "severity" : "err" }
                }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 1"
      }
    },
    "transform": {},
    "actions": {
      "slack_notify": {
        "throttle_period": "15m",
        "slack": {
          "channel": "#alerts",
          "message": "SENTINL Alert! Found {{payload.hits.total}} Kernel Errors"
        }
      }
    }
  }
}
```

Once this works, you can start playing with mustache to iterate through the results, and include them in the Slack notification. 

I hope this helps

**Comment by vainkop** [comment]
In 6.2.4 I get the following error when using this kibana.yaml, even though it worked with 6.2.2. Did the format change?
`Plugin installation was unsuccessful due to error "child "sentinl" fails because [child "settings" fails because [child "slack" fails because ["username" is not allowed, "hook" is not allowed]]]"`
