### ISSUE TITLE
How can I add content of message to alert text?

### ISSUE THREAD

**Issue by koinoyokan17** [sirensolutions/sentinl#433]
1. Sentinl and Kibana version - 5.6.6

2. I want to add content of messages that match my query. Please, check out screenshot (it can be hard to understand what I want to, sorry for this) - http://take.ms/8Bn3K
For example, on screenshot we can see field apache2.access.url - i want to see value in my alert text.

5. Provided on screenshot. Test kibana is available at https://demo.elastic.co/

**Comment by lmangani** [comment]
I'm sorry we can't provide per case support in such detail. Please check out older issues and the examples in our docs, and try to build your first watcher. Sometimes its as simple as creating a widget and using the SPY watcher creator to initiate a template. Once you do so, we'll be more than happy to help you overcome doubts and blockers. Thanks for understanding!
