### ISSUE TITLE
Need some information about sentinl interface

### ISSUE THREAD

**Issue by ly2ly** [sirensolutions/sentinl#437]
Hello, I have some questions about sentinel watchers configuration.
In the documentation I dont find any information about Alarm and Report menu. How these menu works?
![alarm](https://user-images.githubusercontent.com/7696009/40596827-f7ba7b7c-622c-11e8-92ba-28fdd8cb2c11.png)

In the watcher action view for email, what is the signification and utility of the fields: 
throttle
Priority
checkbox save / crop / stateless
Delay
![email](https://user-images.githubusercontent.com/7696009/40596876-4dceb730-622d-11e8-978d-e02bdd680e2d.png)

**Comment by lmangani** [comment]
Hi @ly2ly 

The `alarm` and `report` pages simply show the results produced by respective watchers, not menus. What you see is what you get in terms of their usage. The other items are pretty standard items in monitoring and easy to try and discover:
 
* `throttle`: avoid sending the same condition alert for a determined period
* `priority`: classification of an alert, up to you and your destination
* `checkbox save / crop / stateless`: affect if and how the payload is saved with alerts
* `delay`: delay before a report screenshot is taken to allow pages preloading

Hope this helps!

**Comment by ly2ly** [comment]
Cool, thanks...
