### ISSUE TITLE
I am facing problem in writing condition for Memory usage gauge (Metricbeat System)?? Can someone help??

### ISSUE THREAD

**Issue by SakshamSaxena97** [sirensolutions/sentinl#438]
1. Sentinl and Kibana version -6.2.2 

--Problem in writing condition for Memory usage gauge (Metricbeat System)

**Comment by lmangani** [comment]
@SakshamSaxena97 feel free to open a clean issue with the attemtp + error and we'll happily help. There is no need to write everything in the title, but rather follow the issue template. Thanks!
