### ISSUE TITLE
Code running on Elastic Watcher but not on Sentinl !!

### ISSUE THREAD

**Issue by SakshamSaxena97** [sirensolutions/sentinl#440]
1. Sentinl and Kibana version - 6.2.2

**Code on Elastic Watcher which is working fine!!!!**
PUT _xpack/watcher/watch/filesystem
'''{
  "metadata": {
    "threshold": 0.9,
    "window_period": "5m"
  },
  "trigger": {
    "schedule": {
      "interval": "5m"
    }
  },
  "input": {
    "search": {
      "request": {
        "indices": [
          "logs"
        ],
        "types": [
          "filesystem"
        ],
        "body": {
          "aggs": {
            "host": {
              "terms": {
                "field": "hostname",
                "order": {
                  "disk_usage": "desc"
                }
              },
              "aggs": {
                "disk_usage": {
                  "max": {
                    "field": "used_p"
                  }
                }
              }
            }
          },
          "query": {
            "bool": {
              "filter": [
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-{{ctx.metadata.window_period}}"
                    }
                  }
                },
                {
                  "range": {
                    "used_p": {
                      "gte": "{{ctx.metadata.threshold}}"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  },
  "condition": {
    "compare": {
      "ctx.payload.hits.total": {
        "gt": 0
      }
    }
  },
  "transform": {
  "script": {
    "lang": "painless",
    "source": "def threshold_p = ctx.metadata.threshold*100; return [ 'threshold': (int)threshold_p, 'hosts': ctx.payload.aggregations.host.buckets.stream().map(p -> [ 'key': p.key, 'disk_usage': (int) (p.disk_usage.value*100)]).collect(Collectors.toList()) ];"
  
}
  },
  "actions": {
    "send_email": {
      "email": {
        "profile": "standard",
        "to": ["saksham.saxena@gmail.com"],        
        "subject": "Cluster Status Cool",
        "body": {
          "text": "Some hosts are over {{ctx.payload.threshold}}% utilized:{{#ctx.payload.hosts}}{{disk_usage}}%-{{key}}:{{/ctx.payload.hosts}}"
        }
      }
    }
  }
}
'''

**Same code formulated in Sentinl raising "Failed to get watcher"** 
 Code:- 
'''
{
  "actions": {
    "email_admin": {
      "throttle_period": "0h2m0s",
      "email": {
        "to": "saksham.saxena@gmail.com",
        "from": "sakshamsaxena@localhost",
        "subject": "Alarm",
        "priority": "high",
        "body": "\"Some hosts are over {{ctx.payload.threshold}}% utilized:{{#ctx.payload.hosts}}{{disk_usage}}%-{{key}}:{{/ctx.payload.hosts}}\""
      }
    },
    "New slack action 5fpe0msps0j": {
      "throttle_period": "0h1m1s",
      "slack": {
        "channel": "#test",
        "message": "\"Some hosts are over {{ctx.payload.threshold}}% utilized:{{#ctx.payload.hosts}}{{disk_usage}}%-{{key}}:{{/ctx.payload.hosts}}\"",
        "stateless": false
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "indices": [
          "logs"
        ],
        "types": [
          "filesystem"
        ],
        "body": {
          "aggs": {
            "host": {
              "terms": {
                "field": "hostname",
                "order": {
                  "disk_usage": "desc"
                }
              },
              "aggs": {
                "disk_usage": {
                  "max": {
                    "field": "used_p"
                  }
                }
              }
            }
          },
          "query": {
            "bool": {
              "filter": [
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-{{ctx.metadata.window_period}}"
                    }
                  }
                },
                {
                  "range": {
                    "used_p": {
                      "gte": "{{ctx.metadata.threshold}}"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  },
  "condition": {
    "compare": {
      "ctx.payload.hits.total": {
        "gt": 0
      }
    }
  },
  "transform": {
    "script": {
      "lang": "painless",
      "source": "def threshold_p = ctx.metadata.threshold*100; return [ 'threshold': (int)threshold_p, 'hosts': ctx.payload.aggregations.host.buckets.stream().map(p -> [ 'key': p.key, 'disk_usage': (int) (p.disk_usage.value*100)]).collect(Collectors.toList()) ];"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 5 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "watcher_title"
} 
'''

**Could someone help????**

**Comment by lmangani** [comment]
Generally speaking, you should not copy paste a full watcher, but rather recycle its parts understanding the differences between the two. SENTINL supports the watcher configuration style as far as possible, but does not support "painless" or other server-side scripting. Keep in mind, SENTINL Watchers do notexecute within Elasticsearch (as per X-Pack) but rather within a Kibana backend. You'll need to port any logic in `condition` and `transform` to use plain Javascript. I hope this helps.

**Comment by SakshamSaxena97** [comment]
Thanks @lmangani

**Comment by lmangani** [comment]
@SakshamSaxena97 I'm afraid I don't speak `painless` or 'groovy++' enough to help you with this, but it should be trivial to reproduce whatever it's doing in plan Javascript if you can explain the exact logic.

**Comment by SakshamSaxena97** [comment]
Lets take a fairly smaller query in which I wish to setup cluster health watcher. If cluster health status is red , then alert is generated on the email. It wud be gr8 if u cud help me with the sentinl-script.
