### ISSUE TITLE
Alerts even with zero payload

### ISSUE THREAD

**Issue by Teressss** [sirensolutions/sentinl#441]
So finaly with big help of Imangani I have working alert with all fields I want. Problem is, I am getting these alerts to email and Slack each minute (as I set up), even when it is empty. My condition is payload.hits.total > 0 so I thought when there is ZERO payload, than alert messages will not be sent.
So what am I to do, that alerts will be sent only when there is minimum one payload and when there is zero payload then no alerts will be sent?

**Comment by Teressss** [comment]
I've already solved it myself...

**Comment by soniahjs** [comment]
How did you solve it please? i'm getting the same issue
