### ISSUE TITLE
Alert events have time 2 hours shifted

### ISSUE THREAD

**Issue by Teressss** [sirensolutions/sentinl#442]
Hi, all my events in ES or Logtrail have correct timestamp for example 4 pm. But Sentinl alerts comes with timestamp 2 pm., 2 hours shifted back. How can I repair it?
Thanks

**Comment by lmangani** [comment]
Hi,
This is answered in the FAQ/Documentation: http://sentinl.readthedocs.io/en/latest/FAQ/#watchers-are-not-running-in-my-timezone-why

**Comment by lmangani** [comment]
Keep in mind SENTINL runs within Kibana, so it will inherit time settings accordingly.

**Comment by Teressss** [comment]
> Keep in mind SENTINL runs within Kibana, so it will inherit time settings accordingly.
Yes I know, but ES, Kibana and Logtrail shows correct timestamp, only Sentinl alerts are time shifted.

**Comment by Teressss** [comment]
In another words if Sentinl would take timestamps from Kibana, then it would be fine, because Kibana shows correct timestamp, but Sentinl shows incorrect timestamp, 2 hours shifted back. That's why I opened this ticket.

**Comment by lmangani** [comment]
It's not incorrect, SENTINL internally uses UTC in order to handle multiple data sources in multiple timezones. The timezone is adapted back by the BROWSER when displaying it using the host settings. SENTINL will not take timestamps from "events" but rather from the SYSTEM running Kibana.

**Comment by Teressss** [comment]
As I told you, my system has correct time.

**Comment by lmangani** [comment]
That's great - I suggest you hire a consultant to resolve this.
