### ISSUE TITLE
question : how to enable or disable sentinl  without delete plugins/sentinl ?

### ISSUE THREAD

**Issue by zqc0512** [sirensolutions/sentinl#443]
question : how to enable or disable sentinl  without delete plugins/sentinl ?
a users need can't see the sentinl table in kibana,the  orther is need .
sentinl 5.x with es 5.x.
thanks.

1. Sentinl and Kibana version 

2. Issue description

3. Reproducing the issue step-by-step

4. Expected results vs. actual results

5. Sample of data

6. Additional details

**Comment by lmangani** [comment]
Hi @zqc0512 are you asking for a method to trigger the `enable` status of a watcher without using the UI?

**Comment by lmangani** [comment]
http://sentinl.readthedocs.io/en/latest/FAQ/#can-i-disable-a-watcher-without-deleting-it
