### ISSUE TITLE
Conversion from painless to workable js

### ISSUE THREAD

**Issue by SakshamSaxena97** [sirensolutions/sentinl#444]
**1. Sentinl and Kibana version- 6.2.2** 

2. Issue description
**Watchers: fail to get watcher** on running sentinl watcher.

The problem occurs in my transform script I suppose:
{
"script" : {
"source": "return [ 'hosts' : ctx.payload.aggregations.hosts.buckets.stream().map(b -> b.key).collect(Collectors.toList())]"
"lang": "painless"
}
}

**Could someone help me in converting this sccript to workable javascript for sentinl to run!!**

**Comment by lmangani** [comment]
Honestly, this is the wrong approach to the problem. You should rather understand what your original script does, how this applies to your query response, and attempt describing the desired outcome here for advice. If you're copying this from some example, please post a link to the full article.

**Comment by lmangani** [comment]
Closing as this is not an Issue, but happy to push in the right direction. Feel free to attach a full example here for advice as per above.
