### ISSUE TITLE
Getting Error 406!! Need help !! 

### ISSUE THREAD

**Issue by SakshamSaxena97** [sirensolutions/sentinl#446]
**Sentinl and Kibana version - 6.2.2**

Getting Error 406 !! 
I am trying to apply a basic Cluster_Status Sentinl Watcher in which I m getting Error 406.

My raw code looks like this: 
```
{
  "actions": {
    "email": {
      "throttle_period": "0h2m0s",
      "email": {
        "to": "saksham.saxena@random.com",
        "from": "sakshamsaxena@localhost",
        "subject": "Alarm-sentinl",
        "priority": "high",
        "body": "Cluster Status is Yellow."
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "scheme": "http",
        "host": "localhost",
        "port": 9200,
        "method": "get",
        "path": "/_cluster/health",
        "params": {},
        "headers": {},
        "index": [],
        "body": {}
      }
    }
  },
  "condition": {
    "compare": {
      "ctx.payload.status": {
        "eq": "yellow"
      }
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 5 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "watcher_status"
}
```

I apologize for asking such silly questions but I m fairly new to Lucene and Sentinl as well!! It wud be great if anyone cud help me with this problem!!

**Comment by lmangani** [comment]
How did you generate this watcher? The input query does not seem to be valid.
Please use the SPY Watcher generator from a Visualization showing the data you care to alert on.

**Comment by lmangani** [comment]
406 is due to invalid input query, not an issue with SENTINL. Closing, but feel free to paste questions.
