### ISSUE TITLE
Sentinl configuration with SearchGuard

### ISSUE THREAD

**Issue by ly2ly** [sirensolutions/sentinl#447]
Hello,

I am on kibana 6 made configuration of Sentinl 6 watcher with SearchGuard 6 Portail, but when I receive report in pdf and png I receive an image of my searchguard portail.
I set up username and password inside the watcher configuration but nothing happen.
Are there any other configuration to do?
![my report apsarl leads 1 png](https://user-images.githubusercontent.com/7696009/40975054-2ed09604-68b9-11e8-816a-0b094b0cf671.png)

Edit: After some search I find someone who solve the same problem but I am a noob and I don't understand the configuration. 
https://github.com/sirensolutions/sentinl/issues/407

**Comment by ly2ly** [comment]
I finish to understand...
The solution was escape the parameter of searchguard login portail with a "\"
as
        custom:
          username_input_selector: '#sg\.username'
          password_input_selector: '#sg\.password'
          login_btn_selector: '#sg\.login'

**Comment by lmangani** [comment]
Glad you got this solved. Were you confused by the documentation or any example specifically?

**Comment by ly2ly** [comment]
No finally I understand that I am a very big noob...
But it will be interesting if you give more explanation about parameters or some real case exemples.
