### ISSUE TITLE
How to write a very complex condition?

### ISSUE THREAD

**Issue by Uvizor** [sirensolutions/sentinl#448]
Hi. I need a watcher that would send me a letter with switch ip and switch port that was flapping more than 1000 times yesterday and more than 1000 times day before yesterday. But before, I have this watcher
[watcher.txt](https://github.com/sirensolutions/sentinl/files/2080260/watcher.txt)
and this is output
[out.txt](https://github.com/sirensolutions/sentinl/files/2080258/out.txt)
How can i get "doc_count" for condition in this section
`"5" : {
                                  "doc_count_error_upper_bound" : 0,
                                  "sum_other_doc_count" : 0,
                                  "buckets" : [
                                    {
                                      "key" : "44436274",
                                      "doc_count" : 22871
                                    }
                                  ]
                                },`
Whith my current condition i only can get "doc_count" in section "4"
` "4" : {
                            "doc_count_error_upper_bound" : 0,
                            "sum_other_doc_count" : 4,
                            "buckets" : [
                              ...                              
                            ]
                          },
                          "key" : "10.50.6.25",
                          "doc_count" : 23726
                        }`
Can someone help me?
Kibana Version: 6.2.3

**Comment by lmangani** [comment]
Hi @Uvizor so you would like to iterate each `doc_count` item in aggregation `5` and matching any above `1000`?

**Comment by Uvizor** [comment]
Hi @lmangani yes, this is what i want start with

**Comment by lmangani** [comment]
That's simple, but the format is a little confusing. What is the `key` you care about? Could you make an example based on the output you pasted as of what the detections would be output as?

**Comment by Uvizor** [comment]
The end point is like this
**if** aggregation[5].buckets.doc_count > 1000 time("from" : "now/d-1d") **&&** aggregation[5].buckets.doc_count > 1000 time("from" : "1d-2d") **&&** aggregation[5].buckets.key is the same, **than** send an email with aggregation[5].buckets.doc_count && aggregation[5].buckets.key in it.

**Comment by lmangani** [comment]
You'll need to chain multiple watchers most likely - now, based on your example, you're not even entering the hits payload object. Here's something to play with, exploded for reading convenience;
```
var match = false;
var data = payload.hits.hits[0]._source.payload.aggregations[6].buckets.Flap_ports[3].buckets;
payload.offenders = data.reduce((offenders, item) => {
  if(item[4].buckets){
    item[4].buckets.forEach(function(sub){
        if (sub.doc_count > 1000) {
          match = true;
          offenders.push({key: item.key, count:sub[5].buckets[0].doc_count })
        }
    })
  }
  return offenders;
}, []);
return match;
```

#### output
```json
[{"key":"10.50.6.25","count":23710},{"key":"10.50.5.76","count":22871},{"key":"10.50.18.42","count":3612},{"key":"10.50.5.66","count":3536},{"key":"10.50.10.21","count":3131},{"key":"10.50.13.49","count":1958},{"key":"10.50.10.7","count":1565}]"
```
