### ISSUE TITLE
Feature request: specify operator when creating alerts from SPY

### ISSUE THREAD

**Issue by havlan** [sirensolutions/sentinl#456]
1. Sentinl and Kibana version 
Kibana: 6.2.4
Sentinl: 6.2.4 (tag 6.2.3.3)

2. Issue description
When creating alerts from visualizations it would be very useful to be able to specify what operator to use `>, <, >=, <=, ...` to be placed in the condition script.

3. Reproducing the issue step-by-step
Any visualization, create alert from SPY, then it automatically selects `>` to be used in the condition script.

4. Expected results vs. actual results

5. Sample of data

6. Additional details
Opening the discussion on whether it's possible or not. A dropdown/list could solve the issue.

**Comment by lmangani** [comment]
Hi @havlan indeed the SPY generator is extremely limited and only creates a template to be manually edited in the wizard within SENTINL. We've tried adding all sorts of options to the SPY widget in the past but they turned against us. We'll review if the components can now be used there as well.

**Comment by havlan** [comment]
@lmangani could you elaborate on what went wrong? This issue and #454 would make it easier for an end user to use. (both technical and non-technical users)

**Comment by havlan** [comment]
X-pack alerting lets you specify "Is above" or "Is under", which could be a good starting point.

**Comment by lmangani** [comment]
@havlan the core idea is for the SPY to only push enough data to our widget, and handle all the preferences there at once based on the provided request and query parameters. Happy to check out your PR for #454 and make sure this case is covered in the same context. Thanks for your participation and discussion points, much appreciated!

**Comment by havlan** [comment]
@lmangani  No worries! I will look into it. What branch do you want the pr?
I understand that the SPY widget works just as a default site. But enhancing the end users ability to do "everything" from SPY->wizard would decrease the amount of manual editing required to make a functional watcher.

**Comment by sergibondarenko** [comment]
@havlan you are welcome to do the PR against master branch. Then we test it, improve if necessary and merge.

**Comment by havlan** [comment]
@sergibondarenko @lmangani 
After some thought I guess the '==' operator will sometimes confuse the users, they expect it to hit exactly when the result is equals. Which may never happen, it all depends on the rate of change and which schedule they are using...
