### ISSUE TITLE
Duplicate Emails sent by Sentinl

### ISSUE THREAD

**Issue by smhulkund** [sirensolutions/sentinl#460]
1. Sentinl and Kibana version 
6.2.2

2. Issue description

> Duplicate Emails sent by Sentinl
>   1. Tried changing throttle_period
>   2. Recreated reporter & watcher using wizard
> 

3. Sample data - Raw Anonymized JSON 

```
{
  "actions": {
    "Report": {
      "throttle_period": "0h1m0s",
      "report": {
        "to": "jane@doe.com",
        "from": "john@doe.com",
        "subject": "Report",
        "body": "Report",
        "save": true,
        "snapshot": {
          "res": "1920x1080",
          "url": "Kibana Dashboard URL ---  Every 1 hour"
          "path": "/tmp/",
          "type": "pdf",
          "params": {
            "delay": 30000,
            "username": "_XX_",
            "password": "_XX_"
          },
          "name": "Report"
        }
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [],
        "body": {}
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 100"
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 1 hour"
    }
  },
  "disable": false,
  "report": true,
  "title": "Report"
}
```

I am not sure what is it that i am missing ?

**Comment by lmangani** [comment]
@smhulkund I'm not sure I understand. The watcher seems to run every hour. How many emails are received, and when?

**Comment by smhulkund** [comment]
Apologies for not being clear, when the watcher is triggered every hour it sends out two emails ( attached screen shot )

![duplicate](https://user-images.githubusercontent.com/28353590/41486602-2f353f1c-70b3-11e8-9814-ca8a837c50d9.png)

**Comment by sergibondarenko** [comment]
@smhulkund 
Do you have multiple watchers? Disable all of them except the one you test now.
Could you please try master branch and tell me if you still have those duplicates?
Instruction to test the master is below.

Delete Sentinl:
```
cd kibana
rm -rf kibana/plugins/sentinl
rm -rf kibana/optimize/bundles/*
```

Install Sentinl from master branch:
```
git clone https://github.com/sirensolutions/sentinl
cd sentinl
gulp sync --kibanahomepath=/path/to/kibana/
```
 
Restart Kibana.

**Comment by smhulkund** [comment]
Thank you @sergibondarenko, i wouldn't want to clone on a production system.

Will tar and untar of master branch work ?

**Comment by sergibondarenko** [comment]
You can do
```
wget --no-check-certificate https://github.com/sirensolutions/sentinl/archive/master.zip
unzip master.zip
cd sentinl-master
gulp sync --kibanahomepath=/path/to/kibana
```
You need Internet connection and access to npm in order to allow Sentinl install its dependencies.

**Comment by sergibondarenko** [comment]
Or you can build a release from master branch:

1. Clone Sentinl repo to a test computer and build a release from master:
```
gulp package --version="sentinl-master-6.2.2" && mv ../target/gulp/sentinl* ~/Downloads
```
2. After build is finished the release is available in `~/Downloads/sentinl-master-6.2.2.zip`, move the archive to the production server. 
3. Install it:
```
kibana/bin/kibana-plugin install file:///home/your user name here/Downloads/sentinl-master-6.2.2.zip
```

**Comment by smhulkund** [comment]
Thank you @sergibondarenko, although i followed the procedure, the duplication problem exists. 

It turns out we have 2 instance of sentinl running, this was causing the email duplication. Disabling report on one ( i.e kibana2 ) solved the problem.

![image](https://user-images.githubusercontent.com/28353590/41784966-32c2198c-760f-11e8-8698-ec60fc915ce1.png)

Well, does sentinl support this kind of setup ?

**Comment by lmangani** [comment]
Hi @smhulkund the clustering feature is currently only available in the Siren stack
The only approach possible is to install SENTINL only on a single node at this time

**Comment by smhulkund** [comment]
Thank you @lmangani
