### ISSUE TITLE
Ehancement idea: report templates

### ISSUE THREAD

**Issue by ly2ly** [sirensolutions/sentinl#461]
Hello,

I think about some ideas for ehancements. It will be interesting if users can create report templates in order to reuse them. Another possibility is to be able to do duplicate of existing reports and/or templates.

**Comment by sergibondarenko** [comment]
You can do this:
1. Go to the Raw tab and copy all contents. 
2. Create a new watcher. 
3. Go to the Raw tab of the new watcher and paste what you copied during the first step.

But I agree, a copy button will be easier.

**Comment by lmangani** [comment]
@sergibondarenko we can add a "clone" option or "create from existing watcher" perhaps?
