### ISSUE TITLE
Kibana 6.3.0

### ISSUE THREAD

**Issue by joshsmoore** [sirensolutions/sentinl#463]
Hi I am just wondering if Kibana 6.3.0 support would be happening soon.  If not is there a way I can try to bundle the 6.2.4 plugin with Kibana 6.3.0?

Thanks,

Josh

**Comment by koinoyokan17** [comment]
Hello,
You can build from source and set version to 6.3.0 to check.

**Comment by zozo6015** [comment]
I have trued to build it from source and install it. However the build was successfull but the installation failed with the following error:

``` /usr/share/kibana/bin/kibana-plugin install file:////root/sentinl/target/gulp/sentinl-v6.3.0.zip
Attempting to transfer from file:////root/sentinl/target/gulp/sentinl-v6.3.0.zip
Transferring 98814199 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false --uiSettings.enabled=false
(node:17509) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL Error: [plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })
    at applySpecDefaults (/usr/share/kibana/src/ui/ui_exports/ui_export_types/ui_apps.js:31:11)
    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/map_spec.js:14:95
    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/alias.js:13:83
    at specs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:42)
    at Array.reduce (<anonymous>)
    at types.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:20)
    at Array.reduce (<anonymous>)
    at pluginSpecs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:20:18)
    at Array.reduce (<anonymous>)
    at reduceExportSpecs (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:16:22)
    at collectUiExports (/usr/share/kibana/src/ui/ui_exports/collect_ui_exports.js:19:50)
    at KbnServer.uiExportsMixin (/usr/share/kibana/src/ui/ui_exports/ui_exports_mixin.js:11:66)
    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)
    at KbnServer.uiMixin (/usr/share/kibana/src/ui/ui_mixin.js:27:19)
    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)
    at <anonymous>

{"type":"log","@timestamp":"2018-06-19T12:38:30Z","tags":["warning","config","deprecation"],"pid":17509,"message":"uiSettings.enabled is deprecated and is no longer used"}
{"type":"error","@timestamp":"2018-06-19T12:38:46Z","tags":["fatal"],"pid":17509,"level":"fatal","error":{"message":"[plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })","name":"Error","stack":"Error: [plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })\n    at applySpecDefaults (/usr/share/kibana/src/ui/ui_exports/ui_export_types/ui_apps.js:31:11)\n    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/map_spec.js:14:95\n    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/alias.js:13:83\n    at specs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:42)\n    at Array.reduce (<anonymous>)\n    at types.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:20)\n    at Array.reduce (<anonymous>)\n    at pluginSpecs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:20:18)\n    at Array.reduce (<anonymous>)\n    at reduceExportSpecs (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:16:22)\n    at collectUiExports (/usr/share/kibana/src/ui/ui_exports/collect_ui_exports.js:19:50)\n    at KbnServer.uiExportsMixin (/usr/share/kibana/src/ui/ui_exports/ui_exports_mixin.js:11:66)\n    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)\n    at KbnServer.uiMixin (/usr/share/kibana/src/ui/ui_mixin.js:27:19)\n    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)\n    at <anonymous>"},"message":"[plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })"}
"
```

**Comment by lmangani** [comment]
Thanks for trying. Those are core changes in Kibana we'll have to adjust with, as usual. Please standby for an official 6.3.0 SENTINL release and feel free to send a PR - the change is explained in the error itself.

**Comment by RealLinkers** [comment]
It is very easy to solve it yourself.
Just go to index.js, find the section:

`        injectVars: function (server, options) {
          var config = server.config();
          return {
            kbnIndex: config.get('kibana.index'),
            esShardTimeout: config.get('elasticsearch.shardTimeout'),
            esApiVersion: config.get('elasticsearch.apiVersion'),
            sentinlConfig: {
              appName: config.get('sentinl.app_name'),
              es: {
                watcher: {
                  schedule_timezone: config.get('sentinl.es.watcher.schedule_timezone')
                }
              }
            }
          };
        }`

Remove that line and place server.injectUiAppVars after that your code should look like the example below. Everything is working for me now.

`  return new kibana.Plugin({
    require: requirements,
    uiExports: {
      spyModes: ['plugins/sentinl/dashboard_spy_button/alarm_button'],
      mappings: require('./server/mappings/sentinl.json'),
      app: {
        title: 'Sentinl',
        description: 'Kibana Alert App for Elasticsearch',
        main: 'plugins/sentinl/app',
        icon: 'plugins/sentinl/style/sentinl.svg',
      },
    },
	server: {
		injectUiAppVars: 
		  function (server, options) {
          var config = server.config();
          return {
            kbnIndex: config.get('kibana.index'),
            esShardTimeout: config.get('elasticsearch.shardTimeout'),
            esApiVersion: config.get('elasticsearch.apiVersion'),
            sentinlConfig: {
              appName: config.get('sentinl.app_name'),
              es: {
                watcher: {
                  schedule_timezone: config.get('sentinl.es.watcher.schedule_timezone')
                }
              }
            }
          };
        }
	},`

**Comment by InspurKelly** [comment]
@RealLinkers 
I follow you settings, but don't work.

Error: [$injector:unpr] Unknown provider: sentinlConfigProvider <- sentinlConfig <- EditorController
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=sentinlConfigProvider%20%3C-%20sentinlConfig%20%3C-%20EditorController
    at vendors.bundle.js:133
    at vendors.bundle.js:133
    at Object.getService [as get] (vendors.bundle.js:133)
    at vendors.bundle.js:133
    at getService (vendors.bundle.js:133)
    at injectionArgs (vendors.bundle.js:133)
    at Object.instantiate (vendors.bundle.js:133)
    at vendors.bundle.js:133
    at Object.link (vendors.bundle.js:159)
    at vendors.bundle.js:133
    at invokeLinkFn (vendors.bundle.js:133)
    at nodeLinkFn (vendors.bundle.js:133)
    at compositeLinkFn (vendors.bundle.js:133)
    at vendors.bundle.js:133
    at vendors.bundle.js:133
    at boundTranscludeFn (vendors.bundle.js:133) "<div class="application" ng-class="'tab-' + chrome.getFirstPathSegment() + ' ' + chrome.getApplicationClasses()" ng-view="">"

Have you encountered this problem? If you know, please tell me, Thank you!

**Comment by karinskyolga** [comment]
I also receive a similar error message:

Error: [$injector:unpr] Unknown provider: sentinlConfigProvider <- sentinlConfig
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=sentinlConfigProvider%20%3C-%20sentinlConfig
    at vendors.bundle.js:133
    at vendors.bundle.js:133
    at Object.getService [as get] (vendors.bundle.js:133)
    at vendors.bundle.js:133
    at getService (vendors.bundle.js:133)
    at injectionArgs (vendors.bundle.js:133)
    at Object.invoke (vendors.bundle.js:133)
    at extend.instance (vendors.bundle.js:133)
    at nodeLinkFn (vendors.bundle.js:133)
    at compositeLinkFn (vendors.bundle.js:133)
    at nodeLinkFn (vendors.bundle.js:133)
    at compositeLinkFn (vendors.bundle.js:133)
    at compositeLinkFn (vendors.bundle.js:133)
    at compositeLinkFn (vendors.bundle.js:133)
    at compositeLinkFn (vendors.bundle.js:133)

**Comment by lmangani** [comment]
@karinskyolga there is NO release for 6.3.0 yet. Those are known issues, but there is no purpose in trying to run 6.2 SENTINL in 6.3 Kibana (as per previous versions)
