### ISSUE TITLE
Feature request: Add watcher title as a column in alerts tab table

### ISSUE THREAD

**Issue by havlan** [sirensolutions/sentinl#470]
1. Sentinl and Kibana version 
Kibana: 6.2.4
Elastic Search: 6.2.4
Sentinl: 6.2.4

2. Issue description
![screenshot from 2018-06-21 11-29-48](https://user-images.githubusercontent.com/18334546/41711024-61c0515e-7547-11e8-9bdf-7a0d71c7d12d.png)
In the image above it would be useful to know which alarm triggered, by displaying its title. For example with an extra column.

3. Reproducing the issue step-by-step
Create any alarm and execute it, preview the Alerts tab.

4. Expected results vs. actual results
An extra column with alarm title or something in the alerts tab.

5. Sample of data
Any data and an alarm which triggers

6. Additional details
This might apply to reports as well, but I'm not sure.

**Comment by havlan** [comment]
Ill gladly work on it, but I was wondering if it breaks security or if it's not wanted AS a feature

**Comment by lmangani** [comment]
The message allows for identifiers already (same problem would be at the receiver side AFAIK) but we can sure add this reference without breaking anything.

**Comment by havlan** [comment]
Okay. I'll reconsider whether if it's necessary or not.
Thanks.

**Comment by lmangani** [comment]
@havlan perhaps we could extend the current view to use a standard kibana table and let the users choose what "columns" they want to see instead to broaden the usefulness of such change?

**Comment by sergibondarenko** [comment]
@havlan here is the template where you need to change this https://github.com/sirensolutions/sentinl/blob/master/public/pages/alarms/alarms.html

**Comment by havlan** [comment]
@sergibondarenko @lmangani  
```JavaScript
 $scope.alarm_columns = [
    {
      name:'alarm._index',
      label:'Index',
      visible: true
    },
    {
      name: 'alarm._source[\'@timestamp\'] | dateFormat',
      label: 'Timestamp',
      visible: true
    },
    {
      name: 'alarm._source.watcher',
      label: 'Watcher',
      visible: true
    },
    {
      name:'alarm._source.level',
      label:'Level',
      visible: true
    },
    {
      name:'alarm._source.message',
      label:'Message',
      visible: false
    },
    {
      name:'alarm._source.action',
      label:'Action',
      visible: true
    },
    {
      name:'alarm._source.report',
      label:'Report',
      visible: true
    }
  ];
```
I successfully bind them to html elements so that you could make visible true or false (except timestamp). But I'm stuck on how  to create the table.
```html
<label ng-repeat="col in alarm_columns" ng-if="col.name!='_source.@timestamp'">
          <input type="checkbox" value="{{col.label}}" ng-model="col.visible">{{col.label}}
      </label>
```

**Comment by lmangani** [comment]
As discussed, the iteration should only happen within the `_source` object, eveything above it is Elasticsearch indexing and should not be presented in any case. If you instead wish to extend the set of stored fields, you can patch the [esHistory](https://github.com/sirensolutions/sentinl/blob/23591e823b1676840aeb3f0ed03eab1c8533edbf/server/lib/actions/do_actions.js#L234) invokation for a specific action.
