### ISSUE TITLE
Unable to specify message when creating new actions

### ISSUE THREAD

**Issue by havlan** [sirensolutions/sentinl#473]
1. Sentinl and Kibana version 
Kibana: 6.2.4
Sentinl: 6.2.4 (master)

2. Issue description
Unable to specify message when creating new actions in sentinl.

First image: https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.3-3/sentinl-v6.2.4.zip
![screenshot from 2018-06-22 13-49-05](https://user-images.githubusercontent.com/18334546/41775181-35bb674c-7623-11e8-8a1a-6e20de74d009.png)

Second image: https://github.com/sirensolutions/sentinl master branch
![screenshot from 2018-06-22 13-48-51](https://user-images.githubusercontent.com/18334546/41775161-213f5382-7623-11e8-906d-ad5484feacf2.png)

3. Reproducing the issue step-by-step
(master)
In the process of creating a watcher I am unable to specify what message I would like to send.

4. Expected results vs. actual results
Expected is the first image.
Actual is the last image.

5. Sample of data

6. Additional details

**Comment by sergibondarenko** [comment]
I'll fix it today asap

**Comment by sergibondarenko** [comment]
The fix is available in the release packages https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.3-3
