### ISSUE TITLE
Do I need Siren Investigate?

### ISSUE THREAD

**Issue by zinefer** [sirensolutions/sentinl#474]
Sorry if this is a dumb question, but I am a little confused by the first line in the readme:
```SENTINL 6 extends Siren Investigate and Kibana with Alerting and Reporting```

Do I need Siren Investigate for SENTINL to work?

Thanks!

**Comment by lmangani** [comment]
You don't - SENTINL works with standard Kibana, but if/when you use Siren Investigate additional features are available (clustering, etc)
