### ISSUE TITLE
Unable to delete watcher/reporter actions

### ISSUE THREAD

**Issue by azelezni** [sirensolutions/sentinl#480]
1. Sentinl and Kibana version 
6.2.3

2. Issue description
When creating a new watcher or reporter, I'm unable to delete actions like the default "email_admin" or any other action that I add.

3. Reproducing the issue step-by-step
Create new watcher/reporter, try to delete the default "email_admin" action, no error is shown but action is not removed even after saving.

4. Expected results vs. actual results

5. Sample of data

6. Additional details

**Comment by sergibondarenko** [comment]
This related to https://github.com/sirensolutions/sentinl/issues/473
The fix will be available today.

**Comment by sergibondarenko** [comment]
The fix is available in the release packages https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.3-3
