### ISSUE TITLE
Watchers/Reporters actions are duplicated to new Watchers/Reporters

### ISSUE THREAD

**Issue by azelezni** [sirensolutions/sentinl#481]
1. Sentinl and Kibana version 
6.2.3

2. Issue description
When creating a new Watcher/Reporter, the default actions are duplicated from previously created Watchers/Reporters

3. Reproducing the issue step-by-step
Create a new Watcher/Reporter, add some custom actions and save.
Create another new Watcher/Reporter, don't add any actions and save, this watcher/reporter will have the same actions as the previous one.

4. Expected results vs. actual results

5. Sample of data

6. Additional details

**Comment by SnehaDoughnut** [comment]
I am facing the same issue. My new watcher configuration is not getting saved and not able to edit them in the UI,editor tab. Is there a way to configure watcher on command line ?

**Comment by sergibondarenko** [comment]
Hi @azelezni @SnehaDoughnut 
This issue was fixed. Get the updated package from the release https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.3-3
