### ISSUE TITLE
Installation issue // chrome_path" must be a string // 6.2.4

### ISSUE THREAD

**Issue by omarix** [sirensolutions/sentinl#492]
Hi,
Please I need your help to install sentinl , I faced the following error when install Sentinl on a fresh ELK installation 

Sentinl and Kibana version : 6.2.4
OS: ubuntu server 16.04

Installation issue // chrome_path" must be a string]

```
./kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/prerelease/sentinl-v6.2.4.zip
Found previous install attempt. Deleting...
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/prerelease/sentinl-v6.2.4.zip
Transferring 40956695 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
[sentinl] fail to make report engine executable: ENOENT: no such file or directory, scandir '/usr/share/kibana/plugins/sentinl/node_modules/puppeteer/.local-chromium'!
Plugin installation was unsuccessful due to error "child "sentinl" fails because [child "settings" fails because [child "report" fails because [child "chrome_path" fails because ["chrome_path" must be a string]]]]"
```

journalctl

```
Jul 06 01:18:46 es-lab-n2 kibana[22528]: [sentinl] fail to make report engine executable: ENOENT: no such file or directory, scandir '/usr/share/kibana/plugins/sentinl/node_modules/puppeteer/.local-chromium'!
Jul 06 01:18:47 es-lab-n2 kibana[22528]: {"type":"error","@timestamp":"2018-07-06T00:18:47Z","tags":["fatal"],"pid":22528,"level":"fatal","error":{"message":"Option \"report.executable_path\" was deprecated. Use \"report.chrome_path\" ins
Jul 06 01:18:47 es-lab-n2 kibana[22528]: FATAL Error: Option "report.executable_path" was deprecated. Use "report.chrome_path" instead!
```
Regards

**Comment by havlan** [comment]
Hi!
Did you read the comments below the release? Have you followed the doc?
Comment:
Added wizard to UI.

ATTENTION!!!
Master branch doesn't contain any new code. You should use only the attached .zip archive.
Default report engine - horseman (pahntomjs).
If you want to use enother report engine - puppeteer, you should know that Chrome is not included in the build. But you can setup chrome_path for system Chrome in kibana.yml, look [the doc](https://github.com/sirensolutions/sentinl/blob/master/docs/Config-Example.md#example-extended-1).


Post your kibana.yml file.

**Comment by sergibondarenko** [comment]
@omarix It was a bug, I fixed it. Please get the new package from here https://github.com/sirensolutions/sentinl/releases/tag/prerelease
Please note, it is a pre-release, not stable yet. Reopen the issue if you still have it.

**Comment by omarix** [comment]
Hi @sergibondarenko , 
we are evaluating Sential to swap ElastAlert and we are  imprisoned for you reactivity, (good point), 
Here my feedback , the installation completed with success except the Error ".local-chromium"
```
# ./kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/prerelease/sentinl-v6.2.4.zip
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/prerelease/sentinl-v6.2.4.zip
Transferring 40958031 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
[sentinl] fail to make report engine executable: ENOENT: no such file or directory, scandir '/usr/share/kibana/plugins/sentinl/node_modules/puppeteer/.local-chromium'!

Plugin installation complete
```
Another action was required to run the service which is:

```
# chown -R kibana:kibana /usr/share/kibana/plugins/sentinl
```
Thank you gain 

Regards.

Omar

**Comment by lmangani** [comment]
Hi @omarix 

Unlike PhantomJS, Chromium requires a bunch of extra dependencies on the system. At this time you should install chromium (with pupetteer global, if you like npm) on the target system running SENTINL, and provide the executable path for SENTINL to use in its configuration. Let us know if you need any help doing so.

**Comment by lmangani** [comment]
@omarix if ` /usr/share/kibana/plugins/sentinl/node_modules/puppeteer/.local-chromium` actually exists, try `chromod +x /usr/share/kibana/plugins/sentinl/node_modules/puppeteer/.local-chromium`  and restart SENTINL, this might also work.

**Comment by sergibondarenko** [comment]
@omarix alright, it is not an error, it is a warning. The message will be improved. 
The message means that the build doesn't include puppeteer chrome. By default, it uses another report engine - `horseman` (pahntomjs). Look the doc https://github.com/sirensolutions/sentinl/blob/master/docs/HOWTO-Create-Reports.md#sentinl-v6

**Comment by sergibondarenko** [comment]
@omarix But you can set puppeter to work instead of horseman. Then you should have chrome path too, look the config example, report section https://github.com/sirensolutions/sentinl/blob/master/docs/HOWTO-Create-Reports.md#sentinl-v6

**Comment by omarix** [comment]
Thanks @all for your support, I will test reports , in case facing any issue I will open a new thread 
Happy weekend 

Regards. 

Omar
