### ISSUE TITLE
Fatal Error while initialization:  uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })

### ISSUE THREAD

**Issue by RobOrville** [sirensolutions/sentinl#498]
1. Sentinl and Kibana version 
Version of Sentinl: 6.2.4 
Kibana version: 6.3.0

2. Issue description
While initialization of the plugin (use it first time) i got the following error:
kibana[31849]: FATAL Error: [plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })
kibana[31849]: at applySpecDefaults (/usr/share/kibana/src/ui/ui_exports/ui_export_types/ui_apps.js:31:11)
kibana[31849]: at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/map_spec.js:14:95
kibana[31849]: at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/alias.js:13:83
kibana[31849]: at specs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:42)
kibana[31849]: at Array.reduce (<anonymous>)
kibana[31849]: at types.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:20)
kibana[31849]: at Array.reduce (<anonymous>)
kibana[31849]: at pluginSpecs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:20:18)
kibana[31849]: at Array.reduce (<anonymous>)
kibana[31849]: at reduceExportSpecs (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:16:22)
kibana[31849]: at collectUiExports (/usr/share/kibana/src/ui/ui_exports/collect_ui_exports.js:19:50)
kibana[31849]: at KbnServer.uiExportsMixin (/usr/share/kibana/src/ui/ui_exports/ui_exports_mixin.js:11:66)
kibana[31849]: at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)
kibana[31849]: at KbnServer.uiMixin (/usr/share/kibana/src/ui/ui_mixin.js:27:19)
kibana[31849]: at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)
kibana[31849]: at <anonymous>
systemd[1]: kibana.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit kibana.service entered failed state.
systemd[1]: kibana.service failed.

3. Reproducing the issue step-by-step
To reproduce this issue you must create a offline-package of this plugin on a staging server and tar it. After this you put it into your kibana-plugins directory and untar it, after this, starting kibana in version 6.3.0 and you will see the error.

**Comment by sergibondarenko** [comment]
@RobOrville we haven't done 6.3.0 release yet. Coming soon.

**Comment by lmangani** [comment]
Closing. Watch out for official 6.3.0 in the coming weeks
