### ISSUE TITLE
How To Write sentinl input

### ISSUE THREAD

**Issue by cddisk2000** [sirensolutions/sentinl#500]
I Try To Write sentinl input search message Within 15 minutes but error 

this is my sentinl input  who can help me how to write  ( ELK Version 5.6.8 )

{
  "search": {
    "request": {
      "index": [
        "logstash-*"
      ],
      "body": {
        "query": {
          "match": {
            "message": "Accepted"
          },
          "range": {
            "@timestamp": {
              "gte": "now-15m"
            }
          }
        }
      }
    }
  }
}

![image](https://user-images.githubusercontent.com/32296520/42746873-80d77d8c-890c-11e8-8909-57a575989221.png)

**Comment by havlan** [comment]
Hi!
Whats your error message? Post some logs from Kibana when you are creating the watcher.

**Comment by cddisk2000** [comment]
Show Me This Error Log ( Web UI )
![image](https://user-images.githubusercontent.com/32296520/42750267-2d7870da-8919-11e8-909d-f7d666d201a0.png)

Console Error
![image](https://user-images.githubusercontent.com/32296520/42750305-5f0b79f8-8919-11e8-9931-76cd976ea3f5.png)

**Comment by lmangani** [comment]
@cddisk2000 your query is malformed as the error indicates. Mind SENTINL does not have its own DSL, our input queries are just valid Elasticsearch queries, and they should work as executed by CURL or Sense, etc.

I suggest to take your query, execute it manually via Kibana console until it produces results.
