### ISSUE TITLE
Transform script not updating payload

### ISSUE THREAD

**Issue by milevyo** [sirensolutions/sentinl#505]
HI every body, 
I am trying to be brief.

In Transformation panel, I reduced my script to something as simple as this (it was longer and more complex :) )
```
{
  "script": "payload.aggregations.events='test'"
}
```

the mustash script in message body is:
`Events: {{payload.events}}`

But i didn't get the expected result and the output was:
`Events: `

in the log file, it was reported that the transform was applied successfully.

**Comment by lmangani** [comment]
I'll try to be just as brief:  `payload.aggregations.events` != `payload.events`

**Comment by milevyo** [comment]
Thanks @lmangani , that was a typewriting mistake. I updated the post accordingly.

**Comment by lmangani** [comment]
Could you try storing your custom variable to the root payload object, ie:
```
{
  "script": "payload.events='test'"
}
```

**Comment by milevyo** [comment]
@lmangani , i tried it, without success.

**Comment by lmangani** [comment]
This unfortunately doesn't help and I cannot reproduce your issue so far - are the logs reporting any error as the watcher executes?

**Comment by milevyo** [comment]
Thank you @lmangani , maybe you can provide me a script that works in your machine for test purpose

**Comment by milevyo** [comment]
i can see a warning in the log: "no data was found that match the used \"script\" conditions"

my script condition is:
```
{
  "script": {
    "script": "payload.hits.total > 1"
  }
}
```

**Comment by lmangani** [comment]
In order to get any help we would need to see the actual response to your watcher query

**Comment by milevyo** [comment]
This is the action "mustash" script
```
Malware spreading noticed
{{#payload.aggregations.by_threat_name.buckets}}
Malware: {{{key}}} 
    Affected hosts: {{#count_host.buckets}}  {{key}} {{/count_host.buckets}} 
--------------------------------------------------------------
{{/payload.aggregations.by_threat_name.buckets}}


{{#payload.aggregations.by_threat_name.buckets}}
    { 
        "event": {
            "desc": "Malware spreading - {{{key}}}",
            "threath_name": {{{key}}},
            "affected_host":[{{affected_hosts}}]
            "severity": "critical",
            "severity-id": "4",
            "group": "known-bad",
            "tag": "malware"
        }
    },
{{/payload.aggregations.by_threat_name.buckets}}

```

is output is:
```

Malware spreading noticed
Malware: JS/Mindspark.K  Affected hosts ********  Affected hosts *************


    { 
        "event": {
            "desc": "Malware spreading - JS/Mindspark.K",
            "threath_name": JS/Mindspark.K,
            "affected_host":[]
            "severity": "critical",
            "severity-id": "4",
            "group": "known-bad",
            "tag": "malware"
        }
    },

```

we wanted to list all affected hosts in affected_host comas separated, all the output should be json compatible (to be parsed lately by other tools )

**Comment by milevyo** [comment]
This is the input query:
```

{
  "search": {
    "request": {
      "index": [
        "index-*"
      ],
      "body": {
        "query": {
          "bool": {
            "must": [
              {
                "range": {
                  "event.timestamp": {
                    "gte": "now-4h"
                  }
                }
              },
              {
                "term": {
                  "event.type": {
                    "value": "Threat"
                  }
                }
              },
              {
                "term": {
                  "event.source.type": {
                    "value": "Antivirus"
                  }
                }
              }
            ]
          }
        },
        "aggs": {
          "by_threat_name": {
            "terms": {
              "field": "event.name"
            },
            "aggs": {
              "count_host": {
                "terms": {
                  "field": "host.name"
                }
              },
              "malware_spreading": {
                "bucket_selector": {
                  "buckets_path": {
                    "total_host": "_count"
                  },
                  "script": "params.total_host > 1"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by lmangani** [comment]
Hi @milevyo 

The pipeline inside SENTINL is one way, as follows: 
```
request -> response -> condition -> transform -> action(s) w/ mustache
```

This means anything generated with `mustache` as part of the action is not going to be available to conditions or transforms - you should really be forming the array there and later use it to create the final output format.

**Comment by milevyo** [comment]
Hi @lmangani ,
I understand that, we wanted to do some transformation on the payload before displaying it with moustash.
actually , we wanted to stringify the array of affected hosts so that it can be displayed correctly in the end, and also eliminating the training comas after the lists

**Comment by milevyo** [comment]
Solved
this didn't work:

```
{
  "script": "payload.events='test'"
}
```

but this one did it:

```
{
  "script": {
    "script": "payload.message='test'"
  }
}
```
Thanks again @lmangani for your support.

**Comment by lmangani** [comment]
@milevyo DOH! i did not even notice that, but the docs seem correct. Thanks for confirming!

**Comment by milevyo** [comment]
beside that, I also had to do some character escaping before pasting the code.
I guess it would be better if the text area was reserved for the plain javascript, and hides those unnecessary thing (from js coder point-of-view).
