### ISSUE TITLE
Add possibility to define notification types

### ISSUE THREAD

**Issue by kayrus** [sirensolutions/sentinl#51]
By default "Set Watcher" button under the Kibana search results suggests you to define an email notification only. I suggest to show a dropdown with available notification types.

**Comment by lmangani** [comment]
This is implemented in the next version, will soon be released

**Comment by kayrus** [comment]
@lmangani could you link a commit/pull request?

**Comment by lmangani** [comment]
@kayrus this is in a private branch currently, we'll merge back in the coming hours hopefully - thanks for your patience! ;)

**Comment by lmangani** [comment]
@kayrus the latest version under the sentinl brand provides some additional programming for actions, still a basic update but any comments are welcome!

**Comment by kayrus** [comment]
Thanks, I'll test when I'll get some time

**Comment by lmangani** [comment]
feel free to reopen in case of need or additional input. Thanks for your report!
