### ISSUE TITLE
Sentinl should not chmod files at runtime

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/sentinl#511]
Code should not have to chmod its own components to executable at runtime. File permissions should be managed by an install script or other helper program at install time. 

The reason for this (and for #510) is that code should never be owned by the user that it runs as, so that security issues in the app do not allow a network attacker to overwrite code in the app and thus change its functionality.

```
Jul 24 09:16:04 xxxxxxxx.siren.solutions investigate[30856]: FATAL { Error: EPERM: operation not permitted, chmod '/opt/test101.kibisiem/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs'
Jul 24 09:17:42 xxxxxxxx.siren.solutions investigate[32296]: [sentinl] fail to make report engine executable: EPERM: operation not permitted, chmod '/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome'!
```

**Comment by mazadard** [comment]
I think I have a similar problem: 

{"type":"error","@timestamp":"2018-07-24T10:12:00Z","tags":["fatal"],"level":"fatal","error":{"message":"EPERM: operation not permitted, chmod '/usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs'","name":"Error","stack":"Error: EPERM: operation not permitted, chmod '/usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs'\n    at Error (native)\n    at fs.chmodSync (fs.js:1177:18)\n    at PluginPack.exports.default [as _provider] (/usr/share/kibana/plugins/sentinl/index.js:62:3)\n    at PluginPack.getPluginSpecs (/usr/share/kibana/src/plugin_discovery/plugin_pack/plugin_pack.js:50:25)\n    at MergeMapSubscriber.find$.mergeMap [as project] (/usr/share/kibana/src/plugin_discovery/find_plugin_specs.js:47:39)\n    at MergeMapSubscriber._tryNext (/usr/share/kibana/node_modules/rxjs/src/operator/mergeMap.ts:125:21)\n    at MergeMapSubscriber._next (/usr/share/kibana/node_modules/rxjs/src/operator/mergeMap.ts:115:12)\n    at MergeMapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at RefCountSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)\n    at RefCountSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at Subject.next (/usr/share/kibana/node_modules/rxjs/src/Subject.ts:61:17)\n    at ConnectableSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)\n    at ConnectableSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at MergeAllSubscriber.OuterSubscriber.notifyNext (/usr/share/kibana/node_modules/rxjs/src/OuterSubscriber.ts:13:22)\n    at InnerSubscriber._next (/usr/share/kibana/node_modules/rxjs/src/InnerSubscriber.ts:17:17)\n    at InnerSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at CatchSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)\n    at CatchSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at MergeMapSubscriber.notifyNext (/usr/share/kibana/node_modules/rxjs/src/operator/mergeMap.ts:151:24)\n    at InnerSubscriber._next (/usr/share/kibana/node_modules/rxjs/src/InnerSubscriber.ts:17:17)\n    at InnerSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at CatchSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)","code":"EPERM"},"message":"EPERM: operation not permitted, chmod '/usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs'"}

**Comment by andrewgdotcom** [comment]
Even if I have already set the executable bit on the offending files by hand, sentinl tries to set it anyway. The only workaround seems to be to change the ownership on the two files.

**Comment by havlan** [comment]
@andrewgdotcom change it to kibana user?
For developing I guess installing it as kibana would work. #494  
But this should be fixed permanently

**Comment by sergibondarenko** [comment]
@andrewgdotcom by default Chrome is not executable after Sentinl installation. 
```
kibana-plugin install file:///sentinl.zip
```
As a result puppeteer report engine doesn't work.

> File permissions should be managed by an install script or other helper program at install time.

How can you execute "an install script" during the above installing process?

**Comment by sergibondarenko** [comment]
@andrewgdotcom Kibana X-Pack does chmod for browser binary path too
```
trex@beast:~/Development/siren/kibana_6.2.4_xpack$ grep -rn chmod plugins/x-pack/plugins/reporting/export_types
plugins/x-pack/plugins/reporting/export_types/printable_pdf/server/lib/browsers/index.js:15:  chmod: promisify(fs.chmod, fs),
plugins/x-pack/plugins/reporting/export_types/printable_pdf/server/lib/browsers/index.js:32:    await fsp.chmod(binaryPath, '755');
```

**Comment by andrewgdotcom** [comment]
Then we need to open a bug against x-pack also ;-)

**Comment by lmangani** [comment]
@andrewgdotcom I believe according to their custom license if you open a bug against x-pack, your firstborn child becomes their property, so don't do that ;) Jokes aside, those ugly measure unfortunately exist for a reason we can discuss in a separate private thread.

**Comment by sergibondarenko** [comment]
@andrewgdotcom `chmod` is used in the most recent Kibana code. Plus they have tests for it. I think they know about `chmod`.
```
trex@beast:~/Development/siren/kibana$ grep -rn "chmod" x-pack/
x-pack/plugins/reporting/server/browsers/install.js:15:  chmod: promisify(fs.chmod, fs),
x-pack/plugins/reporting/server/browsers/install.js:41:    await fsp.chmod(binaryPath, '755');
x-pack/plugins/reporting/server/browsers/extract/__tests__/extract.js:91:      it(`Windows doesn't support chmod, so it's missing access tests. Windows is throwing EEXIST.`);
x-pack/plugins/reporting/server/browsers/extract/__tests__/extract.js:144:      it(`Windows doesn't support chmod, so it's missing access tests. Windows is throwing EEXIST.`);
```

**Comment by andrewgdotcom** [comment]
Issue moved to [sirensolutions/sentinl-private #682](https://github.com/sirensolutions/sentinl-private/issues/682) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sergibondarenko** [comment]
@mazadard Kibana user should have permission to execute 
```
chmod +x /usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs
```

**Comment by mazadard** [comment]
Thx! The problem was also about user config of kibana files. I set 'kibana' as owner to solve it.
