### ISSUE TITLE
Alarm not created , Watcher executed successfully.

### ISSUE THREAD

**Issue by rohitjangid96** [sirensolutions/sentinl#517]
This is my raw watcher file :

{
  "actions": {
    "": {
      "throttle_period": "0h0m1s",
      "email": {
        "to": "alarm@localhost",
        "from": "sentinl@localhost",
        "subject": "Alarm",
        "body": "hi"
      }
    },
    "New email action 4jp0reacvuk": {
      "throttle_period": "0h0m1s",
      "email": {
        "to": "alarm@localhost",
        "from": "sentinl@localhost",
        "subject": "Alarm",
        "body": "g",
        "save_payload": true
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "logstash-*"
        ],
        "body": {
          "query": {
            "match": {
              "message": "Error"
            }
          }
        }
      }
    }
  },
  "condition": {
    "compare": {
      "cvlpbatch1.cablevision.com": {
        "gt": 0
      }
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 40 second"
    }
  },
  "disable": false,
  "report": false,
  "title": "testingwatcher"
}
Here are the errors that I am getting in log files. My watcher is executed successfully but the alarms are not created.

{"type":"log","@timestamp":"2018-07-30T12:24:21Z","tags":["info","Sentinl","watcher sentinl-watcher:b3f63530-9192-11e8-babf-fbadee01329f"],"pid":19543,"message":"successfuly executed"}

{"type":"error","@timestamp":"2018-07-30T12:24:21Z","tags":["error","Sentinl","log_history"],"pid":19543,"level":"error","error":{"message":"[security_exception] action [indices:admin/create] is
unauthorized for user [kibana]","name":"Error","stack":"[security_exception] action [indices:admin/create] is unauthorized for user [kibana] :: {"path":"/watcher_alarms-2018.07.30/sentinl-alarm",
"query":{},"body":"{\"@timestamp\":\"2018-07-30T12:24:21.363Z\",\"watcher\":\"testingwatcher\",\"level\":\"INFO\",\"message\":\"hi\",\"action\":\"\",
\"payload\":{},\"report\":false}
","statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"action [indices:admin/create] is unauthorized for user [kibana]\"}],
\"type\":\"security_exception\",\"reason\":\"action [indices:admin/create] is unauthorized for user [kibana]\"},\"status\":403}"}\n at respond
(/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:295:15)\n at checkRespForFailure (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:254:7)\n at HttpConnector. (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n at IncomingMessage.bound (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n at emitNone (events.js:91:20)\n at IncomingMessage.emit (events.js:185:7)\n at endReadableNT (_stream_readable.js:974:12)\n at _combinedTickCallback (internal/process/next_tick.js:80:11)\n at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"message":"[security_exception] action [indices:admin/create] is unauthorized for user [kibana]"}
{"type":"error","@timestamp":"2018-07-30T12:24:21Z","tags":["error","Sentinl","log_history"],
"pid":19543,"level":"error","error":{"message":"[security_exception] action [indices:admin/create]
is unauthorized for user [kibana]","name":"Error","stack":"[security_exception] action [indices:admin/create] is unauthorized for user [kibana]
:: {"path":"/watcher_alarms-2018.07.30/sentinl-alarm","query":{},
"body":"{\"@timestamp\":\"2018-07-30T12:24:21.364Z\",\"watcher\":\"testingwatcher\",\"level\":\"INFO\",\"message\":\"g\",\"action\":\"New email action 4jp0reacvuk\",
\"payload\":{\"took\":0,\"timed_out\":false,\"_shards\":{\"total\":0,\"successful\":0,\"skipped\":0,\"failed\":0},\"hits\":{\"total\":0,
\"max_score\":0,\"hits\":[]}},\"report\":false}","statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",
\"reason\":\"action [indices:admin/create] is unauthorized for user [kibana]\"}],\"type\":\"security_exception\",\"reason\":\"action
[indices:admin/create] is unauthorized for user [kibana]\"},\"status\":403}"}\n at respond (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:295:15)\n
at checkRespForFailure (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:254:7)\n at HttpConnector.
(/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n
at IncomingMessage.bound (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n
at emitNone (events.js:91:20)\n at IncomingMessage.emit (events.js:185:7)\n at endReadableNT (_stream_readable.js:974:12)\n
at _combinedTickCallback (internal/process/next_tick.js:80:11)\n at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},
"message":"[security_exception] action [indices:admin/create] is unauthorized for user [kibana]"}

{"type":"log","@timestamp":"2018-07-30T12:24:21Z","tags":["warning"],"pid":19543,"message":"Detected an unhandled Promise rejection.
\nError: fail to store alarm testingwatcher, action "}
{"type":"log","@timestamp":"2018-07-30T12:24:21Z","tags":["warning"],"pid":19543,"message":"Detected an unhandled Promise rejection.
\nError: fail to store alarm testingwatcher, action New email action 4jp0reacvuk"}

**Comment by lmangani** [comment]
Hi @rohitjangid96 the error is pretty clear here:
```
[security_exception] action [indices:admin/create] is unauthorized for user [kibana]
```

You must be using some authentication plugin - check our [notes](http://sentinl.readthedocs.io/en/latest/Authentication/) for examples as of what we support.
