### ISSUE TITLE
alert (email action) when log have any of IP blacklist (.csv)

### ISSUE THREAD

**Issue by NurAdah** [sirensolutions/sentinl#518]
Hi! so i was wondering on how the csv file of blacklistip.csv (eg) are able to compare with the log.csv and produce action email alert if any of blacklist ip are to be found inside the log? Is it we used the condition in the 'watcher query' to compare or is there any other method ?

Thank you! :)

**Comment by lmangani** [comment]
I'm not sure I understand - is your data already in Elasticsearch or does it reside in a stand-alone csv file?

**Comment by NurAdah** [comment]
It is a stand alone csv file

**Comment by lmangani** [comment]
Not sure how we can help, SENTINL is based on Elasticsearch and can only be used if your data IS in Elasticsearch too. I would suggest importing your CSV and proceeding the normal query way.

**Comment by NurAdah** [comment]
so if i put my condition in Sentinl watcher query eg dst_port == 25, is Sentinl able to alert through email ? saying port 25 is found

**Comment by lmangani** [comment]
Anything you can do in an Elasticsearch query you can do in SENTINL - they use the same DSL

**Comment by NurAdah** [comment]
Alright i'd understand. Thank you :)
