### ISSUE TITLE
Fetch filters from Kibana search (not only the search string)

### ISSUE THREAD

**Issue by kayrus** [sirensolutions/sentinl#52]
Kibana allows to define filters, but when you use "Set Watcher" button, it fetches only the search string. Thus you have to convert filters to search query manually.

Is it hard to add filters support?

**Comment by lmangani** [comment]
Hi @kayrus 
This is definitely possible and the "Set Watcher" helper really leaves much to be desired. If you have time and will to test it we can try this in a dev branch.

**Comment by lmangani** [comment]
Moving to 6.x please reopen if this is still useful / required. Thanks!
