### ISSUE TITLE
Options missing in index.js for kibana.yml in 5.x releases

### ISSUE THREAD

**Issue by bienensenf** [sirensolutions/sentinl#521]
Hello,

I have noticed that there are very few config option in the index.js file, though these should be existing if you read the documentation. Let's take "simple_authentication" as a child of "report" as an example.

https://sentinl.readthedocs.io/en/latest/Config-Example/ This documentation page shows it should be available. However, If you write that in your config file it says that "child simple_authentication is not allowed here". Looking at the index.js file, it tells you why. There is no option for simple_authentication and also for many others no option.

This is the index.js that ships with 5.x releases: 

`import fs from 'fs';
import _ from 'lodash';

export default function (kibana) {
  let requirements = ['kibana', 'elasticsearch'];

  // Kibi: check if saved objects api exists.
  const savedObjectsAPI = `${kibana.rootDir}/src/kibi_plugins/saved_objects_api`;
  if (fs.existsSync(savedObjectsAPI)) {
    requirements.push('saved_objects_api');

    // Kibi: import saved objects api related libs.
    const pathForLibs = `${kibana.rootDir}/plugins/sentinl/public/app.js`;
    const libsToImport = [
      'import \'./services/saved_watchers/index\';',
      'import \'./services/saved_users/index\';',
      'import \'./services/saved_scripts/index\';'
    ];

    const data = fs.readFileSync(pathForLibs);
    const libs = data.toString().trim().split('\n');

    _.forEach(_.difference(libsToImport, libs), (lib) => {
      fs.appendFileSync(pathForLibs, `${lib}\n`);
    });
  }

  return new kibana.Plugin({
    require: requirements,
    uiExports: {
      spyModes: ['plugins/sentinl/dashboard_spy_button/alarm_button'],
      app: {
        title: 'Sentinl',
        description: 'Kibana Alert App for Elasticsearch',
        main: 'plugins/sentinl/app',
        icon: 'plugins/sentinl/sentinl.svg',
        injectVars: function (server, options) {
          var config = server.config();
          return {
            kbnIndex: config.get('kibana.index'),
            esShardTimeout: config.get('elasticsearch.shardTimeout'),
            esApiVersion: config.get('elasticsearch.apiVersion')
          };
        }
      }
    },
    config: function (Joi) {
      return Joi.object({
        enabled: Joi.boolean().default(true),
        es: Joi.object({
          host: Joi.string().default('localhost'),
          port: Joi.number().default(9200),
          timefield: Joi.string().default('@timestamp'),
          default_index: Joi.string().default('watcher'),
          type: Joi.string().default('sentinl-watcher'),
          alarm_index: Joi.string().default('watcher_alarms'),
          alarm_type: Joi.string().default('alarm'),
          script_type: Joi.string().default('sentinl-script'),
          watcher: Joi.object({
            trigger: Joi.number().default(3),
            throttle: Joi.number().default(1),
            recover: Joi.number().default(15000)
          }).default(),
        }).default(),
        sentinl: Joi.object({
          history: Joi.number().default(20),
          results: Joi.number().default(50),
          scriptResults: Joi.number().default(50)
        }).default(),
        settings: Joi.object({
          authentication: Joi.object({
            enabled: Joi.boolean().default(false),
            https: Joi.boolean().default(true),
            verify_certificate: Joi.boolean().default(false),
            path_to_pem: Joi.string(),
            admin_username: Joi.string().default('admin'),
            admin_sha: Joi.string().default('6859a748bc07b49ae761f5734db66848'),
            mode: Joi.string().default('basic'),
            user_index: Joi.string().default('sentinl_users'),
            user_type: Joi.string().default('user'),
            encryption: Joi.object({
              algorithm: Joi.string().default('AES-256-CBC'),
              key: Joi.string().default('b9726b04608ac48ecb0b6918214ade54'),
              iv_length: Joi.number().default(16)
            }).default(),
          }).default(),
          email: Joi.object({
            active: Joi.boolean().default(false),
            user: Joi.string(),
            password: Joi.string(),
            host: Joi.string(),
            ssl: Joi.boolean().default(true),
            timeout: Joi.number().default(5000)
          }).default(),
          slack: Joi.object({
            active: Joi.boolean().default(false),
            username: Joi.string(),
            hook: Joi.string(),
            channel: Joi.string(),
          }).default(),
          webhook: Joi.object({
            active: Joi.boolean().default(false),
            use_https: Joi.boolean().default(false),
            method: Joi.string().default('POST'),
            host: Joi.string(),
            port: Joi.number(),
            path: Joi.string().default(':/{{payload.watcher_id}'),
            body: Joi.string().default('{{payload.watcher_id}}{payload.hits.total}}')
          }).default(),
          report: Joi.object({
            active: Joi.boolean().default(false),
            phantomjs_path: Joi.string().default(undefined),
            tmp_path: Joi.string().default('/tmp/')
          }).default(),
          pushapps: Joi.object({
            active: Joi.boolean().default(false),
            api_key: Joi.string()
          }).default()
        }).default()
      }).default();
    },
    init: require('./init.js')
  });
};`

Since we use ES and Kibana 5.6.7 in our company, I am forced to use Sentinl 5.6.7 (or does it work with 6.x). How do I get back the options though?

Thank you

**Comment by bienensenf** [comment]
Is there a way to get Sentinl 6 working with Kibana 5.6.7? This would also give me the options back. As I plan to use Sentinl in production I need them very urgently.

**Comment by lmangani** [comment]
@bienensenf you are welcome to backport 6.x features to 5.x if you wish, but its not part of our roadmap - it's already hard enough to walk forward to 6.3 and 6.4 right now. If you'd like to make a donation to the project to consider this requirement for your commercial setup, feel free to let us know.

**Comment by bienensenf** [comment]
Hello @lmangani , according to the documentation this should not be a 6.x feature but should work with version 5 as well, at least "simple_authentication". "simple_authentication" is not existing on 5.6.x branch but is existing on 5.5.x branch and 6.x branches, which makes no sense and is the reason why I am asking.

**Comment by lmangani** [comment]
@bienensenf I do perfectly get it, but as said we only work forward and rarely backport fixes and features - this surely creates gaps as you can see unless there are active users on those versions reporting or sending PRs -  the project is Open Source so we're welcoming contributors and allowing anyone with time and will to fill the gaps beteen branches, or for the specific version they need - particularly for business users, we can help for some support back to the project - thanks for understanding!

**Comment by bienensenf** [comment]
Okay, thank you for clarifying. I was just a bit perplex seeing this option in the documentation without any annotation and seeing this in earlier releases. I will consider how to move on. Thank you.
