### ISSUE TITLE
Importing Sentinl-watcher

### ISSUE THREAD

**Issue by neelrana** [sirensolutions/sentinl#533]
**1. Sentinl and Kibana version** 
Sentinl Version 6.2.2
Kibana version: 6.2.2

**2. Issue description**

I am trying to import a sentinl watcher through kibana dev console. I believe that the sentinl json format has changed from v5 to v6. 

I believe sentinl watchers are now stored within .kibana  index, is this correct?
I tried to import the sentinl watchers however I am not able to do so.

**3. Reproducing the issue step-by-step**

> POST .kibana
{
  "_index": ".kibana",
  "_type": "doc",
  "_id": "sentinl-watcher:8708daa0-94c6-11e8-a98f-0b13f7a3011a",
  "_score": 1,
  "_source": {
    "type": "sentinl-watcher",
    "updated_at": "2018-08-06T16:10:39.633Z",
    "sentinl-watcher": {
      "title": "Testing Alerts",
      "input": {
        "search": {
          "request": {
            "index": [
              "apache-*"
            ],
            "body": {
              "query": {
                "bool": {
                  "filter": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": "now-10m"
                        }
                      }
                    },
                    {
                      "query_string": {
                        "query": "event_data.IPAddress:"10.0.3.45""
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "actions": {
        "New visitor": {
          "throttle_period": "0h10m0s",
          "slack": {
            "channel": "#alerts",
            "message": """ You have a new visitor! Please check it out""",
            "stateless": false
          }
        }
      },
      "transform": {},
      "condition": {
        "script": {
          "script": "payload.hits.total > 0"
        }
      },
      "report": false,
      "disable": false,
      "trigger": {
        "schedule": {
          "later": "every 10 minutes"
        }
      }
    }
  }
}

Can someone please assist?  Thank you

**Comment by lmangani** [comment]
In the latest versions admins have the option to choose the storage method they prefer - this is currently subject to a couple of bugs being fixed in #408 please refer there for both answers! Thanks!

**Comment by lmangani** [comment]
The implicit part was this now depends on the settings you see referred in 6.x compared to 5.x. 
You should then import watchers according to your choice, if you want to emulate the old setup set to save on a regular index as opposed to the .kibana ones. Hope this helps!
