### ISSUE TITLE
The payload in watcher alarm is empty when alarm is raised

### ISSUE THREAD

**Issue by krishan-agrawal-guavus** [sirensolutions/sentinl#536]
I tried installing sentinl tag - 6.2.4 on my kibana 6.2.4 version.
but I am observing that payload in the alarms is empty.

<img width="1210" alt="screen shot 2018-09-12 at 5 13 05 pm" src="https://user-images.githubusercontent.com/30039204/45422927-59fbb400-b6af-11e8-8ce7-02f8d446c850.png">

**Comment by lmangani** [comment]
Hi @krishan-agrawal-guavus you need to explicitly enable the option to save payloads alongside alerts. By default, this is false.  Please reference our [docs](https://sentinl.readthedocs.io/en/latest/Watcher-Actions/#storing-payload)
