### ISSUE TITLE
Email Alert body {{ _source.message }} limits to only 10 lines even payload.hits.total > 500

### ISSUE THREAD

**Issue by manish2479** [sirensolutions/sentinl#538]
Hi,

I have set the email action but in body message, I get only 10 lines form the source.message field where else the query return more than 10 lines hit with "payload.hits.total > 500", which can be seen here from the email output where it found 461775 total hits.

Version
kibana-6.2.4-1
/usr/share/kibana/bin/kibana-plugin list
sentinl@6.0.0

but the version I have downloaded is 
https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.3-1/sentinl-v6.2.2.zip

```
Found {{payload.hits.total}} Error AND NOT CRON_JOBID
{{#payload.hits.hits}} {{ _source.message }}  
{{/payload.hits.hits}}
{{payload.hits.total}}
```
Where, "{{ _source.message }}" is the index search in kibana to list all the messages.

Here is the email message I get
```
Found 461775 Cron_Error AND NOT CRON_JOBID
Aug 29 13:02:47 noden6 kernel: [1535572967.071651] Cron_Error: Skipped 2 previous similar messages  
Aug 29 13:02:46 noden1 kernel: [1535572966.978553] Cron_Error: Skipped 2 previous similar messages  
Aug 29 13:02:47 noden7 kernel: [1535572967.084495] Cron_Error: Skipped 2 previous similar messages  
Aug 29 13:02:47 noden2 kernel: [1535572967.009380] Cron_Error: Skipped 2 previous similar messages  
Aug 29 13:02:46 noden4 kernel: [1535572966.906165] Cron_Error: Skipped 1 previous similar message  
Aug 29 13:02:46 noden9 kernel: [1535572966.894810] Cron_Error: Skipped 1 previous similar message  
Aug 29 13:02:47 noden10 kernel: [1535572967.112690] Cron_Error: Skipped 3 previous similar messages  
Aug 29 13:02:46 noden17 kernel: [1535572966.671520] Cron_Error: Skipped 1 previous similar message  
Aug 29 13:02:46 noden13 kernel: [1535572966.613536] Cron_Error: Skipped 5 previous similar messages  
Aug 29 13:02:47 noden7 kernel: message repeated 2 times: [ [1535572967.084495] Cron_Error: Skipped 2 previous similar messages] 
461775
```

Expected result is that I should get all those 461775 hits of messages lines in the email and it's limited to 10 lines output only. Is there I am missing something here or configured not right. Any help would be really appreciated.

Thank You,

**Comment by sergibondarenko** [comment]
@manish2479 @292293011 guys, when you create an issue in this repository you see the following default message, don't you? The goal of the message is to let you know what input data are required. Please include the full watcher doc too.

@292293011 is your question related to the original question of this issue? If yes, give more data, if no - create a new issue with more data. 

---
Default message:
```
<!--
Thanks for taking time to report an issue. Please try to:

* Be precise: describe expected results vs. actual results
* Be clear: explain how to reproduce the problem, step by step
* Include only one problem per report
* Include details about your setup/system/os where possible

This section will NOT appear in your Issue report!
-->

1. Sentinl and Kibana version 

2. Issue description

3. Reproducing the issue step-by-step

4. Expected results vs. actual results

5. Sample of data

6. Additional details
```

**Comment by manish2479** [comment]
> @manish2479 If {{ _source.message }} a json code, Here is the webhook meesage I get
> `[object Object] [object Object] [object Object] [object Object] [object Object]`
> I want the right json string，can you help me?
> 
> Thank You.

**Comment by manish2479** [comment]
Hi Sergii,

I have updated the post with the version of kibana and sentinl. Also I have updated the expected result which I am looking for and the "{{ _source.message }}" is the index search in kibana.

Thank you

**Comment by manish2479** [comment]
Hi Sergii,

Just wanted to see if you need anything else from my end or if you got a chance to test this issue.

Thank You

**Comment by sergibondarenko** [comment]
It is because Elasticsearch defaults to 10 results for a query. You have to put additional info into watcher input: `from` and `size`. For example:
```
{
    "from" : 0, "size" : 10,
    "query" : {
        "term" : { "user" : "bad user" }
    }
}
```
Currently there is 10000 docs hard limit in Elasticsearch. For getting more documents, you must have many queries (pagination). Sentinl can't do the pagination yet, only one query is done per watcher execution.

Read the official Elasticsearch docs for the details
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-request-from-size.html#search-request-from-size

P.S.
Processing a large number of docs can take a long time, depends on the condition script complexity.

**Comment by manish2479** [comment]
Hi Sergii,

Thank you, that makes sense now and I included those additional info and it worked as expected and I really appreciate your help. We can set this ticket as closed.

Thank you!
