### ISSUE TITLE
Compatible with Kibana 6.4.X

### ISSUE THREAD

**Issue by changi67** [sirensolutions/sentinl#541]
1. Sentinl and Kibana version 

Sentinl 6.2.4
Kibana 6.4.1

2. Issue description
Unable to deploy the plugin

3. Reproducing the issue step-by-step
Plugin install 

Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false --uiSettings.enabled=false
(node:17) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL Error: [plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })
    at applySpecDefaults (/usr/share/kibana/src/ui/ui_exports/ui_export_types/ui_apps.js:30:11)
    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/map_spec.js:33:95
    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/alias.js:32:83
    at specs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:50:42)
    at Array.reduce (<anonymous>)
    at types.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:50:20)
    at Array.reduce (<anonymous>)
    at pluginSpecs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:39:18)
    at Array.reduce (<anonymous>)
    at reduceExportSpecs (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:35:22)
    at collectUiExports (/usr/share/kibana/src/ui/ui_exports/collect_ui_exports.js:19:50)
    at KbnServer.uiExportsMixin (/usr/share/kibana/src/ui/ui_exports/ui_exports_mixin.js:11:66)
    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:169:16)
    at KbnServer.uiMixin (/usr/share/kibana/src/ui/ui_mixin.js:27:19)
    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:169:16)
    at <anonymous>

{"type":"log","@timestamp":"2018-09-20T09:30:13Z","tags":["warning","config","deprecation"],"pid":17,"message":"uiSettings.enabled is deprecated and is no longer used"}
{"type":"error","@timestamp":"2018-09-20T09:30:31Z","tags":["fatal"],"pid":17,"level":"fatal","error":{"message":"[plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })","name":"Error","stack":"Error: [plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })\n    at applySpecDefaults (/usr/share/kibana/src/ui/ui_exports/ui_export_types/ui_apps.js:30:11)\n    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/map_spec.js:33:95\n    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/alias.js:32:83\n    at specs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:50:42)\n    at Array.reduce (<anonymous>)\n    at types.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:50:20)\n    at Array.reduce (<anonymous>)\n    at pluginSpecs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:39:18)\n    at Array.reduce (<anonymous>)\n    at reduceExportSpecs (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:35:22)\n    at collectUiExports (/usr/share/kibana/src/ui/ui_exports/collect_ui_exports.js:19:50)\n    at KbnServer.uiExportsMixin (/usr/share/kibana/src/ui/ui_exports/ui_exports_mixin.js:11:66)\n    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:169:16)\n    at KbnServer.uiMixin (/usr/share/kibana/src/ui/ui_mixin.js:27:19)\n    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:169:16)\n    at <anonymous>"},"message":"[plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })"}

4. Expected results vs. actual results
Install goes well

5. Sample of data
Not needed

6. Additional details
Can provide if needed.

**Comment by Grashee** [comment]
At this moment there is no release for the 6.4 version

**Comment by rajapaladugula** [comment]
The latest version available is 6.2.4 --> https://github.com/sirensolutions/sentinl/releases
You need to downgrade Kibana to 6.2.4 to use SENTINL .

**Comment by sergibondarenko** [comment]
@rajapaladugula we work on the upgrade now. A lot of Kibana internal things became incompatible.

**Comment by sergibondarenko** [comment]
@rajapaladugula @Grashee @changi67 guys we have v6.4 pre-release https://github.com/sirensolutions/sentinl/releases/tag/tag-6.4.1-beta

**Comment by changi67** [comment]
Installed 6.4.1 and so far so good.
Previous configuration is working.

**Comment by fbaligand** [comment]
@changi67 
Which OS do you have tested ?

**Comment by sergibondarenko** [comment]
@rajapaladugula @Grashee @changi67 @fbaligand update, report (screenshot) was fixed, the packages were updated https://github.com/sirensolutions/sentinl/releases/tag/tag-6.4.1-beta
