### ISSUE TITLE
Unable to use the aggs payload values generated in to the Action message

### ISSUE THREAD

**Issue by rajapaladugula** [sirensolutions/sentinl#543]
1. Sentinl and Kibana version : 6.2.4

2. Issue description
Watcher was able to generate the {{payload.hits.total}} in the message field of Actions. I was unable to figure out the correct syntax to use payload values generated from aggregations (hosts, values). Tried Several different ways changing the script. No Luck.
3. Reproducing the issue step-by-step

4. Expected results vs. actual results
Expected:
Watcher Notification - HIGH MEMORY USAGE! Hosts with HIGH MEMORY Usage (above 75%):
<HOST_NAMES>
Memory Usage is at:  XX%
at times: xx:xx

Actual:
Watcher Notification - HIGH MEMORY USAGE! Hosts with HIGH MEMORY Usage (above 75%):
[object Object]
Memory Usage is at:  %
at times:

5. Sample of data
{
  "actions": {
    "Slack_alarm_9acc021a-95a8-4777-9d1d-3e471377b597": {
      "name": "Slack Sample Alarm",
      "throttle_period": "5m",
      "slack": {
        "priority": "medium",
        "stateless": false,
        "message": "Watcher Notification - HIGH MEMORY USAGE! Hosts with HIGH MEMORY Usage (above 50%):\n\n{{payload.aggregations.hosts.value}}\n\n Memory Usage is at: {{payload.aggregations.values.value}} % \n\n at times: {{trigger.triggered_time}} \n\n",
        "channel": "#jenkins"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "search_type": "query_then_fetch",
        "index": [
          "metricbeat-*"
        ],
        "body": {
          "query": {
            "bool": {
              "filter": [
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-60m",
                      "lte": "now"
                    }
                  }
                },
                {
                  "term": {
                    "metricset.name": "memory"
                  }
                },
                {
                  "range": {
                    "system.memory.used.pct": {
                      "gte": "0.50"
                    }
                  }
                }
              ]
            }
          },
          "aggs": {
            "hosts": {
              "terms": {
                "field": "beat.hostname",
                "size": 10
              },
              "aggs": {
                "values": {
                  "avg": {
                    "field": "system.memory.used.pct"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": "return payload.aggregations.hosts.buckets.size() > 0"
  },
  "transform": {
    "script": {
      "inline": "return ['hosts': payload.aggregations.hosts.buckets.stream().map(b -> [b.key: b.values.value]).collect(Collectors.toList()) ]"
    }
  },
  "trigger": {
    "schedule": {
      "interval": "10m"
    }
  },
  "disable": false,
  "report": false,
  "title": "watcher_aggs",
  "save_payload": false,
  "spy": false,
  "impersonate": false
}

6. Additional details
I dont find any errors in the Kibana Logs and it shows that the message was executed to Slack.
Tried {{payload.aggregations.hosts.buckets}} & {{payload.aggregations.hosts.values}} as well. No Luck.

**Comment by lmangani** [comment]
There's nothing wrong with SENTINL here, You just need to carefully read and understand the response JSON structure and the `mustache` format in order to leverage them correctly.

If you seek help, you need to share the full response you are trying to use, not the original query which clearly, we cannot replicate anywhere. Or you can just copy paste the response somewhere (codepen, etc) and play with `mustache`

Hope this helps.

**Comment by rajapaladugula** [comment]
Hi @lmangani Thanks for the quick response. Please find the below response:

{
  "took": 10,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 359,
    "max_score": 0,
    "hits": [
{
        "_index": "metricbeat-6.4.0-2018.09.25",
        "_type": "doc",
        "_id": "pcqJEWYBQC5dbawBhu97",
        "_score": 0,
        "_source": {
          "@timestamp": "2018-09-25T16:21:56.644Z",
          "metricset": {
            "rtt": 641,
            "name": "memory",
            "module": "system"
          },
          "system": {
            "memory": {
              "hugepages": {
                "free": 0,
                "reserved": 0,
                "surplus": 0,
                "default_size": 2097152,
                "total": 0,
                "used": {
                  "bytes": 0,
                  "pct": 0
                }
              },
              "total": 8092745728,
              "used": {
                "bytes": 7865540608,
                "pct": 0.9719
              },
              "free": 227205120,
              "actual": {
                "free": 5404475392,
                "used": {
                  "pct": 0.3322,
                  "bytes": 2688270336
                }
              },
              "swap": {
                "used": {
                  "pct": 0.0001,
                  "bytes": 1048576
                },
                "free": 8320446464,
                "total": 8321495040
              }
            }
          },
          "beat": {
            "name": "localhost.localdomain",
            "hostname": "localhost.localdomain",
            "version": "6.4.0"
          },
          "host": {
            "name": "localhost.localdomain"
          }
        }
      }
    ]
  },
  "aggregations": {
    "hosts": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "localhost.localdomain",
          "doc_count": 359,
          "values_avg": {
            "value": 0.9786100278551532
          }
        }
      ]
    }
  }
}

I was unable to figure out the correct syntax to "transform" the values generated from 'aggs'.
Here inside the actions, i am trying to transform all the host names in payload to a list called ''hosts" and also use {{trigger.triggered_time}} from payload.
