### ISSUE TITLE
TypeError: _boom2.default.create is not a function?

### ISSUE THREAD

**Issue by aabababb** [sirensolutions/sentinl#547]
1. Sentinl and Kibana version 6.2.4

2. TypeError: _boom2.default.create is not a function

3. ./kibana-plugin remove sentinl
./kibana-plugin install file:///share/sentinl-v6.2.4.zip

4. TypeError: _boom2.default.create is not a function

can't install again?

**Comment by sergibondarenko** [comment]
@aabababb I can't reproduce your issue. My list of actions (OS Ubuntu):
```
$ wget https://artifacts.elastic.co/downloads/kibana/kibana-6.2.4-linux-x86_64.tar.gz
$ tar -xzvf kibana-6.2.4-linux-x86_64.tar.gz
$ cd kibana-6.2.4-linux-x86_64
$ wget https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.4/sentinl-v6.2.4.zip
$ ./bin/kibana-plugin install file:///home/trex/Development/kibana-6.2.4-linux-x86_64/sentinl-v6.2.4.zip
Attempting to transfer from file:///home/trex/Development/siren/elastic/kibana/kibana-6.2.4-linux-x86_64/sentinl-v6.2.4.zip
Transferring 195753041 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
$ ./bin/kibana
```

**Comment by aabababb** [comment]
> 
> 
> @aabababb I can't reproduce your issue. My list of actions (OS Ubuntu):
> 
> ```
> $ wget https://artifacts.elastic.co/downloads/kibana/kibana-6.2.4-linux-x86_64.tar.gz
> $ tar -xzvf kibana-6.2.4-linux-x86_64.tar.gz
> $ cd kibana-6.2.4-linux-x86_64
> $ wget https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.4/sentinl-v6.2.4.zip
> $ ./bin/kibana-plugin install file:///home/trex/Development/kibana-6.2.4-linux-x86_64/sentinl-v6.2.4.zip
> Attempting to transfer from file:///home/trex/Development/siren/elastic/kibana/kibana-6.2.4-linux-x86_64/sentinl-v6.2.4.zip
> Transferring 195753041 bytes....................
> Transfer complete
> Retrieving metadata from plugin archive
> Extracting plugin archive
> Extraction complete
> Optimizing and caching browser bundles...
> Plugin installation complete
> $ ./bin/kibana
> ```

sorry,I remove all ELK,install angain,not this error now.
