### ISSUE TITLE
how to find Sentinl  version?

### ISSUE THREAD

**Issue by aabababb** [sirensolutions/sentinl#549]
1. Sentinl and Kibana version 6.2.4

2.how to find Sentinl  version?

3. use this
 ./kibana-plugin list

4. sentinl@6.0.0?

**Comment by aabababb** [comment]
> 
> 
> If you want to find out the version of your installed sentinl plugin you can look in the `package.json` in your directory of sentinl-plugin
"name": "sentinl",
  "version": "6.0.0",

I see,but why is 6.0.0? not 6.2.4?

**Comment by aabababb** [comment]
> 
> 
> @aabababb because you didn't sent any PR's to update this OSS plugin. You think all world just waiting new version of ES and fix their plugins?)))))) But you can create great PR for support kibana 6.2.4 ;)

sorry, I mean I download sentinl-v6.2.4.zip,but ./kibana-plugin list see sentinl@6.0.0

**Comment by fbaligand** [comment]
Hi @aabababb 

If you look at package.json inside sentinl-v6.2.4.zip, there are 2 versions : 
- plugin version
- kibana version

And you can see that kibana version is 6.2.4 and plugin version is 6.0.0

**Comment by aabababb** [comment]
> 
> 
> Hi @aabababb
> 
> If you look at package.json inside sentinl-v6.2.4.zip, there are 2 versions :
> 
>     * plugin version
> 
>     * kibana version
> 
> 
> And you can see that kibana version is 6.2.4 and plugin version is 6.0.0

I get it,thank you.
