### ISSUE TITLE
how to find the local patch of shell?

### ISSUE THREAD

**Issue by aabababb** [sirensolutions/sentinl#555]
1. Sentinl and Kibana version 6.2.4

2. Issue description

send-alert.sh

#!/bin/bash
curl http://alert-service:8888/send-alert -XPOST -d @$1

"cmd": {
     "name": "send alert",
     "script": "/path/send-alert.sh",
     "argument": "file"
 },

3. Reproducing the issue step-by-step
send the shell alert. don't where to use the path.

4. Expected results vs. actual results

action to execute the send-alert.sh

**Comment by sergibondarenko** [comment]
I don't understand, what type of action is it? Can you show the full watcher? As far as I know, Sentinl doesn't have a possibility to exec bash scripts.

**Comment by aabababb** [comment]
> 
> 
> I don't understand, what type of action is it? Can you show the full watcher? As far as I know, Sentinl doesn't have a possibility to exec bash scripts.

this file --->> send-alert.sh

#!/bin/bash
curl http://alert-service:8888/send-alert -XPOST -d @$1

then action run the send-alert.sh

**Comment by havlan** [comment]
@aabababb elaborate so we can understand your issue properly. Do you want to run the script when an alert triggers?
