### ISSUE TITLE
Create watcher looking for specific values

### ISSUE THREAD

**Issue by Grashee** [sirensolutions/sentinl#566]
**Kibana version:**
6.3
**Elasticsearch version:**
6.3
**Original install method (e.g. release pkg link, gulp, from source, etc.):**
release zip
**Question:**

Hey guys,
Is it possible to create an watcher, who looks after the last 30 minutes of an index and checks whether a text field has a certain value? If so, he should count them and if they are larger than 20, raise an alarm.

**Sample of data you have in Elasticsearch**

Fieldname: message
Field-type: string
Field-value: "error"

**Comment by lmangani** [comment]
Absolutely. If you can think of it in ES terms, you can make it happen:

1) forge an ES query looking for your text field - this is the most and only important part
2) create a condition to count the results threshold (could be as simple as the result count, or iterating)
3) create an action to deliver the results
