### ISSUE TITLE
Find out all variables of mustache

### ISSUE THREAD

**Issue by Grashee** [sirensolutions/sentinl#567]
Hey guys,

I have a question about the mustache functions. 
Is there any list about all possible mustache-variables, which I can use? Or where can I find out the variables of mustache?

Best regards,
Robert

**Comment by havlan** [comment]
@Grashee Hey! You could always look up their [documentation](https://mustache.github.io/mustache.5.html) (Idk if that's the right type) You could also do a little hack with script conditions, say something like ```payload.str = JSON.stringify(payload);```
And then printing it like this {{{payload.str}}} in the template (I think this should work).
More documentation and a little tutorial is available at https://havlan.github.io/mini-sentinl-tutorial/  (already somewhat outdated)

**Comment by Grashee** [comment]
Thanks @havlan
