### ISSUE TITLE
Unable to save new watcher

### ISSUE THREAD

**Issue by manu2** [sirensolutions/sentinl#570]
**Kibana version: 6.3.0**

**Elasticsearch version: 6.2.4**

**Server OS version:Red Hat Enterprise Linux Server release 6.10 (Santiago)**

**Browser version Version 64.0.3282.167 (Official Build) (64-bit)**

**Browser OS version: CentOS release 6.9 **

**Original install method (e.g. release pkg link, gulp, from source, etc.): from zip**

**Describe the bug: When trying to save a new watcher from kibana dashboard, I get error like Error: Save watcher:Save 'watcher':Index 'watcher'
```
Error: Index 'watcher'
    at new SentinlError (http://hostname:6702/bundles/sentinl.bundle.js:3:71993)
    at WatcherService.<anonymous> (http://hostname:6702/bundles/sentinl.bundle.js:22:346324)
    at tryCatch (http://hostname:6702/bundles/vendors.bundle.js:133:364594)
    at Generator._invoke (http://hostname:6702/bundles/vendors.bundle.js:133:366669)
    at Generator.prototype.(anonymous function) [as throw] (http://hostname:6702/bundles/vendors.bundle.js:133:364878)
    at step (http://hostname:6702/bundles/sentinl.bundle.js:22:341023)
    at http://hostname:6702/bundles/sentinl.bundle.js:22:341184
    at <anonymous>
```
   The watcher index is up and available in es.
```
{"watcher":{"aliases":{},"mappings":{"doc":{"properties":{"sentinl-user":{"properties":{"password":{"type":"text"},"sha":{"type":"text"},"username":{"type":"text"}}},"sentinl-watcher":{"properties":{"actions":{"type":"object","enabled":false},"condition":{"type":"object","enabled":false},"custom":{"type":"object","enabled":false},"dashboard_link":{"type":"text"},"disable":{"type":"boolean"},"impersonate":{"type":"boolean"},"input":{"type":"object","enabled":false},"report":{"type":"boolean"},"save_payload":{"type":"boolean"},"sentinl":{"type":"object","enabled":false},"spy":{"type":"boolean"},"title":{"type":"text"},"transform":{"type":"object","enabled":false},"trigger":{"type":"object","enabled":false},"username":{"type":"text"},"wizard":{"type":"object","enabled":false}}}}}},"settings":{"index":{"creation_date":"1539007031135","number_of_shards":"5","number_of_replicas":"1","uuid":"PjGWJhImTvqEAaZyJN68hA","version":{"created":"6030099"},"provided_name":"watcher"}}}}
```
All watchers fail to save. Sample:
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new",
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 5 minutes"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "<mos-{now/d}>",
            "<mos-{now/d-1d}>"
          ],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 100"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "manu@something.com",
          "from": "manu@something.com",
          "subject": "SENTINL Alarm",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      }
    }
  }
}
```
**

**Steps to reproduce:**
1. Add new sentinl watch using 'New' button on top right
2. Add conditions actions to it
3. Click on 'Save'. 

**Expected behavior: A new watcher should be added ideally**

**Sample of data you have in Elasticsearch**

**Full watcher document**

**Screenshots (if relevant): **

**Errors in browser console (if relevant):
```
[object Object]: Save watcher:Save 'watcher':Index 'watcher'
Error: Save watcher:Save 'watcher':Index 'watcher'
Error: Index 'watcher'
    at new SentinlError (http://hostname:6702/bundles/sentinl.bundle.js:3:71993)
    at WatcherService.<anonymous> (http://hostname:6702/bundles/sentinl.bundle.js:22:346324)
    at tryCatch (http://hostname:6702/bundles/vendors.bundle.js:133:364594)
    at Generator._invoke (http://hostname:6702/bundles/vendors.bundle.js:133:366669)
    at Generator.prototype.(anonymous function) [as throw] (http://hostname:6702/bundles/vendors.bundle.js:133:364878)
    at step (http://hostname:6702/bundles/sentinl.bundle.js:22:341023)
    at http://hostname:6702/bundles/sentinl.bundle.js:22:341184
    at <anonymous>**
```
**Provide Kibana logs and/or server output (if relevant):**

**Any additional context: Sentinl Config from kibana.yml
```
sentinl:
      es:
        host: 'localhost'
        port: 9200
        default_type: 'doc'
        default_index: 'watcher'
        alarm_index: 'watcher_alarms'
        alarm_type: 'sentinl-alarm'
      settings:
          email:
                active: true
                user: manu
                host: smtp.something.com
          report:
                active: true
```
**
'

**Comment by sergibondarenko** [comment]
The problem is here
```
sentinl:
      es:
        default_type: 'doc'
        default_index: 'watcher'
```
Currently, Sentinl saves watchers only in index specified in kibana.yml var `kibana.index`, by default `.kibana`. Just delete `default_index: 'watcher'` and `default_type: 'doc'` and you will be able to save watchers.
Also, soon we add a possibilty to save watchers in any index.

Please reopen the issue if you still have this problem.

**Comment by manu2** [comment]
Removed the configuration for default index and default type. Still getting same error.
Here is complete kibana.yml

`server.port: 6702
server.host: 0.0.0.0

elasticsearch.url: "https://hostname:9200"
elasticsearch.username: "user"
elasticsearch.password: "pass"
elasticsearch.ssl.verificationMode: none

elasticsearch.requestHeadersWhitelist: ["Authorization", "sgtenant"]
elasticsearch.requestTimeout: 30000
elasticsearch.shardTimeout: 30000


tilemap.url: "http://a.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png"
xpack.reporting.csv.maxSizeBytes: 104857600
xpack.security.enabled: false
searchguard.session.ttl: 86400000
searchguard.cookie.ttl: 86400000
sentinl:
    es:
        host: 'localhost'
        port: 9200
        alarm_index: 'watcher_alarms'
        alarm_type: 'sentinl-alarm'
    settings:
        email:
            active: true
            user: manu
            host: smtp.something.com
        report:
            active: true

`

**Comment by sergibondarenko** [comment]
Are you sure the error you get does contain `Index 'watcher'` words? Please paste the error here.
Make sure Kibana is restarted after the config change.

I see you use X-Pack. Make sure the user you use for login has rights to save docs in the system index (`.kibana` by default).

Also, in order to make Sentinl execute watchers automatically by schedule, you should have a Sentinl user with system index read/monitor and watcher index write/read permissions in X-Pack. Then put this user in the kibana.yml
```
sentinl:
  settings:
    authentication:
      enabled: true
      username: sentinluser
      password: sentinlpassword
```

**Comment by manu2** [comment]
> Are you sure the error you get does contain `Index 'watcher'` words? Please paste the error here.
> Make sure Kibana is restarted after the config change.
> 
> I see you use X-Pack. Make sure the user you use for login has rights to save docs in the system index (`.kibana` by default).
> 
> Also, in order to make Sentinl execute watchers automatically by schedule, you should have a Sentinl user with system index read/monitor and watcher index write/read permissions in X-Pack. Then put this user in the kibana.yml
> 
> ```
> sentinl:
>   settings:
>     authentication:
>       enabled: true
>       username: sentinluser
>       password: sentinlpassword
> ```

Hi, I have restarted the server. Uninstalled and reinstalled sentinl also.The complete error when saving the watcher is:
`Error: Save wizard:Save 'watcher':Index 'watcher'
Error: Index 'watcher'
    at new SentinlError (http://ptpmongo1.newark:6702/bundles/sentinl.bundle.js:3:71993)
    at WatcherService.<anonymous> (http://ptpmongo1.newark:6702/bundles/sentinl.bundle.js:22:346324)
    at tryCatch (http://ptpmongo1.newark:6702/bundles/vendors.bundle.js:133:364594)
    at Generator._invoke (http://ptpmongo1.newark:6702/bundles/vendors.bundle.js:133:366669)
    at Generator.prototype.(anonymous function) [as throw] (http://ptpmongo1.newark:6702/bundles/vendors.bundle.js:133:364878)
    at step (http://ptpmongo1.newark:6702/bundles/sentinl.bundle.js:22:341023)
    at http://ptpmongo1.newark:6702/bundles/sentinl.bundle.js:22:341184
    at <anonymous>`

**I can visualize the chart also from the query but unable to save it.** My elastic search user has admin role in sg_roles.yml:

`sg_all_access:
  readonly: true
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    admin_tenant: RW
`

Do I need to create roles for sentinl alerting?(Example I have a role for x-pack alerting with following config in sg_roles.yml as mentioned here [https://docs.search-guard.com/latest/search-guard-xpack-alerting](https://docs.search-guard.com/latest/search-guard-xpack-alerting) ):

`
sg_alerting:
  cluster:
    - indices:data/read/scroll
    - cluster:admin/xpack/watcher/watch/put
    - cluster:admin/xpack/watcher*
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana*':
      '*':
        - READ
    '?watches*':
      '*':
        - INDICES_ALL
    '?watcher-history-*':
      '*':
        - INDICES_ALL
    '?triggered_watches':
      '*':
        - INDICES_ALL
    '*':
      '*':
        - READ
`


Result of hostname/watcher:
`{"watcher":{"aliases":{},"mappings":{"doc":{"properties":{"sentinl-user":{"properties":{"password":{"type":"text"},"sha":{"type":"text"},"username":{"type":"text"}}},"sentinl-watcher":{"properties":{"actions":{"type":"object","enabled":false},"condition":{"type":"object","enabled":false},"custom":{"type":"object","enabled":false},"dashboard_link":{"type":"text"},"disable":{"type":"boolean"},"impersonate":{"type":"boolean"},"input":{"type":"object","enabled":false},"report":{"type":"boolean"},"save_payload":{"type":"boolean"},"sentinl":{"type":"object","enabled":false},"spy":{"type":"boolean"},"title":{"type":"text"},"transform":{"type":"object","enabled":false},"trigger":{"type":"object","enabled":false},"username":{"type":"text"},"wizard":{"type":"object","enabled":false}}}}}},"settings":{"index":{"creation_date":"1539007031135","number_of_shards":"5","number_of_replicas":"1","uuid":"PjGWJhImTvqEAaZyJN68hA","version":{"created":"6030099"},"provided_name":"watcher"}}}}`

Result of hostname/watcher_alarms:
`{"watcher_alarms":{"aliases":{},"mappings":{"sentinl-alarm":{"properties":{"@timestamp":{"type":"date"},"action":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"attachment":{"type":"binary"},"error":{"type":"boolean"},"level":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"message":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"payload":{"type":"object","dynamic":"true"},"report":{"type":"boolean"},"type":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"watcher":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}},"settings":{"index":{"creation_date":"1528969442464","number_of_shards":"5","number_of_replicas":"1","uuid":"tZQYa1h2TiKrs4V0yfofMw","version":{"created":"6020499","upgraded":"6030099"},"provided_name":"watcher_alarms"}}}}`

**Comment by sergibondarenko** [comment]
Try to remove Kibana webpack bundles and restart it
```
rm -rf kibana/optimize/bundles/*
```

**Comment by thetimmachine** [comment]
FYI, I was able to resolve by deleting and recreating the .kibana index as described here: https://github.com/sirensolutions/sentinl/issues/523#issuecomment-414593521

**Comment by sergibondarenko** [comment]
@thetimmachine what is your version of Kibana?

**Comment by thetimmachine** [comment]
> @thetimmachine what is your version of Kibana?

6.3.2

**Comment by sergibondarenko** [comment]
@thetimmachine yes, we added a couple of new properties to the watcher in the newest version. Thus the `.kibana` index mapping should be updated.

**Comment by sergibondarenko** [comment]
Thus the solution is to change `.kibana` index mapping using this guide https://github.com/sirensolutions/sentinl/issues/523#issuecomment-414593521
