### ISSUE TITLE
Unable to delete a report

### ISSUE THREAD

**Issue by lbesuchet** [sirensolutions/sentinl#574]
**Kibana version:**
6.2.4

**Elasticsearch version:**
6.2.4

**Describe the bug:**
Unable to delete a report

**Steps to reproduce:**
1. Generate a report
2. Go to Reports tab 
3. Click on the trash bin button of the report
=> an error message appears, report is not deleted

**Expected behavior:**
Report is deleted

**Screenshots (if relevant):**
![error](https://user-images.githubusercontent.com/13847894/46726178-18463500-cc7e-11e8-9aba-837d7fb283d6.png)

**Comment by lbesuchet** [comment]
@szydan any comment before closing the issue would be welcome, thanks ...

**Comment by szydan** [comment]
@lbesuchet sorry the ticket got auto-closed by linked PR which I merged  
@sergibondarenko could you comment more on this one, please

**Comment by sergibondarenko** [comment]
Sorry, I forgot to comment. In 1 hour the fix will be synchronised with the
public repo. Packages under the release will be updated.
