### ISSUE TITLE
Documentation isn't updated on readthedocs

### ISSUE THREAD

**Issue by marvin-w** [sirensolutions/sentinl#576]
**Describe the bug:**

The documentation doesn't reflect the real world.

**Steps to reproduce:**
1. Open https://sentinl.readthedocs.io/en/latest/Config-Example/ and check that the configuration example has old values which prevent kibana from starting (causing #540)
2. The actual source code of the docs however has the correct examples (https://github.com/sirensolutions/sentinl/commit/4f5768b6319955396866e43bfb65cb899dcae40e)

**Expected behavior:**

The documentation in the source code matches the documentation on the website.

**Any additional context:**

See also #540

**Comment by sergibondarenko** [comment]
The docs were synchronized.
