### ISSUE TITLE
Watacher Slack Action: "/" converted to "&#x2F;"

### ISSUE THREAD

**Issue by sn-x** [sirensolutions/sentinl#582]
First things first: Thank for a great product! Installation and configuration were really straight forward.

Now the issue: Some characters get transformed when using Action -> Slack. 

For example, I am trying to send "payload.hits.hits.0._source.message" to slack, and my message gets displayed as:
`at process._tickDomainCallback (internal&#x2F;process&#x2F;next_tick.js:228:7)`
instead of
`at process._tickDomainCallback (internal/process/next_tick.js:228:7)`

Is there a function I should use to encode/escape the message?

**Comment by lmangani** [comment]
Have you tried using a triple bracket in your mustache template? `{{{ key }}}`?

**Comment by sn-x** [comment]
Works like a charm! 

Thanks!
