### ISSUE TITLE
Unknown config key: investigate_core.clusterplugins?

### ISSUE THREAD

**Issue by aabababb** [sirensolutions/sentinl#587]
**Kibana version:**6.2.4

**Elasticsearch version:**6.2.4

**Server OS version:**centos7

**Browser version:**firefox 56

**Browser OS version:**

**Original install method (e.g. release pkg link, gulp, from source, etc.):**

**Describe the bug:**
get this error
{"type":"log","@timestamp":"2018-10-23T03:30:00Z","tags":["warning","Sentinl","watcher_handler"],"pid":13212,"message":"Siren federate: \"elasticsearch.plugins\" is not available when running from kibana: Error: Unknown config key: investigate_core.clusterplugins"}

**Comment by sergibondarenko** [comment]
Do you use Siren Investigate together with Federate plugin? If you use Kibana, just ignore the warning.

**Comment by aabababb** [comment]
> 
> 
> Do you use Siren Investigate together with Federate plugin? If you use Kibana, just ignore the warning.

I don't use Siren Investigate and Federate plugin.thanks you

**Comment by sergibondarenko** [comment]
It is only a warning. We expect to have this.
