### ISSUE TITLE
Trying to gradlew build branch-6.2.x-1 results in errors

### ISSUE THREAD

**Issue by tarmendeos** [sirensolutions/sentinl#590]
**Kibana version:**
6.2.4
**Elasticsearch version:**
6.2.4
**Server OS version:**

**Browser version:**

**Browser OS version:**

**Original install method (e.g. release pkg link, gulp, from source, etc.):**

**Describe the bug:**
downloadKibi results in the following:
./gradlew downloadKibi
:downloadKibi

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':kibi'.
> Cannot resolve external dependency solutions.siren:investigate-core:6.0.0 because no repositories are defined.

Trying to gulpPackage results in the following:
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/sirensolutions/gun-master.git/' not found
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

These didn't happen with sentinl 5.4.3-SNAPSHOT, is the project no longer independently buildable?
**Steps to reproduce:**
1. clone branch-6.2.x-1
2. gradlew gulpPackage

**Expected behavior:**

**Sample of data you have in Elasticsearch**

**Full watcher document**

**Screenshots (if relevant):**

**Errors in browser console (if relevant):**

**Provide Kibana logs and/or server output (if relevant):**

**Any additional context:**

**Tips:**

1. Try to query Elasticsearch manually first. Do you receive the results you want for your query?
For example, on Linux, you can query Elasticsearch using `curl`:
```
curl -X GET "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": { 
    "match_all": {}
  }
}
'
```

**Comment by sergibondarenko** [comment]
Try to build Sentinl package using Sentinl build script
```
1. git clone git@github.com:sirensolutions/sentinl.git
2. cd sentinl
3. npm install && npm install -g gulp
4. git checkout branch-6.2.x-1
5. gulp package --version="6.2.4" && mv ../target/gulp/sentinl* ~/sentinl-v6.2.4.zip
```
Use the build script instead of the 5th step to create multiple versions https://github.com/sirensolutions/sentinl/blob/branch-6.2.x-1/scripts/createReleases.sh
