### ISSUE TITLE
My webhook url is "https://oapi.dingtalk.com/robot/send?access_token=b5c3379c355c2c49XXX",How do I use the WebHook function?

### ISSUE THREAD

**Issue by antianchi** [sirensolutions/sentinl#598]
My webhook url is "https://oapi.dingtalk.com/robot/send?access_token=b5c3379c355c2c49XXX",How do I use the WebHook function?No host,No port.I can't possibly know Host and Port.
**The WebHook function**
![web hook](https://user-images.githubusercontent.com/25560330/47712671-46160c80-dc73-11e8-9be2-b4da0f6e4ab9.jpg)

**Comment by sergibondarenko** [comment]
Try to use the following parameters
port = 80
host = oapi.dingtalk.com
path = /robot/send?access_token=b5c3379c355c2c49XXX

**Comment by antianchi** [comment]
Thank you very much.I did what you said, and my problem was solved.

**Comment by sawdyj** [comment]
I am having a similar issue trying to post a slack message via the slack hooks api and getting the following error.

POST /api/sentinl/watcher/_execute 200 620ms - 9.0B"}
{"type":"log","@timestamp":"2019-01-16T15:00:30Z","tags":["error","Sentinl"],"pid":28848,"message":"fail to ship webhook, Error: getaddrinfo ENOTFOUND https://hooks.slac                                            k.com https://hooks.slack.com:80"}

I have used the above mentioned notation.
port: 80
Host: https://hooks.slack.com
Endpoint: /services/XXXXX/XXXXX/XXXXXXXXXXXXXXXXX

How does my Kibana.yml file need to be setup for webhooks? I am currently using the following documentation. https://sentinl.readthedocs.io/en/latest/Watcher-Actions/#webhook-via-proxy 
I am using the webhook-via-proxy.

**Comment by sergibondarenko** [comment]
> How does my Kibana.yml file need to be setup for webhooks? I am currently using the following documentation. https://sentinl.readthedocs.io/en/latest/Watcher-Actions/#webhook-via-proxy

It is watcher config, not kibana.yml. Please paste here your kibana.yml and watcher?

> I am using the webhook-via-proxy.

I'm not sure it is supported.

**Comment by sawdyj** [comment]
Kibana.yml
#Sentinl
sentinl:
  settings:
    email:
      active: true
      host: smtp.gmail.com
      port: 465
      user: XXXXX@gmail.com
      password: XXXX
      ssl: true
      timeout: 10000
    report:
      active: true
      engine: horseman # options: horseman, puppeteer
    slack:
      active: true
      token: 'XXXX'
    webhook:
      active: false
      method: POST
      host: 'proxy'
      port: '3128'
      path: 'https://hooks.slack.com/services/XXXXX/XXXXX/XXXXXXXXXXXXXXXXXXXX'


Watcher
{
  "actions": {
    "Webhook_04bd55aa-2deb-4b6e-bf0b-2a8b859fe686": {
      "name": "Webhook",
      "throttle_period": "1m",
      "webhook": {
        "priority": "low",
        "stateless": false,
        "method": "POST",
        "host": "https://hooks.slack.com",
        "port": "80",
        "path": "/services/XXXX/XXXX/XXXX",
        "body": "{\n  \"watcher\": \"{{watcher.title}}\",\n  \"payload_count\": \"{{payload.hits.total}}\"\n}",
        "params": {
          "watcher": "{{watcher.title}}",
          "payload_count": "{{payload.hits.total}}"
        },
        "headers": {
          "Content-Type": "application/json"
        },
        "auth": "",
        "message": "",
        "use_https": false
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "gnss"
        ],
        "body": {
          "query": {
            "bool": {
              "filter": {
                "range": {
                  "timestamp": {
                    "gte": "now-15m/m",
                    "lte": "now/m",
                    "format": "epoch_millis"
                  }
                }
              }
            }
          },
          "size": 0,
          "aggs": {
            "dateAgg": {
              "date_histogram": {
                "field": "timestamp",
                "time_zone": "Europe/Amsterdam",
                "interval": "1m",
                "min_doc_count": 1
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.aggregations.dateAgg.buckets.some(b => b.doc_count>=0)"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 2 minutes"
    }
  },
  "disable": true,
  "report": false,
  "title": "Web_Hook",
  "wizard": {
    "chart_query_params": {
      "queryType": "count",
      "scheduleType": "every",
      "over": {
        "type": "all docs"
      },
      "last": {
        "n": 15,
        "unit": "minutes"
      },
      "interval": {
        "n": 1,
        "unit": "minutes"
      },
      "timezoneName": "Europe/Amsterdam",
      "threshold": {
        "n": 0,
        "direction": "above eq"
      },
      "timeField": "timestamp"
    }
  },
  "save_payload": false,
  "spy": false,
  "impersonate": false
}

**Comment by sergibondarenko** [comment]
@sawdyj sorry, could you please create a new issue where yo answer to all default questions? Also, paste kibana log after the watcher was executed there? Make sure you have `logging.verbose: true` in kibana.yml
