### ISSUE TITLE
Error: unknown export types home in plugin sentinl

### ISSUE THREAD

**Issue by 90wukai** [sirensolutions/sentinl#602]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |    6.0.0     |
| Elasticsearc |         |
| Server OS    |    kibana docker      |
| Browser      |         |

#### Original Install Method

- [x] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1.
1.
1.

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Errors in Browser Console (if relevant)
```
```

#### Kibana logs and/or server output (attached if relevant)
```
{"type":"log","@timestamp":"2018-11-01T11:05:52Z","tags":["fatal"],"pid":1,"level":"fatal","message":"unknown export types home in plugin sentinl","error":{"message":"unknown export types home in plugin sentinl","name":"Error","stack":"Error: unknown export types home in plugin sentinl\n    at UiExports.consumePlugin (/usr/share/kibana/src/ui/ui_exports.js:54:13)\n    at KbnServer.<anonymous> (/usr/share/kibana/src/ui/index.js:139:19)\n    at next (native)\n    at step (/usr/share/kibana/src/ui/index.js:41:191)\n    at /usr/share/kibana/src/ui/index.js:41:361"}}
```

**Comment by havlan** [comment]
@90wukai Please add: version of sentinl, version of elasticsearch and the steps that led to this error (helpful in order to reproduce bugs)

**Comment by sergibondarenko** [comment]
@90wukai do you use the release we issued 3 days ago https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.4-3-public
Please use it.

**Comment by 90wukai** [comment]
@sergibondarenko @havlan fix it with use the correct version. Thanks!
