### ISSUE TITLE
Elasticsearch wont start after installing plugin

### ISSUE THREAD

**Issue by ralph23** [sirensolutions/sentinl#607]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |         |
| Elasticsearc |Version: 6.4.2, Build: default/rpm/04711c2/2018-09-26T13:34:09.098244Z, JVM: 1.8.0_191  |
| Server OS    |     rhel 7    |
| Browser      |  chrome       |
| Plugin  | sentinl-v6.4.2.zip

#### Original Install Method

- [ ] kibana-plugin

#### Bug Description
my elasticsearch wont completely start after adding plugin. The errors are related to the log4j2.properties file not finding something.......
```
● elasticsearch.service - Elasticsearch
Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
Active: active (running) since Wed 2018-11-14 08:25:14 EST; 10s ago
Docs: http://www.elastic.co
Main PID: 17942 (java)
CGroup: /system.slice/elasticsearch.service
├─17942 /bin/java -Xms1g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -Xss1...
└─18000 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller

Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,094 main ERROR Null object returned for RollingFile in Appenders.
Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,094 main ERROR Null object returned for RollingFile in Appenders.
Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,095 main ERROR Null object returned for RollingFile in Appenders.
Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,095 main ERROR Null object returned for RollingFile in Appenders.
Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,095 main ERROR Null object returned for RollingFile in Appenders.
Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,096 main ERROR Unable to locate appender "rolling" for logger config "root"
Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,096 main ERROR Unable to locate appender "index_indexing_slowlog_rolling" for logger con...log.index"
Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,096 main ERROR Unable to locate appender "audit_rolling" for logger config "org.elastics...uditTrail"
Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,097 main ERROR Unable to locate appender "index_search_slowlog_rolling" for logger confi...h.slowlog"
Nov 14 08:25:19 elasticsearch[17942]: 2018-11-14 08:25:19,097 main ERROR Unable to locate appender "deprecation_rolling" for logger config "org.el...precation"
```
![image](https://user-images.githubusercontent.com/41958945/48488757-84710700-e7ef-11e8-84c6-b1b3edfe528d.png)

**Comment by sergibondarenko** [comment]
Strange error. Did you install Sentinl like it is specified in the readme? https://github.com/sirensolutions/sentinl#attention-siren-10-users-should-use-the-native-version-bundled-with-their-distribution
What if you uninstall Sentinl? Can you start Elasticsearch now?

**Comment by ralph23** [comment]
> Strange error. Did you install Sentinl like it is specified in the readme? https://github.com/sirensolutions/sentinl#attention-siren-10-users-should-use-the-native-version-bundled-with-their-distribution
> What if you uninstall Sentinl? Can you start Elasticsearch now?

I did and elasticworks now

**Comment by ralph23** [comment]
> Strange error. Did you install Sentinl like it is specified in the readme? https://github.com/sirensolutions/sentinl#attention-siren-10-users-should-use-the-native-version-bundled-with-their-distribution
> What if you uninstall Sentinl? Can you start Elasticsearch now?

**Comment by ralph23** [comment]
@sergibondarenko   I reinstalled elasticsearch and the problem went away but i would like to use the pulugin.  I manually downloaded the zip file and  installed it this way `kibana-plugin install file://......`

**Comment by sergibondarenko** [comment]
Sorry, it is not clear to me, do you still have the problem? Sentinl is a Kibana plugin and it doesn't interfere with Elasticsearch work.

**Comment by ralph23** [comment]
> Sorry, it is not clear to me, do you still have the problem? Sentinl is a Kibana plugin and it doesn't interfere with Elasticsearch work.

I use it in  kibana

**Comment by ralph23** [comment]
> > Sorry, it is not clear to me, do you still have the problem? Sentinl is a Kibana plugin and it doesn't interfere with Elasticsearch work.
> 
> I use it in kibana

>Also is  there a version of sentinl that works with 6.4.2

**Comment by sergibondarenko** [comment]
You can find packages for all available versions in the releases section https://github.com/sirensolutions/sentinl/releases
