### ISSUE TITLE
Quirky behaviour by Scheduler

### ISSUE THREAD

**Issue by varunsharma27** [sirensolutions/sentinl#610]
![sentinl](https://user-images.githubusercontent.com/18154526/48756040-98b87680-ecbd-11e8-89c5-0fed4f5afe39.png)
Local Timezone:- GMT 5:30+, at time around 12:37 am
The next execution time is coming out as 15:45 which is neither 10:15 nor 17:15. Why is that so? Is there any timezone translation happening? If there is a difference in browser and server timezone then it should be specified in the result else it just brings in confusion.

**Comment by sergibondarenko** [comment]
This will be fixed in this issue https://github.com/sirensolutions/sentinl-private/issues/791

PS
@varunsharma27 Siren people open issues here https://github.com/sirensolutions/sentinl-private
