### ISSUE TITLE
I can't find the url address of the download。

### ISSUE THREAD

**Issue by sunchanglong1991** [sirensolutions/sentinl#611]
I can't find the url address of the download. I want to install it via url, but I can only find the download package and can't find the corresponding download link. Where is it?

For example: 
./kibana-plugin install **https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.3-3/sentinl-v6.2.4.zip**

Where should I find the corresponding url now?

**Comment by sergibondarenko** [comment]
The link you provided is valid. So you can just do 
```
./kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.3-3/sentinl-v6.2.4.zip
```
If you need another version, go to releases https://github.com/sirensolutions/sentinl/releases, find a .zip with the version number you need, click mouse right button, select "Copy link address" option.
