### ISSUE TITLE
Sentinl plugin for Kibana 6.5

### ISSUE THREAD

**Issue by sc7565** [sirensolutions/sentinl#612]
Do we have any updates regarding Kibana plugin support for 6.5.0 version?

**Comment by sergibondarenko** [comment]
There is a breaking change in the v6.5. It will be fixed soon. I'll keep you updated.

**Comment by sergibondarenko** [comment]
The release for v6.5 is ready https://github.com/sirensolutions/sentinl/releases/tag/tag-6.5.0-0
