### ISSUE TITLE
Plugin initialization disabled 

### ISSUE THREAD

**Issue by maxianlong** [sirensolutions/sentinl#617]
hi, my kibana 6.4.3 install sentinl 6.4.3 having an error , {"type":"log","@timestamp":"2018-11-22T02:59:06Z","tags":["info"],"pid":60982,"message":"Plugin initialization disabled."} ,i don not know why!

**Comment by sergibondarenko** [comment]
Did Sentinl start?
Catch the full log starting from Kibana restart and paste it here.
Paste kibana.yml here.

**Comment by lmangani** [comment]
This is usually a sign of a corrupted or otherwise invalid configuration. Please reinstall and attach the full logs, including the installation ones to reopen the ticket. Thanks!
