### ISSUE TITLE
Question: execute transform script from file source

### ISSUE THREAD

**Issue by cherweg** [sirensolutions/sentinl#62]
Hi,
is it possible to execute script in the transfrom block from a file source? 
e.g.:
`
   "transform": {
      "script": {
         "file": "myscript"
      }
   }
`

i´d like to transform the payload with a complex groovy script and write some fields back to a new index.

regards
christian

**Comment by lmangani** [comment]
Hi @cherweg 
Currently only inline javascript is supported, but definitely an option to use saved scripts would be interesting and reasonably simple to implement (No groovy support is planned, tho)

**Comment by lmangani** [comment]
This feature is semi-implemented in the latest 4.x and 5.x releases, where scripts/tranforms can be saved. If you'd like this feature, please do reopen the proposal and we'll happily look into it. Thanks!
