### ISSUE TITLE
Sentinl plugin for Kibana 6.5.1

### ISSUE THREAD

**Issue by StefanSa** [sirensolutions/sentinl#626]
Hi there,
First thank you for Sentinl.
Is there a chance to get a Sentinl v6.5.1 for Kibana 6.5.1 ?

**Comment by sergibondarenko** [comment]
@StefanSa  @SexyCatGirls  here is the package https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.5.1.zip
