### ISSUE TITLE
{{payload.hits.hits}} datas is empty

### ISSUE THREAD

**Issue by jjlu521016** [sirensolutions/sentinl#628]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |      6.2.4   |
| Elasticsearc |       6.2.4  |
| Server OS    |      CentOS7   |
| Browser      |   chrome      |

when i use below config,i can't get data from  {{payload.hits.hits}} ,but the {{payload.hits}} can get data,what can i do?
#### Full Watcher JSON
```
{
  "actions": {
    "Webhook_683bd385-86b3-46ba-8e1b": {
      "name": "message",
      "throttle_period": "1m",
      "webhook": {
        "priority": "high",
        "stateless": false,
        "method": "POST",
        "host": "oapi.dingtalk.com",
        "port": "443",
        "path": "/robot/send?access_token=xxx",
        "body": "{\n\"msgtype\":\"text\",\n\"text\":{\n    \"content\":\"message detail \\n {{payload.hits.hits.0._source.message}} \n    \"\n}\n}",
        "headers": {
          "Content-Type": "application/json"
        },
        "message": "Test message",
        "use_https": true
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "*"
        ],
        "body": {
          "query": {
            "bool": {
              "must": [
                {
                  "match": {
                    "message": "info"
                  }
                },
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-1m"
                    }
                  }
                }
              ]
            }
          },
          "size": 0,
          "aggs": {
            "dateAgg": {
              "date_histogram": {
                "field": "@timestamp",
                "time_zone": "Asia/Shanghai",
                "interval": "1m",
                "min_doc_count": 1
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total >= 1"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 1 minutes"
    }
  },
  "disable": true,
  "report": false,
  "title": "msg_dingding",
  "wizard": {},
  "save_payload": false,
  "spy": false,
  "impersonate": false
}
```

**Comment by aogg** [comment]
me too

**Comment by aogg** [comment]
ok!

delete    size=0

**Comment by smartrics** [comment]
Suffering of the same problem... this is the response of my query:
`{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": null,
    "hits": [
      {
        "_index": "ipt",
        "_type": "doc",
        "_id": "5lQthWgBtZkMaOX5oCbL",
        "_score": null,
        "fields": {
          "numberAttr": [
            42
          ],
          "stringAttr": [
            "foobar"
          ]
        },
        "sort": [
          1548422585046
        ]
      }
    ]
  }
}
`

whilst this works and the right value is extracted: `{{payload.hits.total}}`

anything in `payload.hits.hits` isn't extracted. For example both return blanks:

- `{{payload.hits.hits[0].fields.numberAttr[0]}}`
- `{{payload.hits.hits[0].fields.stringAttr[0]}}`

could you please suggest
