### ISSUE TITLE
No Valid Url when installing 6.2.4 package

### ISSUE THREAD

**Issue by sawdyj** [sirensolutions/sentinl#629]
Trying to install the 6.2.4 plugin on Centos 7.5.

https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.4/sentinl-v6.2.4.zip

Getting the following error when running the following command in my kibana directory
**./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.4/sentinl-v6.2.4.zip**

Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.4/sentinl-v6.2.4.zip
Picked up proxy http://cache1.uk.logica.com:80 from environment variable.
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.4/sentinl-v6.2.4.zip/https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.4/sentinl-v6.2.4.zip-6.2.4.zip
Picked up proxy "proxy_name" from environment variable.
Plugin installation was unsuccessful due to error "No valid url specified."

The url does work. It seems strange that the transfer url is concatenating the elastic and github. Please could somebody help with this issue. Many thanks!

**Comment by sawdyj** [comment]
I've also tried to install using this method where I have used wget to extract the zip file into the plugins directory.
bin/kibana-plugin install file:///plugin/sentinl-v6.2.4.zip

Attempting to transfer from file:///plugin/sentinl-v6.2.4.zip
Error: ENOTFOUND
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/file:///plugin/sentinl-v6.2.4.zip/file:///plugin/sentinl-v6.2.4.zip-6.2.4.zip
Picked up proxy http://cache1.uk.logica.com:80 from environment variable.
Plugin installation was unsuccessful due to error "No valid url specified."

**Comment by sergibondarenko** [comment]
Did you specify a full system path to the local zip? For example
```
bin/kibana-plugin install file:///home/user/Downloads/sentinl-v6.2.4.zip
```

**Comment by sawdyj** [comment]
Thank you this did work. I am however getting the following issue where the sentinl menu is not displaying correctly similar to #294 .

**Comment by sergibondarenko** [comment]
@sawdyj Please open a new issue for it.  I need Kibana log. Restart Kibana and catch all log beginning from the start.
