### ISSUE TITLE
how can i config a watcher then the  attachment will send with mail at V6.2.4

### ISSUE THREAD

**Issue by tom143tc** [sirensolutions/sentinl#631]
HI all,
i want to config  a watcher,send alarm with mail.
alarm will filting the log and send to the user there are how many errors and what's them are. 
i try to send the error logs by attachment , how should i config it ?

my watcher like this:
```
{
  "actions": {
    "email_admin": {
      "throttle_period": "1m",
      "email": {
        "to": "XX",
        "from": "XX",
        "subject": "{{payload.hits.total}} ...",
        "priority": "high",
        "body": "......."
          }
        }
      }
    }
  },
"input"{},
"condition"{},
....
}
```

**Comment by havlan** [comment]
@tom143tc it would be easier to help if we had some sample data, could you provide that? 
Check the documentation on howto create a watcher

**Comment by sergibondarenko** [comment]
@tom143tc do you know [Elasticsearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html)? This is a must for working with Sentinl.

**Comment by tom143tc** [comment]
> @tom143tc do you know [Elasticsearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html)? This is a must for working with Sentinl.

i can query the error logs, i don't know how can the logs be send with mail by attachment....

**Comment by tom143tc** [comment]
@sergibondarenko Although the attempt still failed，thanks very much  for you help. I think i using the sentinl on a wrong way.My original intention is using sentinl for alerting the coding man that the app had some running exception and sending the error count by email and the error logs  about the part of exception  by attachment .And, i find the config of email.body can't send the detials of payload.hits.hits[i].
