### ISSUE TITLE
Can not delete configuration parameter of sentinl watcher

### ISSUE THREAD

**Issue by ypc123ypc** [sirensolutions/sentinl#633]
## version
* sentinl:6.2.4
* kibana:6.2.4
---
## description
* i copied sentinl watcher json configuration from other version to my server. but some parameter is useless, i hop delete it, but i failed.

### configuration
* my configuration 
```
{
  "actions": {
   ....
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "metricbeat-6.4.2-*"
        ],
        "body": {
          "size": 0,
          "aggs": {
            "hostname": {
              "terms": {
                "field": "beat.hostname",
                "min_doc_count": 30
              },
              "aggs": {
                "cpupct": {
                  "avg": {
                    "field": "system.cpu.total.norm.pct"
                  }
                }
              }
            }
          },
          "docvalue_fields": [
            "@timestamp"
          ],
          "query": {
            "bool": {
              "must": [
                {
                  "query_string": {
                    "query": "metricset.module:system AND metricset.name:cpu AND system.cpu.total.norm.pct:>0.8",
                    "analyze_wildcard": true,
                    "default_field": "*"
                  }
                },
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-15m",
                      "lte": "now",
                      "format": "epoch_millis"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 30"
    },
    "array_compare": {
      "payload.aggregations.hostname.buckets": {
        "path": "doc_count",
        "gte": {
          "value": 30,
          "quantifier": "some"
        }
      }
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 15 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "aaaaa(80%)",
  "wizard": {},
  "save_payload": false,
  "spy": false,
  "impersonate": false
}
``` 
* i holp delete '"wizard": {}' parameter in my configuration, but it's still there when i edit it again. is a bug? my english is poor, I don't know if I'm describing it clearly

**Comment by ypc123ypc** [comment]
> Seems like a leftover, small one. It doesn't effect watcher work, right?
> Btw, do you use the latest 6.2.4 release from Oct 30? There is a bunch of fixes https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.4-3-public

i don't know how to look my specific version, is `./kibana-plugin list` ? the command show my sentinl version is 6.0.0. and in package.json:
```
  "name": "sentinl",
  "version": "6.0.0",
  "kibana": {
    "version": "6.2.4"
  },
```
> installed by sentinl-v6.2.4.zip package (no remember what minor version is)

* My array_compare condition not work now ,so i try to troubleshooting the problem. when i compared my json config with the correct one, i find the correct config is don't have "wizard" parameter, so i try to delete it, but my failed.

**Comment by sergibondarenko** [comment]
> i don't know how to look my specific version

Sentinl version is Kibana version. On occasion we issue new releases with updates/fixes for the same Kibana version. Just pick the latest release .zip if you don't rember the date when you downloaded Sentinl.

> ... i find the correct config is don't have "wizard" parameter

The `wizard` property does nothing with `array_compare` condition. Try to execute your query manually by `curl` and see if you receive aggregation buckets
```
curl -X GET "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": { 
    put your query here
  }
```

Here is an example of `compare_codition` work. Presume Elasticsearch returns payload:
```
    payload = {
      time: moment().subtract(moment.duration(10, 'm')).format(), // time 10 min ago
      aggregations: {
        top_amounts: {
          buckets: [
            { doc_count: 5 },
            { doc_count: 1 },
            { doc_count: 2 }
          ]
        }
      },
      hits: {
        total: 285133,
        hits: [
          { _source: { amount: -57 }},
          { _source: { amount: 55 }},
          { _source: { amount: -20 }},
...
        ]
      }
    };
```

And you have this in the watcher condition:
```
      array_compare: {
        'payload.aggregations.top_amounts.buckets': {
          path: 'doc_count',
          gte: {
            value: 5,
            quantifier: 'some'
          }
        }
      }
```

The condition is matched and the watcher is executed because there is at least one doc with `doc_count: 5`. If you want to match all, put this in condition `quantifier: 'all'`.

**Comment by sergibondarenko** [comment]
Also, you can use [Kibana dev tools](https://www.elastic.co/guide/en/kibana/current/console-kibana.html) instead of the `curl` to test your query.

**Comment by ypc123ypc** [comment]
yes,sergibondarenko,i know what you mean, and i solved my problem when i remove “wizard” parameter in new configuration(sounds weird, i do not know why). tks very much.
But still i conn't remove “wizard” parameter at current configuration, i need to create new configuration,and copy current configuration, then remove “wizard” parameter.....

anyway, the problem has been solved. tks sergibondarenko again.  : )

**Comment by ypc123ypc** [comment]
yes sergibondarenko,you are right,the wizard property does nothing with array_compare condition...
the reason for this problem is array_compare can't work when aggregations is empty

**Comment by sergibondarenko** [comment]
> this problem is array_compare can't work when aggregations is empty

What do you mean? Do you mean that the watcher is not triggered when there are no aggregations?
If yes, then it is correct behavior. The `array_compare` condition requires either `all` or `some` of values in the aggregation buckets.

**Comment by ypc123ypc** [comment]
yes,so i solved the problem by this condition:
```
payload.aggregations[2] && payload.aggregations[2].buckets.length > 0
```
tks sergibondarenko very much！
