### ISSUE TITLE
Sentinl for Kibana 6.5 fails starting up with error "Cannot find module later/later"

### ISSUE THREAD

**Issue by Grashee** [sirensolutions/sentinl#634]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |    6.5     |
| Elasticsearch |      6.5   |
| Server OS    |   CentOS      |
| Browser      |    Opera     |

#### Original Install Method

- [x] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

### Bug Details
I want to update my old SENTINL Installation (old version 6.3) to 6.5 and I have changed the packages (directories containing sentinl). After that I want to start my Kibana installation but it breaks down with the error (see server output)

#### Expected Behavior
Kibana is starting up,

#### Kibana logs and/or server output (attached if relevant)
Dec 07 10:10:59 server kibana[14774]: FATAL  Error: Cannot find module 'later/later'
Dec 07 10:10:59 server systemd[1]: kibana.service: main process exited, code=exited, status=1/FAILURE
Dec 07 10:10:59 server systemd[1]: Unit kibana.service entered failed state.
Dec 07 10:10:59 server systemd[1]: kibana.service failed.

**Comment by sergibondarenko** [comment]
> ...I have changed the packages (directories containing sentinl)

Did you install Sentinl like this?
```
./bin/kibana-plugin install sentinl.zip
```

Did you notice any error during or after the installation? Please try to reinstall Sentinl using the command above, the `later` package must be there.

**Comment by Grashee** [comment]
I´ve reinstalled sentinl, now it works.

**Comment by sergibondarenko** [comment]
@Grashee can we close this issue too? https://github.com/sirensolutions/sentinl/issues/635

**Comment by Grashee** [comment]
@sergibondarenko No the #635 issue is a new problem I have
