### ISSUE TITLE
Where to find Sentinl in Kibana 6.5

### ISSUE THREAD

**Issue by Grashee** [sirensolutions/sentinl#635]
Hey guys,

I have installed SENTINL in my Kibana Installation with version 6.5.0.
My problem is, where can I find SENTINL? There is no icon in my spaces where I can open sentinl.

The original link from kibana version 6.3.0 doesn´t work. It shows me an error which says there is no plugin installed with the name sentinl.

Is there a new way to access sentinl?

Best regards!

**Comment by sergibondarenko** [comment]
I can't reproduce the issue. Please give more details:

1. What OS?
2. Give your installation process log
3. Restart Kibana and paste all its log here

## Reproducing
OS Ubuntu v18
```
$ wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.0.tar.gz
$ tar -xzvf elasticsearch-6.5.0.tar.gz && ./elasticsearch-6.5.0/bin/elasticsearch
$ wget https://artifacts.elastic.co/downloads/kibana/kibana-6.5.0-linux-x86_64.tar.gz
$ tar -xzvf kibana-6.5.0-linux-x86_64.tar.gz
$ cd kibana-6.5.0-linux-x86_64
$ ./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.5.0.zip
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.5.0.zip
Transferring 242842901 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
$ ./bin/kibana
...
  log   [08:58:44.123] [info][Sentinl][init] initializing ...
  log   [08:58:44.132] [info][Sentinl][init] Chrome bin found at: /home/trex/dist/elastic/kibana-6.5.0-linux-x86_64/plugins/sentinl/node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome
  log   [08:58:44.162] [info][Sentinl][init_indices] checking watcher_alarms-2018.12.10 index ...
  log   [08:58:44.164] [info][Sentinl][init] PhantomJS bin found at: /home/trex/dist/elastic/kibana-6.5.0-linux-x86_64/plugins/sentinl/phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  log   [08:58:44.187] [info][Sentinl][init_indices] creating watcher_alarms-2018.12.10 index ...
...
```

## Result
Sentinl was installed and accessible from the left nav bar.
![screenshot from 2018-12-10 10-03-42](https://user-images.githubusercontent.com/5389745/49721647-14756580-fc63-11e8-8c60-16f14b24b4ce.png)
![screenshot from 2018-12-10 10-03-57](https://user-images.githubusercontent.com/5389745/49721649-14756580-fc63-11e8-8555-4f9d13b39ef7.png)

**Comment by Grashee** [comment]
Hi @sergibondarenko 

I have a typo in my first post (my Kibana Version is 6.5.1)

System-Information
OS: CentOS
Kibana-Version: 6.5.1
Sentinl: 6.5.1


I have restarted my Kibana-service, and now Kibana does not start...

Now I restarted the whole server and re-installed the zip-package with kibana-plugin and getting the following error after a few minutes:

Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false
(node:15648) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/share/kibana/node/bin/node]
 2: 0x8c21ec [/usr/share/kibana/node/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/share/kibana/node/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/share/kibana/node/bin/node]
 5: v8::internal::Factory::NewTransitionArray(int) [/usr/share/kibana/node/bin/node]
 6: v8::internal::TransitionsAccessor::Insert(v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [/usr/share/kibana/node/bin/node]
 7: v8::internal::Map::ConnectTransition(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::SimpleTransitionFlag) [/usr/share/kibana/node/bin/node]
 8: v8::internal::Map::CopyReplaceDescriptors(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Handle<v8::internal::LayoutDescriptor>, v8::internal::TransitionFlag, v8::internal::MaybeHandle<v8::internal::Name>, char const*, v8::internal::SimpleTransitionFlag) [/usr/share/kibana/node/bin/node]
 9: v8::internal::Map::CopyAddDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [/usr/share/kibana/node/bin/node]
10: v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag) [/usr/share/kibana/node/bin/node]
11: v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Object::StoreFromKeyed, bool*) [/usr/share/kibana/node/bin/node]
12: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/usr/share/kibana/node/bin/node]
13: v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/share/kibana/node/bin/node]
14: v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed, v8::internal::MaybeHandle<v8::internal::Object>) [/usr/share/kibana/node/bin/node]
15: v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/share/kibana/node/bin/node]
16: v8::internal::KeyedStoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/share/kibana/node/bin/node]
17: v8::internal::Runtime_KeyedStoreIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/share/kibana/node/bin/node]
18: 0x3281f91842fd

.
.
.


<--- Last few GCs --->

[15648:0x4106bc0]  1162705 ms: Mark-sweep 1326.8 (1466.9) -> 1326.8 (1466.9) MB, 1302.7 / 0.0 ms  allocation failure GC in old space requested
[15648:0x4106bc0]  1164257 ms: Mark-sweep 1326.8 (1466.9) -> 1326.8 (1435.9) MB, 1306.1 / 0.0 ms  last resort GC in old space requested
[15648:0x4106bc0]  1165851 ms: Mark-sweep 1326.8 (1435.9) -> 1326.8 (1435.9) MB, 1594.0 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1efbc5225879 <JSObject>
    1: OutputStream(aka OutputStream) [0x33e5586022d1 <undefined>:~5547] [pc=0x3281fa15f263](this=0x33e5586022d1 <undefined>,options=0x33e5586022d1 <undefined>)
    2: /* anonymous */(aka /* anonymous */) [0x33e5586022d1 <undefined>:~11351] [pc=0x3281faa85087](this=0x33e5586022d1 <undefined>,self=0x3353ef466111 <AST_If map = 0x2ef7e1bbe531>,compressor=0x25d082ede161 <Compressor map = 0x3f4195db8...

"

**Comment by sergibondarenko** [comment]
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

I have never seen this error but I googled it and it seems a Node.JS error related to Kibana optimization. [They recomend to encrease Node.JS heap size](https://github.com/elastic/kibana/issues/15683#issuecomment-353617621), for example
```
NODE_OPTIONS="--max-old-space-size=4096" bin/kibana-plugin install sentinl.zip
```

What Node.js version do you have? `node -v`

**Comment by sergibondarenko** [comment]
If you installed Sentinl well and fail to start Kibana, set the `NODE_OPTIONS` as env variable.

**Comment by Grashee** [comment]
@sergibondarenko SENTINLs installation isn´t successfull the error I wrote above is an error which occurs while the installation is in process. 

I observed the RAM during the installation and can not see any bottlenecks which indicates thereupon is an RAM error. But I will try fixing it by changing the env variable.

**Comment by sergibondarenko** [comment]
You can have terabytes of RAM but Node.js limit is around 1400 MB for the 64-bit machine https://github.com/nodejs/node/issues/7937#issuecomment-269997873

**Comment by Grashee** [comment]
Thanks for your help! @sergibondarenko 

I´ve fixed it, setting the NODE_OPTIONS temporary to 4GB.

**Comment by fredtw** [comment]
Thanks, this helps me to fix the problem @fredTW
