### ISSUE TITLE
Trouble with Range Filtering and Cardinality Aggregate Query

### ISSUE THREAD

**Issue by certuc3m** [sirensolutions/sentinl#636]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |  6.3.2       |
| Elasticsearc |  6.3.2       |
| Server OS    |  Linux (Ubuntu 18.04       |
| Browser      |   Linux Chrome 67.0.3396.62 (Build Oficial - 64 bits)      |

#### Original Install Method

- [X] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

### Bug Details
Range condition does not work as expected

#### Bug Description
We have setup a watcher to monitor sessions on a fw. The watcher makes a query to ES an get the top 50 talker hosts (result of an aggregate query, field TopSRC.value is the number of different IP destinations contacted).

It is supposed that the watcher only includes those hosts that had hit more than 5000 destination IP, but it includes all hosts returned by ES (50) no matter the number of Destination IPs contacted.

#### Steps to Reproduce
1. Create a new Watcher Advanced
1. Change the ES query to create a cardinality aggregation query (https://www.elastic.co/guide/en/elasticsearch/reference/6.3/search-aggregations-metrics-cardinality-aggregation.html)
1. Change the condition to check values returned from ES using a Range Filtering, quite similar to sentinl doc (https://sentinl.readthedocs.io/en/latest/Watcher-Anatomy/#condition_1)

#### Expected Behavior
Only those values higher than bottom limit should raise an alert

#### Sample of data you have in Elasticsearch
```
{
  "_index": "watcher_alarms",
  "_type": "sentinl-alarm",
  "_id": "V6JSl2cBdzNNkZqdu1eO",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2018-12-10T08:54:00.813Z",
    "error": false,
    "report": false,
    "watcher": "ScanIP-Externo",
    "action": "Webhook",
    "level": "low",
    "message": "test",
    "payload": {
      "took": 719,
      "timed_out": false,
      "_shards": {
        "total": 300,
        "successful": 300,
        "skipped": 295,
        "failed": 0
      },
      "hits": {
        "total": 213926,
        "max_score": 0,
        "hits": []
      },
      "aggregations": {
        "bucketAgg": {
          "doc_count_error_upper_bound": -1,
          "sum_other_doc_count": 108042,
          "buckets": [
            {
              "key": "185.143.223.104",
              "doc_count": 16624,
              "TopSRC": {
                "value": 14357
              }
            },
            {
              "key": "176.119.4.61",
              "doc_count": 10619,
              "TopSRC": {
                "value": 9545
              }
            },
            {
              "key": "185.156.177.101",
              "doc_count": 10181,
              "TopSRC": {
                "value": 9052
              }
            },
            {
              "key": "185.156.177.124",
              "doc_count": 3773,
              "TopSRC": {
                "value": 3554
              }
            },
            {
              "key": "185.156.177.125",
              "doc_count": 3115,
              "TopSRC": {
                "value": 2946
              }
            },
            {
              "key": "185.176.27.6",
              "doc_count": 2630,
              "TopSRC": {
                "value": 2611
              }
            },
            {
              "key": "79.124.56.130",
              "doc_count": 2785,
              "TopSRC": {
                "value": 2572
              }
            },
            {
              "key": "194.28.115.245",
              "doc_count": 2497,
              "TopSRC": {
                "value": 2432
              }
            },
```
#### Full Watcher JSON
```
{
  "actions": {
    "email_html_alarm_b313fde0-faa2-4973-92ea-4d1335bcba99": {
      "name": "test",
      "throttle_period": "10m",
      "email_html": {
        "stateless": false,
        "subject": "{{payload.hits.total}} new results from watcher {{watcher.title}}",
        "priority": "high",
        "html": "<p>Hi {{watcher.username}}</p>\n<p>There are {{payload.hits.total}} results found by the watcher <i>{{watcher.title}}</i>.</p>\n\n<table border=\"1\"><th>IPs</th><th>#Dest. IP</th><th>#Conn</th>{{#payload.aggregations.bucketAgg.buckets}}<tr><td>{{key}}</td><td>{{TopSRC.value}}</td><td> {{doc_count}}</td></tr>{{/payload.aggregations.bucketAgg.buckets}}</table><hr>",
        "to": "certuc3m",
        "from": "root@es.uc3m.es"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "panos*"
        ],
        "body": {
          "query": {
            "bool": {
              "must": [
                {
                  "match_all": {}
                },
                {
                  "match_all": {}
                },
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-15m/m",
                      "lte": "now/m",
                      "format": "epoch_millis"
                    }
                  }
                },
                {
                  "match_phrase": {
                    "Type": {
                      "query": "TRAFFIC"
                    }
                  }
                }
              ],
              "filter": [],
              "should": [],
              "must_not": [
                {
                  "bool": {
                    "should": [
                     {
                        "match_phrase": {
                          "SourceIP": "10.0.0.0/8"
                        }
                      },
                      {
                        "match_phrase": {
                          "SourceIP": "192.168.0.0/16"
                        }
                     }
                    ],
                    "minimum_should_match": 1
                  }
                }
              ]
            }
          },
          "size": 0,
          "aggs": {
            "bucketAgg": {
              "terms": {
                "field": "SourceIP",
                "size": 50,
                "order": {
                  "TopSRC": "desc"
                }
              },
              "aggs": {
                "TopSRC": {
                  "cardinality": {
                    "field": "DestinationIP"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 0"
    },
    "range": {
      "field_to_check": "value",
      "min": 5000
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 1 minutes"
    }
  },
  "disable": true,
  "report": false,
  "title": "ScanIP-Range",
  "wizard": {},
  "save_payload": true,
  "spy": false,
  "impersonate": false
}
```
#### Errors in Browser Console (if relevant)
```
```

**Comment by lmangani** [comment]
@certuc3m I would assume the script condition is returning true before the range condition is even checked. Use a single method whenever possible to validate the input or you might get false positives.

**Comment by certuc3m** [comment]
> @certuc3m I would assume the script condition is returning true before the range condition is even checked. Use a single method whenever possible to validate the input or you might get false positives.

I have tried also, but I have got the same results. 50 hosts, most of them with fewer connections than the minimum level (5000).

I think that I have not set the field name correctly because it is a Cardinality Aggregation and entries are indexed by key. Could it be?

payload.aggregations.bucketAgg.buckets has the following data:
[
{
"key": "185.143.223.104",
"doc_count": 16624,
"TopSRC": {
"value": 14357
}
},
{
"key": "176.119.4.61",
"doc_count": 10619,
"TopSRC": {
"value": 9545
}
},
{
"key": "185.156.177.101",
"doc_count": 10181,
"TopSRC": {
"value": 9052
}
},
{
"key": "185.156.177.124",
"doc_count": 3773,
"TopSRC": {
"value": 3554
}
},
{
"key": "185.156.177.125",
"doc_count": 3115,
"TopSRC": {
"value": 2946
}
}....


And we look for values higher than 5000 on "TopSRC.value"

Thanks for your time

**Comment by certuc3m** [comment]
> Now `range` works only for docs in `payload.hits.hits`, it doesn't work for aggregation buckets. But you can achieve what you want using JavaScript, for example, try this condition:
> 
> ```
>   "condition": {
>     "script": {
>       "script": "payload.aggregations.bucketAgg.buckets.filter(b => b.TopSRC.value >= 5000).length > 0"
>     }
>   },
> ```

The script only checks that at least one value is over 5000, but you gave a point to solution. Overwrite payload.aggregations.bucketAgg.buckets

"condition": {
    "script": {
      "script": "var test=payload.aggregations.bucketAgg.buckets.filter(b => b.TopSRC.value >= 5000);payload.aggregations.bucketAgg.buckets=test;test.length > 0"
    }
  },

Now it works like charm. Thank you ver much
