### ISSUE TITLE
Anomaly watcher for ping times

### ISSUE THREAD

**Issue by Grashee** [sirensolutions/sentinl#639]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |      6.5   |
| Elasticsearch |  6.5   |
| Server OS    |    CentOS     |
| Browser      |     Opera    |

#### Original Install Method

- [X] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

### Creation of an Anomaly watcher for ping times
Hey guys,

I want to create an anomaly watcher which checks for ping-times which are higher then the average.

Example situation:
In a normal day there are around 3 million documents in my index. The average load times are 0-300 milli seconds, but sometimes there are higher values around 600-2000 milli seconds. That are the values which I want to be detected.

How can I create an anomaly detector for something like this?

I´ve tried it before with the tutorial (https://sentinl.readthedocs.io/en/latest/HOWTO-Anomaly-Detection/) but this watcher sents me everytime an anomaly email with allpossible all documents.

Thanks to all who can help!

**Comment by lmangani** [comment]
@Grashee this is quite a simple case generally speaking, but the best answer greatly depends on the query and response you're trying to use. If you're willing to attach a sample response, we can nudge you in the right direction.

**Comment by Grashee** [comment]
Hi @lmangani , 
I get the following result from my watcher: 

```
{
  "@timestamp": "2018-12-12T14:25:54.170Z",
  "error": false,
  "report": false,
  "watcher": "Ping-Anomalie-Überwachung",
  "action": "Anomalie Alarmierung: Ping",
  "level": "high",
  "message": "Series Alarm : 67067621",
  "payload": {},
  "type": "sentinl-alarm",
  "_index": "watcher_alarms-2018.12.12",
  "id": "9pXPomcBlrsVYzI-TRr_"
}
```

and my watcher looks like this:

```
{
  "actions": {
    "email_html_alarm_66a478ea-06ec-4800-bd56-2c6e6826c940": {
      "name": "Anomalie Alarmierung: Ping",
      "throttle_period": "1m",
      "email_html": {
        "stateless": false,
        "subject": "Anomalie Alarmierung | {{payload.hits.total}} neue Ergebnisse von {{watcher.title}}",
        "priority": "high",
        "html": "<h1 style="background-color:DodgerBlue;color:white;padding:5px">Anomalies</h1>
<div style="background-color:Tomato;color:white;padding:5px">
<ul>
{{#payload.anomaly}}
<li><b>id:</b> {{_id}} <b>Amount</b>: {{_source.Amount}}</li>
{{/payload.anomaly}}
</ul>
</div>",
        "to": "grashee@grashee.de",
        "from": "server@grashee.de"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "performance-*"
        ],
        "body": {
          "size": 10000,
          "query": {
            "bool": {
              "must": [
                {
                  "exists": {
                    "field": "Ping"
                  }
                }
              ]
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 0"
    },
    "anomaly": {
      "field_to_check": "Ping"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 10 minutes"
    }
  },
  "disable": true,
  "report": false,
  "title": "Ping-Anomalie-Überwachung",
  "save_payload": false,
  "spy": false,
  "impersonate": false
}
```

**Comment by lmangani** [comment]
@Grashee I was referring to the query response, rather than SENTINL's :)

**Comment by Grashee** [comment]
Oh sorry, here is a sample response of the query:

```
{
  "took" : 836,
  "timed_out" : false,
  "_shards" : {
    "total" : 202,
    "successful" : 202,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 67386821,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "performance-2018.08.22",
        "_type" : "doc",
        "_id" : "axJBYGUB1_dyxclTUxS3",
        "_score" : 1.0,
        "_source" : {
          "@version" : "1",
          "activity" : "ping",
          "@timestamp" : "2018-08-22T06:10:18.028Z",
          "Ping" : 15.600000000000001,
          "type" : "performance",
          "website" : "grashee.de"
        }
      },
      {
        "_index" : "performance-2018.08.22",
        "_type" : "doc",
        "_id" : "bBJBYGUB1_dyxclTUxS3",
        "_score" : 1.0,
        "_source" : {
          "@version" : "1",
          "activity" : "ping",
          "@timestamp" : "2018-08-22T06:10:18.048Z",
          "Ping" : 46.800000000000004,
          "type" : "performance",
          "website" : "grashee.de"
        }
      }
    ]
  }
}
```

**Comment by sergibondarenko** [comment]
> The average load times are 0-300 milli seconds, but sometimes there are higher values around 600-2000 milli seconds. 

I don't see `load` property in the response sample. Did you mean `Ping` value?
You can query for the value range you want to see in `Ping`, for example, get docs with `Ping` value greater then or equal to 600:
```
{
    "query": {
        "range" : {
            "Ping" : {
                "gte" : 600
            }
        }
    }
}
```
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html

Then the condition is simple
```
  "condition": {
    "script": {
      "script": "payload.hits.total > 0"
    }
  }
```

**Comment by Grashee** [comment]
Hey @sergibondarenko ,
Thanks for the help, this works!

Can you also say me how I just watch the last 15minutes?

**Comment by Grashee** [comment]
I´ve created this but this does not work....

```
        "query": {
          "bool": {
            "must": [
              {
                "range": {
                  "Ping": {
                    "gte": 600
                  }
                }
              },
              {
                "range": {
                  "@timestamp": {
                    "gte": "now-1h"
                  }
                }
              }
            ]
          }
        }
```

**Comment by lmangani** [comment]
@Grashee you need to balance Watcher execution with "lookback" period and make those match to achieve your goal, so a watcher `every 15m`  should look in timerange ` now() -15m`

**Comment by sergibondarenko** [comment]
@Grashee try count the docs in the Kibana dev console, for example
```
GET /performance-*/doc/_count
{
        "query": {
          "bool": {
            "must": [
              {
                "range": {
                  "Ping": {
                    "gte": 600
                  }
                }
              },
              {
                "range": {
                  "@timestamp": {
                    "gte": "now-1h"
                  }
                }
              }
            ]
          }
        }
}
```

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html

**Comment by Grashee** [comment]
Hey guys,

My watcher works now, but I have a problem executing them. I have configured that the watcher should run every 1 h but after this time they are not executed . Is there anything which I must to activate?

Best regards!

**Comment by sergibondarenko** [comment]
What does happen if you execute the watcher manually by clicking the play icon on the watcher under the Watchers tab? Paste the recent Kibana log here after you executed it.

**Comment by sergibondarenko** [comment]
> I have configured that the watcher should run every 1 h but after this time they are not executed

> When I manually run the watcher everything works fine and it sends me a mail, if the amount of events are reached.

Maybe you don't have the required amount of events in 1 hour for watcher? Did you play with schedule and condition?

Show me your condition.

**Comment by Grashee** [comment]
@sergibondarenko 
```
  "condition": {
    "script": {
      "script": "payload.hits.total > 0"
    },
    "anomaly": {
      "field_to_check": "Ping"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 1h"
    }
  }
```

**Comment by sergibondarenko** [comment]
Try this to see whether watcher is triggered if the are no data at all. Check after 1+ minutes.
```
  "condition": {
    "script": {
      "script": "payload.hits.total >= 0"
    },
    "anomaly": {
      "field_to_check": "Ping"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 1m"
    }
  }
```

**Comment by sergibondarenko** [comment]
> "later": "every 1h"

There is no need to wait 1 hour to check if the watcher will be executed automatically. You can create a JS or bash script to index documents you need and test the watcher with much lower schedule intervals over these docs.

**Comment by sergibondarenko** [comment]
Strange, I can't reproduce it. Maybe you have "action Throttled for 1m" message in Alarms?

Please put `logging.verbose: true` to kibana.yml, restart Kibana and test Sentinl with the watcher below. Verbose mode will show you debug messages in the log.

Watcher for the test:
```
{
  "actions": {
    "email_html_alarm_7dea59ad-3048-40e7-8789-5c66422a87f8": {
      "name": "email html alarm",
      "throttle_period": "1s",
      "email": {
        "to": "",
        "from": "",
        "stateless": false,
        "subject": "{{payload.hits.total}} new results from watcher {{watcher.title}}",
        "priority": "high",
        "body": "There are {{payload.hits.total}} results found by the watcher {{watcher.title}}"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [],
        "body": {}
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total >= 0"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 1 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "watcher_title",
  "save_payload": false,
  "spy": false,
  "impersonate": false
}
```

Expected result
![screenshot from 2019-01-16 19-01-50](https://user-images.githubusercontent.com/5389745/51268863-46e05400-19c1-11e9-8bbf-c11bef53b0df.png)

**Comment by Grashee** [comment]
Hey @sergibondarenko 

is there a problem using this "spelling"
```
  "trigger": {
    "schedule": {
      "later": "every 1m"
    }
  }
```
instead of 
```
  "trigger": {
    "schedule": {
      "later": "every 1 minutes"
    }
  }
```




> Maybe you have "action Throttled for 1m" message in Alarms?

Yeah I get these messages when I execute 2 watchers behind each other

**Comment by sergibondarenko** [comment]
> is there a problem using this "spelling"

We use later.js text parser there, here are examples of values you can set https://bunkat.github.io/later/parsers.html#text

**Comment by Grashee** [comment]
The problem was using "every 1m" instead of "every 1 minutes".

**Comment by mehmetcakmaz** [comment]
@Grashee Could you send latest anomaly detection query.

**Comment by mohitrawat0123** [comment]
> > is there a problem using this "spelling"
> 
> We use later.js text parser there, here are examples of values you can set https://bunkat.github.io/later/parsers.html#text

much useful.
