### ISSUE TITLE
Sentinl plugin for Kibana 6.5.2 or 6.5.3

### ISSUE THREAD

**Issue by rhysxevans** [sirensolutions/sentinl#644]
Hi

Any ETA on a plugin for kibana 6.5.2 or 6.5.3?

Thanks

**Comment by sergibondarenko** [comment]
I added new packages to the existing release https://github.com/sirensolutions/sentinl/releases/tag/tag-6.5.0-0
Please let me know if something doesn't work.

**Comment by celesteking** [comment]
There's no 6.5.4. Setting up a CI build would definitely help.
