### ISSUE TITLE
kaae.json settings are not applied

### ISSUE THREAD

**Issue by juhwankim** [sirensolutions/sentinl#65]
Hi,

Does not work when default_index, type, alarm_index (in kaae.json) is edited.
The two files below are not using the values (default_index, type) of kaae.json file.

installedPlugins/kaae/server/scheduler.js
function getWatcher(count,client) {
  return client.search({
    index:'watcher',   //<--- not using values of kaae.json
    type:"watch",      //<--- not using values of kaae.json
    size:count
  });
}

installedPlugins/kaae/server/routes.js
  // List Watchers
  server.route({
    path: '/api/kaae/list',
    method: ['POST', 'GET'],
    handler: function (req, reply) {
      const boundCallWithRequest = _.partial(server.plugins.elasticsearch.callWithRequest, req);
      boundCallWithRequest('search', {
        index: 'watcher',   //<---- not using values of kaae.json
        size: config.kaae.results ? config.kaae.results : 50,
        allowNoIndices: false
      })
      .then(
        function (res) {
          reply(res);
        },
        function (error) {
          reply(handleESError(error));
        }
      );
    }
  });

**Comment by urban-it-solutions** [comment]
**scheduler.js:**

function getCount(client) {
  _var config = require('../../kaae.json');_
  return client.count({
    _index: config.es.default_index,
    type: config.es.type_
  });
}

function getWatcher(count,client) {
  var config = require('../../kaae.json');
  return client.search({
    index: config.es.default_index,
    type: config.es.type,
    size:count
  });
}

**routes.js:**

export default function (server) {
  _var config = require('../../kaae.json');_
...
// List Watchers
  server.route({
    path: '/api/kaae/list',
    method: ['POST', 'GET'],
    handler: function (req, reply) {
      const boundCallWithRequest = _.partial(server.plugins.elasticsearch.callWithRequest, req);
      boundCallWithRequest('search', {
        _index: config.es.default_index,_
        allowNoIndices: false

**Comment by lmangani** [comment]
```kaae.json``` should not be accessed directly, ```config.js``` will provide it depending on priority of lookup. Those settings are about to be moved to Kibana.yml so this is transitory only. 
This said, issue was already patched in our private branch, will merge back soon to master, sorry to keep you guys waiting.

**Comment by lmangani** [comment]
release 4.6.3 moves the configuration to the internal yaml and should fully address this inconsistency. Nightly build updated with latest snapshot pre-release for testing.

NOTE: watcher_alarm-* index mapping changed to support reports

**Comment by fbaligand** [comment]
@lmangani 
So now : where is sentinl config stored ? in kibana.yml ?
Is there a wiki page explaining how to configure sentinl ?
Is $sentinl/sentinl.json not any more processed ?

**Comment by lmangani** [comment]
@fbaligand  the wiki has been updated, configuration now goes in kibana.yml to keep things cleaner

**Comment by fbaligand** [comment]
Mmhh... it seems that this wiki part has not been updated :)
https://github.com/sirensolutions/sentinl#configuration--usage

**Comment by lmangani** [comment]
README != WIKI :)

https://github.com/sirensolutions/sentinl/wiki/SENTINL-Config-Example

We'll update the README tomorrow or so with more details, but it already points at the right link.

**Comment by fbaligand** [comment]
Indeed :)

Now the most important : I just tested to configure sentinl in kibana.yml, and activated email notification... and it works great !

**Comment by juhwankim** [comment]
I've checked the kibana.yml. Thank you:)

But I'm afraid there has been another problem.
When you install SENTINL and restart kibana, the index creates fine based on the settings of sentinl.es.default_index, but the sentinl.es.type settings are ignored. The type is always set to "watch".

This is the code i've used: 

[ kibana.yml ]
sentinl.es.timefield: '@timestamp'
sentinl.es.default_index: watcher_test
sentinl.es.type: watch_test
sentinl.es.alarm_index: watcher_test_alarms

[ sentinl ]
{
  "_index": "watcher_test",
  "_type": "watch_test",
  "_id": "test",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 15 minutes"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": "topbeat-*",
          "body": {
            "size": 10,
            "query": {
              "constant_score": {
                "filter": {
                  "range": {
                    "load.load1": {
                      "gte": 0.7,
                      "lte": 100
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 1"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "30m",
        "email": {
          "to": "test@localhost",
          "from": "test@localhost",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "{{#payload.hits.hits}}{{#_source}}{{#load}}load1: {{load1}}{{/load}}\n{{/_source}}{{/payload.hits.hits}}"
        }
      }
    }
  }
}

[ watcher_test metadata ]
{
"state": "open",
"settings": {
"index": {
"routing": {
"allocation": {
"require": {
"box_type": "hot"
}
}
},
"creation_date": "1483595759090",
"number_of_shards": "1",
"number_of_replicas": "1",
"uuid": "Ws5eqNfnQ6qA6aZpfd-0dQ",
"version": {
"created": "2030399"
}
}
},
"mappings": {
"watch": {
"properties": {
"input": {
"type": "object",
"enabled": false
},
"server": {
"index": "not_analyzed",
"type": "string"
},
"condition": {
"type": "object",
"enabled": false
},
"transform": {
"type": "object",
"enabled": false
},
"@timestamp": {
"format": "strict_date_optional_time||epoch_millis",
"type": "date"
},
"service_name": {
"index": "not_analyzed",
"type": "string"
}
}
},
"_default_": {
"properties": {
"server": {
"index": "not_analyzed",
"type": "string"
},
"@timestamp": {
"format": "strict_date_optional_time||epoch_millis",
"type": "date"
},
"service_name": {
"index": "not_analyzed",
"type": "string"
}
}
}
},
"aliases": [ ]
}

**Comment by lmangani** [comment]
I'm not sure allowing to change types was a good idea to begin with, as they are more and more used to distinguish between different kind of watchers/reports to the point I no longer see the value of adding them. No issue with the index names, of course.
