### ISSUE TITLE
Sentinl page not correctly displayed: Red status

### ISSUE THREAD

**Issue by sawdyj** [sirensolutions/sentinl#650]
![image](https://user-images.githubusercontent.com/45589218/50161452-b7695780-02d3-11e9-8429-da167e369d3d.png)

Getting the following after a successful install of the sentinl plugin after restarting kibana.
Installed via:  ./bin/kibana-plugin install file:///home/common/downloads/sentinl-v6.2.4.zip
All menus load this status breakdown page.

I am running elassandra. I'm unsure if the error is timestamp related or index mapping. Please could someone lend a hand. Thanks!

My kibana.log file contains the following
```
{"type":"log","@timestamp":"2018-12-18T10:06:58Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
{"type":"log","@timestamp":"2018-12-18T10:07:00Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
{"type":"log","@timestamp":"2018-12-18T10:07:03Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
{"type":"log","@timestamp":"2018-12-18T10:07:05Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
{"type":"log","@timestamp":"2018-12-18T10:07:08Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
{"type":"log","@timestamp":"2018-12-18T10:07:10Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
{"type":"log","@timestamp":"2018-12-18T10:07:13Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
{"type":"log","@timestamp":"2018-12-18T10:07:15Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
{"type":"log","@timestamp":"2018-12-18T10:07:18Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
{"type":"log","@timestamp":"2018-12-18T10:07:20Z","tags":["info","elasticsearch"],"pid":20337,"names":["sentinl-watcher","sentinl-user"],"message":"Adding mappings to kibana index for SavedObject types \"sentinl-watcher\", \"sentinl-user\""}
```

#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |      6.2.4   |
| Elassandra | 6.2.3.5        |
| Server OS    |    centos 7.5     |
| Browser      |         |

**Comment by sawdyj** [comment]
This is an attempt on a windows machine. Tried removing all data from elassandra and then it installs with the Unknown type error. I can view the kibana menus fine but no data. However, as soon as I attempt to make a kibana index of my data that I stream in it crashes with the following. Not sure if this error is much better than the last. Sorry for posting so many logs. Thanks.

Attempting to transfer from file:///C:\Users\sawdyj\Downloads\sentinl-v6.2.3.zip
Transferring 242956909 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete

C:\kibana-6.2.3-windows-x86_64\bin>kibana.bat
  log   [14:48:01.265] [info][status][plugin:kibana@6.2.3] Status changed from uninitialized to gree
n - Ready
  log   [14:48:01.345] [info][status][plugin:elasticsearch@6.2.3] Status changed from uninitialized
to yellow - Waiting for Elasticsearch
  log   [14:48:01.351] [info][status][plugin:sentinl@6.0.0] Status changed from uninitialized to gre
en - Ready
  log   [14:48:01.359] [info][status][plugin:console@6.2.3] Status changed from uninitialized to gre
en - Ready
  log   [14:48:01.366] [info][status][plugin:metrics@6.2.3] Status changed from uninitialized to gre
en - Ready
  log   [14:48:02.191] [info][status][plugin:timelion@6.2.3] Status changed from uninitialized to gr
een - Ready
  log   [14:48:02.228] [info][listening] Server running at http://localhost:5601
  log   [14:48:02.366] [info][status][plugin:elasticsearch@6.2.3] Status changed from yellow to gree
n - Ready
  log   [14:48:02.371] [info][Sentinl][init] initializing ...
  log   [14:48:02.436] [info][Sentinl][init] Chrome bin found at: C:\kibana-6.2.3-windows-x86_64\plu
gins\sentinl\node_modules\puppeteer\.local-chromium\linux-564778\chrome-linux\chrome
  log   [14:48:02.493] [info][Sentinl][init_indices] checking .kibana index ...
  log   [14:48:02.871] [info][Sentinl][init_indices] creating .kibana index ...
  log   [14:48:03.652] [error][Sentinl][init] start: Error: init indices: Error: create index: [i_o_
exception] Unknown type _kibana.doc_sentinl-watcher_input :: {"path":"/.kibana","query":{},"body":"{
\"mappings\":{\"doc\":{\"properties\":{\"sentinl-watcher\":{\"properties\":{\"wizard\":{\"type\":\"o
bject\",\"enabled\":false},\"input\":{\"type\":\"object\",\"enabled\":false},\"actions\":{\"type\":\
"object\",\"enabled\":false},\"transform\":{\"type\":\"object\",\"enabled\":false},\"condition\":{\"
type\":\"object\",\"enabled\":false},\"trigger\":{\"type\":\"object\",\"enabled\":false},\"report\":
{\"type\":\"boolean\"},\"disable\":{\"type\":\"boolean\"},\"save_payload\":{\"type\":\"boolean\"},\"
impersonate\":{\"type\":\"boolean\"},\"spy\":{\"type\":\"boolean\"},\"title\":{\"type\":\"text\"},\"
username\":{\"type\":\"text\"},\"sentinl\":{\"type\":\"object\",\"enabled\":false},\"dashboard_link\
":{\"type\":\"text\"},\"custom\":{\"type\":\"object\",\"enabled\":false}}},\"sentinl-user\":{\"prope
rties\":{\"username\":{\"type\":\"text\"},\"sha\":{\"type\":\"text\"},\"password\":{\"type\":\"text\
"}}}}}}}","statusCode":500,"response":"{\"error\":{\"root_cause\":[{\"type\":\"i_o_exception\",\"rea
son\":\"Unknown type _kibana.doc_sentinl-watcher_input\"}],\"type\":\"i_o_exception\",\"reason\":\"U
nknown type _kibana.doc_sentinl-watcher_input\",\"caused_by\":{\"type\":\"invalid_request_exception\
",\"reason\":\"Unknown type _kibana.doc_sentinl-watcher_input\"}},\"status\":500}"}
  log   [14:48:04.071] [info][Sentinl][init] PhantomJS bin found at: C:\kibana-6.2.3-windows-x86_64\
plugins\sentinl\phantomjs\phantomjs-2.1.1-windows\bin\phantomjs.exe
 error  [14:58:32.943]  [i_o_exception] Unknown type _kibana.doc_sentinl-watcher_input :: {"path":"/
.kibana/doc/index-pattern%3Ab82b0340-0467-11e9-b401-e956cf8b6277","query":{"refresh":"wait_for"},"bo
dy":"{\"type\":\"index-pattern\",\"updated_at\":\"2018-12-20T14:58:32.948Z\",\"index-pattern\":{\"ti
tle\":\"observable*\",\"timeFieldName\":\"timestamp\"}}","statusCode":500,"response":"{\"error\":{\"
root_cause\":[{\"type\":\"i_o_exception\",\"reason\":\"Unknown type _kibana.doc_sentinl-watcher_inpu
t\"}],\"type\":\"i_o_exception\",\"reason\":\"Unknown type _kibana.doc_sentinl-watcher_input\",\"cau
sed_by\":{\"type\":\"invalid_request_exception\",\"reason\":\"Unknown type _kibana.doc_sentinl-watch
er_input\"}},\"status\":500}"}
    at respond (C:\kibana-6.2.3-windows-x86_64\node_modules\elasticsearch\src\lib\transport.js:295:1
5)
    at checkRespForFailure (C:\kibana-6.2.3-windows-x86_64\node_modules\elasticsearch\src\lib\transp
ort.js:254:7)
    at HttpConnector.<anonymous> (C:\kibana-6.2.3-windows-x86_64\node_modules\elasticsearch\src\lib\
connectors\http.js:159:7)
    at IncomingMessage.bound (C:\kibana-6.2.3-windows-x86_64\node_modules\elasticsearch\node_modules
\lodash\dist\lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by lmangani** [comment]
Hi - we don't directly support Elassandra so make sure you use the exact Kibana and ES API versions. Closing this as a non-issue but feel free to continue commenting for advice if needed.
