### ISSUE TITLE
Very slow. How much memory does it take to install this application?

### ISSUE THREAD

**Issue by ithjz** [sirensolutions/sentinl#653]
sh kibana &
[2] 9095
[root@localhost bin]#   log   [13:00:33.170] [info][optimize] Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, space_selector, login, logout, dashboardViewer, apm, canvas, infra, sentinl and kibana. This may take a few minutes

**Comment by lmangani** [comment]
Please understand the optimization process is progressive for ALL plugins and not related to sentinl.
