### ISSUE TITLE
 getaddrinfo ENOTFOUND github.com github.com:443"

### ISSUE THREAD

**Issue by ithjz** [sirensolutions/sentinl#654]
sh kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.5.3.zip
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.5.3.zip
Error: Client request error: getaddrinfo ENOTFOUND github.com github.com:443
Plugin installation was unsuccessful due to error "Client request error: getaddrinfo ENOTFOUND github.com github.com:443"

**Comment by lmangani** [comment]
Please follow the issue submission guideline and fill all required fields.
