### ISSUE TITLE
Do you have sentinl to kibana package, provide one,

### ISSUE THREAD

**Issue by ithjz** [sirensolutions/sentinl#655]
Do you have sentinl to kibana package, provide one, Baidu Yunpan can be
I failed several times to install the plug-in and it was stuck.
SH kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.5.3.zip
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.5.3.zip
Transferring 134205068 bytes...
Transfer complete
Retrieving metadata from plugin Archive
Extracting plugin Archive
Extraction complete
Optimizing and caching browser bundles...

**Comment by lmangani** [comment]
Please follow the issue submission guideline and fill all required fields.
