### ISSUE TITLE
Am I configuring mail correctly?

### ISSUE THREAD

**Issue by ithjz** [sirensolutions/sentinl#656]
Am I configuring mail correctly?

![_20181223164145](https://user-images.githubusercontent.com/15103507/50382065-bff5cf80-06d1-11e9-84d5-f00ab6ddcadf.png)

**Comment by J0rg3M3nd3z** [comment]
Your YAML seems not aligned correctly, refer to my comments at the end of #512 for an example of what helped me. Hope that helps.

**Comment by ithjz** [comment]
Look at the log, copy other people's mail configuration
