### ISSUE TITLE
Always got "Optimizing and caching bundles out of memory only while installing sentinl plugin

### ISSUE THREAD

**Issue by Theoooooo** [sirensolutions/sentinl#659]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       | 6.5.3 |
| Elasticsearc | 6.5.3 |

#### Original Install Method

- [x] Release pkg link (into the release section 6.5.3)
- [ ] Gulp
- [ ] Source
- Other: 

#### Bug Description
Installing the plugin cause an infinite "Optimizing and caching bundles" no matters of how many RAM i allow to the service (test with 4g, 8g and 12g of RAM)
jvm options was also changes in elasticsearch.
It occur everytime i try to install the plugin after changing the amount of RAM the 3 times.

#### Steps to Reproduce
1. install the plugin in offline mode 
2. wait for the installation until it finished

#### Expected Behavior

The installation is done and now the service is doing the optimization for an infinite amount of time until it ran out of memory and crash.

The issue remain the same even if i allocate more ram to the server and the service.

#### Screenshots (if relevant)
(i can't replicate the issue right now i can't have access to the error for now)

**Comment by Grashee** [comment]
Hi @Theoooooo 

i had the same issue. How did you change the RAM which is allocated to kibana? (maybe [my issue](https://github.com/sirensolutions/sentinl/issues/635) helps you)

I hope this helps you, have a nice day!

Best regards,
Robert

**Comment by Theoooooo** [comment]
@Grashee thanks for the reply.
When i mean the service, i mean Elasticsearch. It wasn't clear at all because kibana use an index in elasticsearch and i though it was impacting the performance.

I will try the option you gave me above and i will post an update

**Comment by Grashee** [comment]
Hey @Theoooooo ,

If you want to install a plugin for kibana (for example sentinl), you must increase the RAM of the kibana service if the service needs more. Elasticsearch has nothing to do with the installation of a plugin in kibana.

The above command will set the RAM for kibana to 4GB. 

The process "Optimizing and caching browser bundles" should come in the kibana console/log, cause elasticsearch don´t do something like this (as far as I know).

Best regards,
Robert

**Comment by Theoooooo** [comment]
@Grashee 
I though the "NODE_OPTIONS="--max-old-space-size=4096"" was only for the docker version ^^
I will wait until there is a version for the 6.5.4 to try this out.

thanks for the explanation

**Comment by sergibondarenko** [comment]
@Theoooooo you can get the latest version 6.5.4 zip here https://github.com/sirensolutions/sentinl/releases/tag/tag-6.5.0-0
