### ISSUE TITLE
Index defines itself by time, different points per day, index_today's time  Select an Index input box, can you write a time function?

### ISSUE THREAD

**Issue by ithjz** [sirensolutions/sentinl#662]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |    6.5.3     |
| Elasticsearc |    6.5.3     |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1.
1.
1.

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Errors in Browser Console (if relevant)
```
```

#### Any additional information

Index defines itself by time, different points per day, index_today's time

Select an Index input box, can you write a time function?

**Comment by lmangani** [comment]
I'm not sure I understand the question or the final purpose here without context or any example.

I'll assume you're referring to the Alert Indices - those are indeed created as [daily indices](https://github.com/sirensolutions/sentinl/blob/master/server/lib/helpers.js#L68) by Sentinl and cannot be modified in order for the Sentinl Kibana App to use their data consistently. If you prefer to store Alerts your own way, you can disable alert indexing and write using the output functions. I hope this helps.
