### ISSUE TITLE
 Displaying logs information in the body of email alert 

### ISSUE THREAD

**Issue by Tvlasev** [sirensolutions/sentinl#670]
| Type         | Version |
|--------------|---------|
| Kibana       |     6.5.4    |
| Elasticsearc |   6.5.4      |
| Server OS    |     Windows 10 Pro    |
| Browser      |    Chorme     |

I collect logs with filebeat and logstash. I've created an alarm which is triggered when a log is collected and send email. But in this mail there is almost no info. I want to display the message and source of the log but I have access Only to the number of the results and watcher's name. How I can display the whole logs information (document properties like message, source, host.id, tags, e.t.c) in the body of email alert? 

As far I know this info is stored in the payload.hits.hits array. But my payload.hits.hits array is empty. Why is that? Anyone have an idea?  

This is my alarm:

```
{
  "@timestamp": "2019-01-28T13:16:29.664Z",
  "error": false,
  "report": false,
  "watcher": "demo-watcher",
  "action": "email html alarm",
  "level": "high",
  "message": "Series Alarm : 2",
  "payload": {
    "took": 3,
    "timed_out": false,
    "_shards": {
      "total": 45,
      "successful": 45,
      "skipped": 0,
      "failed": 0
    },
    "hits": {
      "total": 2,
      "max_score": 0,
      "hits": []
    },
    "aggregations": {
      "dateAgg": {
        "buckets": [
          {
            "key_as_string": "2019-01-28T13:30:00.000+02:00",
            "key": 1548675000000,
            "doc_count": 2
          }
        ]
      }
    }
  },
  "type": "sentinl-alarm",
  "_index": "watcher_alarms-2019.01.28",
  "id": "1LqalGgBvPzmw9f_ph9u"
}
```

**Comment by lmangani** [comment]
You should use the `{ mustache }` syntax to print out any part of the payload into the notification body of your `action`. The exact way depends much on the specific case but that's the direction to achieve your goal. If you experiment with it and have doubts feel free to open a new issue with the full example including the notification elements. Hope this helps.
