### ISSUE TITLE
Browserslist: caniuse-lite is outdated. Please run next command 'npm update caniuse-lite browserslist'

### ISSUE THREAD

**Issue by YuMingYuMi** [sirensolutions/sentinl#672]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |  6.5.4       |
| Elasticsearc |  6.5.4       |
| Server OS    |  Windows Server 2012 R2    |

![image](https://user-images.githubusercontent.com/28705172/52043449-b1c18b80-257a-11e9-94f3-380cae72a25e.png)

please tell me what detail i should provide if you need.

**Comment by YuMingYuMi** [comment]
![image](https://user-images.githubusercontent.com/28705172/52100239-b7b67b80-2611-11e9-967e-48194e558d8f.png)

When I visit my kibana, it show that.

![image](https://user-images.githubusercontent.com/28705172/52100272-d157c300-2611-11e9-8d5d-95cb5f045dba.png)

and then I restart it , the problem issue...

**Comment by YuMingYuMi** [comment]
Browserslist: caniuse-lite is outdated. Please run next command 'npm update caniuse-lite browserslist'

**Comment by sergibondarenko** [comment]
This is a Kibana bug which had been resolved 7 days ago. Not sure if they ported it back to v6.5.4
https://github.com/elastic/kibana/issues/29464

**Comment by ichintu** [comment]
I posted this here: https://github.com/elastic/kibana/pull/29358 But shareing here as i wasnt sure where to put this.
I am having same issue on latest .deb package for 6.5.3 after adding the following
############ Disable xpack features #########
xpack.infra.enabled: false
xpack.logstash.enabled: false
xpack.canvas.enabled: false
#############################################

**Comment by MohdRashid01** [comment]
Below is the container logs showing of kibana
mohd@master-node:~$ docker container logs 2bc214e8b809
{"type":"log","@timestamp":"2021-05-19T12:03:31Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for elastalert-kibana-plugin, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
{"type":"log","@timestamp":"2021-05-19T12:04:11Z","tags":["info","optimize"],"pid":1,"message":"Optimization of bundles for elastalert-kibana-plugin, kibana, stateSessionStorageRedirect, status_page and timelion complete in 40.61 seconds"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:kibana@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:elasticsearch@undefined","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:elastalert-kibana-plugin@1.0.4","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:apm_oss@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:console@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:interpreter@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:metrics@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:tile_map@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:timelion@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["status","plugin:elasticsearch@undefined","info"],"pid":1,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["info","migrations"],"pid":1,"message":"Creating index .kibana_1."}
{"type":"log","@timestamp":"2021-05-19T12:04:12Z","tags":["fatal","root"],"pid":1,"message":"{ Method Not Allowed :: {\"path\":\"/.kibana_1\",\"query\":{},\"body\":\"{\\\"mappings\\\":{\\\"dynamic\\\":\\\"strict\\\",\\\"properties\\\":{\\\"config\\\":{\\\"dynamic\\\":\\\"true\\\",\\\"properties\\\":{\\\"buildNum\\\":{\\\"type\\\":\\\"keyword\\\"}}},\\\"migrationVersion\\\":{\\\"dynamic\\\":\\\"true\\\",\\\"type\\\":\\\"object\\\"},\\\"type\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"namespace\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"updated_at\\\":{\\\"type\\\":\\\"date\\\"},\\\"references\\\":{\\\"type\\\":\\\"nested\\\",\\\"properties\\\":{\\\"name\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"type\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"id\\\":{\\\"type\\\":\\\"keyword\\\"}}},\\\"index-pattern\\\":{\\\"properties\\\":{\\\"fieldFormatMap\\\":{\\\"type\\\":\\\"text\\\"},\\\"fields\\\":{\\\"type\\\":\\\"text\\\"},\\\"intervalName\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"notExpandable\\\":{\\\"type\\\":\\\"boolean\\\"},\\\"sourceFilters\\\":{\\\"type\\\":\\\"text\\\"},\\\"timeFieldName\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"type\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"typeMeta\\\":{\\\"type\\\":\\\"keyword\\\"}}},\\\"visualization\\\":{\\\"properties\\\":{\\\"description\\\":{\\\"type\\\":\\\"text\\\"},\\\"kibanaSavedObjectMeta\\\":{\\\"properties\\\":{\\\"searchSourceJSON\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"savedSearchRefName\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"uiStateJSON\\\":{\\\"type\\\":\\\"text\\\"},\\\"version\\\":{\\\"type\\\":\\\"integer\\\"},\\\"visState\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"search\\\":{\\\"properties\\\":{\\\"columns\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"description\\\":{\\\"type\\\":\\\"text\\\"},\\\"hits\\\":{\\\"type\\\":\\\"integer\\\"},\\\"kibanaSavedObjectMeta\\\":{\\\"properties\\\":{\\\"searchSourceJSON\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"sort\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"version\\\":{\\\"type\\\":\\\"integer\\\"}}},\\\"dashboard\\\":{\\\"properties\\\":{\\\"description\\\":{\\\"type\\\":\\\"text\\\"},\\\"hits\\\":{\\\"type\\\":\\\"integer\\\"},\\\"kibanaSavedObjectMeta\\\":{\\\"properties\\\":{\\\"searchSourceJSON\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"optionsJSON\\\":{\\\"type\\\":\\\"text\\\"},\\\"panelsJSON\\\":{\\\"type\\\":\\\"text\\\"},\\\"refreshInterval\\\":{\\\"properties\\\":{\\\"display\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"pause\\\":{\\\"type\\\":\\\"boolean\\\"},\\\"section\\\":{\\\"type\\\":\\\"integer\\\"},\\\"value\\\":{\\\"type\\\":\\\"integer\\\"}}},\\\"timeFrom\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"timeRestore\\\":{\\\"type\\\":\\\"boolean\\\"},\\\"timeTo\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"uiStateJSON\\\":{\\\"type\\\":\\\"text\\\"},\\\"version\\\":{\\\"type\\\":\\\"integer\\\"}}},\\\"url\\\":{\\\"properties\\\":{\\\"accessCount\\\":{\\\"type\\\":\\\"long\\\"},\\\"accessDate\\\":{\\\"type\\\":\\\"date\\\"},\\\"createDate\\\":{\\\"type\\\":\\\"date\\\"},\\\"url\\\":{\\\"type\\\":\\\"text\\\",\\\"fields\\\":{\\\"keyword\\\":{\\\"type\\\":\\\"keyword\\\",\\\"ignore_above\\\":2048}}}}},\\\"server\\\":{\\\"properties\\\":{\\\"uuid\\\":{\\\"type\\\":\\\"keyword\\\"}}},\\\"kql-telemetry\\\":{\\\"properties\\\":{\\\"optInCount\\\":{\\\"type\\\":\\\"long\\\"},\\\"optOutCount\\\":{\\\"type\\\":\\\"long\\\"}}},\\\"timelion-sheet\\\":{\\\"properties\\\":{\\\"description\\\":{\\\"type\\\":\\\"text\\\"},\\\"hits\\\":{\\\"type\\\":\\\"integer\\\"},\\\"kibanaSavedObjectMeta\\\":{\\\"properties\\\":{\\\"searchSourceJSON\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"timelion_chart_height\\\":{\\\"type\\\":\\\"integer\\\"},\\\"timelion_columns\\\":{\\\"type\\\":\\\"integer\\\"},\\\"timelion_interval\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"timelion_other_interval\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"timelion_rows\\\":{\\\"type\\\":\\\"integer\\\"},\\\"timelion_sheet\\\":{\\\"type\\\":\\\"text\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"version\\\":{\\\"type\\\":\\\"integer\\\"}}}},\\\"_meta\\\":{\\\"migrationMappingPropertyHashes\\\":{\\\"config\\\":\\\"87aca8fdb053154f11383fce3dbf3edf\\\",\\\"migrationVersion\\\":\\\"4a1746014a75ade3a714e1db5763276f\\\",\\\"type\\\":\\\"2f4316de49999235636386fe51dc06c1\\\",\\\"namespace\\\":\\\"2f4316de49999235636386fe51dc06c1\\\",\\\"updated_at\\\":\\\"00da57df13e94e9d98437d13ace4bfe0\\\",\\\"references\\\":\\\"7997cf5a56cc02bdc9c93361bde732b0\\\",\\\"index-pattern\\\":\\\"66eccb05066c5a89924f48a9e9736499\\\",\\\"visualization\\\":\\\"52d7a13ad68a150c4525b292d23e12cc\\\",\\\"search\\\":\\\"181661168bbadd1eff5902361e2a0d5c\\\",\\\"dashboard\\\":\\\"eb3789e1af878e73f85304333240f65f\\\",\\\"url\\\":\\\"c7f66a0df8b1b52f17c28c4adb111105\\\",\\\"server\\\":\\\"ec97f1c5da1a19609a60874e5af1100c\\\",\\\"kql-telemetry\\\":\\\"d12a98a6f19a2d273696597547e064ee\\\",\\\"timelion-sheet\\\":\\\"9a2a2748877c7a7b582fef201ab1d4cf\\\"}}},\\\"settings\\\":{\\\"number_of_shards\\\":1,\\\"auto_expand_replicas\\\":\\\"0-1\\\"}}\",\"statusCode\":405,\"response\":\"<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx/1.19.10</center>\\r\\n</body>\\r\\n</html>\\r\\n\"}\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:308:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:267:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4935:19)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  status: 405,\n  displayName: 'MethodNotAllowed',\n  message: 'Method Not Allowed',\n  path: '/.kibana_1',\n  query: {},\n  body:\n   '<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx/1.19.10</center>\\r\\n</body>\\r\\n</html>\\r\\n',\n  statusCode: 405,\n  response:\n   '<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx/1.19.10</center>\\r\\n</body>\\r\\n</html>\\r\\n',\n  toString: [Function],\n  toJSON: [Function] }"}

 FATAL  Method Not Allowed :: {"path":"/.kibana_1","query":{},"body":"{\"mappings\":{\"dynamic\":\"strict\",\"properties\":{\"config\":{\"dynamic\":\"true\",\"properties\":{\"buildNum\":{\"type\":\"keyword\"}}},\"migrationVersion\":{\"dynamic\":\"true\",\"type\":\"object\"},\"type\":{\"type\":\"keyword\"},\"namespace\":{\"type\":\"keyword\"},\"updated_at\":{\"type\":\"date\"},\"references\":{\"type\":\"nested\",\"properties\":{\"name\":{\"type\":\"keyword\"},\"type\":{\"type\":\"keyword\"},\"id\":{\"type\":\"keyword\"}}},\"index-pattern\":{\"properties\":{\"fieldFormatMap\":{\"type\":\"text\"},\"fields\":{\"type\":\"text\"},\"intervalName\":{\"type\":\"keyword\"},\"notExpandable\":{\"type\":\"boolean\"},\"sourceFilters\":{\"type\":\"text\"},\"timeFieldName\":{\"type\":\"keyword\"},\"title\":{\"type\":\"text\"},\"type\":{\"type\":\"keyword\"},\"typeMeta\":{\"type\":\"keyword\"}}},\"visualization\":{\"properties\":{\"description\":{\"type\":\"text\"},\"kibanaSavedObjectMeta\":{\"properties\":{\"searchSourceJSON\":{\"type\":\"text\"}}},\"savedSearchRefName\":{\"type\":\"keyword\"},\"title\":{\"type\":\"text\"},\"uiStateJSON\":{\"type\":\"text\"},\"version\":{\"type\":\"integer\"},\"visState\":{\"type\":\"text\"}}},\"search\":{\"properties\":{\"columns\":{\"type\":\"keyword\"},\"description\":{\"type\":\"text\"},\"hits\":{\"type\":\"integer\"},\"kibanaSavedObjectMeta\":{\"properties\":{\"searchSourceJSON\":{\"type\":\"text\"}}},\"sort\":{\"type\":\"keyword\"},\"title\":{\"type\":\"text\"},\"version\":{\"type\":\"integer\"}}},\"dashboard\":{\"properties\":{\"description\":{\"type\":\"text\"},\"hits\":{\"type\":\"integer\"},\"kibanaSavedObjectMeta\":{\"properties\":{\"searchSourceJSON\":{\"type\":\"text\"}}},\"optionsJSON\":{\"type\":\"text\"},\"panelsJSON\":{\"type\":\"text\"},\"refreshInterval\":{\"properties\":{\"display\":{\"type\":\"keyword\"},\"pause\":{\"type\":\"boolean\"},\"section\":{\"type\":\"integer\"},\"value\":{\"type\":\"integer\"}}},\"timeFrom\":{\"type\":\"keyword\"},\"timeRestore\":{\"type\":\"boolean\"},\"timeTo\":{\"type\":\"keyword\"},\"title\":{\"type\":\"text\"},\"uiStateJSON\":{\"type\":\"text\"},\"version\":{\"type\":\"integer\"}}},\"url\":{\"properties\":{\"accessCount\":{\"type\":\"long\"},\"accessDate\":{\"type\":\"date\"},\"createDate\":{\"type\":\"date\"},\"url\":{\"type\":\"text\",\"fields\":{\"keyword\":{\"type\":\"keyword\",\"ignore_above\":2048}}}}},\"server\":{\"properties\":{\"uuid\":{\"type\":\"keyword\"}}},\"kql-telemetry\":{\"properties\":{\"optInCount\":{\"type\":\"long\"},\"optOutCount\":{\"type\":\"long\"}}},\"timelion-sheet\":{\"properties\":{\"description\":{\"type\":\"text\"},\"hits\":{\"type\":\"integer\"},\"kibanaSavedObjectMeta\":{\"properties\":{\"searchSourceJSON\":{\"type\":\"text\"}}},\"timelion_chart_height\":{\"type\":\"integer\"},\"timelion_columns\":{\"type\":\"integer\"},\"timelion_interval\":{\"type\":\"keyword\"},\"timelion_other_interval\":{\"type\":\"keyword\"},\"timelion_rows\":{\"type\":\"integer\"},\"timelion_sheet\":{\"type\":\"text\"},\"title\":{\"type\":\"text\"},\"version\":{\"type\":\"integer\"}}}},\"_meta\":{\"migrationMappingPropertyHashes\":{\"config\":\"87aca8fdb053154f11383fce3dbf3edf\",\"migrationVersion\":\"4a1746014a75ade3a714e1db5763276f\",\"type\":\"2f4316de49999235636386fe51dc06c1\",\"namespace\":\"2f4316de49999235636386fe51dc06c1\",\"updated_at\":\"00da57df13e94e9d98437d13ace4bfe0\",\"references\":\"7997cf5a56cc02bdc9c93361bde732b0\",\"index-pattern\":\"66eccb05066c5a89924f48a9e9736499\",\"visualization\":\"52d7a13ad68a150c4525b292d23e12cc\",\"search\":\"181661168bbadd1eff5902361e2a0d5c\",\"dashboard\":\"eb3789e1af878e73f85304333240f65f\",\"url\":\"c7f66a0df8b1b52f17c28c4adb111105\",\"server\":\"ec97f1c5da1a19609a60874e5af1100c\",\"kql-telemetry\":\"d12a98a6f19a2d273696597547e064ee\",\"timelion-sheet\":\"9a2a2748877c7a7b582fef201ab1d4cf\"}}},\"settings\":{\"number_of_shards\":1,\"auto_expand_replicas\":\"0-1\"}}","statusCode":405,"response":"<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx/1.19.10</center>\r\n</body>\r\n</html>\r\n"}

Below is the kibana error showing from tail
mohd@master-node:~$ tail -f /var/log/syslog | grep kibana
May 19 17:34:27 master-node dockerd[21119]: time="2021-05-19T17:34:27.635400734+05:30" level=error msg="pulling image failed" error="pull access denied for fxlabs/kibana7, repository does not exist or may require 'docker login': denied: requested access to the resource is denied" module=node/agent/taskmanager node.id=kwpyr5ixo3xx6psp782zxtgre service.id=l72vyvlugvi5oenim9kv5f3tq task.id=z79oe6r2aau6rmry5j4qqra13
^Z
