### ISSUE TITLE
Kibana 6.6.0 Support

### ISSUE THREAD

**Issue by rhysxevans** [sirensolutions/sentinl#674]
Hi

Any chance of getting a Kibana 6.6.0 compatible release ?

Thanks

**Comment by sergibondarenko** [comment]
Here it is https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.6.0.zip Please report if something is wrong.

**Comment by rhysxevans** [comment]
thanks
