### ISSUE TITLE
6.6.0 release exception: TypeError: reply is not a function 

### ISSUE THREAD

**Issue by arreyder** [sirensolutions/sentinl#677]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       | 6.6.0 |
| Elasticsearch | 6.6.0 |
| Server OS    | Official ES Kibana Container CentOS Linux release 7.6.1810 (Core) |
| Browser      |  Google Chrome 72.0.3626.81  |

#### Original Install Method

- [x] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1. Install the plugin
1. Start Kibana
1. Click on SentiNL link in left sidebar.

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
No watches installed.
```

#### Screenshots (if relevant)
![image](https://user-images.githubusercontent.com/682990/52391528-33c22080-2a63-11e9-913f-4a0b518ff9ec.png)

#### Errors in Browser Console (if relevant)
```
```

#### Kibana logs and/or server output (attached if relevant)
```
Feb 07 04:43:24 ip-10-0-184-8 kibana.service[18386]: Debug: internal, implementation, error
Feb 07 04:43:24 ip-10-0-184-8 kibana.service[18386]:     TypeError: reply is not a function
Feb 07 04:43:24 ip-10-0-184-8 kibana.service[18386]:     at handler (/usr/share/kibana/plugins/sentinl/server/routes/routes.js:25:14)
Feb 07 04:43:24 ip-10-0-184-8 kibana.service[18386]:     at module.exports.internals.Manager.execute (/usr/share/kibana/node_modules/hapi/lib/toolkit.js:35:106)
Feb 07 04:43:24 ip-10-0-184-8 kibana.service[18386]:     at Object.internals.handler (/usr/share/kibana/node_modules/hapi/lib/handler.js:50:48)
Feb 07 04:43:24 ip-10-0-184-8 kibana.service[18386]:     at exports.execute (/usr/share/kibana/node_modules/hapi/lib/handler.js:35:36)
Feb 07 04:43:24 ip-10-0-184-8 kibana.service[18386]:     at Request._lifecycle (/usr/share/kibana/node_modules/hapi/lib/request.js:263:62)
Feb 07 04:43:24 ip-10-0-184-8 kibana.service[18386]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Feb 07 04:43:24 ip-10-0-184-8 kibana.service[18386]: {"type":"error","@timestamp":"2019-02-07T04:43:24Z","tags":[],"pid":1,"level":"error","error":{"message":"reply is not a function","name":"TypeError","stack":"TypeError: reply is not a function\n    at handler (/usr/share/kibana/plugins/sentinl/server/routes/routes.js:25:14)\n    at module.exports.internals.Manager.execute (/usr/share/kibana/node_modules/hapi/lib/toolkit.js:35:106)\n    at Object.internals.handler (/usr/share/kibana/node_modules/hapi/lib/handler.js:50:48)\n    at exports.execute (/usr/share/kibana/node_modules/hapi/lib/handler.js:35:36)\n    at Request._lifecycle (/usr/share/kibana/node_modules/hapi/lib/request.js:263:62)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/sentinl/time","path":"/api/sentinl/time","href":"/api/sentinl/time"},"message":"reply is not a function"}
````

**Comment by sergibondarenko** [comment]
It is because Kibana upgraded hapi webserver to from v14 to v17. And the new version has different API. https://stackoverflow.com/questions/47486666/typeerror-reply-is-not-a-function 
I put high priority on this issue and let you know when we fix the code.

**Comment by Detzler** [comment]
confirm bug on kibana 6.6.0 and sentinl 6.6.0

**Comment by laizhouzhang** [comment]
When can I use 6.6.0?

**Comment by ggens** [comment]
> confirm bug on kibana 6.6.0 and sentinl 6.6.0

me too

**Comment by flover97** [comment]
same problem

**Comment by sergibondarenko** [comment]
@flover97 @ggens @laizhouzhang @Detzler @arreyder 
Fixed, get the package here https://github.com/sirensolutions/sentinl/releases/tag/tag-6.6.0-0
Please report if something is wrong.

**Comment by ggens** [comment]
> @flover97 @ggens @laizhouzhang @Detzler @arreyder
> Fixed, get the package here https://github.com/sirensolutions/sentinl/releases/tag/tag-6.6.0-0
> Please report if something is wrong.

it's work for me, thk

**Comment by arreyder** [comment]
Thanks!
