### ISSUE TITLE
6.6.0 - KIbana doesn't start up after 6.6.0 version installed.

### ISSUE THREAD

**Issue by pbuxtonccuk** [sirensolutions/sentinl#683]
Hi,

I installed this using the kibana-plugin install method, on Ubuntu, using the right package.

It appears that the installer results in it  not setting permission correctly in some way, as Kibana service goes in a loop when  restarted, relating to permissions not being set.

Is there a work around for this??   The previous 6.2.4 issue, which seems related, that fix doesn't work for me...

Really disappointing, because in a windows install I didn't have this issue....

**Comment by sergibondarenko** [comment]
Fixed, get the package here https://github.com/sirensolutions/sentinl/releases/tag/tag-6.6.0-0
Please report if something is wrong.

**Comment by pbuxtonccuk** [comment]
Thanks, can confim it's resolved my issue!! Thanks for the quick response!
