### ISSUE TITLE
how condition script date format work?

### ISSUE THREAD

**Issue by vdingtian** [sirensolutions/sentinl#687]
like this,it's not work
```
"condition": {
  "script": {
    "script": "var myDate = new Date(); var hour = myDate.getHours();
                   if (hour ==17 && payload.hits.total < 10000){return true;} "
  }
}
```

How to code correctly ??

**Comment by sergibondarenko** [comment]
You can do shorter
```
"script": "new Date().getHours() === 17 && payload.hits.total < 10000"
```
Script is normal JavaScript, read more about how to work with date and time here https://javascript.info/date

**Comment by vdingtian** [comment]
![image](https://user-images.githubusercontent.com/5812577/53218802-8709b500-3698-11e9-969c-b76323b7204d.png)

script too long，ui  Unfriendly，

**Comment by lmangani** [comment]
Perhaps you should try a paid solution and see if its more friendly?
