### ISSUE TITLE
No watchers found issue

### ISSUE THREAD

**Issue by OsmanAktemur** [sirensolutions/sentinl#688]
Hi,

I installed Sentinl 5.6.3 version and create watcher with wizard. But watchers don't trigger automatically. And i see `[debug][Sentinl][scheduler] no watchers found` on the kibana logs.
Kibana..yml:
![image](https://user-images.githubusercontent.com/7611781/53228761-35126080-3693-11e9-8317-337a2d9f965e.png)
Logs:
![image](https://user-images.githubusercontent.com/7611781/53228801-60954b00-3693-11e9-85cc-91638d3bceeb.png)

**Comment by lmangani** [comment]
You probably have some form of authentication preventing the watchers from being saved.
Check for errors in Elasticsearch as you attempt to save/schedule for hints.

**Comment by OsmanAktemur** [comment]
@lmangani 
I can succesfully create watcher :
![image](https://user-images.githubusercontent.com/7611781/53229166-95ee6880-3694-11e9-878c-df535df80fdf.png)

![image](https://user-images.githubusercontent.com/7611781/53229196-a7377500-3694-11e9-8e62-6114c20fa69d.png)

**Comment by OsmanAktemur** [comment]
@lmangani 
I can succesfully create watcher :
![image](https://user-images.githubusercontent.com/7611781/53229166-95ee6880-3694-11e9-878c-df535df80fdf.png)

![image](https://user-images.githubusercontent.com/7611781/53229196-a7377500-3694-11e9-8e62-6114c20fa69d.png)

**Comment by OsmanAktemur** [comment]
> You probably have some form of authentication preventing the watchers from being saved.
> Check for errors in Elasticsearch as you attempt to save/schedule for hints.

@lmangani 
I can succesfully create watcher :
![image](https://user-images.githubusercontent.com/7611781/53229166-95ee6880-3694-11e9-878c-df535df80fdf.png)

![image](https://user-images.githubusercontent.com/7611781/53229196-a7377500-3694-11e9-8e62-6114c20fa69d.png)

**Comment by varun0002** [comment]
@lmangani Getting exact same issue with 5.6.x. Any resolution on this.
