### ISSUE TITLE
Some Sentinl configuration questions

### ISSUE THREAD

**Issue by jnilssn** [sirensolutions/sentinl#689]
Hi!

We are trying to use Sentinl to send daily/weekly/monthly reports (screenshots) of Kibana dashboards in emails, but have a few questions:

1. Is it possible to include several report attachments in the same email sent from a watcher?

2. We would like to send the email every time the watcher triggers, so no input or condition is really needed. Is it possible to create a watcher without specifying these parts somehow, or to set them to not send any query to elastic to get the input and that the condition always is true?

3. Is there any support for time zones when configuring the time at which watchers should trigger? 

Any guidelines or suggestions what to do would be very appreciated!

#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |  6.5.3 |
| Elasticsearc | 6.5.3 |
| Server OS    | Ubuntu 16.04.6 |
| Browser      | Google Chrome Version 72.0.3626.96 |

**Comment by lmangani** [comment]
1. Not really. You need multiple watchers possibly.
2. Sure. Just return true or use an always true condition.
3. Everything is UTC internally. The browser TZ should do the rest.

Sorry for the delay responding. If you need more details, just reopen.

Thanks!
