### ISSUE TITLE
Plugin sentinl [6.6.0] is incompatible with Kibana [6.6.1]

### ISSUE THREAD

**Issue by arekstuka** [sirensolutions/sentinl#690]
Hi

Incompatible plugin with Kibana 6.6.1 - when we can expect the update?

below error from the CLI
Plugin installation was unsuccessful due to error "Plugin sentinl [6.6.0] is incompatible with Kibana [6.6.1]"

when we can expect the update? 

thx
Arek

**Comment by sergibondarenko** [comment]
@arekstuka @atranel I've attached the new package https://github.com/sirensolutions/sentinl/releases/tag/tag-6.6.0-0

**Comment by arekstuka** [comment]
HI

Thank You so much for the replay, plugin has been installed successful thru
cli, but how can i use this in Kibana?

i need to do something more? i cant find any option in kibana regarding to
the sentinl.

thanks

Arek

Serdecznie pozdrawiam / Kind regards

*Arkadiusz Stuka*
___________________________________________

Mobile:  +48 501-633-689
Skype: arekstuka
e-mail: arekstuka@gmail.com


pon., 25 lut 2019 o 09:56 Sergii Bondarenko <notifications@github.com>
napisał(a):

**Comment by arekstuka** [comment]
> @arekstuka @atranel I've attached the new package https://github.com/sirensolutions/sentinl/releases/tag/tag-6.6.0-0

After installation kibana must be restarted. 
i see the option "Sentinl" in Kibana menu. Now its time to play with it. :)

**Comment by namechenxinyu** [comment]
"Plugin sentinl [6.6.1] is incompatible with Kibana [7.0.1]"

**Comment by kouteybi** [comment]
The same problem.
Plugin sentinl [6.6.1] is incompatible with Kibana [7.0.0]

**Comment by cslimani** [comment]
Is current version [6.6.X]  compatible with Kibana [6.7.1] ?

**Comment by leiwng** [comment]
Plugin sentinl [6.6.0] is incompatible with Kibana [7.3.0]

**Comment by wangy265** [comment]
Plugin sentinl [6.6.1] is incompatible with Kibana [6.6.2]

**Comment by testrod** [comment]
Plugin sentinl [6.6.1] is incompatible with Kibana [7.3.1]
