### ISSUE TITLE
Alert when no records in result set.

### ISSUE THREAD

**Issue by pbuxtonccuk** [sirensolutions/sentinl#692]
Hi,

I have Sentinl working fine, and pushing to Slack.

However, I'm not sure it can handle my requirement.

I was hoping that I could set the watcher up, to send an alert if there are NO matching records (ergo, the record count = 0).  In particular, if there are no rows with a timestamp within the last x hours, I want an alert.

No matter what I try, it doesn't seem to do this.  Tried to setup with Wizard...

Is there a way I can do this?

Regards
Paul

**Comment by lmangani** [comment]
Sorry for the delay responding. If you still need help please attach the full configuration details to reopen.
