### ISSUE TITLE
how to set key-value  in actions?

### ISSUE THREAD

**Issue by vdingtian** [sirensolutions/sentinl#694]
I had seen structure of arrays like this：
payload.newlist.push({name: bucket.key })

how to push key-value  in  structure of map?   I want'to display key-value in actions 

"buckets": [
          {
            "key": 3,
            "value": 137
          },
          {
            "key": 20,
            "value": 58
          }]

**Comment by lmangani** [comment]
Sorry for the delay responding. I do not understand the question. If you still need help please attach the full configuration details to reopen.
