### ISSUE TITLE
sentinl-v6.6.0.zip 128mb / sentinl-v6.6.1.zip 28mb 

### ISSUE THREAD

**Issue by arekstuka** [sirensolutions/sentinl#697]
Why instalation 6.6.0 is 128mb and 6.6.1 only 28mb?
there is missing some components in 6.6.1 ?

**Comment by lmangani** [comment]
I'm quite certain the older version bundled PhantomJS and other elements for report generation. You can check from the release package.json

**Comment by arekstuka** [comment]
> I'm quite certain the older version bundled PhantomJS and other elements for report generation. You can check from the release package.json

Thanks, 

Could You provide me the instruction how can i create watcher for specific fields from the index, or watcher which can observe specific sting in the field , during the watcher wizzard i have a field : IS OVER and then i can only chose all docs and  top. 
If You have somewhere sample confix, or instruction please let me know
Arek
