### ISSUE TITLE
How can i use 6.6.1 in kibana6.6.2 ?

### ISSUE THREAD

**Issue by labosen** [sirensolutions/sentinl#703]
My ELK ver is all 6.6.2.
Is there any way to install sentinl6.6.1 to kibana6.6.2? 
(Byfar there isn't a sentinl6.6.2 version)

I use:
kibana-plugin install sentinl6.6.1

Plugin installation was unsuccessful due to error "Plugin sentinl [6.6.1] is incompatible with Kibana [6.6.2]"

How do i do? 
downgrade ELK version or find something else
......

**Comment by labosen** [comment]
somebody in emergency can use this kibana-plugin elasticalert:

https://github.com/bitsensor/elastalert-kibana-plugin/releases

Maybe

**Comment by chenyg0911** [comment]
you try to download the plugin to local, update plugin package.json version
t6.6.2, and then install the plugin

labosen <notifications@github.com> 于2019年3月22日周五 上午11:29写道：

**Comment by labosen** [comment]
@chenyg0911  thx, this works well
