### ISSUE TITLE
Sentinl 6.6.1 is not working with Searchguard enabled cluster.

### ISSUE THREAD

**Issue by chaitrahegde115** [sirensolutions/sentinl#717]
Hi,
  I installed Sentinl 6.6.1 plugin with Searchguard. But in kibana UI there is no option to create new watcher.
<img width="935" alt="sentinl-plugin" src="https://user-images.githubusercontent.com/49516212/56263821-0dbf9900-6102-11e9-99ff-214a2b31e089.png">

**Comment by lmangani** [comment]
The plugins is crashing as you can see by the unfillled variables `{{ currentTime }}` etc.
Check the Kibana logs for errors, you will surely have to remove the plugin to correct this.

**Comment by lmangani** [comment]
Please submit a new issue following the Issue requirements in order to get help with your case. Thanks!
