### ISSUE TITLE
Need help : Getting  apply condition "script" : Unexpected number

### ISSUE THREAD

**Issue by rsingh2411** [sirensolutions/sentinl#718]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |     6.6.0    |
| Elasticsearc |    6.6.0     |
| Server OS    |    mac    |
| Browser      |   chrome      |

#### Original Install Method

- [ ] Release pkg link

#### Bug Description

Following are the debug logs
og   [14:10:00.023] [debug][Sentinl][watcher 72ce7dd0-611a-11e9-9563-6904a742842d] condition: {
  "script": {
    "script": "var match=false; if (payload.hits.total == 0) {match=false;} else {  if (payload.hits.hits.0._source.CURR_LOG_LEVEL == 'DEBUG') {match=true;} match; } match;"
  }
}
  log   [14:10:00.025] [error][Sentinl][scheduler] watcher 72ce7dd0-611a-11e9-9563-6904a742842dUnexpected number: schedule execute: WatcherHandlerError: execute advanced watcher : exec condition : apply condition "script" : Unexpected number: SyntaxError: 
#### Steps to Reproduce
1.
1.
1.

#### Sample of data you have in Elasticsearch
```
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "twitter",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "user" : "kimchy",
          "post_date" : "2020-11-15T14:12:12",
          "message" : "This si test",
          "CURR_LOG_LEVEL" : "DEBUG"
        }
      }
    ]
  }
}

```

#### Full Watcher JSON
```
{
  "actions": {
      "name": "Watcher Log Level Change",
      "email_admin" : {
      "throttle_period" : "1m",
      "email": {
        "stateless": false,
        "subject": "CRITICAL | [REPLACE_WITH_CLUSTER_NAME] | Log level set to DEBUG/TRACE",
        "body": "{{payload.hits.total}}  Log level is changed to DEBUG/TRACE",
        "priority": "high",
        "to": "xxxxxxx",
        "from": "rxxxxxxx"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": ["<logstash-audit-{now/d}>"],
        "body": {
          "query": {
            "bool": {
              "must": {
                "exists": {
                  "field": "CURR_LOG_LEVEL"
                }
              },
              "filter": {
                "range": { "post_date": { "gte": "now-5m" } }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
      "script": {
        "script": "var match=false; if (payload.hits.total == 0) {match=false;} else {  if (payload.hits.hits.0._source.CURR_LOG_LEVEL == 'DEBUG') {match=true;} match; } match;"
      }
  },
  "trigger": {
    "schedule": {
      "later": "every 1 minute"
    }
  },
  "disable": false,
  "report": false,
  "title": "Watcher Log Level Change",
  "save_payload": false,
  "spy": false,
  "impersonate": false
}


```

#### Errors in Browser Console (if relevant)
```
```

**Comment by rsingh2411** [comment]
Any updates please

**Comment by rsingh2411** [comment]
Solved the issue changed this to `payload.hits.hits.0._source.CURR_LOG_LEVEL` to `payload.hits.hits[0]._source.CURR_LOG_LEVEL` Mustache Demo works conditions. but script condition doesn't work. This should be documented.

**Comment by lmangani** [comment]
Glad you got it sorted. This is a known limitation in general, documented in a few examples, and not related to how SENTINL works. The mustache demo runs in the browser and has a little superpowers apparently.
