### ISSUE TITLE
 Preparation for Kibana 5 : click on alarms bell icon and app icon led to a blank page

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#72]
A bug detected in Kibana 5 branch :
- when I am on "Alarms" tab, if I click on "bell icon", I get a blank page. It seems that on link, it misses a "/" at url's end
- if I already have opened "kaae" app, and I click again on "kaae app icon", I get also a blank page. I think it is for the same reason than "bell icon" bug (an ending "/" is missing in url).

**Comment by lmangani** [comment]
5.2.2 is ready for testing, closing old issues to make space for new ones :)
https://github.com/sirensolutions/sentinl/releases/tag/tag-5.2.2
