### ISSUE TITLE
Kibana 7.0 Support

### ISSUE THREAD

**Issue by mafshin** [sirensolutions/sentinl#723]
The most recent version of `Sentinl is 6.6.1`, in order to make it compatible with `Kibana 7.0.0` I modified `package.json` version numbers, its icon is now appeared in `Kibana 7.0.0` and the watchers I defined in previous version are displayed and they work. But there is a console error in the browser which makes some of the plugin scripts fail to execute.

The problem is with browser CSP security:

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'nonce-dwjrTXO4EkwheuE2'". Either the 'unsafe-inline' keyword, a hash ('sha256-SHHSeLc0bp6xt4BoVVyUy+3IbVqp3ujLaR+s+kSP5UI='), or a nonce ('nonce-...') is required to enable inline execution.`

Is there any workaround to bypass this issue?

**Comment by ltfi** [comment]
We also have same problem, is there any solution?

**Comment by mafshin** [comment]
An intermediate solution we came up with was managing our alerts via
Grafana.

Its nightly build supports ES 7.0 and it has easy integration with
different providers e.g. Slack.

The only downside is that you have duplicate all of your dashboards in
Grafana to set alert for them.

**Comment by ltfi** [comment]
Screen duplication is not appropriate for us, but thanks for mentioned idea..

**Comment by Bader972016** [comment]
Just wondering if there is any progress on Kibana 7.0 support. Not trying to be impatient/annoying. Thanks!

**Comment by xwin1989** [comment]
I hava same question :cry:

**Comment by kedych** [comment]
Same question, the Elastic Stack 7.2 is released in recent days.

**Comment by kedych** [comment]
Excuse me, does @ltfi  have any work-around solution? Thanks.

**Comment by lmangani** [comment]
At this time there are no plans and no sponsors for this macro effort. If anyone wants to step up and help the project get forward compatibility with PRs or Sponsorships, feel free to reach out. 

This is Open-Source and it only works as a two-way street. Join and help the project stay alive!

**Comment by lmangani** [comment]
@kedych FYI there's no workaround other than implementing the compatibility within the 7.x stack
