### ISSUE TITLE
BUG : wrong line deleted on "Alarms" tab

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#73]
A bug detected in Kibana 4 and Kibana 5 branch :
- when I am on "Alarms" tab, if I delete the second alarm line, the wrong line is deleted (for example : the first line is deleted)

**Comment by fbaligand** [comment]
@lmangani 
Finally, after test on Kibana 4.6.3, I reproduce also the issue.
=> So this issue is not specific to Kibana 5.
=> I update the issue title and description.
=> Can you remove "5.0" tag ?

**Comment by fbaligand** [comment]
I tested with very latest sentinl version.

**Comment by lmangani** [comment]
Checking! thanks for the update!

**Comment by lmangani** [comment]
Confirmed indeed, gets more severe as reordering of rows takes place. Sorting out a solution.

**Comment by fbaligand** [comment]
I think that deleting by elasticsearch Id is the robust solution. 

Fabien

**Comment by lmangani** [comment]
We do delete by index/type/id but the table picks the wrong ID due to reordering by timestamp (it seems) I am testing a fix currently.

**Comment by fbaligand** [comment]
Nice news !

Fabien

**Comment by fbaligand** [comment]
Once you'll publish a fix, I'm ready to test it and give feedback. 

Fabien

**Comment by fbaligand** [comment]
I presume you use angularjs ?
This would be clean to have elasticsearch id included in json associated to each table line. 
And generate delete link using angularjs and using directly elasticsearch id in current json doc. 

Fabien

**Comment by lmangani** [comment]
its all angular, and the right value is already there - resolution is quite trivial in essence, just need time to fit this between other 100 tasks :)

**Comment by lmangani** [comment]
If you reload the alarms page (click about, then back to alarms) is the correct "ghost" alarm you deleted actually gone?

**Comment by fbaligand** [comment]
I already tried it this afternoon, several times. And it is still the wrong one that is deleted :(

Fabien

**Comment by lmangani** [comment]
ok thanks for confirming this, the solution is just a couple lines i will port it here

**Comment by fbaligand** [comment]
I understand you have lots of issues to process. 
However, you have only two issues that are tagged "bug" and not "5.0".
It sounds like an objective criteria to prioritize this issue :)

**Comment by lmangani** [comment]
I'm sorry? If your guess is this is my only project/task and you'd be terribly wrong :)

**Comment by fbaligand** [comment]
I'm really sorry if I tell something that hurt you. 
As an opensource commiter on my home time on several projects, I clearly understand it's complicated to answer all issues and you do your best about that. No problem.

**Comment by lmangani** [comment]
The full fix addresses more elements, but as a hotpatch you can try change line 133 in ```public/templates/alarms.html``` as follows:
```
<a href="javascript:;" ng-click="deleteAlarm($index-1)" class="delete-rule"><i class="fa fa-trash"></i></a>
```

**Comment by fbaligand** [comment]
Thanks a lot !
I will try it tomorrow and give you feedback !

**Comment by fbaligand** [comment]
I'm sorry to ask that, but what are kibana bundles and where are they ?

**Comment by lmangani** [comment]
I will release a new version with the fix tomorrow morning so hopefully no problem but in general, when you make a change to a plugin file in order for this to take effect you need to manually remove ```/opt/kibana/optimize/bundles``` to force Kibana to rebuild them on restart (it takes a while)

**Comment by fbaligand** [comment]
Thanks a lot for the release and the tips !
Please put a comment here when you'll release.

**Comment by lmangani** [comment]
Please ignore the manual patch and i'll post here as soon as the new release is out

**Comment by lmangani** [comment]
Fix is available and tested, will be published during the day today - thanks for your patience ;)

**Comment by fbaligand** [comment]
Nice news !
Thanks !

Fabien

**Comment by fbaligand** [comment]
Hi, 
Is the release published ?
I presume that every night, a new `sentinl-latest.tar.gz` is published here 
https://github.com/sirensolutions/sentinl/releases/tag/snapshot
Right ?

If so, can you tell me, for info, at what time ?

**Comment by lmangani** [comment]
The build is only triggered when changes are pushed. As this update includes also new features for reports and a few more things, ẃe still need some testing but you are most welcome to join us doing so: 
[sentinl-latest.tar.gz](https://github.com/sirensolutions/sentinl/files/659003/sentinl-latest.tar.gz)

**Comment by fbaligand** [comment]
Hi @lmangani 

I have tested with Kibana 4.6.3, and now, when I delete a line, I got a fatal error :(

```
 Fatal Error
Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.4.7/$rootScope/inprog?p0=%24apply (http://localhost:4001/bundles/commons.bundle.js?v=10154:27774)

Version: 4.6.3
Build: 10154

Error: Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.4.7/$rootScope/inprog?p0=%24apply (http://localhost:4001/bundles/commons.bundle.js?v=10154:27774)
__WEBPACK_AMD_DEFINE_RESULT__</window.onerror@http://localhost:4001/bundles/commons.bundle.js?v=10154:64667:25
[2297]/</$scope.deleteAlarm@http://localhost:4001/bundles/sentinl.bundle.js?v=10154:113478:10
anonymous/fn@http://localhost:4001/bundles/commons.bundle.js?v=10154 line 41028 > Function:2:798
ngEventHandler/</callback@http://localhost:4001/bundles/commons.bundle.js?v=10154:51255:18
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:4001/bundles/commons.bundle.js?v=10154:43695:17
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:4001/bundles/commons.bundle.js?v=10154:43795:21
ngEventHandler/<@http://localhost:4001/bundles/commons.bundle.js?v=10154:51260:18
jQuery.event.dispatch@http://localhost:4001/bundles/commons.bundle.js?v=10154:22814:16
jQuery.event.add/elemData.handle@http://localhost:4001/bundles/commons.bundle.js?v=10154:22501:7
```

**Comment by lmangani** [comment]
Thanks, this helps! Could you expand the bundle and confirm the line/command causing the error?

**Comment by lmangani** [comment]
Could you try this patched release? [sentinl-latest.tar.gz](https://github.com/sirensolutions/sentinl/files/659099/sentinl-latest.tar.gz)

**Comment by fbaligand** [comment]
I just tested your patched release.
And the result is unfortunately the same :(

```
Fatal Error
Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.4.7/$rootScope/inprog?p0=%24apply (http://localhost:4001/bundles/commons.bundle.js?v=10154:27774)

Version: 4.6.3
Build: 10154

Error: Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.4.7/$rootScope/inprog?p0=%24apply (http://localhost:4001/bundles/commons.bundle.js?v=10154:27774)
__WEBPACK_AMD_DEFINE_RESULT__</window.onerror@http://localhost:4001/bundles/commons.bundle.js?v=10154:64667:25
[2297]/</$scope.deleteAlarm@http://localhost:4001/bundles/sentinl.bundle.js?v=10154:113478:10
anonymous/fn@http://localhost:4001/bundles/commons.bundle.js?v=10154 line 41028 > Function:2:798
ngEventHandler/</callback@http://localhost:4001/bundles/commons.bundle.js?v=10154:51255:18
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:4001/bundles/commons.bundle.js?v=10154:43695:17
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:4001/bundles/commons.bundle.js?v=10154:43795:21
ngEventHandler/<@http://localhost:4001/bundles/commons.bundle.js?v=10154:51260:18
jQuery.event.dispatch@http://localhost:4001/bundles/commons.bundle.js?v=10154:22814:16
jQuery.event.add/elemData.handle@http://localhost:4001/bundles/commons.bundle.js?v=10154:22501:7
```

**Comment by fbaligand** [comment]
Sorry for the question, but :
How do I expand the bundle  ?

**Comment by lmangani** [comment]
Thanks @fbaligand I need to really replicate this locally to get to the bottom of it before release.
To expand the bundle you can click the error row and it should indicate where the error spawns.

**Comment by fbaligand** [comment]
More info about the context so that you can reproduce the problem :
* it happens not everytime. 
* I invite you to test :
  * first row
  * intermediate row 
  * last row
* my OS :  windows 10
* here the definition of my alarm which generates one console alert per minute :
``` json
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "watcher1",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 minute"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": "logstash*",
          "body": {
            "query": {
              "filtered": {
                "query": {
                  "query_string": {
                    "analyze_wildcard": true,
                    "query": "_type:request"
                  }
                }
              }
            },
            "size": 3
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 0"
      }
    },
    "transform": {},
    "actions": {
      "to_console": {
        "throttle_period": "1m",
        "console": {
          "priority": "WARN",
          "message": "Series Alarm {{ payload._id}} > 0: {{ payload.hits.total }}"
        }
      }
    }
  }
}
```

**Comment by lmangani** [comment]
long overdue... latest nightly snapshot has been uploaded with pre-release version (as well as relative branch), including this fix alongside other improvements to guarantee results consistency on add/delete.

NOTE: watcher_alarm-* index mapping changed to support reports

**Comment by fbaligand** [comment]
Nice news !
I will test it soon and give you feedback !

**Comment by lmangani** [comment]
Thanks @fbaligand and happy holidays!

**Comment by fbaligand** [comment]
@lmangani 
Merry Christmas and happy new year ! :)

**Comment by fbaligand** [comment]
Hi @lmangani 

I tried sentinl last version... and I'm sad to say it's not working at all :(

Here are the details about my test :
- I removed sentinl plugin and all its related indexes in elasticsearch
- I installed sentinl in Kibana 4.6.3 (on windows 10), using :
`kibana plugin -i sentinl -u https://github.com/sirensolutions/sentinl/releases/download/snapshot/sentinl-latest.tar.gz`
- then, at kibana start, I detect a surprising log error (that I hadn't before, and after sentinl plugin removal, I don't get any more) :
`log   [18:57:53.464] [error][status][plugin:elasticsearch@1.0.0] Status changed from green to red - Unknown config key: elasticsearch.plugins`
- then, when launching sentinl app, I get a blank screen...
I can see Sentinl header black line, but below, it's blank.
- when looking at XHR requests, I saw the following error :
`http://localhost:4001/api/sentinl/example` raises a `404 Not Found` error.

**Comment by lmangani** [comment]
Fixed + new snapshot uploaded. 

NOTE: this was due to a Kibi-only lookup we inadvertently left in place, thanks for catching it!

**Comment by fbaligand** [comment]
Hi @lmangani 
Thanks for the fix.
Now kibana startup works well without error log, and I have no more blank screen when going to sentinl app.

However, I have a new blocking error :
- I created a new watcher "watcher1" (the same I mention above in the comments)
- and when sentinl executes it, it raises a kibana fatal error : I mean that Kibana is then stopped.
- here are the logs :
```
  log   [18:20:06.436] [info][status][Sentinl] Saving Watcher with ID: watcher1
  log   [18:20:25.145] [info][status][Sentinl] Scheduled Watch: watcher1 every every 1 minute
  log   [18:21:00.006] [info][status][Sentinl] Executing watch: watcher1
C:\Developpement\outils\elk\kibana-4.6.3-windows-x86\installedPlugins\sentinl\server\lib\scheduler.js:146
            if (sirenJoinAvailable) {
                ^

ReferenceError: sirenJoinAvailable is not defined
    at watching (C:/Developpement/outils/elk/kibana-4.6.3-windows-x86/installedPlugins/sentinl/server/lib/scheduler.js:129:17)
    at C:/Developpement/outils/elk/kibana-4.6.3-windows-x86/installedPlugins/sentinl/server/lib/scheduler.js:106:15
    at [object Object].scheduleTimeout [as _onTimeout] (C:\Developpement\outils\elk\kibana-4.6.3-windows-x86\installedPlugins\sentinl\node_modules\later\later.js:846:9)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by lmangani** [comment]
@fbaligand apologies for this mess and thanks for your useful feedback here - certain SENTINL features require functions stock Kibana does not provide causing this glitch depending on the ES plugin setup. Its finally sorted with the last code and passing tests at least here....

**Comment by fbaligand** [comment]
Do you mean you pushished the fix in "Nightly Build 4.x" ?

2016-12-27 10:53 GMT+01:00 Lorenzo Mangani <notifications@github.com>:

**Comment by lmangani** [comment]
Yes release has been updated, or you can rebuild it locally with:
```
npm instlal --production
npm run archive
```

**Comment by fbaligand** [comment]
Hi @lmangani 

I just tried the last version, and it works great !

- no more error at startup
- alarms deletion is perfect : 
  - the right line is deleted (whatever its position)
  - no error is thrown
  - alarms list is then refreshed

hooray :1st_place_medal: !

**Comment by lmangani** [comment]
@fbaligand thank you so much for testing this during the holidays and for taking time to update status. Your help is much appreciated - next we'll try port those fixes to the 5.x branch and take it from there :)

**Comment by fbaligand** [comment]
For 5.x branch, should I open a new issue ?

**Comment by fbaligand** [comment]
@lmangani 
Do you have ported fix on 5.x branch ?
Do you want that I open a new issue for 5.x branch ?

**Comment by fbaligand** [comment]
@lmangani 
Do you have ported fix on 5.x branch ?
Do you want that I open a new issue for 5.x branch ?

**Comment by lmangani** [comment]
Yes please, we need to track this separately for 5.x

**Comment by fbaligand** [comment]
OK !
That's done : #88
