### ISSUE TITLE
[404 - GET] - api/sentinl/time Not found [KIBANA 6.8.0]

### ISSUE THREAD

**Issue by bard0x** [sirensolutions/sentinl#731]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |  6.8.0  |
| Elasticsearc |  6.8.0   |
| Server OS    |  Windows 10   |
| Browser      |   Chrome   |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
**x** Other: 

#### Bug Description

I tried to install sentinl on Kibana 6.8.0. Above my configuration for sentinl in kibana.yml:

sentinl:
  es:
    hosts: ["xxx.xxx.xxx.xxx"]
    port: 9200
  settings:
    authentication:
      enabled: true 
      username: 'elastic'
      password: 'xxxxxxx'

When I try to run sentinl from kibana dashboard, the console of chrome get me this error:

**_Failed to load resource: the server responded with a status of 404 (Not Found)_**

Why this happens? The connection with my ES instance is OK, but I don't be able to run correctly sentinl.

**Comment by lmangani** [comment]
The plugin likely failed to install due to version incompatibilities. Check the kibana logs on startup.
