### ISSUE TITLE
Does sentinl have a plan to support kibana 6.8.0?

### ISSUE THREAD

**Issue by k-kyle** [sirensolutions/sentinl#737]
# Does sentinl have a plan to support kibana 6.8.0?
Transferring 134770542 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin sentinl [6.6.0] is incompatible with Kibana [6.8.0]"
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |       6.8.0  |
| Elasticsearc |        6.8.0 |

**Comment by lmangani** [comment]
At this time there are no plans and no sponsors for this macro effort. If anyone wants to step up and help the project get forward compatibility with PRs or Sponsorships, feel free to reach out.

**Comment by k-kyle** [comment]
ok,thank you for your reply.
