### ISSUE TITLE
can't edit the match condition

### ISSUE THREAD

**Issue by yizhishang** [sirensolutions/sentinl#760]
#### Versions

| Type         | Version |  deployed    |
|--------------|---------|---------|
| Kibana       |     6.7.0    |  deployed in docker |
| Elasticsearc |    6.7.0     |  deployed in win10
| Server OS    |  win10  |  |
| Browser      |    firefox     | |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1.
1.
1.

#### Sample of data you have in Elasticsearch
```json
{
  "_index": "filebeat-6.7.0-2019.11.15",
  "_type": "doc",
  "_id": "lDIrbm4B5Yv4UJNMoKxR",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-11-15T08:26:20.158Z",
    "logMaxSize": "10MB",
    "level_value": 30000,
    "springProfile": "dev",
    "tags": [
      "k8s-demo"
    ],
    "beat": {
      "name": "Lenovo-yizhishang",
      "hostname": "Lenovo-yizhishang",
      "version": "6.7.0"
    },
    "logger_name": "org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver",
    "pattern.console": "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n",
    "@version": "1",
    "host": {
      "name": "Lenovo-yizhishang"
    },
    "message": "Resolved exception caused by Handler execution: org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object 'video' on field 'id': rejected value [null]; codes [NotNull.video.id,NotNull.id,NotNull.java.lang.Long,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [video.id,id]; arguments []; default message [id]]; default message [不能为null]",
    "log": {
      "file": {
        "path": "F:\\logs\\k8s-demo\\server.log"
      }
    },
    "level": "WARN",
    "springAppName": "k8s-demo",
    "thread_name": "XNIO-2 task-3",
    "prospector": {
      "type": "log"
    },
    "offset": 42912,
    "source": "F:\\logs\\k8s-demo\\server.log",
    "logBusinessLevel": "DEBUG",
    "collect": "1",
    "logPath": "/logs",
    "input": {
      "type": "log"
    }
  },
  "fields": {
    "@timestamp": [
      "2019-11-15T08:26:20.158Z"
    ]
  },
  "highlight": {
    "tags": [
      "@kibana-highlighted-field@k8s-demo@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1573806380158
  ]
}
```

#### Full Watcher JSON
```
```

#### Errors in Browser Console (if relevant)
```
```

#### Kibana logs and/or server output (attached if relevant)
```code
D:\Program Files\kibana-6.7.0-windows-x86_64\bin>kibana.bat
  log   [16:18:21.446] [info][status][plugin:kibana@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.473] [info][status][plugin:elasticsearch@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.475] [info][status][plugin:xpack_main@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.478] [info][status][plugin:graph@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.486] [info][status][plugin:monitoring@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.488] [info][status][plugin:spaces@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.494] [warning][security] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml
  log   [16:18:21.498] [warning][security] Session cookies will be transmitted over insecure connections. This is not recommended.
  log   [16:18:21.503] [info][status][plugin:security@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.515] [info][status][plugin:searchprofiler@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.518] [info][status][plugin:ml@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.547] [info][status][plugin:tilemap@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.549] [info][status][plugin:watcher@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.556] [info][status][plugin:grokdebugger@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.560] [info][status][plugin:dashboard_mode@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.561] [info][status][plugin:logstash@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.566] [info][status][plugin:beats_management@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.585] [info][status][plugin:apm@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.587] [info][status][plugin:tile_map@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.589] [info][status][plugin:task_manager@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.591] [info][status][plugin:maps@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.594] [info][status][plugin:interpreter@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.600] [info][status][plugin:canvas@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.603] [info][status][plugin:license_management@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.605] [info][status][plugin:cloud@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.606] [info][status][plugin:index_management@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.616] [info][status][plugin:console@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.617] [info][status][plugin:console_extensions@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.619] [info][status][plugin:notifications@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.620] [info][status][plugin:index_lifecycle_management@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.651] [info][status][plugin:infra@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.653] [info][status][plugin:rollup@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.659] [info][status][plugin:remote_clusters@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.663] [info][status][plugin:cross_cluster_replication@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:18:21.670] [info][status][plugin:translations@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.678] [info][status][plugin:upgrade_assistant@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.687] [info][status][plugin:uptime@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.689] [info][status][plugin:oss_telemetry@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.691] [info][status][plugin:sentinl@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.697] [info][status][plugin:metrics@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:21.847] [info][status][plugin:timelion@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:22.442] [info][status][plugin:elasticsearch@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.444] [info][Sentinl][init] initializing ...
  log   [16:18:22.445] [error][Sentinl][init] setting puppeteer report engine: Error: ENOENT: no such file or directory, scandir 'D:\Program Files\kibana-6.7.0-windows-x86_64\plugins\sentinl\node_modules\puppeteer\.local-chromium'
  log   [16:18:22.464] [info][Sentinl][init_indices] checking watcher_alarms-2019.11.15 index ...
  log   [16:18:22.483] [info][license][xpack] Imported license information from Elasticsearch for the [data] cluster: mode: basic | status: active
  log   [16:18:22.486] [info][status][plugin:xpack_main@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.487] [info][status][plugin:graph@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.495] [info][status][plugin:searchprofiler@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.496] [info][status][plugin:ml@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.503] [info][status][plugin:tilemap@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.504] [info][status][plugin:watcher@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.506] [info][status][plugin:grokdebugger@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.507] [info][status][plugin:logstash@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.515] [info][status][plugin:beats_management@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.525] [info][status][plugin:index_management@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.528] [info][status][plugin:index_lifecycle_management@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.529] [info][status][plugin:rollup@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.539] [info][status][plugin:remote_clusters@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.546] [info][status][plugin:cross_cluster_replication@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.549] [info][kibana-monitoring][monitoring-ui] Starting monitoring stats collection
  log   [16:18:22.561] [info][status][plugin:security@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.561] [info][status][plugin:maps@6.7.0] Status changed from yellow to green - Ready
  log   [16:18:22.588] [info][license][xpack] Imported license information from Elasticsearch for the [monitoring] cluster: mode: basic | status: active
  log   [16:18:22.883] [warning][reporting] Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml
  log   [16:18:22.898] [info][status][plugin:reporting@6.7.0] Status changed from uninitialized to green - Ready
  log   [16:18:22.972] [info][listening] Server running at http://0.0.0.0:5601
  log   [16:18:22.982] [info][status][plugin:spaces@6.7.0] Status changed from yellow to green - Ready
```

![image](https://user-images.githubusercontent.com/12756407/68928532-407b5e00-07c5-11ea-9e63-0e996b7837f7.png)

#### Any additional information
can't edit the Match Condition
![image](https://user-images.githubusercontent.com/12756407/68928516-35c0c900-07c5-11ea-8896-d1a973a36a83.png)

**Comment by taoyantu** [comment]
> ### System Details
> #### Versions
> Type	Version	deployed
> Kibana	6.7.0	deployed in docker
> Elasticsearc	6.7.0	deployed in win10
> Server OS	win10	
> Browser	firefox	
> #### Original Install Method
> * [ ]  Release pkg link
> * [ ]  Gulp
> * [ ]  Source
> * Other:
> 
> ### Bug Details
> #### Bug Description
> #### Steps to Reproduce
> 
> #### Expected Behavior
> #### Sample of data you have in Elasticsearch
> ```json
> {
>   "_index": "filebeat-6.7.0-2019.11.15",
>   "_type": "doc",
>   "_id": "lDIrbm4B5Yv4UJNMoKxR",
>   "_version": 1,
>   "_score": null,
>   "_source": {
>     "@timestamp": "2019-11-15T08:26:20.158Z",
>     "logMaxSize": "10MB",
>     "level_value": 30000,
>     "springProfile": "dev",
>     "tags": [
>       "k8s-demo"
>     ],
>     "beat": {
>       "name": "Lenovo-yizhishang",
>       "hostname": "Lenovo-yizhishang",
>       "version": "6.7.0"
>     },
>     "logger_name": "org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver",
>     "pattern.console": "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n",
>     "@version": "1",
>     "host": {
>       "name": "Lenovo-yizhishang"
>     },
>     "message": "Resolved exception caused by Handler execution: org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object 'video' on field 'id': rejected value [null]; codes [NotNull.video.id,NotNull.id,NotNull.java.lang.Long,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [video.id,id]; arguments []; default message [id]]; default message [不能为null]",
>     "log": {
>       "file": {
>         "path": "F:\\logs\\k8s-demo\\server.log"
>       }
>     },
>     "level": "WARN",
>     "springAppName": "k8s-demo",
>     "thread_name": "XNIO-2 task-3",
>     "prospector": {
>       "type": "log"
>     },
>     "offset": 42912,
>     "source": "F:\\logs\\k8s-demo\\server.log",
>     "logBusinessLevel": "DEBUG",
>     "collect": "1",
>     "logPath": "/logs",
>     "input": {
>       "type": "log"
>     }
>   },
>   "fields": {
>     "@timestamp": [
>       "2019-11-15T08:26:20.158Z"
>     ]
>   },
>   "highlight": {
>     "tags": [
>       "@kibana-highlighted-field@k8s-demo@/kibana-highlighted-field@"
>     ]
>   },
>   "sort": [
>     1573806380158
>   ]
> }
> ```
> 
> #### Full Watcher JSON
> #### Screenshots (if relevant)
> #### Errors in Browser Console (if relevant)
> #### Kibana logs and/or server output (attached if relevant)
> ```
> D:\Program Files\kibana-6.7.0-windows-x86_64\bin>kibana.bat
>   log   [16:18:21.446] [info][status][plugin:kibana@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.473] [info][status][plugin:elasticsearch@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.475] [info][status][plugin:xpack_main@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.478] [info][status][plugin:graph@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.486] [info][status][plugin:monitoring@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.488] [info][status][plugin:spaces@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.494] [warning][security] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml
>   log   [16:18:21.498] [warning][security] Session cookies will be transmitted over insecure connections. This is not recommended.
>   log   [16:18:21.503] [info][status][plugin:security@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.515] [info][status][plugin:searchprofiler@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.518] [info][status][plugin:ml@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.547] [info][status][plugin:tilemap@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.549] [info][status][plugin:watcher@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.556] [info][status][plugin:grokdebugger@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.560] [info][status][plugin:dashboard_mode@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.561] [info][status][plugin:logstash@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.566] [info][status][plugin:beats_management@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.585] [info][status][plugin:apm@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.587] [info][status][plugin:tile_map@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.589] [info][status][plugin:task_manager@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.591] [info][status][plugin:maps@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.594] [info][status][plugin:interpreter@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.600] [info][status][plugin:canvas@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.603] [info][status][plugin:license_management@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.605] [info][status][plugin:cloud@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.606] [info][status][plugin:index_management@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.616] [info][status][plugin:console@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.617] [info][status][plugin:console_extensions@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.619] [info][status][plugin:notifications@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.620] [info][status][plugin:index_lifecycle_management@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.651] [info][status][plugin:infra@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.653] [info][status][plugin:rollup@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.659] [info][status][plugin:remote_clusters@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.663] [info][status][plugin:cross_cluster_replication@6.7.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [16:18:21.670] [info][status][plugin:translations@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.678] [info][status][plugin:upgrade_assistant@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.687] [info][status][plugin:uptime@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.689] [info][status][plugin:oss_telemetry@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.691] [info][status][plugin:sentinl@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.697] [info][status][plugin:metrics@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:21.847] [info][status][plugin:timelion@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:22.442] [info][status][plugin:elasticsearch@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.444] [info][Sentinl][init] initializing ...
>   log   [16:18:22.445] [error][Sentinl][init] setting puppeteer report engine: Error: ENOENT: no such file or directory, scandir 'D:\Program Files\kibana-6.7.0-windows-x86_64\plugins\sentinl\node_modules\puppeteer\.local-chromium'
>   log   [16:18:22.464] [info][Sentinl][init_indices] checking watcher_alarms-2019.11.15 index ...
>   log   [16:18:22.483] [info][license][xpack] Imported license information from Elasticsearch for the [data] cluster: mode: basic | status: active
>   log   [16:18:22.486] [info][status][plugin:xpack_main@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.487] [info][status][plugin:graph@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.495] [info][status][plugin:searchprofiler@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.496] [info][status][plugin:ml@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.503] [info][status][plugin:tilemap@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.504] [info][status][plugin:watcher@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.506] [info][status][plugin:grokdebugger@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.507] [info][status][plugin:logstash@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.515] [info][status][plugin:beats_management@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.525] [info][status][plugin:index_management@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.528] [info][status][plugin:index_lifecycle_management@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.529] [info][status][plugin:rollup@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.539] [info][status][plugin:remote_clusters@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.546] [info][status][plugin:cross_cluster_replication@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.549] [info][kibana-monitoring][monitoring-ui] Starting monitoring stats collection
>   log   [16:18:22.561] [info][status][plugin:security@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.561] [info][status][plugin:maps@6.7.0] Status changed from yellow to green - Ready
>   log   [16:18:22.588] [info][license][xpack] Imported license information from Elasticsearch for the [monitoring] cluster: mode: basic | status: active
>   log   [16:18:22.883] [warning][reporting] Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml
>   log   [16:18:22.898] [info][status][plugin:reporting@6.7.0] Status changed from uninitialized to green - Ready
>   log   [16:18:22.972] [info][listening] Server running at http://0.0.0.0:5601
>   log   [16:18:22.982] [info][status][plugin:spaces@6.7.0] Status changed from yellow to green - Ready
> ```
> 
> ![image](https://user-images.githubusercontent.com/12756407/68928532-407b5e00-07c5-11ea-9e63-0e996b7837f7.png)
> 
> #### Any additional information
> can't edit the Match Condition
> ![image](https://user-images.githubusercontent.com/12756407/68928516-35c0c900-07c5-11ea-8896-d1a973a36a83.png)

It's the same with me. How to solve it ？
