### ISSUE TITLE
I also face this problem.Can not see the setted watcher lists in sentinl.But the watcher job work normal.

### ISSUE THREAD

**Issue by Wangyegithubv** [sirensolutions/sentinl#762]
I also face this problem.Can not see the setted watcher lists in sentinl.But the watcher job work normal.
kibana sentinl error:
Sentinl Alarms: An HTTP request has failed to connect. Please check if the Kibana server is running and that your browser has a working connection, or contact your system administrator.

_Originally posted by @Wangyegithubv in https://github.com/sirensolutions/sentinl/issues/469#issuecomment-568948158_

**Comment by ss736** [comment]
Please set the results field in sentinl section of your kibana.yml and then restart kibana.

Note: set the results values around 1000, if you believe that there will be almost 1000 sentinl alerts.

Reference: https://sentinl.readthedocs.io/en/latest/Config-Example/

The results value show how many sentinl alerts who want to see in Sentinl dashboard.

Let me know if you are still unable to see the alert.
