### ISSUE TITLE
no such package available : @elastic/eslint-config-kibana

### ISSUE THREAD

**Issue by superbyang** [sirensolutions/sentinl#80]
When I try to run "npm install" in sentinl, it tells "404 no such package available : @elastic/eslint-config-kibana".

**Comment by lmangani** [comment]
Could you pull the latest master and check if this is resolved?

**Comment by superbyang** [comment]
@lmangani sure, it works now, thanks a lot.

**Comment by lmangani** [comment]
Thanks for the status update @superbyang
