### ISSUE TITLE
Can I send anonymous email when notify someone?

### ISSUE THREAD

**Issue by superbyang** [sirensolutions/sentinl#81]
If inscribe

**Comment by lmangani** [comment]
This depends on your mail server settings accepting the anonymous sender. SENTINL only sends to SMTP. Hope this helps.

**Comment by superbyang** [comment]
Thx @lmangani , I checked 'emailjs' that SENTINL used, seems it doesn't support anonymous email.

**Comment by lmangani** [comment]
please define anonymous I might be misunderstanding - if the SMTP server allows the authenticated session, your user can identify themselves as anonymous but the origination would not be. If you're talking about delivering an email without SMTP, that's not currently in scope indeed.

**Comment by superbyang** [comment]
I am talking about send email with a fake sender using SMTP (without login process). But it seems 'emailjs' only support send with authenticated session（not so sure.）？

**Comment by shamil** [comment]
Since config moved to kibana.yml I can't specify empty username/password for email. My SMTP local relay doesn't require credentials? Is that something that is known limitation?

**Comment by lmangani** [comment]
@shamil this is a different issue I believe, please do open a new one and attach the relevant logs from kibana, etc. Thanks!
