### ISSUE TITLE
Mapping error Kibi 4.5.4

### ISSUE THREAD

**Issue by gromit6891** [sirensolutions/sentinl#82]
After installing the Sentinl plugin in Kibi 4.5.4 Community Standalone, Kibi reports a mapping error and disables it.

```
[error][warning][Sentinl] [mapper_parsing_exception] Mapping definition for [attachment] has unsupported parameters:  [enabled : false]
```

Is there somewhere the mapping definitions can be edited?

**Comment by lmangani** [comment]
Thanks @gromit6891 for reporting - issue should be fixed, could you pull latest code or release and test again?!

**Comment by gromit6891** [comment]
You guys rock, tested and all good,
