### ISSUE TITLE
alarms history @timestamp

### ISSUE THREAD

**Issue by gubr123** [sirensolutions/sentinl#83]
Hi.
Using kibana 4.6.3 and latest sentinl version. 
question about the alarms history timestamp.

For some reason the timestamp of the triggered alarms are in UTC time and not my current time.

Any idea why that is? How do I change that?

In addition, is there a way to see in the alarms history one record per each watcher triggered, and not one per each of its actions?

Thanks

**Comment by lmangani** [comment]
Hi @gubr123 
We're working to extend this aspect and implementing filtering for results. Meanwhile, since the executions are logged in Elasticsearch itself (watcher_alarms-*) you can create any visualizer or logic to display them in Kibana

**Comment by gubr123** [comment]
@lmangani 
Great, thanks. Any idea about the alarm history timestamp issue?

**Comment by lmangani** [comment]
Ooops! I read from the bottom up I guess :) Timestamps of received events are always in UTC internally by design. Please open a dedicated feature request to propose custom timestamp display preference in future versions.
