### ISSUE TITLE
Is it required to store sentinl.json in /etc ?

### ISSUE THREAD

**Issue by camlizo** [sirensolutions/sentinl#84]
Is it required to store the config file sentinl.json in /etc ? and nowhere else ?
Because I would like to use Sentil for alerting but I do not have root access on the target server.

**Comment by lmangani** [comment]
Hi @camlizo 

The sentinl settings currently must exist in either in ```/opt/kibana/installedPlugins/sentinl/sentinl.json``` (overwritten on each update) or copied to ```/etc/sentinl.json``` so you can use the first path for testing.

This weekend we're moving the configuration to the main Kibana/Kibi yml configuration, so next release will drop this requirement entirely.

**Comment by camlizo** [comment]
Good news !
Can we know when we can use the next release ?

**Comment by lmangani** [comment]
we're testing it right now, hopefully before or during the weekend will be out

**Comment by camlizo** [comment]
very excited to use it !
Thanks!
