### ISSUE TITLE
Sentinl stopped working after upgrading

### ISSUE THREAD

**Issue by shamil** [sirensolutions/sentinl#85]
Hi,

After upgrading to latest `master` sentinl stopped to work.

The plugin loads fine, but seems like all requests are handled by `example` route which gets 404 every time, and the URL is: http://kibana.example.com/api/sentinl/example

Kibana 4.6.3
Sentinl latest `master` branch (https://github.com/sirensolutions/sentinl/tree/0ebba4e22fe0304660861590d3cc4f0e85caf729)

**Comment by lmangani** [comment]
Hi @shamil could you give a shot using the latest snapshot? It contains a fix for this already

**Comment by shamil** [comment]
@lmangani I'm using `master` branch, which branch should I try?

**Comment by lmangani** [comment]
Please try install the nightly build release snapshot for a test:
https://github.com/sirensolutions/sentinl/releases/download/snapshot/sentinl-latest.tar.gz

**Comment by lmangani** [comment]
@shamil just pushed the latest code to master, you can also build a release to test

**Comment by shamil** [comment]
@lmangani works!

Not related to this bug, but since config moved to `kibana.yml` I can't specify empty username/password for email. My SMTP local relay doesn't require credentials? Is that something that is known limitation?

**Comment by lmangani** [comment]
please open a separate issue and we'll look into this right away

**Comment by shamil** [comment]
There is an issue open with similar problem: https://github.com/sirensolutions/sentinl/issues/81

**Comment by shamil** [comment]
Actually it's closed.
