### ISSUE TITLE
Preparation for Kibana 5 : wrong line deleted on "Alarms" tab

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#88]
A bug detected in Kibana 5 branch :
- when I am on "Alarms" tab, if I delete the second alarm line, the wrong line is deleted (for example : the first line is deleted)

**Comment by lmangani** [comment]
5.2.2 released for testing - closing old issues to welcome new ones:
https://github.com/sirensolutions/sentinl/releases/tag/tag-5.2.2
