### ISSUE TITLE
Use POST rather than GET to save a watcher

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#89]
Currently, when a watcher is saved, an AJAX GET request is sent with JSON content URL-encoded in URI.

First, this is weird from a REST point of view.
But it is also annoying when Kibana is behind a Reverse Proxy (like Apache). Because Apache decodes URL-encoded "/" characters.

So if you define a watcher which contains `{now/d}`, when you try to save it in Sentinl, you get a 404 error from Apache server.

=> It would be great to use POST rather than GET to save a watcher.

**Comment by lmangani** [comment]
Indeed, we also have an internal ticket on the private repository for the same improvement. Will track its delivery here.

**Comment by fbaligand** [comment]
@lmangani 
Nice news to see that there's already an internal ticket on that !
And thanks to track its delivery here :+1:

**Comment by huawangpp** [comment]
+1 
We hit the same issue. 
Thanks

**Comment by fbaligand** [comment]
Hi @huawangpp ,

Actually, I just realized that this issue is fixed since [24 January](https://github.com/sirensolutions/sentinl/commit/cf70604b0986aa866879401f2e9a075c2962448d) !

You can get the release including the fix here : 
https://github.com/sirensolutions/sentinl/releases/tag/tag-4.6.3-1

But you have to build the plugin package with dependencies using `npm install`

**Comment by fbaligand** [comment]
I just tested the fix => it works great !
Thanks @fabiocorneti !

=> I close the issue.
