### ISSUE TITLE
New kibana.yml based sentinl configuration

### ISSUE THREAD

**Issue by kayrus** [sirensolutions/sentinl#90]
You've changed the json configuration from /etc/sentinl.json to config/kibana.yml but didn't provide an example. How should I configure sentinl now?

**Comment by lmangani** [comment]
Hi @kayrus this is in our Wiki ready to copy paste:

https://github.com/sirensolutions/sentinl/wiki/SENTINL-Config-Example

**Comment by kayrus** [comment]
@lmangani I tried to find something in the repo, didn't even think that you have a wiki. Thanks.

**Comment by lmangani** [comment]
No problem!

**Comment by kayrus** [comment]
Quick question. If I don't want to overwrite kibana.yml and want a separate file to configure sentinl.yml only, what should I do? You mention kibi file, but I didn't find any mention of this file in kibana source.

**Comment by lmangani** [comment]
The settings need to go in appendix to your kibana.yml, there's currently no alternate way to store settings.

**Comment by kayrus** [comment]
I use it in kubernetes and separate directory was more convenient. Because you have two config sources which could be updated independently. Now I have to invent yet another wheel.

**Comment by lmangani** [comment]
That's a valid point, please open a separate issue with any proposal you find useful. We want this to make your life easier, not complex ;) Thanks!

**Comment by kayrus** [comment]
done #91
