### ISSUE TITLE
Separate configuration for sentinl

### ISSUE THREAD

**Issue by kayrus** [sirensolutions/sentinl#91]
In kubernetes you can mount configurations only into the directories. When kaae supported `/etc/kaae.json` I created a `/etc/kaae` which contained config file from kubernetes configmap: `/etc/kaae/kaae.json`. So I just made a symlink to `/etc/kaae.json` and it worked flawlessly.

Same configuration was implemented with kibana.

Now you've merged kibana and sentinl configuration into one file and if you have two separate configurations you have to merge them into one file.

That would be great if you provide an alternative to load config from external path.

Thanks in advance.

**Comment by sethyes** [comment]
+1

**Comment by huawangpp** [comment]
+1 too. 
Also the wiki still hints there is support for kibi.yml file, which doesn't work and should get updated, https://github.com/sirensolutions/sentinl/wiki/SENTINL-Config-Example
