### ISSUE TITLE
TUTORIAL: Getting values from multi-aggregations by condition

### ISSUE THREAD

**Issue by moueimei** [sirensolutions/sentinl#94]
I have a payload like this:
<pre>
{ 
"@timestamp": "2017-01-18T05:22:00.188Z",
  "level": "DEBUG",
  "message": "Series Alarm : 27853959",
  "action": "console_dev",
  "payload": {
    "took": 166,
    "timed_out": false,
    "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
    },
    "hits": {
      "total": 27853959,
      "max_score": 1,
      "hits": [
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKscw",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.216",
            "cost": 11,
            "channel": "arrowbjone.bj.1252921383.clb.myqcloud.com/123.206.4.91:9000",
            "roomId": -170812632,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:09.439Z",
            "path": "/data/moniter/logs/netty-BJ01-4.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        },
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKscx",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.216",
            "cost": 11,
            "channel": "arrowbjone.bj.1252921383.clb.myqcloud.com/123.206.4.91:9000",
            "roomId": -170812632,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:09.469Z",
            "path": "/data/moniter/logs/netty-BJ01-4.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        },
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKsc0",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.216",
            "cost": 12,
            "channel": "arrowbjone.bj.1252921383.clb.myqcloud.com/123.206.4.91:9000",
            "roomId": -170812632,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:09.560Z",
            "path": "/data/moniter/logs/netty-BJ01-4.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        },
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKsc2",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.158",
            "cost": 11,
            "channel": "arrowbjthree.bj.1252921383.clb.myqcloud.com/123.206.4.48:9000",
            "roomId": -170812574,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:08.549Z",
            "path": "/data/moniter/logs/netty-BJ03-9.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        },
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKsc8",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.158",
            "cost": 11,
            "channel": "arrowbjthree.bj.1252921383.clb.myqcloud.com/123.206.4.48:9000",
            "roomId": -170812574,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:08.732Z",
            "path": "/data/moniter/logs/netty-BJ03-9.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        },
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKsdB",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.158",
            "cost": 12,
            "channel": "arrowbjthree.bj.1252921383.clb.myqcloud.com/123.206.4.48:9000",
            "roomId": -170812574,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:08.886Z",
            "path": "/data/moniter/logs/netty-BJ03-9.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        },
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKsdE",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.158",
            "cost": 11,
            "channel": "arrowbjthree.bj.1252921383.clb.myqcloud.com/123.206.4.48:9000",
            "roomId": -170812574,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:08.976Z",
            "path": "/data/moniter/logs/netty-BJ03-9.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        },
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKsdJ",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.158",
            "cost": 11,
            "channel": "arrowbjthree.bj.1252921383.clb.myqcloud.com/123.206.4.48:9000",
            "roomId": -170812574,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:09.126Z",
            "path": "/data/moniter/logs/netty-BJ03-9.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        },
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKsdK",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.158",
            "cost": 10,
            "channel": "arrowbjthree.bj.1252921383.clb.myqcloud.com/123.206.4.48:9000",
            "roomId": -170812574,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:09.156Z",
            "path": "/data/moniter/logs/netty-BJ03-9.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        },
        {
          "_index": "websocket-2017.01.18",
          "_type": "CMPlay-arrow-io-netty",
          "_id": "AVmu36ngZh_zuXdAKsdM",
          "_score": 1,
          "_ttl": 844690713,
          "_source": {
            "nettyId": "10.46.100.158",
            "cost": 11,
            "channel": "arrowbjthree.bj.1252921383.clb.myqcloud.com/123.206.4.48:9000",
            "roomId": -170812574,
            "@version": "1",
            "@timestamp": "2017-01-18T00:00:09.218Z",
            "path": "/data/moniter/logs/netty-BJ03-9.log",
            "host": "localhost",
            "type": "CMPlay-arrow-io-bj",
            "tags": [
              "北京WEBSOCKET监控"
            ]
          }
        }
      ]
    },
    "aggregations": {
      "events_last2_minute": {
        "doc_count": 83636,
        "articles_over_time": {
          "buckets": [
            {
              "key_as_string": "2017-01-18 01:21:00",
              "key": 1484716860000,
              "doc_count": 83636,
              "zonees": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": [
                  {
                    "key": "CMPlay-arrow-io-bj",
                    "doc_count": 57785,
                    "nettyIds": {
                      "doc_count_error_upper_bound": 0,
                      "sum_other_doc_count": 38405,
                      "buckets": [
                        {
                          "key": "10.46.100.86",
                          "doc_count": 1942,
                          "max_cost": {
                            "value": 42
                          },
                          "avg_cost": {
                            "value": 13.228115345005149
                          }
                        },
                        {
                          "key": "10.46.100.152",
                          "doc_count": 1939,
                          "max_cost": {
                            "value": 23
                          },
                          "avg_cost": {
                            "value": 11.829809179989686
                          }
                        },
                        {
                          "key": "10.46.100.219",
                          "doc_count": 1939,
                          "max_cost": {
                            "value": 40
                          },
                          "avg_cost": {
                            "value": 12.631253223310985
                          }
                        },
                        {
                          "key": "10.46.100.240",
                          "doc_count": 1939,
                          "max_cost": {
                            "value": 28
                          },
                          "avg_cost": {
                            "value": 12.757607013924703
                          }
                        },
                        {
                          "key": "10.46.100.201",
                          "doc_count": 1938,
                          "max_cost": {
                            "value": 38
                          },
                          "avg_cost": {
                            "value": 13.329721362229103
                          }
                        },
                        {
                          "key": "10.46.100.77",
                          "doc_count": 1938,
                          "max_cost": {
                            "value": 40
                          },
                          "avg_cost": {
                            "value": 13.003611971104231
                          }
                        },
                        {
                          "key": "10.46.100.14",
                          "doc_count": 1937,
                          "max_cost": {
                            "value": 23
                          },
                          "avg_cost": {
                            "value": 12.002065049044916
                          }
                        },
                        {
                          "key": "10.46.100.146",
                          "doc_count": 1937,
                          "max_cost": {
                            "value": 25
                          },
                          "avg_cost": {
                            "value": 11.017036654620547
                          }
                        },
                        {
                          "key": "10.46.100.11",
                          "doc_count": 1936,
                          "max_cost": {
                            "value": 25
                          },
                          "avg_cost": {
                            "value": 11.586260330578513
                          }
                        },
                        {
                          "key": "10.46.100.104",
                          "doc_count": 1935,
                          "max_cost": {
                            "value": 44
                          },
                          "avg_cost": {
                            "value": 13.158139534883722
                          }
                        }
                      ]
                    }
                  },
                  {
                    "key": "CMPlay-arrow-io-sh",
                    "doc_count": 25851,
                    "nettyIds": {
                      "doc_count_error_upper_bound": 0,
                      "sum_other_doc_count": 10985,
                      "buckets": [
                        {
                          "key": "10.47.101.231",
                          "doc_count": 1557,
                          "max_cost": {
                            "value": 55
                          },
                          "avg_cost": {
                            "value": 37.48490687219011
                          }
                        },
                        {
                          "key": "10.47.101.236",
                          "doc_count": 1541,
                          "max_cost": {
                            "value": 52
                          },
                          "avg_cost": {
                            "value": 37.70668397144711
                          }
                        },
                        {
                          "key": "10.47.101.13",
                          "doc_count": 1500,
                          "max_cost": {
                            "value": 53
                          },
                          "avg_cost": {
                            "value": 38.328
                          }
                        },
                        {
                          "key": "10.47.101.79",
                          "doc_count": 1497,
                          "max_cost": {
                            "value": 163
                          },
                          "avg_cost": {
                            "value": 38.857715430861724
                          }
                        },
                        {
                          "key": "10.47.101.100",
                          "doc_count": 1490,
                          "max_cost": {
                            "value": 54
                          },
                          "avg_cost": {
                            "value": 38.9986577181208
                          }
                        },
                        {
                          "key": "10.47.101.181",
                          "doc_count": 1490,
                          "max_cost": {
                            "value": 139
                          },
                          "avg_cost": {
                            "value": 38.95838926174497
                          }
                        },
                        {
                          "key": "10.47.101.215",
                          "doc_count": 1490,
                          "max_cost": {
                            "value": 57
                          },
                          "avg_cost": {
                            "value": 39.01812080536913
                          }
                        },
                        {
                          "key": "10.47.101.56",
                          "doc_count": 1448,
                          "max_cost": {
                            "value": 55
                          },
                          "avg_cost": {
                            "value": 39.5310773480663
                          }
                        },
                        {
                          "key": "10.47.101.15",
                          "doc_count": 1438,
                          "max_cost": {
                            "value": 54
                          },
                          "avg_cost": {
                            "value": 39.82058414464534
                          }
                        },
                        {
                          "key": "10.47.101.22",
                          "doc_count": 1415,
                          "max_cost": {
                            "value": 66
                          },
                          "avg_cost": {
                            "value": 41.190106007067136
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  },
  "report": false
}
and an condition, that should iterate over the payload:
    "condition": {
      "script": {
        "script": "var status=false;payload.aggregations.events_last2_minute.articles_over_time.buckets.forEach(function(e){e.zonees.buckets.forEach(function(e){e.nettyIds.buckets.forEach(function(e){var avg=parseFloat(e.avg_cost.value);if(avg>=50.0){status=true;return status;};});});});"
      }
    }

the full watcher config like this:
 {
  "_index": "watcher",
  "_type": "watch",
  "_id": "watcher_alarms",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 minutes"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "<websocket-{now/d}>"
          ],
          "body": {
            "aggs": {
              "events_last2_minute": {
                "filter": {
                  "range": {
                    "@timestamp": {
                      "format": "yyyy-MM-dd hh:mm:ss",
                      "from": "now-1m/m"
                    }
                  }
                },
                "aggs": {
                  "articles_over_time": {
                    "date_histogram": {
                      "field": "@timestamp",
                      "interval": "1m",
                      "time_zone": "+08:00",
                      "format": "yyyy-MM-dd hh:mm:ss"
                    },
                    "aggs": {
                      "zonees": {
                        "terms": {
                          "field": "type"
                        },
                        "aggs": {
                          "nettyIds": {
                            "terms": {
                              "field": "nettyId"
                            },
                            "aggs": {
                              "avg_cost": {
                                "avg": {
                                  "field": "cost"
                                }
                              },
                              "max_cost": {
                                "max": {
                                  "field": "cost"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "var status=false;payload.aggregations.events_last2_minute.articles_over_time.buckets.forEach(function(e){e.zonees.buckets.forEach(function(e){e.nettyIds.buckets.forEach(function(e){var avg=parseFloat(e.avg_cost.value);if(avg>=50.0){status=true;return status;};});});});"
      }
    },
    "transform": {},
    "actions": {
      "console_dev": {
        "console": {
          "priority": "DEBUG",
          "message": "======{{#payload.aggregations.events_last2_minute.articles_over_time.buckets}}{{#zonees.buckets}}key:{{key}}\t{{#nettyIds.buckets}}key:{{key}}\t max:{{max_cost.value}}\t avg:{{avg_cost.value}}\n{{/nettyIds.buckets}}\n{{/zonees.buckets}}\n{{/payload.aggregations.events_last2_minute.articles_over_time.buckets}}========"
        }
      }
    }
  }
}
</pre>
1st Problem:
I need data of avg_cost.value gt 50 condition, 
No idea what is going wrong.
2nd Problem:
Whether watcher config search support  GET /{_INDEX}/{_TYPE}/_search?search_type=count request?

**Comment by lmangani** [comment]
Hi @moueimei please edit your case and put the code between ```<pre></pre>``` brackets for readability. Could you also describe the errors you are getting in your attempts.

**Comment by moueimei** [comment]
no errors

**Comment by lmangani** [comment]
The first issue is with your condition script. You can only create variables within the payload object itself (ie: payload.avg - this is usually best done in a transform script!) - take this example - mind it returns false for your specific dataset:
```
payload.aggregations.events_last2_minute.articles_over_time.buckets.forEach(function(e){e.zonees.buckets.forEach(function(e){e.nettyIds.buckets.forEach(function(e){payload.avg=parseFloat(e.avg_cost.value);if(payload.avg>=50.0){status=true;return status;};});});})
```

**Comment by moueimei** [comment]
thanks
