### ISSUE TITLE
new install attempt causes "Error retrieving metadata from plugin archive"

### ISSUE THREAD

**Issue by neonfrontier** [sirensolutions/sentinl#95]
Hello, I am attempting to install your plugin for testing on a ubuntu kibana (elk stack) install.

The wiki install instructions gave me a variety of errors until I figured out which commands worked to attempt an install. (If you want more testers, it might be a good idea to update those instructions.)

Here's where i'm up to:

```
git clone https://github.com/sirensolutions/sentinl
``` 

```
cd sentinl && npm install --production && npm run archive
``` 

```
bin/kibana-plugin install file://pwd/sentinl-latest.tar.gz 
Attempting to transfer from file:///home/myuser/sentinl/sentinl-latest.tar.gz 
Transferring 2203376 bytes.................... 
Transfer complete 
Retrieving metadata from plugin archive 
Error: Could not find the End of Central Directory Record 
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"
```

This also caused the same error:
```
bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/snapshot/sentinl-latest.tar.gz
```
Thank you in advance for any assistance you can provide!

**Comment by lmangani** [comment]
@neonfrontier it would be easier if you could point at the "instructions that need update" explicitly. 
What version of Kibana are you even running? Details are required to understand and help out.

**Comment by gparapid** [comment]
Hi,
He is using Kibana 5.x probably, based on the plugin install syntax and error. I am having same error when trying to install on Kibana 5.0.0 to 5.1.2, based on your isntruction from issue #16

**Comment by lmangani** [comment]
Thanks @gparapid good point
@neonfrontier version 5.x is not released yet, just an experimental branch - I personally do not have a 5.x setup yet to test with, so any input or contributions are greatly appreciated

**Comment by neonfrontier** [comment]
Yes sorry the version I am using is 5.1.2.
I was just following your wiki install section.
Happy to do testing once I can actually complete the install. :)

**Comment by sylviagc** [comment]
I have installed Kibana 5.2.0 and have attempted to install Sense.  I followed the instructions found here: https://www.elastic.co/guide/en/sense/current/installing.html#manual_download
for the manual download which did not work for me.  Thus the command is incorrect or out-dated.  Here is what finally worked for me.  From  the directory kibana\bin> 
        kibana-plugin install file://PATH_TO_FILE_sense-2.0.0-beta7.tar.gz

I was then presented with a new error: 

Error: Could not find the End of Central Directory Record
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

Any suggestion on how to fix this issue would be greatly appreciated.

**Comment by fbaligand** [comment]
2 things : 
- since kibana 5, sense is included out-of-the-box in kibana.  No need to install it. You can find it into "dev tools", and then "console". Yes, the plugin has been renamed. 
- then, why open an issue about sense plugin in sentinl ? There is no relation...
