### ISSUE TITLE
Error saving watcher - Index/Input naming

### ISSUE THREAD

**Issue by markusza** [sirensolutions/sentinl#96]
Hi. 

I'm trying to create a watcher, but I have an issue saving the watcher. 
We use a index naming convention like below:

**_company_product-2017.11_**

The default when creating a new watcher is below
 
```
"index": [
            "<company_product-{now/d}>",
            "<company_product-{now/d-1d}>"
          ]
```
The above doesn't work as it reference the day in the index, we use month indexes.

I'm following the guide on elastic to reference the index the "correct" way, but it still doesn't save.
https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html

```
"index": [
            "<company_product-{now/M{YYYY.MM}}>"
...
```

The only way the watcher save if I reference the whole index name like: _**company_product-2017.11**_

**Comment by lmangani** [comment]
@markusza what version of ES and Kibana are you using?

**Comment by markusza** [comment]
@lmangani Apologies, forgot to mention. 

ES - 2.4.3
Kibana - 4.5.4
