### ISSUE TITLE
Email notification not working

### ISSUE THREAD

**Issue by gparapid** [sirensolutions/sentinl#97]
1. Issue Description
Cant make watcher or reported notify via email

2. Reproducing the Issue step-by-step
my kibana.yml configuration:

>server.port: 5601
server.host: "127.0.0.1"
elasticsearch.url: "http://127.0.0.1:9200"
logging.verbose: true
sentinl:
  es:
    timefield: '@timestamp'
    default_index: watcher
    type: watch
    alarm_index: watcher_alarms
  sentinl:
    history: 20
    results: 50
  settings:
    email:
      active: true
      host: localhost
      ssl: false
    report:
      active: true
      tmp_path: /tmp/

Reporter:

>{
  "_index": "watcher",
  "_type": "watch",
  "_id": "reporter_testni",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 minute"
      }
    },
    "report": true,
    "actions": {
      "report_admin": {
        "report": {
          "to": "sentinl@localhost",
          "from": "sentinl@localhost",
          "subject": "SENTINL Report",
          "priority": "high",
          "body": "Sample SENTINL Screenshot Report",
          "snapshot": {
            "res": "1280x900",
            "url": "http://www.google.com",
            "path": "/tmp/",
            "params": {
              "delay": 5000
            }
          }
        }
      }
    }
  }
}

And Watcher:

>{
  "_index": "watcher",
  "_type": "watch",
  "_id": "watcher-testmail",
  "_score": 1,
  "_source": {
    "disable": false,
    "uuid": "watcher-testmail",
    "trigger": {
      "schedule": {
        "later": "every 1 minute"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": "[filebeat-{now/d}]",
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 1"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "email": {
          "to": "sentinl@localhost",
          "from": "sentinl@localhost",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      }
    }
  }
}
3. Expected Results vs. Actual Results
No data is forwarded to the smtp host at all on port 25.

From kibana log on reporter execution:

`["status","info","Sentinl"],"pid":24575,"message":"Executing report: reporter_testni"}
{"type":"log","@timestamp":"2017-01-20T13:48:00+00:00","tags":["status","info","Sentinl"],"pid":24575,"message":"Processing action: report_admin"}
{"type":"log","@timestamp":"2017-01-20T13:48:00+00:00","tags":["status","info","Sentinl","report"],"pid":24575,"message":"Subject: SENTINL Report, Body: Sample SENTINL Screenshot Report"}`
["status","info","Sentinl","report"],"pid":24575,"message":"Reporting Disabled! Email Required!"}

And log for watcher does not even pass condition in `(!emailServer || !config.settings.email.active)`

`{"type":"log","@timestamp":"2017-01-20T13:51:00+00:00","tags":["status","info","Sentinl"],"pid":24575,"message":"Executing watch: watcher-testmail"}
{"type":"log","@timestamp":"2017-01-20T13:51:00+00:00","tags":["status","info","Sentinl"],"pid":24575,"message":"Processing action: email_admin"}
{"type":"log","@timestamp":"2017-01-20T13:51:00+00:00","tags":["status","info","Sentinl","email"],"pid":24575,"message":"Subject: Sentinl Alarm, Body: Found 35888 Events"}
{"type":"log","@timestamp":"2017-01-20T13:51:00+00:00","tags":["status","info","Sentinl","email"],"pid":24575,"message":"Delivery Disabled!"}
{"type":"log","@timestamp":"2017-01-20T13:51:00+00:00","tags":["status","info","Sentinl"],"pid":24575,"message":"Storing Alarm to ES with type:email_admin"}
{"type":"log","@timestamp":"2017-01-20T13:51:00+00:00","tags":["status","info","Sentinl"],"pid":24575,"message":"Alarm stored successfully to ES with type: [email_admin]"}
`

As you can see from the watcher and reporter configuration, email is set..Any idea what the issue might be ?

4. Additional Details
Setup is:
ES 2.4.4
Kibana 4.5.4
Centos 6.8
Sentinl 4.6.3-SNAPSHOT

Thanks !

**Comment by lmangani** [comment]
HI @gparapid 
All I can guess is the settings are not properly formatted for whatever reason ie localhost instead of "localhost" but I can't tell from the specific paste

**Comment by gparapid** [comment]
I am so embarresed right now...As I had v5.0 before downgrade, I was editind kibana.xml inside /etc/kibana...
insted of /opt/kibana/config.closing

**Comment by lmangani** [comment]
We all did it at least once! :)
